### ISSUE TITLE
does this support Push Button for manual control ?

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#1]
as the title, does this firmware support RETRACTIVE switches or just standard ROCKER switch type for manual control?

**Comment by rojer** [comment]
currently only rocker-type switches are supported

**Comment by andyblac** [comment]
are you willing to add push button (retractive) type, push for on, push for off. as rocker type are not Wife friendly when using with HomeKit.

**Comment by rojer** [comment]
yes, that's easy to do.
needless to say, we strive to be as wife-friendly as possible :)

**Comment by andyblac** [comment]
thats great to here 🙂

**Comment by RRostron** [comment]
+1 for push button support  :D

**Comment by rojer** [comment]
released in 1.1.0

**Comment by andyblac** [comment]
my flashing cable has arrived, just flash 1.3.0 all working good, thanks.
