### ISSUE TITLE
What's the burned-In-address of Shelly switch?

### ISSUE THREAD

**Issue by 13566602464** [mongoose-os-apps/shelly-homekit#100]
What's the burned-In-address of Shelly switch?

**Comment by timoschilling** [comment]
What does you mean? Did you mean whats the address of your switch or what does the address stands for / what of the shelly provides this address?

**Comment by schemhad** [comment]
Maybe you mean the MAC-Address. It is an burned-in Network-Address, 48-bit, looks like "DE:AD:BE:EF:CA:FE"...

**Comment by andyblac** [comment]
closing ticket, please reopen if you require additional help.
