### ISSUE TITLE
Shelly 2.5 sometimes losing position

### ISSUE THREAD

**Issue by Binganga** [mongoose-os-apps/shelly-homekit#1005]
I use a total of two Shelly 2.5 for my shutter controls in my home.
Shelly Homekit firmware 2.10.1 is installed.
I have noticed for months that they repeatedly "forget" their shutter position.. The strange thing is that this happens in 99% only to one at a time. Rarelly both.

E.g.:
If my shutters are 60% opened and I say "Hey Siri, shutter living room 50%", then it happens that e.g. one goes down correctly, but the other goes up completely...

The same happens in the opposite direction, so sometimes the Shelly thinks the position is fully open even though the shutters are almost completely down.

However, it's not like these always work incorrectly. It sometimes runs smoothly for a few hours/days, and then sometimes a Shelly forgets his position.

I did not have this problem with the original Shelly firmware using Alexa.

What I have done several times so far:
- Reboot
- Calibrate
- Revert to stock -> reinstallation.

Unfortunately no improvement... And since this problem has been bugging me for months, I thought it's time to look for help here :-)

Does anyone have an idea what the problem could be?

**Comment by MagOO33** [comment]
Hello,
you should look at the last reboot time in UI.
If your device reboots at the last command time, it may be an inductive spike.
Look at shelly's website, the sell the right capa+resistor.

**Comment by Binganga** [comment]
It looks like that this is the solution. I have testing some things and could notice how the last reboot time was several seconds ago. Thank you very much.

**Comment by MagOO33** [comment]
shelly's RC snubber is 100 nF, 100 Ohm, 0.5 W and 600 V AC ...
Looks the same, no info on max voltage and power.

**Comment by Binganga** [comment]
So, after I returned to stock firmware my Shellys didnt reboot for over 550.000s (-> over 6 days). With the Homekit Firmware my Shellys rebootet 2-3x a day... so I dont think this has something to do with the RC snubber... (i have ordered them but had no place to install them... so my Shellys are still working without them).

The reason why I think that there is a bug in the Homekit Firmware... years ago everything went fine... after several updates it went worse and with every new firmware it looked like that the Shellys crashed while driving.

As I said after returning to stock there seems to be no problem anymore.

Best regards

**Comment by Binganga** [comment]
1 Week later and still no reboots with the originale Shelly Firmware. In my opinion there seems to be a bug in the Homekit Firmware.
