### ISSUE TITLE
Expose Operating Temperature to HomeKit

### ISSUE THREAD

**Issue by kloibs** [mongoose-os-apps/shelly-homekit#1010]
Hi all,

I was curious if there would be any way to expose the operating temperature of the Shelly in HomeKit as an attribute. 

Maybe I’m alone in this, but I enjoy checking in from time to time to ensure things are running smoothly, and would enjoy the ability to create a Siri Shortcut to ask Siri for a readout of the temperature for each device.

Thank you for all you continue to do, and if this isn’t possible (or worth it) then kindly disregard 🤗

**Comment by rojer** [comment]
you are most definitely not alone. there's ~~an app~~a bug for that already: https://github.com/mongoose-os-apps/shelly-homekit/issues/384

**Comment by kloibs** [comment]
Damn. Guess I didn’t comb through previous issues thoroughly enough. Apologies for the oversight!
