### ISSUE TITLE
Shelly 1 Garagedoor Movement Time is wrong.

### ISSUE THREAD

**Issue by PhilippBLG** [mongoose-os-apps/shelly-homekit#1017]
Heey,

So I updated to Version 2.11 today and found that when the garagedoor is closed and I open it it shorty writes opening for like 5 seconds and then says the Garagendoor is closed and just after the 30seconds when the sensor senses that the door is open it says open. I set the movement time to 45 seconds but it somehow doesn’t use that setting and I always get 2 notifications when opening the garagedoor.

hope there’s a fix for that.

**Comment by rojer** [comment]
can you open the debug log page from the web ui, perform the action you describe and post the log here? it should help me understand what's going on.

**Comment by PhilippBLG** [comment]
![704EB789-1A31-41BB-988C-CA0C7C27CF55](https://user-images.githubusercontent.com/38071782/175143928-7a3391a9-1cbe-45fe-8fd7-52ca26f1b222.png)

i think you can see the problem here pretty clearly.

**Comment by marcus-aa** [comment]
Maybe this was closed too soon, I get a sense it may be related

https://github.com/mongoose-os-apps/shelly-homekit/issues/609

**Comment by joddye2** [comment]
> Maybe this was closed too soon, I get a sense it may be related
> 
> #609

Yes, this problem persist since 2021 (for me)

**Comment by rameezk** [comment]
I’ve just stumbled onto this exact issue now too. 

I’ve also tried moving the magnet (of the sensor) and changed between Normally Open and Normally Closed (even swapped between OC and NC switches). But the issue still persists. 

It’s almost as if the “new state” is read at 5 seconds no matter what.

**Comment by marcus-aa** [comment]
Not completed, should stay open.
