### ISSUE TITLE
Status in Homekit

### ISSUE THREAD

**Issue by Minimarcel08** [mongoose-os-apps/shelly-homekit#1019]
For some time now, I have noticed that the status of the Shelly is not shown correctly in the Home app. This was already the case before the update and also occurs with the new update. However, I can't say exactly if it's a Apple problem or not. The Shelly can be controlled without problems via the Home app.

**Comment by rojer** [comment]
i have noticed it on my older ipad mini (ios 12) too: ui is not updated but responds to actions.
newer ios seems to not get into that state, ui on my iphone (ios 15) is always up to date.
almost certainly an ios issue.
