### ISSUE TITLE
Support for Shelly i3

### ISSUE THREAD

**Issue by gijsstegehuis** [mongoose-os-apps/shelly-homekit#102]
Would it be possible to add support for the Shelly i3?
It would make an awesome Homekit stateless button.

Would be much appreciated.

**Comment by rojer** [comment]
i've actually take a stab at it recently and ran into a problem with inputs in i3 being extremely noisy for some reason.
not a problem on 1 or 2.5, but for some reason on i3 it is, and a big one.
need to investigate.

**Comment by rojer** [comment]
will be in the next release

**Comment by timoschilling** [comment]
@rojer can you ship a new release with i3 support please

**Comment by rojer** [comment]
2.5.0 is coming soon, just waiting for confirmation for a couple fixes and thinking of maybe getting a couple more in. soon.

**Comment by rojer** [comment]
2.5.0 released.

**Comment by gijsstegehuis** [comment]
Awesome work @rojer. Will take this for a spin in the coming days.

**Comment by gijsstegehuis** [comment]
Works like a charm @rojer

**Comment by jerzytraczynski** [comment]
Does this support double or long press?

**Comment by rojer** [comment]
yes
