### ISSUE TITLE
Shelly 2.5 Roller Shutter Percentage Value Problem 2.10.1 vs 2.11.0

### ISSUE THREAD

**Issue by loyalgame** [mongoose-os-apps/shelly-homekit#1021]
Hello community,

I used two Shelly 2.5 with software 2.10.1 and they worked without issues. I was able to use the slider option in Apple Home fully. 

I installed additional 15 new Shelly 2.5 with 2.11.0 and identified, that it is not possible to drive the roller shutter to „fully open 100%“ and fully closed 0%. The roller shutter always starts acting for 1% and then cancels the request. If I set 99 instead of 100%, it drives to 99% without a problem, but 100% (and 0%) via slider does not work. 
With my older Shellys with 2.10.1 it still works. 

I often use this slider option to directly open a partially closed roller shutter instead of clicking on the icon (where it first starts closing, has to be stopped, and then clicked again for opening direction). 

Is there something known ?

Best regards,
Andreas

**Comment by timoschilling** [comment]
Double of #1015
