### ISSUE TITLE
Power saving mode

### ISSUE THREAD

**Issue by askarkurymbayev** [mongoose-os-apps/shelly-homekit#1022]
Good afternoon! I have a question about power saving mode?
There are three kinds of mode: disabled, 1 and 2
what is the difference between mode one and mode two?
And what is the algorithm of these modes?

**Comment by pjpgoncalves** [comment]
bump

**Comment by kostyay** [comment]
bump

**Comment by markirb** [comment]
The behavior of this is different for ESP8266 (gen 1 shellys) and ESP32 (gen 2 shellys):

ESP8266:
https://github.com/mongoose-os-libs/wifi/blob/master/mos.yml#L88
WiFi sleep mode: 0 - none, 1 - light, 2 - modem
Explanation:
https://blog.creations.de/?p=149

ESP32:
https://github.com/mongoose-os-libs/wifi/blob/master/mos.yml#L103
Power save mode for station: 0 - none, 1 - min, 2 - max.
Explanation: ?

**Comment by rojer** [comment]
my understanding is that 1 (light sleep) is a deeper sleep than 2 (modem), the latter only affecting the radio power. but i have not actually measured the power consumption.

**Comment by lucaspinelli85** [comment]
I still haven’t understood the difference between level 1 and 2.

Can someone explain it to me in a simple and understandable way? Thank you

**Comment by 1974here** [comment]
Hi, same question here. I did follow the link from markirb but this does not answer the question... At least I do not understand to. Pls help..

**Comment by markirb** [comment]
Can you specify more what you don't understand after reading the link?

**Comment by lucaspinelli85** [comment]
Currently I still don’t understand anything about the difference between the two modes

**Comment by markirb** [comment]
For Gen1 Shelly Devices:
2 - Modem Sleep Mode: your modem (Wi-Fi) will periodically go to sleep i.e. power save mode in between. This saves some energy

1 - Light sleep mode: additionally to the modem the processor will periodically also sleep. This saves even more energy. 

Are there inherent problems? Maybe, depends on configuration and device. light sleep will not work with e.g. ShellyRGBW2 as the PWM of the lights use timers which do not work anymore then.

**Comment by lucaspinelli85** [comment]
So level 1 saves more energy than level 2?

Can you tell me what the generation 1 and generation 2 shellys are?

**Comment by 1974here** [comment]
Thank you Markus, this explanation helps me.. One more question though: If the modem periodically goes to sleep then it will no longer react to Wi-Fi commands. So it is only for users who work with hardwired switches only?

**Comment by aonez** [comment]
Here are the explanations:
https://github.com/mongoose-os-apps/shelly-homekit/wiki/WiFi-Settings

> On Plus and newer devices / ESP32 and ESP32C3:
> 
> 2 - Maximal Saving 1 - Minimal Saving 0 - No saving
> 
> On Gen1 Devices / ESP8266
> 
> 2 - Modem Sleep Mode: your modem (Wi-Fi) will periodically go to sleep i.e. power save mode in between. This saves some energy.
> 1 - Light Sleep mode: additionally to the modem the processor will periodically also sleep. This saves even more energy. 0 - No sleep
