### ISSUE TITLE
Shelly 25 as a thermostat

### ISSUE THREAD

**Issue by askarkurymbayev** [mongoose-os-apps/shelly-homekit#1026]
Greetings to all participants!
an idea came up, how about using Shelly 25 as a thermostat, one relay for heating and the second for cooling.
also with the latest firmware shelly 25 you can connect a sensor such as a temperature sensor

**Comment by timoschilling** [comment]
Which firmware do you mean? Ours are supporting temperature sensors only on the 1 and 1pm, and stock doesn’t support them on the 2.5 as well.

**Comment by askarkurymbayev** [comment]
I'm sorry, I misunderstood about the sensors, and in fact the external sensor works through Add-on for Shelly 1 at 1PM
but I think it would be nice to use Shelly as a thermostat

**Comment by timoschilling** [comment]
There is already a feature request open for that. Closed as double of #895
