### ISSUE TITLE
Flashing lights

### ISSUE THREAD

**Issue by AStoker** [mongoose-os-apps/shelly-homekit#1029]
Just started happening, but the lights will flash off and on every 2 seconds or so. Seems to maybe have something to do with the Wi-Fi connection, as it will disconnect sometimes. Can't seem to find documentation as to why this is happening. Seems to happen randomly and will occasionally self resolve. But randomly flashing lights isn't great (especially while watching the latest season of Stranger Things).

**Comment by rojer** [comment]
can't imagine why it would be happening... does the device reboot? check uptime in the web interface, does it reset or keep ticking?

**Comment by AStoker** [comment]
I think it's rebooting frequently. The uptime is never that long. I'm about to try and revert to factory firmware to see if that solves it. It's not having this trouble on the other 3 Shelly devices running the same HomeKit firmware.

**Comment by AStoker** [comment]
Interestingly, I turned on AP mode to try and connect directly to it better and whenever I connect to it the lights flash.

**Comment by rojer** [comment]
this looks like hardware issue related to power stability.

**Comment by markirb** [comment]
I had this experience now. It only occurs for me when the power-saving for wifi is enabled (1 = light sleep). Does not happen otherwise (disabled or 2 = modem sleep)

**Comment by markirb** [comment]
Ok forget it, this is not power related:

See: https://blog.creations.de/?p=149

quote:
Because of the halted system clock some peripherals might not work in this mode, use Auto Modem Sleep in those cases.

**Comment by rojer** [comment]
right, light sleep interferes with timers. don't do it.
