### ISSUE TITLE
shelly1 - HomeKit Paired but not connecting 

### ISSUE THREAD

**Issue by Zeses** [mongoose-os-apps/shelly-homekit#1035]
Using the HomeKit Settings and the provided QR code the Shelly1 Paired successfully and was added to HomeKit successfully.
(I note there was no security pin requirements as per the instructions, has this requirement ben removed?)

However I don't see any pending or Active connections in the HomeKit Settings on the Shelly1
And from the HomeKit app the device I added states "No Response" so I can't control the Shelly1

Any suggestions?

**Comment by timoschilling** [comment]
> (I note there was no security pin requirements as per the instructions, has this requirement ben removed?)

That code is inside the QR code and is not explicit required when you pair with the QR

**Comment by RichiG88** [comment]
I have the same issue, too. First, I thought it would be a problem with the Wi-Fi signal strength, but after moving the Shelly next to the router, the problem still persists. I can see the paired state in the web settings of the Shelly, but the connection counter won’t change from zero. I also tried resetting the HomeKit settings but this was no success and it showed me the same QR code afterwards. There’s no option to set a new one.

**Comment by RichiG88** [comment]
I found the problem. It was because my iPad was set as the control center, but it was not connected to the WLAN. Once the iPad is connected, the Shelly is also available in HomeKit. Nevertheless, I cannot create any other HomeKit code.

**Comment by rojer** [comment]
> I cannot create any other HomeKit code.

that is by design: generated code depends on device's unique ID and wifi credentials, and will remain the same.
