### ISSUE TITLE
Detached mode with stateless swich in edge input mode

### ISSUE THREAD

**Issue by tamasharasztosi** [mongoose-os-apps/shelly-homekit#1036]
My idea is to use stateful wall switch (pushable ones that also change the their output on-off so not momentary) to turn a lamp on-off even if the switch goes from 0 to 1 or 1 to 0. Is it possible to implement Edge input mode into Detached mode?

Or is there a solution there I missed? I checked [this](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Stateless-Toggle-Switch) but its not a solution for my problem.

I use Shelly 2.5, but for this problem it would be a better choice to use a i4 since I dont use the relay. I dont know if is it already implemented there.

Thank you!:)

**Comment by tamasharasztosi** [comment]
Anyone?

**Comment by mileswilson** [comment]
I'm also interested in this. I have a regular double "rocker" style switch setup - with a smart bulb in the light. 

I'd like to be able to change either hard wired switch (edge mode) and have use an automation to adjust the smart bulb between bright and dim. Leaving the relay in the on position all the time. 

Is this possible?
