### ISSUE TITLE
2nd Gen Revert to Stock?

### ISSUE THREAD

**Issue by MokkaSchnalle** [mongoose-os-apps/shelly-homekit#1038]
Hi,

does anyone know how to revert to the stock firmware for Plus devices.
AFAIK the binaries are not publicly available.

I already tried to revert via the Web GUI button, but this es just bringing me to the firmware page.

**Comment by rojer** [comment]
revert to stock for 2nd gen is possible but an unfortunate last-minute bug found creeped into 2.11.0 that prevents it from working properly. it'z already been fixed and will be included in the next releasebut meanwhile, you can download stock firmware [here](http://rojer.me/files/shelly/stock/).

**Comment by MokkaSchnalle** [comment]
Awesome, Thank you for this info!
