### ISSUE TITLE
Rollershutter with Shelly 2.5 on big Window (2,40mx2,15m) fails to calibrate correctly

### ISSUE THREAD

**Issue by aqzsed123456** [mongoose-os-apps/shelly-homekit#1041]
I installed 10 Shelly 2.5 with Homekit FW, 8 with standard windows and 2 with bay windows (2.40m*2.15m).

On standard windows no problem, on the other hand on bay windows (2.40m*2.15m) the calibration is bad.
Indeed, the rollershutter does not close completely.

I swapped shellys to check if this one failed, but no change.
Also, with the standard shelly firmware, everything works fine without any issues.

I noticed that the power value of these windows was only 7w while some single windows were 9 or 10w.

I saw issue #985

https://github.com/mongoose-os-apps/shelly-homekit/issues/985
who had the same problem as me

Can you help me?

thank you in advance

**Comment by timoschilling** [comment]
Double of #985

**Comment by aqzsed123456** [comment]
why close my request, I know this is probably the same problem as request #985 but for now no one has given the solution.

Can you help us?

**Comment by timoschilling** [comment]
We don’t allow reposts of issues just to get new attention

**Comment by aqzsed123456** [comment]
I understand very well but what should I do to find the solution?
thank you in advance

**Comment by timoschilling** [comment]
Wait, cross the fingers and hope

**Comment by aqzsed123456** [comment]
thank you timoshilling
I understand but who can solve the problem? did he take our problem into account? And do you think this is fixable?
thanks to you
