### ISSUE TITLE
Not possible to connect to homekit (not paired)

### ISSUE THREAD

**Issue by IAgerre92** [mongoose-os-apps/shelly-homekit#1044]
On the homekit settings I don't know how to pair or connect the shelly 2.5 to homekit.
It only appears this:

Paired: no
Connections: server not running

And a setup button which doesn't work.
What can I do?

**Comment by Rafaehzu** [comment]
I have the same problem, in the settings page I can see ´Paired YES´ but when I try to add add it I get this message: Accessory cannot be added. Inaccessible Accessory

**Comment by rojer** [comment]
> setup button which doesn't work.

can you explain? is it inactive? what happens when you press it?

**Comment by IAgerre92** [comment]
The button just didn’t do anything.
I downgrade it to a previous version and it worked fine. Then I updated it to the last version and everything is perfect.

**Comment by rojer** [comment]
ok, i'll chalk it up to gremlins and close for now.

**Comment by grzywka-kalisz** [comment]
I still have this problem. Can You help with this.  I push SETUP but no reaction. How i need to downgrade this softwear?
