### ISSUE TITLE
Revert to stock - Shelly Plus 1

### ISSUE THREAD

**Issue by jaleitao** [mongoose-os-apps/shelly-homekit#1046]
I need to temporarily revert a Shelly Plus 1 to stock. 
Tried the GUI

![image](https://user-images.githubusercontent.com/110119582/181297733-e3ba6578-9827-4962-8379-4bf2e9cf101b.png)

and scripting

```
Downloading Firmware...
Now Reverting to stock firmware

Devices found: 1 Upgradeable: 1 Flashed: 0
```

no luck
Anyone to kindly help?

**Comment by mkoxyz** [comment]
I've got the same issue.
In parallel I tried the same at a Plug S and this worked.

**Comment by mkoxyz** [comment]
Thanks a lot for the quick response - it works in this way!
