### ISSUE TITLE
Question:  Could we test the Beta Versions 

### ISSUE THREAD

**Issue by rionshin** [mongoose-os-apps/shelly-homekit#1048]
Hello 

i saw in the repository a lot of version as 2.9.4 Beta and 2.9.5 , could we test it , and is there any document what is new in this builds ?

**Comment by timoschilling** [comment]
Why would you use that version, when we already on 2.11?

**Comment by rionshin** [comment]
> Why would you use that version, when we already on 2.11?

Ops my mistake I had read it as 2.90 which is bigger than 2.11 😂
