### ISSUE TITLE
Support for Shelly EM

### ISSUE THREAD

**Issue by tdacorrosivo** [mongoose-os-apps/shelly-homekit#1052]
Good morning, I would like to know if you are working on compatibility with Shelly EM, thank you for the incredible work you do, will there be compatibility with this device? A hug

**Comment by rojer** [comment]
short answer: not at the moment and probably not any time soon. but maybe at some point.

**Comment by tdacorrosivo** [comment]
thank you very much for responding, you do an incredible job, hopefully soon we can enjoy Shelly Em, hug

**Comment by timoschilling** [comment]
Double of #990
