### ISSUE TITLE
Paired but no Added

### ISSUE THREAD

**Issue by Rafaehzu** [mongoose-os-apps/shelly-homekit#1055]
I have the 2.11.1 version , i have paired it but when I try to add add it I get this message: Accessory cannot be added. Inaccessible Accessory

Paired: yes
Connections: 0 pending0 active12 max

thanks

**Comment by Rafaehzu** [comment]
Solved, thanks

**Comment by rojer** [comment]
"paired" means it is already paired with a controller, to be able to add you need to remove it from the other one or to reset.
