### ISSUE TITLE
Sensor based automation - 1/1PM

### ISSUE THREAD

**Issue by kurtwarwick-new** [mongoose-os-apps/shelly-homekit#1056]
Hi

I realize that this request seems similar to the thermostat request - however, what would be great, and potentially a good step towards that request, is the ability to automate the relay position (on/off) based on the reading of a given sensor. The stock firmware already supports this, and it would be amazing to have this feature added to this custom firmware.

For a bit of context; I have a S1 hooked up to water heater, which needs to be turned off at a certain temperature to prevent possible bursting. Sadly, this is the only S1 I have that is on stock simply due to the lack of this feature.

Thanks so much for your amazing work, BTW! Every release is appreciated and much awaited!

Thanks

Kurt

**Comment by timoschilling** [comment]
We decided to not support automatization on the device. In the HomeKit world it’s up to HomeKit to automate things.
