### ISSUE TITLE
2.11.2 Crashing

### ISSUE THREAD

**Issue by bmpalmeida** [mongoose-os-apps/shelly-homekit#1061]
Hello All,

One of my devices, a Shelly 2.5PM is crashing and never connects back to the WiFi network, i have to power cycle to connect.

I've manage to get the core dump, and i had shared this before and roger mentioned that it was due to network traffic, i did another test, and i manage to get the device fully stable using 2.9.5, but not with 2.10.0.

[coredump.txt](https://github.com/mongoose-os-apps/shelly-homekit/files/9395263/coredump.txt)

**Comment by jonasman** [comment]
Mine has similar behaviour. Didnt check the logs tho
