### ISSUE TITLE
Support HTTPS port

### ISSUE THREAD

**Issue by pawelphilipczyk** [mongoose-os-apps/shelly-homekit#1064]
I’m wondering if it would be a quick fix to add support for HTTPS into devices. 

I’m trying to build simple Shelly devices lookup app but as most pages are served over HTTPS these days it’s a blocker. Fetching from http is no longer allowed on https pages at least in Chrome. Anyway I’m looking for proper solution not a hack. 

Thanks for all the hard work in this project!

**Comment by rojer** [comment]
not simple. we do not have the space for TLS support, it requires resizing filesystem.
possible in principle but not worth doing just to get local HTTPS.
