### ISSUE TITLE
Shelly1 no reachable after Update to 2.11.2

### ISSUE THREAD

**Issue by Spy-1** [mongoose-os-apps/shelly-homekit#1067]
Hi, after I flashed 2 Shelly 1 with current FW 2.11.2,configured and added in Komekit, I could operate them in Homekit for a short time and after a short time both Shelly 1 are not reachable anymore.
One is still displayed with an IP address in the Fitzbox, the other can no longer be found.
I can no longer get to the GUI for both.
What do I have to do to reactivate the Shellys.

**Comment by wyssale1** [comment]
same behaviour for me

**Comment by antlaranjeira** [comment]
Me too, after update 4 of 6x, 4x of the 6x I use as roller shutters stop working!

**Comment by 00x7** [comment]
The issue could be connected to your WiFi setup or the strength of the WiFi signal. On a setup with multiple access points, locking my unresponsive Shellys to their nearest access point [brought them back up for me](https://github.com/mongoose-os-apps/shelly-homekit/issues/1078#issuecomment-1250348797).

Haven't had any similar connectivity issues on previous shelly-homekit releases, so I can only assume that something has changed in 2.11.2.

**Comment by xyz667** [comment]
Having the same problem with my 1L. 
Rebooting fixes this for some (short) time, before being unresponsive again.

**Comment by pboudoin** [comment]
Same issue here

**Comment by adrdon** [comment]
I seem to have a similar issue, homekit worked fine after I got all the shelly and home hub on the same network but the main issue is, I cannot operate shellys via the shelly app. Is this normal??

**Comment by Spy-1** [comment]
yes

**Comment by adrdon** [comment]
Noooo, really? But why? You can't do that much in "homekit" compared to shelly app.
Is it possible to make it so Shelly app works as well?

**Comment by Spy-1** [comment]
No

**Comment by adrdon** [comment]
😂
Straight to the point.
Well at least i know know
