### ISSUE TITLE
Shelly1  server not running

### ISSUE THREAD

**Issue by but1head** [mongoose-os-apps/shelly-homekit#1068]
hi. I updated the original firmware then uploaded the homekit firmware, when i press "setup" in homekit settings i have forever loading spinner. 
<img width="515" alt="image" src="https://user-images.githubusercontent.com/7607579/187677423-51ac0f1e-657b-4a6a-84ea-4c36e14e864a.png">

Model: Shelly1
Device ID: shelly1-2DFE38
---
Version:2.11.2
Build:
20220812-225235/2.11.2-g1b146b4-master

**Comment by kdoughe12** [comment]
I'm having the same issue

**Comment by but1head** [comment]
downgrade for 1.9.1 firmware works okay

> I'm having the same issue

**Comment by martinblq** [comment]
@but1head how did you do to downgrade? I have the exact same problem than you. When I try to downgrade using the form here:
![CleanShot 2022-09-01 at 17 39 21@2x](https://user-images.githubusercontent.com/5744655/187955514-0c86a22a-0c27-4f74-ab4d-ff276372493a.png). 

And the file in .zip format that I downloaded [here](https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.9.1).

I'm stuck here: 
<img width="638" alt="CleanShot 2022-09-01 at 17 42 23@2x" src="https://user-images.githubusercontent.com/5744655/187956151-4334c139-c319-4f97-a1e8-b8b7051c858d.png">

**Comment by but1head** [comment]
i have installed from [here](https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.9.1) 
"build_id": "20210518-005833/2.9.1-gb7dcbef-master",
"version": "2.9.1"

**Comment by martinblq** [comment]
@but1head yes, I know (this is the same link I sent you). But I can't use the .zip file to downgrade, I'm stuck at upload step and nothing happens. Do you have an idea @rojer please? 🙏🏻

**Comment by martinblq** [comment]
@but1head @rojer just to let you understand better what I did, here is a quick video. I found my firmware [here](https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.9.0)

https://user-images.githubusercontent.com/5744655/187966958-75ae5909-1a89-485f-88cc-f3fee4dab8bf.mp4

**Comment by rojer** [comment]
> when i press "setup" in homekit settings i have forever loading spinner.

open the "debug log" link and then press setup, please post log contents here.

**Comment by martinblq** [comment]
I used the script and it finally worked!
Thank you for your help :)

——------

Martin Blanquer
+33 6 01 64 53 64 ⏤ ***@***.***
