### ISSUE TITLE
Shelly25 roller shutter reboot during calibrate process

### ISSUE THREAD

**Issue by robnantes** [mongoose-os-apps/shelly-homekit#1069]
Hello,

This is a new installation, I'm using the lastest version of the firmware 20220812-225358/2.11.2-g1b146b4-master on a Shelly2.5 in roller shutter mode.
During the setup process when I click the calibrate button, the roller shutter is moving to the fully open position and during this process the status on the shelly switch to unreachable. When the roller shutter is reach the top it doesn't move down.
The calibration process failed.

Here is the dump of the core file from /debug/core
[core.txt](https://github.com/mongoose-os-apps/shelly-homekit/files/9462765/core.txt)

**Comment by llKoull** [comment]
Same problem here! Did you found a solution?

**Comment by robnantes** [comment]
The shelly had a problem, the power measurement didn't report consumption information, so the calibration process can't work properly.
I sent back the shelly and ordered a new one, and the new shelly works great.
