### ISSUE TITLE
Shelly 2.5 home kit server not running

### ISSUE THREAD

**Issue by gazamb** [mongoose-os-apps/shelly-homekit#1072]
Hello,
I have set up several shelly devices and used the homekit feature no problem with the github firmware for homekit. I just went to setup a device for myself but the homekit section says:
Paired: no
Connections: Server not running
When I click on setup the circle on the button just spins and spins and nothing happens. 

![Screenshot 2022-09-03 000345](https://user-images.githubusercontent.com/112746188/188258175-00e5fb24-44b9-41fe-9691-b81b3185fa5d.png)

**Comment by corcuito92** [comment]
Anyone can help with this? I have the same issue. Server not running and no way to setup the code…

**Comment by grzywka-kalisz** [comment]
Hi. I have same problem with shelly 2.5
No body can help?

**Comment by grzywka-kalisz** [comment]
Update:
I have also an exist shelly 2.5
I check firmware. I have install on existing also 2.11.2  
But when i install this on new shelly is not working.  Still server stopped. For homekit.

**Comment by grzywka-kalisz** [comment]
Update:
I install 2.09.2
Start working.
Than update. Still working.
