### ISSUE TITLE
[Question] Shelly 1 Garage door 12V

### ISSUE THREAD

**Issue by xszuflax** [mongoose-os-apps/shelly-homekit#1073]
Hello,

is there any particular reason why the Garage Door Opener configuration suggest 24V instead of 12V?

I just installed Shelly 1 with contact sensor in Garage Door Opener configuration, and it works perfectly with 12V 20W inbox power adapter. 

It kinda stressed me out after I installed the 12V one :-D

**Comment by xszuflax** [comment]
Maybe the docu update?

**Comment by timoschilling** [comment]
I think the voltage doesn't matter, as long as they is supported by the Shelly.
