### ISSUE TITLE
[question] Valve could support for automations?

### ISSUE THREAD

**Issue by cjpatoilo** [mongoose-os-apps/shelly-homekit#1074]
In the future Valve should have any support for automations?

**Comment by sroettgermann** [comment]
I think this isn't related to shelly-homekit, but Apple should take care of it. Currently it is impossible to create any automations with regard to valves. 
As mentioned somewhere here in the wiki, you can use apps like Eve or Home+ instead of the basic Home.app to define automations.

**Comment by timoschilling** [comment]
As @sroettgermann says it’s not in our hand, it’s a limitation of the home app, use alternative apps
