### ISSUE TITLE
Shelly UNI - Bootloop after flash 2.11.2

### ISSUE THREAD

**Issue by AlexSG92** [mongoose-os-apps/shelly-homekit#1077]
Hi,

After flashing my device, it keeps rebooting and won't let me configure anything.ç

Attached are the documents that I have been able to get. Let me know if there is anything I can do
![2022-09-08_00-11](https://user-images.githubusercontent.com/7228966/188992684-d819eba2-ba05-4aac-8043-fbc9e2b37f61.png)
[core.pdf](https://github.com/mongoose-os-apps/shelly-homekit/files/9521928/core.pdf)

**Comment by rojer** [comment]
thanks for reporting, but unfortunately the core file is incomplete, try fetching multiple times to see if you can get a complete file (should end with `--- END CORE DUMP ---`.

**Comment by NikolaT56** [comment]
Hello, the problem was the power supply to the board. It is now working properly. Regards.
