### ISSUE TITLE
[Question] Rollers in Security section iOS 16

### ISSUE THREAD

**Issue by xszuflax** [mongoose-os-apps/shelly-homekit#1079]
Hello,

is there any new accessory type which would put my rollers in the Security section instead of the climate section in iOS 16?

I have external anti-theft ones, and I would like to see them same as Garage Doors.

Regards,
Marcin

**Comment by timoschilling** [comment]
There is no way to move them from climate to security. 

But we have already a feature request open to show up window covers as garage doors, so I will close this as a double. 

But keep in mind if you use the maybe upcoming garage door mode, you no longer can use Siri on a HomePod or a locked iPhone to control them.

**Comment by xszuflax** [comment]
Thanks
