### ISSUE TITLE
STA+AP

### ISSUE THREAD

**Issue by BufferOverflow1011** [mongoose-os-apps/shelly-homekit#1090]
after reseting, the device will be in AP mode , after connection to STA, now the device is in STA+AP.  the AP is taking some time to switch off . where can i adjust this time

**Comment by timoschilling** [comment]
After you connect to STA, the AP is immediately off, maybe your Computer/Mobilephone didn't refresh the wifi list instantly. Or if its really on, you can disable AP in the WiFi Settings.
