### ISSUE TITLE
Shelly 2 2.1 21 protection from having both SW enabled the same time

### ISSUE THREAD

**Issue by x23piracy** [mongoose-os-apps/shelly-homekit#1094]
Hi,

i discovered this shelly homekit fw and used it for three shelly 2.5 and 2 shelly 1 at the end i tried my old shelly 2 and realized to late that it doesn't support rollershutter, is there a way to protect both relaise being enabled the same time? always turn off the enabled relay before turning on the other.

If this is not possible i'll replace it with a new shelly 2.5 but before i had a custom fw with tasmote supporting shuttermode, i am hoping for a option i am not seeing in the webif of the homekit fw.

Please help.

Best Regards X23

**Comment by timoschilling** [comment]
Sorry for the late response. Our rollershutter logic requires a power measurement which the shelly 2 didn't have, so we can't offer it there.
