### ISSUE TITLE
Expected behavour - Shelly 1L creating own bridge and unused switch

### ISSUE THREAD

**Issue by gitoreillhubch** [mongoose-os-apps/shelly-homekit#1097]
Hi all, 

Quick check, have flashed a Shelly 1L and have it operating on network. Just want to check that it creating its own bridge into homekit and also creating both a switch and an "unconfigured button" (I only have one lighting circuit attached) is expected behaviour?

Thanks, 
C

**Comment by timoschilling** [comment]
Yes that’s all expected. The button is an stateless switch which allows you to use the second input of the Shelly in HomeKit. You can disable them in the web Ui. The bridge is needed to provide 2 accessories in HomeKit. Technically a bridge is only a collection of accessories.

**Comment by gitoreillhubch** [comment]
Great, thanks @timoschilling
