### ISSUE TITLE
Garage door Support

### ISSUE THREAD

**Issue by marcopeeters** [mongoose-os-apps/shelly-homekit#11]
Is it possible to configure it as a garage door opener? So HomeKit will see it as a real garage door?

**Comment by rojer** [comment]
It is doable, though not exactly trivial.
One would need to implement the service and some state transitions - opening, closing, etc.
Input pin would be used to detect when the door is closed.

**Comment by kmetabg** [comment]
This feature is support from original firmware using Auto OFF settings. 
Mostly garage doors need just a impulse < 1 sec to triger the motion. 
If tehre is similar feature called Auto Off which can be set from 0.1 to X sec all will be ok.

**Comment by rojer** [comment]
i see. yeah, that'd be much easier to do.
