### ISSUE TITLE
HomeKit server fails to start

### ISSUE THREAD

**Issue by alexlunnon** [mongoose-os-apps/shelly-homekit#1108]
Just flashed Shelly1 OTA sucessfully with 2.11.2 (`20220812-225235/2.11.2-g1b146b4-master`) however HomeKit settings never populate. 

<img width="488" alt="Screen Shot 2022-10-21 at 6 49 24 pm" src="https://user-images.githubusercontent.com/3113017/197142893-60e14771-bc11-4079-8928-107885d6e2b6.png">

Looking in console it appears as if there is a recurring error trying to check for updates and subsequently an error after clicking on Setup which becomes an infinite spinner.  

<img width="608" alt="Screen Shot 2022-10-21 at 6 52 30 pm" src="https://user-images.githubusercontent.com/3113017/197143273-29c04fb6-5fbe-4f65-a9af-8414b789fcf8.png">

Any ideas?

**Comment by alexlunnon** [comment]
Downgrading to `2.9.1` build `20210518-005833/2.9.1-gb7dcbef-master` resolves the issue per https://github.com/mongoose-os-apps/shelly-homekit/issues/1068

**Comment by iFrez** [comment]
Same error with `shellycolorbulb`, but no `2.9.1` FM for it.
