### ISSUE TITLE
Shelly (1L) doesnt install HomeKit firmware

### ISSUE THREAD

**Issue by ApNfS** [mongoose-os-apps/shelly-homekit#1112]
I am just starting with shelly and bought 8 pieces of Shelly 1L for my house. I installed the first and I am able to use the webinterface from the device. But I am not able to install the HomeKit firmware. I allways get the following error message:

{"status":"updating","has_update":false,"new_version":"","old_version":"20201014-165335/1244-production-Shelly1L@6a254598"}

It on both ways the same if I use:
http://192.168.187.201/ota?url=http://shelly.rojer.cloud/update   or
http://192.168.187.201/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1L.zip

Of course first I have checked the current firmware, but its the newest one available.

I really dont know what to do / what I am doing wrong on this.
Could somebody help me with this ?

**Comment by A-vesalius** [comment]
Update the Shelly to latest stock firmware, will need to get it on your Wi-Fi with stock setting first.  After latest stock firmware update then the script should work.
