### ISSUE TITLE
Garage Door Opener new setting

### ISSUE THREAD

**Issue by Semir333** [mongoose-os-apps/shelly-homekit#1118]
Dear Developers!

I take a suggestion for a new setting option for peapole who not want to add/not have a reed switch for the SW line. In some cases really hard to built in an external reed switch, thats why i write my suggestion.
If the user not used the SW line, the Homekit shows a non reliable state.

My suggestion is a **Not in use** option, where the state is setted and opposite state what switched related to movement time.
So start from open, push the switch, movement time is over, and the status is switched to the opposite state automaticly, without any electrical triggering from Shelly SW input.

**Comment by timoschilling** [comment]
The problem is that the Shelly then never really know the state of the door, the device can only guess the state. That means HomeKit can’t tell you the truth about it’s open or closed. That means for security reasons this is not an option.
