### ISSUE TITLE
Add support for Dimmer and RGBW devices

### ISSUE THREAD

**Issue by vanrri** [mongoose-os-apps/shelly-homekit#112]

**Comment by andyblac** [comment]
ticket already open https://github.com/mongoose-os-apps/shelly-homekit/issues/72 / https://github.com/mongoose-os-apps/shelly-homekit/issues/14

**Comment by markus7017** [comment]
@vanrri ?

**Comment by vanrri** [comment]
Ok got it!

Hope this is picked up soon.

**Comment by andyblac** [comment]
duplicate closing ticket.
