### ISSUE TITLE
Shelly Uni won't connect / seen as a bridge by homekit

### ISSUE THREAD

**Issue by derschmichel** [mongoose-os-apps/shelly-homekit#1123]
After successfully adding a few Shelly 1 Plus to my homekit setup I tried to add a Shelly Uni today. Installing the firmware went well but homekit refuses to add the device. Scanning the QR code works just fine but the device is shown as a bridge and after a few seconds a "Device can't be added" message appears. I tried to switch it to the garage opener mode, it then get's detected but still can't be added. The iPhone is on iOS 16.1.1

**Comment by timoschilling** [comment]
That it is shown as bridge is right, that's needed to support some features. Sometimes it can happen that you need some tries to add it to HomeKit, so please try agin.

**Comment by derschmichel** [comment]
Thanks for your fast reply, after scanning the code a few times more it worked.
