### ISSUE TITLE
IoBroker connection fails 

### ISSUE THREAD

**Issue by tonibert** [mongoose-os-apps/shelly-homekit#1126]
Good work!

My problem is when I change the firmware, the IO broker adapter no longer finds my Shelly (2.5).
I use IOBroker to control other automations that do not (yet) work with Homekit.

In order to control the shutters via Siri, I would also like to use your firmware.

**Comment by timoschilling** [comment]
We do not support other home systems then HomeKit and are incompatible to the Shelly stock api.

**Comment by tonibert** [comment]
Thanks for the answer. Too bad, I think your solution is great but unfortunately not for my requirements. But that's not your problem. All the best for you and your project
