### ISSUE TITLE
Shelly1 GarageDoor with Addon and reed

### ISSUE THREAD

**Issue by HarrySteff** [mongoose-os-apps/shelly-homekit#1127]
Dear all,
I have a problem with a shelly1 configured as a garage door opener. I connected a magnetic reed contact to the addon. Garage door opens and closes perfectly but if garage is closed after the 15 sec timeout in Home app it says „Blocked“ webinterface status is „stopped“.
If I open the garage door everything is fine.
Can somebody help? 
shelly is powered with 220V .

thank you

**Comment by Steviek1982** [comment]
Hi,

i have the same issue but so far - unfortunately - no solution. Maybe I’ll try to switch the power supply to 12v

kind regards

Stefan

**Comment by timoschilling** [comment]
Did I understand it right? That problem happens if your door closes after the 15 sec?

**Comment by HarrySteff** [comment]
@timoschilling  yes that’s right… if I have the web interface open I can see the change of status from closing… to „stopped“ after the 15 sec (in apple home status is blocked, then)

**Comment by timoschilling** [comment]
Then increase the time to a value a bit higher then it needs in the maximum to close the door

**Comment by HarrySteff** [comment]
My door only need 11 sec to close. It looks like the reed contact did not send any signal to the Shelly-addon. But beforehand it worked with a Meross garage opener… so I’m not sure what else I could try…

**Comment by markirb** [comment]
input sensors are not yet supported for the add-on. there is an open PR for this, but its untested...:
https://github.com/mongoose-os-apps/shelly-homekit/pull/967

**Comment by timoschilling** [comment]
@markirb thanks for the hint. 
@HarrySteff we do not support the addon for garage door opener’s

**Comment by HarrySteff** [comment]
@timoschilling thanks, I could, but I need a hint how I can test it? If I press update at web-interface, it says „up to date“
