### ISSUE TITLE
RGBW2 separate control of channels

### ISSUE THREAD

**Issue by Stanly001CZ** [mongoose-os-apps/shelly-homekit#1128]
Hi guys, I just would like to asku you if and when do you plan to have separate control of 4 channels - use 4 white led strips. Thank you so much! Have a nice day

**Comment by timoschilling** [comment]
<img width="488" alt="Screenshot 2022-11-17 at 09 56 12" src="https://user-images.githubusercontent.com/165599/202401207-6099e149-835a-40c3-9d9d-1ae8daec2db6.png">
We already support that.
