### ISSUE TITLE
Shelly 1 Missing Occupany or Doorbell Setting

### ISSUE THREAD

**Issue by bmpreston** [mongoose-os-apps/shelly-homekit#1131]
So I'm missing something, because a lot of documentation points to using Shelly stateless switch as a doorbell, but I don't have Occupancy or Doorbell as a HAP type.  Can someone advise?

Thanks!

**Comment by timoschilling** [comment]
Can you post a screenshot of your settings please

**Comment by bmpreston** [comment]
These are my firmware (showing updated) and my HAP styles. 

Thanks 

![123241F8-F675-4AA4-B255-4C45239083D0](https://user-images.githubusercontent.com/29456939/202898945-f2b5c217-6252-453d-bcf2-0ac888719cb5.png)

![C70CAFB6-F93E-4DA5-B7F8-307FF592AF94](https://user-images.githubusercontent.com/29456939/202898957-99b2f268-c029-4505-9f38-c64b2240fcc8.png)

**Comment by bmpreston** [comment]
I’m confused  what this page is referencing. 

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Input-Switch-Settings

**Comment by burneyboy2002** [comment]
Off top of my head, you select it as a switch and then you should get another box below called input mode with toggle, edege, activation etc..  you then select detatched, [See here](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Switch-Settings) and then save it, link above should explain then you program the input mode in another box below for doorbell etc.

hope this helps

**Comment by bmpreston** [comment]
Appreciate your input. It doesn’t actually give me the doorbell as seen in
previous photos.

Also, momentary doesn’t turn the relay back off.

I’m not using the relay, just watching the input. So I’m a little vexed.

**Comment by markirb** [comment]
As it says on the site, input has to be detached to see these modes.
