### ISSUE TITLE
Shelly 1 not responding to reset

### ISSUE THREAD

**Issue by Octa29** [mongoose-os-apps/shelly-homekit#1134]
Hello!
I have two Shelly 1 relays set as garage door openers.  Reed switches on both doors to get the open/close status.

The Shelly device connected to my garage door received the HomeKit firmware and worked fine until I had to replace my old router with a TP-Link Deco X20 Mesh and the device was not reachable anymore. I reset the Shelly 1 connected to the other garage door which had the stock firmware and reconnected to the router without a problem. But the one with the HomeKit firmware doesn't want to reset after pressing the momentary switch for 5 times. I can hear the Shelly's "click" sound, but it's not reachable or doesn't reset.

Other details:
- Both Shelly 1 relays were set with static IP (192.168.1.249 for non-responsive Shelly and 192.168.1.234 for the other
- The new Mesh system is set to deliver IPs from 192.168.1.100 to 250 and no other device uses 192.168.1.249 IP address. Even though this Mesh doesn't have the option to create two different SSID (one on 2.4 and other on 5Ghz) I was paying attention to have my phone connected to 2.4Ghz when I tried to reconnect it. As I mentioned, the other Shelly reconnected and working just fine.
- I replaced the non-responsive Shelly 1 with a new one on stock software and it works fine, but I would like to fix the problem and connect it to my entrance gate so I can open and close it like I do with my garage doors.

Can you help me fix my Shelly 1? Should I buy a USB to RS232 module to connect it to my Macbook Air to reset it?

Thank you!

**Comment by timoschilling** [comment]
You can reset the shelly by turning the power on / off five times.
