### ISSUE TITLE
Gate opener disconnected when fully open

### ISSUE THREAD

**Issue by simonfield76** [mongoose-os-apps/shelly-homekit#1136]
Dear all it’s been a while that I’m playing with a shelly 1 in gate opener state.

since I have installed a magnetic sensor on a 2 door gate the system is working like a charm…

I only have the issue that as soon as the gate is fully opened the shelly become unreachable (disconnected).

I do not really understand where could be the issue… from the motherboard of the gate or from the shelly.

Any suggestions or tips is very well appreciated

**Comment by timoschilling** [comment]
Is that only a problem in HomeKit or in the web Ui too?

**Comment by simonfield76** [comment]
Both. The issue is either in homekit either in the webapp
![4D6B171F-88E7-4419-B918-BF981BBE55A6](https://user-images.githubusercontent.com/75778600/204268963-2e11240c-7ef3-405a-99c9-4f4040eb31a4.png)
![4D9C0136-496B-4E6A-8232-709A854FE0F3](https://user-images.githubusercontent.com/75778600/204268981-93e6e04f-8ce4-4253-9cbc-a0c5a135d4be.png)

the log is interrupted as soon as the shelly will appear “disconnected”.

as soon as the gate begin the movement for the closing the web interface auto refresh and will start working again while the log remain stuck.

**Comment by simonfield76** [comment]
As soon as the first leaf/door begin it’s movement the ui immediately return available

**Comment by spalda8** [comment]
I have got totaly same problem.

**Comment by timoschilling** [comment]
Sound like the position change of the garage door blocks your wifi signal

**Comment by simonfield76** [comment]
Ok thank you for pointing this out. Monday I will try changing the position of the shelly and will revert with the results. 👍

**Comment by spalda8** [comment]
SameS pozdravemDavid SpálenskýOdesláno z iPhonu1. 12. 2022 v 13:31, simonfield76 ***@***.***>:﻿
Ok thank you for pointing this out. Monday I will try changing the position of the shelly and will revert with the results. 👍

**Comment by simonfield76** [comment]
> Sound like the position change of the garage door blocks your wifi signal

You were right!!! 

I placed the shelly inside the box of the logic board

but at fully open it was closing the box making a sort of faraday cage blocking all the signals.

I now have moved the shelly in a higher position and now it really works like a charm!!

Thank you for your huge help!! 

![D8B0D24A-3085-40D9-AB21-256F4D7ED9C2](https://user-images.githubusercontent.com/75778600/206474386-aea0985e-db78-48e4-8b83-86e50d82c078.jpeg)
