### ISSUE TITLE
Question: New WiFi options - WiKi Update Required

### ISSUE THREAD

**Issue by drheck** [mongoose-os-apps/shelly-homekit#1139]
Hello together,
i am using the newest firmware and i looking for the description of the new wlan options in the newest firmware.
How can i change the WiFi form Wifi 1 to Wifi 2?
I have added the WiFi 2 and enabled.
Then the device shows connecting and after a few seconds it stays on WiFi 1.
If i disable WiFi 1 its the same.
Both WiFi are reachable from the device (tested with other shellies)

Thank you,
Peter

**Comment by timoschilling** [comment]
If I remind it right, the shelly always uses the best available wifi, so if you want to force it, you need to replace the wifi 1 data.

**Comment by drheck** [comment]
Okay. Thank you. That was the trick.
