### ISSUE TITLE
Wifi signal

### ISSUE THREAD

**Issue by yuvalbeck** [mongoose-os-apps/shelly-homekit#114]
Hi, 
Wifi signal strength status would be a nice feature in the web UI.
Thank you

**Comment by andyblac** [comment]
@rojer while your doing update to webUI, I this some that could be added ?

**Comment by rojer** [comment]
ok, this one didn't make the cut for 2.2, but it's easy to add - an extra field to the Shelly.GetInfo RPC, and a UI change.
if anyone feels like it, feel free to take this one up.

**Comment by rojer** [comment]
added, will be in the next release

**Comment by andyblac** [comment]
one for @schemhad 😄

**Comment by rojer** [comment]
yeah, for now i'm showing RSSI. i don't necessarily agree with signal strength calculation in the PR mentioned above, i'd like to know more about it.
i mean, i know > -50 is great, < -90 is really bad, but what is -70?

**Comment by andyblac** [comment]
from Unifi UI

![Screenshot 2020-10-08 at 18 49 25](https://user-images.githubusercontent.com/77936/95495219-0562ba00-0997-11eb-934a-35601d4036fb.jpg)

**Comment by schemhad** [comment]
-30 -> -66 Very Good
-67 -> -70 Good
-71 -> -79 Okay
-80 -> -90 Bad

**Comment by rojer** [comment]
@schemhad feel free to send a pull request!
