### ISSUE TITLE
AP Station does not display IP Address

### ISSUE THREAD

**Issue by 5xPa** [mongoose-os-apps/shelly-homekit#1140]
First I have been running your Firmware for a long time works great, thanks for all the effort.

I have a few Draytek APs's if I go into station list the IP address is not shown or rather reports 0.0.0.0

Here is an example

The first one is a Merros plug module
E1:E9:32:F9:43  14d 00:03:48 65 Mbps  99% (-51 dbm) SSID  121.15 MB7.83 MB 192.168.0.171

This one is the Shelly module
10:52:1C:F3:27:E8  8d 01:25:15  65 Mbps 87% (-56 dbm)  SSID   72.54 MB5.07 MB 0.0.0.0

It's not causing any problems, just for info.

**Comment by timoschilling** [comment]
Thanks for the info but the WiFi stack is not part of this repo
