### ISSUE TITLE
Plus 1 stopped working

### ISSUE THREAD

**Issue by payensa-sf** [mongoose-os-apps/shelly-homekit#1141]
Hello,

I connected today a new Shelly Plus 1 and updated to the latest stable version, it worked flawlessly but I wanted it to work with mi HomeKit based installation. Then I flashed the HomeKit firmware for that family of relays and it broke down with a small internal explosion after toggling it a couple of times. 

Does anybody know how usual this is or what I did wrong? Of course I don't dare to flash anyone else. 

Thanks

**Comment by timoschilling** [comment]
Sound like you have used two different main lines for the switching and for powering the Shelly. That resulted in a voltage higher than 400V, which kills the Shelly. 

That doesn’t need to happen immediately, it can happen after a while. 

You have an hardware issue, so we can’t help you
