### ISSUE TITLE
Shelly plug S not reachable from homekit or webbrowser

### ISSUE THREAD

**Issue by mauritsklein** [mongoose-os-apps/shelly-homekit#1143]
My Shelly plug S is not reachable from homekit anymore and also not via the webbrowser? I am running 2.11.2. How can I reset the plug and getting everything working again? I've tried the official Shelly hold the button for 10sec and it does blink, but I don't know how to proceed from there? What are the default settings for 2.11.2 and how can I reach the plug? It does show in the Shelly app and asks to connect. But I receive the error: Can't get device info.

**Comment by timoschilling** [comment]
Push the button 5 times in a row
