### ISSUE TITLE
Does the overload protection is enabled with this library?

### ISSUE THREAD

**Issue by Idomo** [mongoose-os-apps/shelly-homekit#1144]
First thing - thank you for working hard on this library, it is really great that someone cares about the HomeKit support.

I’ve just installed it and discovered that this library is “disabling” the Shelly app (makes all devices as “offline”).

So that made me wonder (and a bit worried), does it also disables the Overload Protection feature that the Shelly 1PM is so familiar with?

Thanks,
Ido.

**Comment by timoschilling** [comment]
This firmware didn’t support the Shelly app. 

Overload protection is currently not implemented, see #339 for details
