### ISSUE TITLE
Vintage bulbs, no longer turn on.

### ISSUE THREAD

**Issue by drpodmeer** [mongoose-os-apps/shelly-homekit#1149]
Hello friends, 

I have several vintage bulbs with the latest firmware, and from one day to the next they all stop working, I can not turn them on and off, not reset them and they are not on the network all defective, within 2-3 days.

who has an idea?

**Comment by timoschilling** [comment]
How did you have tried to reset them? Cut them from power and turn them on for 5 sec and turn off again, then it should be reseted. 
The other option is that they are dead, can you measure their power consumption?
All my vintages are died after 1-2 years

**Comment by drpodmeer** [comment]
Yes i made a reset, but no luck. 
unfortunately, I can not measure the power consumption. 
mine died after 5 months, strangely all within 2 days

**Comment by timoschilling** [comment]
Sounds like a hardware problem, try to replace them via the Shelly support
