### ISSUE TITLE
Reverting to stock firmware

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#115]
Shelly has updated the API in v1.8.0, as a result all the link to the zip's are now giving 404 in the readme.

**Comment by rojer** [comment]
@kzyapkov what are the new locations?

**Comment by kzyapkov** [comment]
URLs for all devices are listed at

https://api.shelly.cloud/files/firmware

**Comment by kikofhm** [comment]
how revert to stock firmware? 
the link <http://api.shelly.cloud/firmware/SHSW-1_build.zip>lead me for "404 Not Found" 
I can't revert firmware for original via interface (attach file)

**Comment by andyblac** [comment]
> how revert SHELLY 1 to stock firmware?
> the link http://api.shelly.cloud/firmware/SHSW-1_build.ziplead me for "404 Not Found"
> I can't revert firmware for original via interface (attach file)

Links are in the above post but
Here is one for Shelly 1 http://api.shelly.cloud/firmware/SHSW-1.zip

**Comment by pivale** [comment]
> URLs for all devices are listed at
> 
> https://api.shelly.cloud/files/firmware

Is it possible to add a field for the comercial name?
It will be easier for people not familiar with the product_id

**Comment by rojer** [comment]
updated the links

**Comment by andyblac** [comment]
I have wrote a tool to do this automatically for you, you can find the script here https://github.com/mongoose-os-apps/shelly-homekit/blob/master/tools/flash_shelly.sh simply run `./flashscript.sh -m revert _hostname.local_`
