### ISSUE TITLE
Upgrade to the new Home architecture

### ISSUE THREAD

**Issue by fagallo** [mongoose-os-apps/shelly-homekit#1155]
With the launch of iOS 16.2 It's possible to upgrade iOS device to the "new Home architecture" ? 
However, at least for now, the upgrade is optional. That’s because Apple said  it affects the experience for some users. I read that it is much stricter in checking non-natively compatible devices.

**Comment by timoschilling** [comment]
What’s your intent to write that?

Does you want to know that we are compatible? For my around 30 devices which are covering nearly every usecase, I can say it works like before. 

About compatibility, we are using a reference implementation from Apple so I think it should be compatible. Even our Eve based custom power measurement still works.

**Comment by fagallo** [comment]
Yes. iOS 16.2 official was release yesterday. There is a new menu under home app setting to do that upgrade.
![91466A53-194E-41EB-A20A-C01DFF30309C](https://user-images.githubusercontent.com/116731196/207708508-1f7c2456-e973-471e-b048-45842cf9bf5d.jpeg)

I wanted to know if anyone had a chance to try this new feature in iOS 16.2 or beta and there was no problem to update.  Just this.

**Comment by timoschilling** [comment]
That change is only related to the controller (iOS, HomePod, etc) side of HomeKit. 

Yes it works.
