### ISSUE TITLE
Edge Switch Mode is not available

### ISSUE THREAD

**Issue by SunseekerFfm** [mongoose-os-apps/shelly-homekit#1158]
Hey, in the Original Firmware there is a Mode name Edge Switch, this is needed for Cross circuit lamps.

It is Not possible or come it maybe with an new HomeKit Firmware Next Time?

Thanks for answer.

**Comment by timoschilling** [comment]
We have that option
<img width="492" alt="Untitled" src="https://user-images.githubusercontent.com/165599/208465242-194f304a-66fc-4682-bef2-afa347d99420.png">
Or if you use a stateless switch its this:
<img width="496" alt="Screenshot 2022-12-19 at 16 48 39" src="https://user-images.githubusercontent.com/165599/208465317-ae8a0684-627f-46cf-922b-48370f953464.png">

**Comment by SunseekerFfm** [comment]
Thank you very much for that fast support. 
But i dont have this options, but i have a    almost similar variant and it works. 
When you allowing one More question? Any idear why i dont have your proposed options?

Greetings
SunseekerFfm

**Comment by SunseekerFfm** [comment]
-![image](https://user-images.githubusercontent.com/120943282/208524295-fc026abc-878c-4896-809d-41c211ad5102.png)
