### ISSUE TITLE
Shelly 1pm plus

### ISSUE THREAD

**Issue by moamen121** [mongoose-os-apps/shelly-homekit#1162]
Hi friends, I have a shelly 1pm plus, I added it to the home kit, but every now and then it disconnects and reconnects, why?

**Comment by timoschilling** [comment]
Can you explain a bit more what you mean with "disconnects and reconnects"

**Comment by moamen121** [comment]
I mean that suddenly the shelly writes me not response and after a few minutes it connects

**Comment by timoschilling** [comment]
In the web Ui ?
