### ISSUE TITLE
Shelly 2.5 not sold anymore

### ISSUE THREAD

**Issue by Labulle2024** [mongoose-os-apps/shelly-homekit#1165]
Hi,
I have 5 Shelly that stoped working and with the support request they always offer me to replace with Shelly 2PM that is more powerfull as they said. 
so do you plan to develop a roller shutter firmware for the new Shelly 2PM ? that seem to be the replacement for shelly 2.5 that is not in sell anymore on Shelly.cloud

thanks a lot for your work !

**Comment by timoschilling** [comment]
Yes we plan to support the plus 2pm, see #1013

**Comment by timoschilling** [comment]
I don’t know when it will be supported. Maybe replace them with a plus 2pm and use Homebridge until we are ready.

**Comment by Labulle2024** [comment]
Hi,

Thanks a lot for your answers and this last tip.

Regards,

Le jeu. 22 déc. 2022 à 17:24, Timo Schilling ***@***.***> a
écrit :
