### ISSUE TITLE
Expose long push as stateless button in momentary mode

### ISSUE THREAD

**Issue by AlexDavidenko** [mongoose-os-apps/shelly-homekit#1166]
Use case:
By default in momentary mode the long push starts a timer, which is rarely used. 
When using detached mode but the short press still controls the actual relay the short push action takes a long time to perform because of the whole shortcuts logic.

Instead I suggest having an option to either start a timer (default) or expose the long push action as a stateless button with single press only. 
If you need the whole single press, double press, long push you can still use detached mode. 

If exposing long push only in momentary mode you're enjoying both worlds, the relay will trigger faster and you still have long push as a stateless button to control other accessories.

**Comment by timoschilling** [comment]
I think you mean something like this https://github.com/mongoose-os-apps/shelly-homekit/pull/1011

**Comment by AlexDavidenko** [comment]
yeah, perfect. Thanks
