### ISSUE TITLE
Problem with python script

### ISSUE THREAD

**Issue by miomia** [mongoose-os-apps/shelly-homekit#1167]
I have used the ./flash-shelly.py -a and  script to update my shelly's to stock firmware .  I received the error "ModuleNotFoundError: No module named 'zeroconf'" After I tried to install 'zeroconf' with the command "pip3 install zeroconf" I received many errors. How else can I solve the problem? 
I am on macOS 11.4  (Big Sur)
<img width="968" alt="Снимок экрана 2022-12-23 в 19 36 55" src="https://user-images.githubusercontent.com/87931470/209383079-20c4ac41-7e5c-4d34-ae17-59fe04374a81.png">
<img width="1119" alt="Снимок экрана 2022-12-23 в 19 39 18" src="https://user-images.githubusercontent.com/87931470/209383144-2a3c5293-d2d6-4852-9377-79fda1c5b64d.png">

**Comment by timoschilling** [comment]
Looks like you have a problem with your python setup. 

You could also revert via web Ui

**Comment by miomia** [comment]
> You could also revert via web Ui
 How can I restore via web Ui ?

**Comment by timoschilling** [comment]
<img width="483" alt="Untitled" src="https://user-images.githubusercontent.com/165599/211348289-54cde294-d714-4d0c-9be6-f2139b1fa8e9.png">

**Comment by pascal9275** [comment]
Hello, I have a similar issue.
I have updated a Shelly plus 1pm and wanted to revert it to stock.
I have used the revert from the web UI.
The window indicated it will resend the version 0.12.0 ( I was on 0.13 beta)
The update goes up to 89% and then stops
I made several retry, it always stops at 89 %
Any suggestions?
