### ISSUE TITLE
Shelly 1PM Plus issues after updating

### ISSUE THREAD

**Issue by FrederikKier** [mongoose-os-apps/shelly-homekit#1169]
![Skærmbillede 2022-12-28 kl  12 49 40](https://user-images.githubusercontent.com/87178697/209807725-1eba4d62-40f5-44c7-9958-f6901eb17240.png)

After updating, my device is offline, and the attached picture is what I see, what i connect to the device. Any ideas?

**Comment by FrederikKier** [comment]
After 3 hours I now have contact to the shelly 👍🏻

**Comment by Mymi42** [comment]
Hello, 
Did you do something in particular to access to your shelly ? I have the same message with my shelly 1 since this morning...
