### ISSUE TITLE
Get Power Reading via REST Api possible?

### ISSUE THREAD

**Issue by esamecar** [mongoose-os-apps/shelly-homekit#1175]
Hi, I am afraid, that this is a RTMF thing, maybe you can point me to the correct direction. With the stock firmware it was possible to get the rolling power consumption value with a timestamp, is this still possible? (At least it does not work with the same call no more.)

Thanks

Marco

**Comment by timoschilling** [comment]
Actually we only support the current power consumption. A history is already requested on an older issue.
