### ISSUE TITLE
Can't install mongoose on shelly 2.5 from HomeKitBG 0.1.11

### ISSUE THREAD

**Issue by Ferran-Hermida-Rivera** [mongoose-os-apps/shelly-homekit#1179]
Hi, I have two Shelly 2.5 from HomeKitBG with firmware version 0.1.11. I have tried follow the procedure to upgrade their firmware to mongoose's firmware and it didn't work. I have later tried to use the script but it didn't work either.  In fact, they are not even showing up when I execute ./flash-shelly.py -l, but they do ping. Hence, they are properly connected to the Internet; I just can't change the firmware. Any help?

**Comment by timoschilling** [comment]
Sorry we can only give support for the flash of stock firmware to our firmware. You need to get your shelly to run with the original firmware first. Then we can help you.
