### ISSUE TITLE
Shelly is added to HomeKit but won’t connect 

### ISSUE THREAD

**Issue by rmkromkamp** [mongoose-os-apps/shelly-homekit#1184]
I have a Shelly 2.5. It has the newest HomeKit firmware. It’s connected to the WiFi. I van control it on the web in safari. It connects to HomeKit. But it’s stil saying it’s offline

**Comment by timoschilling** [comment]
Where do you see it as offline?

**Comment by rmkromkamp** [comment]
Only in HomeKit itself. But I could just add it into HomeKit.

**Comment by rmkromkamp** [comment]
Installed the last firmware on the Shelly after I found this failure but didn’t fixed it. Have an Apple TV

**Comment by timoschilling** [comment]
Is the Shelly the only HomeKit devices you have?

**Comment by rmkromkamp** [comment]
No I have Hue, Aqara, Eufy and HomeBridge. Work all perfect. It’s only this Shelly

**Comment by timoschilling** [comment]
Try to reset the HomeKit connection and reconnect them

**Comment by rmkromkamp** [comment]
Ive rebooted the Apple TV and I’ve removed the Shelly HUB from the Home app. Then connected it again into HomeKit. Adding the Shelly HUB and the 2 switches worked again fine. Only it’s still disconnected in the Home app.

**Comment by A-vesalius** [comment]
I have had the same issue with several Shelly 1L's I bought. Still unuseable.

https://github.com/mongoose-os-apps/shelly-homekit/issues/1099#issuecomment-1309706859
https://github.com/mongoose-os-apps/shelly-homekit/issues/1099#issuecomment-1361619364

**Comment by rmkromkamp** [comment]
I moved back to the normal Shelly firmware. But wasn’t even able to add it to HomeKit with HomeBridge. Assen the HK firmware again and added the Shelly back into HomeKit. Adding works fine, but it’s stil offline when it’s added to HomeKit. I’m stil able to control it in the web-interface. Driving me crazy

**Comment by timoschilling** [comment]
Have you try to remove them from HomeKit and not only resetting them via Ui?

**Comment by rmkromkamp** [comment]
Yes multiple times. With resetten and without resetten

**Comment by timoschilling** [comment]
How is your wifi setup? Do you have multiple access points? Is the non working Shelly on a different AP, then the other?

**Comment by rmkromkamp** [comment]
I have the solution!! I changed the Mesh WiFi routers into ‘Access Points’ and now everything works fine. That must have changed by some update. But ALL other devices still worked. Was only the Shelly that had a problem. But problem is solved now !! Thank you all for your help
