### ISSUE TITLE
Connect ed reverted

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#1185]
What does it mean?![image](https://user-images.githubusercontent.com/74553551/212135509-c40bcbcc-acc8-4973-a899-f4ef5beeba6f.jpeg) connected reverted?

**Comment by timoschilling** [comment]
If you change your wifi settings and the Shelly can’t connect with the new settings it automatically reversed to the old settings

**Comment by lucaspinelli85** [comment]
Ok but i never change Wi-Fi settings, in the shelly in the modem too...

**Comment by idrive5** [comment]
Intermittently experiencing this same problem.  Any known issue/fix?

No changes are getting made to either router or Shelly
