### ISSUE TITLE
Doorbell switch doesn't ring when Detached

### ISSUE THREAD

**Issue by Macrox14** [mongoose-os-apps/shelly-homekit#1187]
Hello, I have installed my Shelly 1 Plus and when I press the physical switch my doorbell rings (input mode Momentary).

But when I changed it to Detached, the physical switch stop working.

![Screenshot 2023-01-15 125129](https://user-images.githubusercontent.com/31378074/212558035-f277d9d8-0d64-4d01-bae3-42e7db28ea3d.png)

Am I doint something wrong?

This is my cable
![2](https://user-images.githubusercontent.com/31378074/212558137-a0ca3fe3-902f-4aac-86dc-43dbf58ffec2.png)

**Comment by PeterVanDerSanden1975** [comment]
Same schema here but other inputs:
![D739EA0B-B7DA-4D74-9ED1-A7096D9FAF2C](https://user-images.githubusercontent.com/75860125/212559691-85a1af3c-892c-41bc-93d4-c522003a0eb6.png)

Note: hap type doorbell does not work. Motion detect works well.

**Comment by Macrox14** [comment]
@PeterVanDerSanden1975 I’ve tried your schema and same issue: the digital switch works, but the physical doesn’t

**Comment by PeterVanDerSanden1975** [comment]
HomeKit should trigger the physical when the input is enabled:

![F9F98B60-448B-4104-9A21-4B1AA2085004](https://user-images.githubusercontent.com/75860125/212560958-a4eeecbc-a47e-423e-a181-07bdaaa275b2.png)

it is in Dutch, sorry. Let your HomeKit couple switch and physical.

good luck.

**Comment by timoschilling** [comment]
Yes you do something wrong. What you try to do isn’t supported. The detached doorbell mode is only to signal a push on the button in HomeKit as doorbell ring, not to control the doorbell it self. You need to wire the doorbell as bevor you installed the Shelly and then you wire the Shelly input in parallel to the doorbell and not in series like it’s now. 

Maybe someday we will support your wireing as well. There is already a feature request for that.
