### ISSUE TITLE
Shelly 1 update "Error uploading: TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by stodla123** [mongoose-os-apps/shelly-homekit#1188]
Hello i tried to update from 2.10.1 via file to 2.11.2 and it failed. (see below)

Full log is attached

Update via server did not work eighter..

Not sure but i have the suspicion the device is turning the switch on randomly (running on 2.10.1) ??  (just a guess not sure tho, so i wanted to update)

Any help appreciated thank you 

Regards Steve

Firmware
Version:2.10.1
Build:
20211016-122946/2.10.1-gc8923b3-master
Update: Error uploading: TypeError: Failed to fetch
Update from file: shelly-homekit-Shelly1.zip

[logfile_Shelly1.txt](https://github.com/mongoose-os-apps/shelly-homekit/files/10428240/logfile_Shelly1.txt)

**Comment by timoschilling** [comment]
Why are you trying via file and not via UI?

**Comment by stodla123** [comment]
unfortunatelly, clicking on "update" in the gui results in the same error:
![image](https://user-images.githubusercontent.com/64693317/212984243-214419f2-3136-48d3-90a0-fe04b126c179.png)


is there a way to access via ssh and run update?

**Comment by timoschilling** [comment]
> Not sure but i have the suspicion the device is turning the switch on randomly

How is it configured? Is the "Initial state" set to On?

> Update: Error uploading: TypeError: Failed to fetch

I hade the same error, a retry has fixed it for me.
Are you sure that you have used the right firmware?

You can also update them by opening http://A.B.C.D/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip in your browser. Your shelly needs network access for that.

**Comment by stodla123** [comment]
hello and thanks for the reply,

Not sure but i have the suspicion the device is turning the switch on randomly

How is it configured? Is the "Initial state" set to On?
![image](https://user-images.githubusercontent.com/64693317/213924867-11f454f3-32ee-464e-8564-583a0e8681d9.png)

Init State is off since it's my kitchen sink light and i dont want it to go on in case of power failure.

How does this affect turning on or off when a switch is connected? (which is in my case)

Unfortunatelly this:
http://192.168.1.129/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip

![image](https://user-images.githubusercontent.com/64693317/213924823-7dc27bce-8b22-4661-bb61-58310341469c.png)

did not suceed as well...

i do not wanna return to stock fw since my automations are done in homekit.

is there some kind of log where one can see the imput state over a longer period of time in the past? (maybe switch input has been triggered due to electromagnetic radiation?)

regards

**Comment by stodla123** [comment]
Somehow i was able to update to latest FW as of today.
![image](https://user-images.githubusercontent.com/64693317/215316651-5c5e39ba-03c3-4d23-b57f-6cce84d4db12.png)

can't really figure out why..

presumeable it had something to do with network connectivity (although no changes had been made on my network, probably update server not reachable?)

it looked like the shelly was not able to fetch the update.

as for turning the switch on spontanously i'm hoping that's resolved as well.

issue can be closed, thank you @timoschilling 
regards

**Comment by 5xPa** [comment]
I don't know if this is relevant I tried had a similar problem. I tried
http://192.168.0.28/ota?url=http://rojer.me/files/shelly/shelly-homekit-ShellyPlus1PM.zip
which failed.
I then entered 192.168.0.28 which loaded the Shelly page.
I then entered
http://192.168.0.28/ota?url=http://rojer.me/files/shelly/shelly-homekit-ShellyPlus1PM.zip
.
The upgrade applied
