### ISSUE TITLE
Don't get the updated page on shelly 1

### ISSUE THREAD

**Issue by Thoomass** [mongoose-os-apps/shelly-homekit#119]
I typed in the update url and got this: "{"status":"updating","has_update":false,"new_version":"20200827-065344/v1.8.3@4a8bc427","old_version":"20191217-140757/1047-long-id-for-shelly-devices@a0661583"}"
But the Shelly page doesn't update.
I tried to clear the Cache but Nothing changed.

I'm Looking for a solution for Hours, but I didn't find one.
I hope someone can help me.

**Comment by Thoomass** [comment]
Solved: got a mistake at the url, watch out the smal and big letters!

**Comment by rojer** [comment]
glad you got it working
