### ISSUE TITLE
RGBW2 CCT mode has 2 lights, but only one works.

### ISSUE THREAD

**Issue by bobziroll** [mongoose-os-apps/shelly-homekit#1191]
I very well may have something incorrectly configured, I'm not finding great information on how to connect things up. Currently, I'm using an FCOB CCT light strip from RTF-Lighting. I have the warm white connected to the White channel of the RGBW2, and the cool white connected to the Blue channel of the RGBW2. While playing around with the modes, I noticed the CCT mode, which showed 2 separate lights (and put 2 separate lights in HomeKit).

However, for me, only one of them works. And that one that works, works perfectly as far as I can tell. I'm able to change temperatures all the way from warmest to coolest white just fine.

So what is the other light for? Or do I have my RGBW2 connected up wrong or something?

Now that I think about it, I'm guessing what it's doing is noticing that I have 2 wires connected (the White and the Blue) and thinks it's a separate led strip? If I connected both the warm and cool whites to the White, would it still be able to control the white temperature? Or is there some other way I should be connecting everything together?

Sorry for me being so naive. It's been quite a learning curve learning about LED light strips...

**Comment by markirb** [comment]
It's only that 4 channels can steer 2 CCT lights (one to RG and the second one to BW). if you do not use the second one you can set it to hidden in the webinterface then it won't show.

**Comment by bobziroll** [comment]
Ah, that makes sense. Great to know, thanks!

**Comment by bobziroll** [comment]
Is that documented somewhere about the RG & BW light setup on CCT mode?

**Comment by timoschilling** [comment]
I will add it in the UI

**Comment by timoschilling** [comment]
added in https://github.com/mongoose-os-apps/shelly-homekit/pull/1195
