### ISSUE TITLE
Set on/off Shelly DUO by REST Api possible?

### ISSUE THREAD

**Issue by colussim** [mongoose-os-apps/shelly-homekit#1202]
Hi ,
it is possible to set on/off Shelly DUO by REST Api ? 
Is there any documentation of the API input ?

Thanks,

Emmanuel

**Comment by timoschilling** [comment]
Yes
On: `http://a.b.c.d/rpc/Shelly.SetState?id=1&type=11&state={%22state%22:true}`
Off: `http://a.b.c.d/rpc/Shelly.SetState?id=1&type=11&state={%22state%22:false}`

**Comment by colussim** [comment]
ok , thank you very much

Emmanuel
