### ISSUE TITLE
HAP service type for heater

### ISSUE THREAD

**Issue by paulolesgazz** [mongoose-os-apps/shelly-homekit#1208]
Hi,
I would like to use some shelly 1 to manage heaters in my home. Can you add heater in HAP service type ?
Thanks

**Comment by 5xPa** [comment]
I would also make a request. I use Uni modules connected to texecom Alarm system. Would be great if there were  Hap
 types Alarm on (system Armed)
           Alarm Active (Intruder detected)

**Comment by timoschilling** [comment]
This are double requests of https://github.com/mongoose-os-apps/shelly-homekit/issues/895 and https://github.com/mongoose-os-apps/shelly-homekit/issues/552

**Comment by paulolesgazz** [comment]
Reading of temperature is done by Eve Weather module. I can put this module anywhere in room (without wire). Shelly 1 will be used only as relay and put directly in socket of heater.

**Comment by timoschilling** [comment]
ok https://github.com/mongoose-os-apps/shelly-homekit/issues/895 requested support for thermostat and not heater. I reeded the HAP specification and a heater needs the current temperature, so we can add a heater, but it would not work for your case.
