### ISSUE TITLE
Shelly 1L no edge option on second sw

### ISSUE THREAD

**Issue by Djanreek** [mongoose-os-apps/shelly-homekit#1218]
I want to connect you o Shelly 1L two way switch for this i need to configure edge o switch 2 and no this option 
Please help

**Comment by timoschilling** [comment]
What do you want to achieve? Control the relay using each input with a edge switch?

**Comment by Djanreek** [comment]
Yes it’s the only way to employment two way switching

בתאריך יום ו׳, 10 בפבר׳ 2023 ב-13:24 מאת Timo Schilling <
***@***.***>:

**Comment by timoschilling** [comment]
You need to set the first input mode to "edge (both inputs)", then they work in same way.
