### ISSUE TITLE
Doorbell not supported

### ISSUE THREAD

**Issue by gnoto** [mongoose-os-apps/shelly-homekit#1222]
I configured a Shelly 1 Plus as a Doorbell. Everything seems correct but the Home App shows the accessory as not supported and does not allow any configuration.
Any idea?
<img width="490" alt="Screenshot 2023-02-12 at 21 09 55" src="https://user-images.githubusercontent.com/54668134/218334862-9c41de40-141b-4be9-bd9e-873481147076.png">
<img width="527" alt="Screenshot 2023-02-12 at 21 11 51" src="https://user-images.githubusercontent.com/54668134/218334864-3263cb16-fcf7-4abf-9f52-9c44b1d05acd.png">
<img width="170" alt="Screenshot 2023-02-12 at 21 12 04" src="https://user-images.githubusercontent.com/54668134/218334867-34d05760-4ec5-4d34-ac7c-7f3f6c94941a.png">

**Comment by timoschilling** [comment]
That's a common issue, the Home app didn't support it / has no UI for it. But it will work anyway, you will receive notifications if someone rings the bell.

**Comment by insidegui** [comment]
Is there any special setup required in order to get notified when the doorbell is activated? I see it as unsupported in the Home app as well, pressing the switch makes the doorbell ring sound in all HomePods, but I'm not being notified on any device.

**Comment by ghaithster** [comment]
Hoping to get assistance… my building has a four wire intercom set up (12vdc) 
![C0BDEE66-92F4-43DA-A869-FC2DF989B6B6](https://github.com/mongoose-os-apps/shelly-homekit/assets/139072342/33e87b1f-51e1-4433-a448-11cab4517c8b)
with basic panels in each apartment (Listen, Talk, Door). I successfully hooked up the Shelly 1 and slashed it with the HomeKit software. However, I can’t figure out how to get notified when someone presses my apartment button outside. My apartment panel does ring and the wire marked X (see photo) has the tone signal. I connected this wire to the SW of the Shelly 1, and I think I can figure the input correctly, as detached, and then doorbell. I’m pretty sure I’m missing something…

**Comment by nachomezzadra** [comment]
> Is there any special setup required in order to get notified when the doorbell is activated? I see it as unsupported in the Home app as well, pressing the switch makes the doorbell ring sound in all HomePods, but I'm not being notified on any device.

i'm having this exact same issue.  It was working with previous fw/ios versions, but now i'm not getting any notifications at all.  iOS v18.1.1, fw version 2.13.3 (build 20241203-191940/2.13.3-g1cb5084).  Has anyone been able to sort this out?
