### ISSUE TITLE
Shelly RGBW2 + Reset

### ISSUE THREAD

**Issue by 90III01** [mongoose-os-apps/shelly-homekit#1230]
Hello, I've a question about my specific setup:
I've 5 switches with 1 Vimar rele with reset function. Every switch can ON/OFF and reset always turn all OFF. I want to now add an RGBW2 and use the "i" to read the previous state and turn on/off my stripe on signal change. If ON and rele change state (regardless it is on or off) it turn off, if off and state change it turn on. In other words: my rele don't send any input, just power or not power the line, I want to read this change. Of course I'll power the Shelly with a separate always-on line. Is possible to get that playing with settings?

**Comment by timoschilling** [comment]
Yes that works, that’s the edge mode, it changes the state of the strip.
