### ISSUE TITLE
Shelly1v3 + Carplay + Siri

### ISSUE THREAD

**Issue by nullatore** [mongoose-os-apps/shelly-homekit#1234]
Scenario:
Shelly1v3 + Carplay

When iphone's working with Carplay and is locked , Siri doesn't allow to execute any command toward my Shelly accessory (it says to unlock the phone before).
At the same condition (carplay+phone locked) no problem with other HomeKit certified accessory.

Everything's fine with my shelly if iphone is unlock.

**Comment by timoschilling** [comment]
What kind of accessory is your Shelly, a garage door or a switch?

**Comment by nullatore** [comment]
> What kind of accessory is your Shelly, a garage door or a switch?

A switch type lock , input mode = toggle

![image](https://user-images.githubusercontent.com/49812905/221356001-af05d8e9-92c6-408a-ba23-d256b766b7b0.png)

**Comment by vrpt2022** [comment]
> > What kind of accessory is your Shelly, a garage door or a switch?
> 
> A switch type lock , input mode = toggle
> 
> ![image](https://user-images.githubusercontent.com/49812905/221356001-af05d8e9-92c6-408a-ba23-d256b766b7b0.png)

As far as I know SIRI don’t allow security accessories to be activated with a locked phone. Locks/Doors can’t be open through Siri if you don’t unlock the phone. If you have an Apple Watch or HomePod you can try to ask to open the garage door and it will reply that it must be done through unlocked iPhone. Here some comments:
https://www.reddit.com/r/HomeKit/comments/tk8j1s/cant_ask_homepod_to_open_my_garage_via_ismartgate/

**Comment by nullatore** [comment]
> > > What kind of accessory is your Shelly, a garage door or a switch?
> > 
> > 
> > A switch type lock , input mode = toggle
> > ![image](https://user-images.githubusercontent.com/49812905/221356001-af05d8e9-92c6-408a-ba23-d256b766b7b0.png)
> 
> As far as I know SIRI don’t allow security accessories to be activated with a locked phone. Locks/Doors can’t be open through Siri if you don’t unlock the phone. If you have an Apple Watch or HomePod you can try to ask to open the garage door and it will reply that it must be done through unlocked iPhone. Here some comments: https://www.reddit.com/r/HomeKit/comments/tk8j1s/cant_ask_homepod_to_open_my_garage_via_ismartgate/

I think it isn't my case.
With my my iphone locked, I successfully can launch command to all my accessory (included Shelly) from AppleWatch and Ipad.

Furthermore, Siri says me that I have to unlock iphone (not to continue this operation on that device).

**Comment by timoschilling** [comment]
> If you have an Apple Watch or HomePod you can try to ask to open the garage door and it will reply that it must be done through unlocked iPhone.

That’s not right. If your Apple Watch isn’t locked you can open secured devices. 

But in fact your answered your initial issue by your self. Secured devices (lock, garage door, etc.) can’t be open via Siri if a device is locked.
You can only control devices like light bulbs etc if locked. 

In general it’s not up to use how siri works with a Shelly. Because siri only controls HomeKit. The Shelly didn’t have any knowledge about siri.

**Comment by nullatore** [comment]
> > If you have an Apple Watch or HomePod you can try to ask to open the garage door and it will reply that it must be done through unlocked iPhone.
> 
> That’s not right. If your Apple Watch isn’t locked you can open secured devices.
> 
> But in fact your answered your initial issue by your self. Secured devices (lock, garage door, etc.) can’t be open via Siri if a device is locked. You can only control devices like light bulbs etc if locked.
> 
> In general it’s not up to use how siri works with a Shelly. Because siri only controls HomeKit. The Shelly didn’t have any knowledge about siri.

My Shelly configured as a light bulb has the same problem.
My Smart Plug (certified accessory) hasn’t the problem and work also with locked iPhone.
Hmmm…
