### ISSUE TITLE
Shelly DW2 support

### ISSUE THREAD

**Issue by Alex-Bricklayer** [mongoose-os-apps/shelly-homekit#124]
First of all many thanks for the wonderful firmware. Is it possible to extend the software to the Shelly sensors? Especially the Shelly Door/Window 2 would be very useful.

Greetings 

Alex

**Comment by rojer** [comment]
it's possible, but no ETA, as usual.

**Comment by andyblac** [comment]
I'll close this as new ticket has been issued to track this.

**Comment by rojer** [comment]
no, not quite. this is about support for hardware shelly door/window sensors.

**Comment by andyblac** [comment]
ok, my apologises.

**Comment by rojer** [comment]
https://shelly.cloud/products/shelly-door-window-2-smart-home-automation-sensor/

**Comment by andyblac** [comment]
add `SHELLY MOTION` to the list once it's released then.

**Comment by MilanBacaCz** [comment]
Hi all, if never mind I will try make this one [(https://shelly.cloud/products/shelly-door-window-2-smart-home-automation-sensor/).](https://shelly.cloud/products/shelly-door-window-2-smart-home-automation-sensor/) Next week I hope the sensor will arrive and I can start work on it.

**Comment by Ludelag** [comment]
So, I didn't understood at all,will it be done? 

How could I help

**Comment by andyblac** [comment]
it on the to do list.

**Comment by MilanBacaCz** [comment]
Is here anyone who can prepare web UI for Door/Window 2 sensor?

**Comment by andyblac** [comment]
> Is here anyone who can prepare web UI for Door/Window 2 sensor?

it needs more than just webUI, the device needs coding, as i said, it on the todo list, you will will just have to be patient.

**Comment by MilanBacaCz** [comment]
i had the device at home and want to help with coding. I just now study the Rojer code, HomeKit and mongoose api.

**Comment by Ludelag** [comment]
Is there any news redarding the implementation of the firmware for the D/W 2 ?

**Comment by MilanBacaCz** [comment]
Sorry, it does not. I am sick :-( high fever, headaches. With pills from the doctor i am not able thinking. :-( I will be continue when i will be Ok.

S pozdravem,
Milan Bača

**Comment by andyblac** [comment]
@MilanBacaCz get well soon.

**Comment by Ludelag** [comment]
@MilanBacaCz hope you are doing better and recovered. Take care.

**Comment by Ludelag** [comment]
Hello every body, any news here? @MilanBacaCz How are you doing? hope you feel better.

**Comment by Ludelag** [comment]
Hello everyone, there is any news about this issue? thank you

**Comment by BlancoDeMallloca** [comment]
Hi all,
Hope everyone is fine. 

Any update about the sensor support? 
Shelly door&window Lux measurement is a great feature for automation. 
It would be highly appreciable  if this could be implemented.

**Comment by MilanBacaCz** [comment]
I am sorry, i have very few time. :-( There is no progres on my side.

S pozdravem,
Milan Bača

**Comment by jsiegenthaler** [comment]
Hello All. I now have 2 x DW2 myself, and am happy to help in any way that I can.... but that might be limited to Web GUI and Readme updates... however I can code and can test and am willing to help...

**Comment by louis49** [comment]
1073 / 5000
Résultats de traduction
I am completely junior on this type of development, I have a Shelly door window 2, but I started to:
 * Implement the simplest firmware part for the contact sensor part for which a library had already been coded (I have not yet looked into the luxmeter)
* Successfully compiled but not yet tested a flash.
=> I will see in the next few days to test the result of my work when I will have succeeded in connecting it to the serial port (not very standard connection)

I face two questions:
1: How did you go about determining the PIN IDs? (I plan to determine them empirically)
2: From what I could understand the original firmware has a particular battery management (the sensor cuts off when not in use): if this new firmware reduces the battery life from 2 years to 2 weeks I'm not sure users will like it. (There is this type of solution to work around the problem: https://stefan-rehnberg.com/almost-always-on-shelly-dw2/ (not tried))

**Comment by ma-jkl** [comment]
Hi, ano progress guys? Thank you, Michal

**Comment by Ludelag** [comment]
I use it thru Shelly Homebridge plugin and works pretty good, But will be nice to have it shelly homekit firmware

**Comment by ma-jkl** [comment]
> I use it thru Shelly Homebridge plugin and works pretty good, But will be nice to have it shelly homekit firmware

Thank you Ludelag. Will try to do that.

**Comment by ma-jkl** [comment]
Hi,
time flies. Is there any Progress? Regards

**Comment by timoschilling** [comment]
Replaced by https://github.com/mongoose-os-apps/shelly-homekit/issues/1233
