### ISSUE TITLE
Shelly Duo - RGBW

### ISSUE THREAD

**Issue by ulib** [mongoose-os-apps/shelly-homekit#1240]
Hi,
everything went great. Until I changed the password of the WLAN. Now the lamp is no longer accessible ... is also clear that no longer comes in. 

How do I perform a reset? There is no switch... in the original software I think you have to do several times power on / off so plug out / in I have also tried but that did not work. 

Is there a solution?

Thanks

**Comment by timoschilling** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery#from-invalid-wifi-configuration

> On all devices within first 10 seconds after boot, cut the device power and connect it again, repeat that 5 times

**Comment by ulib** [comment]
Thx it works!!!
