### ISSUE TITLE
Garage Door Opener with Shelly 1 and Add on + Reed Sensor

### ISSUE THREAD

**Issue by Cedric9602** [mongoose-os-apps/shelly-homekit#1242]
Hello guys, 
I have the following setup of the garage door opener: 
Via a Shelly 1 and the Add on I have connected a reed sensor as a status monitor, because I can't read the closed or opened signal from the board. Is it possible to read the state of the garage door also via the Add on and a reed sensor instead of the SW input of the Shelly?
Many greetings and thanks :)

**Comment by timoschilling** [comment]
Double of #713

**Comment by Cedric9602** [comment]
Thank you! Haven't found it myself..
