### ISSUE TITLE
Shelly RGBW2 input with 230vac and adapter not working as expected

### ISSUE THREAD

**Issue by OmegaMorello** [mongoose-os-apps/shelly-homekit#1247]
I currently have connected my Shelly RGBW2 with the 110-230VAC adapter as an input so that I can switch it ON or OFF with a wall switch.
Changing the input Toggle causes the LED strip to start flickering really fast as soon as I press the wall switch.
I checked all the connections and they are correct as per Shelly's instructions.

Is there anything I can do to fix it?

**Comment by Morello93** [comment]
This is the log file when it happens:
58687214972 shelly_main.cpp:443     Up 58687.20, HAP 0/1/12 ns 1, RAM: 26076/14856; st 0; 11.1: sta: off, b: 100, h: 224, sa: 100, ct: 400
58692828742 shelly_input.cpp:76     Input 1: change (state 1)
58692834617 shelly_hap_light_bu:197 State changed (switch): off => on
58692847618 shelly_light_bulb_co:99 Starting transition: [r=0.00 g=0.00 b=0.00 w=0.00] -> [r=0.00 g=0.27 b=1.00 w=0.00], 10000 ms
58692852586 shelly_rgbw_controll:38 Output 1: 0.00 => 0.00
58692857155 shelly_rgbw_controll:39 Output 2: 0.00 => 0.27
58692861710 shelly_rgbw_controll:40 Output 3: 0.00 => 1.00
58692866317 shelly_rgbw_controll:42 Output 4: 0.00 => 0.00
58692902442 shelly_input.cpp:76     Input 1: change (state 0)
58692908294 shelly_hap_light_bu:197 State changed (switch): on => off
58692968290 shelly_input.cpp:76     Input 1: change (state 1)
58692974091 shelly_hap_light_bu:197 State changed (switch): off => on
58693037591 shelly_input.cpp:76     Input 1: change (state 0)
58693043401 shelly_hap_light_bu:197 State changed (switch): on => off
58693048574 shelly_input.cpp:76     Input 1: double (state 0)
58693108627 shelly_input.cpp:76     Input 1: change (state 1)
58693114427 shelly_hap_light_bu:197 State changed (switch): off => on
58693177295 shelly_input.cpp:76     Input 1: change (state 0)
58693183027 shelly_hap_light_bu:197 State changed (switch): on => off
58693248622 shelly_input.cpp:76     Input 1: change (state 1)
58693254440 shelly_hap_light_bu:197 State changed (switch): off => on
58693317506 shelly_input.cpp:76     Input 1: change (state 0)
58693323330 shelly_hap_light_bu:197 State changed (switch): on => off
58693328506 shelly_input.cpp:76     Input 1: double (state 0)
58693388501 shelly_input.cpp:76     Input 1: change (state 1)
58693394272 shelly_hap_light_bu:197 State changed (switch): off => on
58693457524 shelly_input.cpp:76     Input 1: change (state 0)
58693463335 shelly_hap_light_bu:197 State changed (switch): on => off
58693528269 shelly_input.cpp:76     Input 1: change (state 1)
58693534075 shelly_hap_light_bu:197 State changed (switch): off => on
58693597296 shelly_input.cpp:76     Input 1: change (state 0)
58693603083 shelly_hap_light_bu:197 State changed (switch): on => off
58693608226 shelly_input.cpp:76     Input 1: double (state 0)
58693668350 shelly_input.cpp:76     Input 1: change (state 1)
58693674151 shelly_hap_light_bu:197 State changed (switch): off => on
58693737623 shelly_input.cpp:76     Input 1: change (state 0)
58693743433 shelly_hap_light_bu:197 State changed (switch): on => off
58693807995 shelly_input.cpp:76     Input 1: change (state 1)
58693813826 shelly_hap_light_bu:197 State changed (switch): off => on
58693882429 shelly_input.cpp:76     Input 1: change (state 0)
58693888254 shelly_hap_light_bu:197 State changed (switch): on => off
58693893765 shelly_input.cpp:76     Input 1: double (state 0)
58693928861 shelly_input.cpp:76     Input 1: change (state 1)
58693934709 shelly_hap_light_bu:197 State changed (switch): off => on
58693996920 shelly_input.cpp:76     Input 1: change (state 0)
58694002702 shelly_hap_light_bu:197 State changed (switch): on => off
58694067874 shelly_input.cpp:76     Input 1: change (state 1)
58694073685 shelly_hap_light_bu:197 State changed (switch): off => on
58694136906 shelly_input.cpp:76     Input 1: change (state 0)
58694142709 shelly_hap_light_bu:197 State changed (switch): on => off
58694147859 shelly_input.cpp:76     Input 1: double (state 0)
58694208119 shelly_input.cpp:76     Input 1: change (state 1)
58694213874 shelly_hap_light_bu:197 State changed (switch): off => on
58694276823 shelly_input.cpp:76     Input 1: change (state 0)
58694282637 shelly_hap_light_bu:197 State changed (switch): on => off
58694347694 shelly_input.cpp:76     Input 1: change (state 1)
58694353440 shelly_hap_light_bu:197 State changed (switch): off => on
58694416551 shelly_input.cpp:76     Input 1: change (state 0)
58694422038 shelly_hap_light_bu:197 State changed (switch): on => off
58694427106 shelly_input.cpp:76     Input 1: double (state 0)
58694487244 shelly_input.cpp:76     Input 1: change (state 1)
58694492724 shelly_hap_light_bu:197 State changed (switch): off => on
58694556864 shelly_input.cpp:76     Input 1: change (state 0)
58694562697 shelly_hap_light_bu:197 State changed (switch): on => off
58694627878 shelly_input.cpp:76     Input 1: change (state 1)
58694633667 shelly_hap_light_bu:197 State changed (switch): off => on
58694696646 shelly_input.cpp:76     Input 1: change (state 0)
58694702460 shelly_hap_light_bu:197 State changed (switch): on => off
58694707614 shelly_input.cpp:76     Input 1: double (state 0)
58694767547 shelly_input.cpp:76     Input 1: change (state 1)
58694773323 shelly_hap_light_bu:197 State changed (switch): off => on
58694836607 shelly_input.cpp:76     Input 1: change (state 0)
58694842367 shelly_hap_light_bu:197 State changed (switch): on => off
58694907641 shelly_input.cpp:76     Input 1: change (state 1)
58694913216 shelly_hap_light_bu:197 State changed (switch): off => on
58694976589 shelly_input.cpp:76     Input 1: change (state 0)
58694982426 shelly_hap_light_bu:197 State changed (switch): on => off
58694987612 shelly_input.cpp:76     Input 1: double (state 0)
58695047446 shelly_input.cpp:76     Input 1: change (state 1)
58695053263 shelly_hap_light_bu:197 State changed (switch): off => on
58695116234 shelly_input.cpp:76     Input 1: change (state 0)
58695121973 shelly_hap_light_bu:197 State changed (switch): on => off
58695187350 shelly_input.cpp:76     Input 1: change (state 1)
58695193163 shelly_hap_light_bu:197 State changed (switch): off => on
58695368202 mgos_sys_config.c:323   Saved to conf9.json
58695383014 shelly_main.cpp:443     Up 58695.37, HAP 0/1/12 ns 1, RAM: 25092/14856; st 0; 11.1: sta: on, b: 100, h: 224, sa: 100, ct: 400
58695417333 shelly_input.cpp:76     Input 1: change (state 0)
58695423161 shelly_hap_light_bu:197 State changed (switch): on => off
58695428429 shelly_input.cpp:76     Input 1: double (state 0)
58702850283 shelly_light_bulb_co:55 Transition finished, end state: [r=0.00 g=0.00 b=0.00 w=0.00]
58703420054 mgos_sys_config.c:323   Saved to conf9.json

**Comment by timoschilling** [comment]
The adapter didn't deliver a clean on/off signal, the on signal is flickering. So it's some kind of a hardware bug. We recommend not to use the adapter. One other option could be a capacitor to stabilize the signal, how to do that you can find via google.
