### ISSUE TITLE
RGBW2 dont work with Wallswitch

### ISSUE THREAD

**Issue by manueltuescher** [mongoose-os-apps/shelly-homekit#1248]
i have wired my shelly rgbw2 according to the diagram below - unfortunately the shelly does not respond to the push button actuations. 

then i rewired everything and wired the bypass -which is included with the rgbw2 shelly- with it. and again, exactly the same problem, the LED strip doesn't give a shit if i have the switch on or not, nothing happens. 

then I reset the rgbw2 to factory settings (factory setting from shelly) and now it works. 

for real is this true that this homekit mod does not support a button/switch? does the switch input I brings nothing? 
or am i missing something? 

thanks for your help, I'm desperate.

![Shelly-RGBW2-LED-Dimmer-Verkabelung](https://user-images.githubusercontent.com/95418143/224790921-76e72c51-ec32-4712-a736-a4236636ba5f.png)

**Comment by timoschilling** [comment]
We support different kinds of switches, you maybe just need to select the right „input mode“. 

But if you have used the ac converter it will not work at all. We didn’t support them. See #1247 for a workaround
