### ISSUE TITLE
Shelly Plus Smoke

### ISSUE THREAD

**Issue by FlightMS** [mongoose-os-apps/shelly-homekit#1249]
Hi,

are there any plans for supporting the Shelly Plus Smoke Alarm?

https://www.shelly.cloud/en/products/shop/shelly-plus-smoke

**Comment by timoschilling** [comment]
Yes and no. Not with a firmware on the device but maybe with a bridge support on a other Shelly. #1233

**Comment by Malaber** [comment]
What kind of bridge would be used to communicate with shelly smoke sensor? Is there some way I/we as community can help with the development here?
