### ISSUE TITLE
Compatibility to Shelly App

### ISSUE THREAD

**Issue by DIY-Bastler** [mongoose-os-apps/shelly-homekit#1251]
Hi there,
First: great work, many thanks! I successfully installed a Shelly 1 with HomeKit.
However, I am wondering if it is normal, that the Shelly app is not connecting to the Shelly 1 running on HomeKit anymore? The app states „device is offline“. Directly after doing the HomeKit firmware update, the app still could find the device.
Thanks!

**Comment by timoschilling** [comment]
Our firmware isn’t compatible with the Shelly app
