### ISSUE TITLE
Support shelly 2.5 PM module

### ISSUE THREAD

**Issue by colussim** [mongoose-os-apps/shelly-homekit#1255]
Hey,
just a short question is the shelly 2.5 PM module supported ? (The 2.5 modules are out of stock ...)

Thanks,
Emmanuel

**Comment by timoschilling** [comment]
I think you mean the „Plus 2PM“, see #1013

**Comment by colussim** [comment]
Yes , thanks

**Comment by timoschilling** [comment]
A 2.5PM didn’t exist. There exists a 2 (discontinued years ago), 2.5 (discontinued weeks ago) and Plus 2PM (current). We already support the 2 and 2.5, but currently not the Plus 2PM.

**Comment by colussim** [comment]
Thank you for these explanations
