### ISSUE TITLE
Doorbell or Sensor as HAP Type für Shelly UNI

### ISSUE THREAD

**Issue by MarkiMarque** [mongoose-os-apps/shelly-homekit#1260]
Hi, very good work. It helps me a lot.
I use a Shelly UNI as a switch for my door intercom. I can use one of the potential free outputs to operate the door buzzer and one input to measure the circuit to the bell. Everything works fine. It is not possible for me to select a HAP type as a "normal" sensor or doorbell.
Is it possible to integrate this in an update?

**Comment by markirb** [comment]
It is already there you only need to use detached mode to achieve this
