### ISSUE TITLE
Garage Door closes after a set time

### ISSUE THREAD

**Issue by Marfre888** [mongoose-os-apps/shelly-homekit#1262]
Hi,

I’m using a Shelly uni to open my apartment garage gate. To avoid tempering with the main gate. I hooked up a remote to open it using the uni. However, this unfortunately means that a contact sensor can’t be installed to read the state of the door

I managed to get it to open successfully. And managed to get it to set to closed again in Homekit once it finishes opening.

However, this gate has an auto close feature of about two minutes, which we make use of, and I can utilise to keep the state of the garage gate true in Homekit

Would it be possible to add the option of Auto close after X minutes? Ideally this has the option of either sending/not sending a pulse.

**Comment by d4rkmen** [comment]
hi, I have managed to use gate's lamp output as an open sensor.
My gate controller has 2 lamp outputs: 
- operation: it's on when gates moving
- gates open: it's on feom the tome gates start opening and till the time its fully closed - best open sensor for me
and not need any contacts

mat be this will help you too
