### ISSUE TITLE
No response in HomeKit when the control center changes.

### ISSUE THREAD

**Issue by Reliktdragons** [mongoose-os-apps/shelly-homekit#1265]
As soon as the control center for HomeKit changes, e.g. Apple TV to HomePod, the Shelly Plus 1 shows no response in HomeKit.

It is accessible via the browser.
A reboot via the browser is enough for it to connect to HomeKit again.

Is there something known?

**Comment by timoschilling** [comment]
Does the same happens when you control it via Home app?

**Comment by Reliktdragons** [comment]
Yes in the Home App it is displayed as no response.
As soon as the control center changes in the Home App at Control Center & Bridge.

**Comment by NS-K** [comment]
Same problem 
Once a new home hub is elected, shelly plus 1PM become unresponsive on homekit and a reboot from the web interface is required
