### ISSUE TITLE
Shelly Plug US plus Homekit firmware?

### ISSUE THREAD

**Issue by dBust3R1** [mongoose-os-apps/shelly-homekit#1267]
I just got a Shelly Plug US plus and I am not finding a homekit firmware for it.  Is there one?  I have some shelly one's flashed and would like to have this plug flashed and working with homekit...  

Any ideas anyone?

The latest shelly firmware has a way to upload a custom firmware from the web interface and it fails with each attempt.  When I try to do the  http://A.B.C.D/ota?url=http://rojer.me/files/shelly/shelly-homekit-ShellyPlug.zip  nothing happens.  

Anyone?

**Comment by timoschilling** [comment]
The firmware you tried is only for the old non plus eu plug. The plus us plug is currently not supported. Support is already requested here https://github.com/mongoose-os-apps/shelly-homekit/issues/1267.
