### ISSUE TITLE
Garage door alert debouncing

### ISSUE THREAD

**Issue by mccahan** [mongoose-os-apps/shelly-homekit#1268]
Hello! I have a Shelly1 hooked up to a normally-closed garage door sensor that works great, except when closing it fires alerts in rapid succession for closed-open-closed, within a second or so of each other. In general, it reads correctly as open when the door is open and closed when it's closed. The gap between the sensor and the magnet might be a little large, but the construction of the door makes it a little difficult to get closer.

Is there any straightforward way to do software debouncing of the sensor signal here to avoid the multiple alerts? A configurable debounce of a second or two would allow it to settle.

Thanks!

<img width="361" alt="Screenshot 2023-04-22 at 19 43 59@2x" src="https://user-images.githubusercontent.com/2308923/233814848-6d5df0a3-d9fe-48d0-8642-bd09c9527ae0.png">

**Comment by timoschilling** [comment]
Double of #1087
