### ISSUE TITLE
HomeKit QR setup code

### ISSUE THREAD

**Issue by yuvalbeck** [mongoose-os-apps/shelly-homekit#127]
It would be great to have auto generated HomeKit codes and QR codes in particular- not having to setup it manually.

**Comment by rojer** [comment]
good idea

**Comment by schemhad** [comment]
That shouldn't be complicated... I'll take a look at that when I got some time to...

**Comment by schemhad** [comment]
@rojer
Is there already some kind of Setup-PIN like e.g. "ABCD"? If not, we have to define it...

The rest looks like Devicetype (like e.g. "5" for a lightbulb), Setup-Code ("111-22-333"), Version "0", Revised "0", Flag "8" (Wireless IP)

So: "511122333008" - to Base36: "6IT11G7K" + Setup-PIN ("ABCD")

URL: "X-HM://6IT11G7KABCD"

This, generated to an QR-Code should/could work ...

**Comment by rojer** [comment]
thing, is we don't store plain-text pin on the device, this is explicitly prohibited by the standard.
does the qr code contain pin in plain text?

**Comment by rojer** [comment]
the only point when we have code in plaintext is when users enters it into the text field. we can generate and display qr code at that point.

**Comment by schemhad** [comment]
I didn't got the dev-docs atm, but ist looks like plain text Setup-PIN to me... maybe we could open an popup window or overlay while setting the Setup-Code with a warning, that the generated QR code will only displayed this one time... otherwise it would be a serious security problem.

**Comment by rojer** [comment]
yeah, we can do that. user can save or print the code for later use if they like.

**Comment by sebastianheise** [comment]
It could just be displayed on the setup website. (Unless there isn't enough memory on the device...?)

**Comment by rojer** [comment]
yes, that's the idea. basically, when you press "save" in the homekit section of the configuration and we have plaintext code value, we should pop up a window with QR code. code can be generated in javascript, so it won't even use much space (only some JS code).

**Comment by schemhad** [comment]
But is there already a default (Setup-)PIN / Password like "ABCD"? 
To secure it, we should generate a random four character PIN at this point, but we have to give it to the OS...

**Comment by rojer** [comment]
> But is there already a default (Setup-)PIN / Password like "ABCD"?

no, there isn't. user has to assign setup pin after flashing. they enter it as plaintext, it is sent to the device as plaintext but is not stored directly, and is instead converted into cryptographic material used for HAP pairing.

**Comment by cduvenhorst** [comment]
This needs be implemented in homekit-adk PAL "HAPPlatformAccessorySetupDisplay.c".

The setup payload will then dynamically change every 5 minutes or so if unpaired. Precondition is a persistent setupID, which may be set in the config or could be generated if the config setting is missing.

**Comment by rojer** [comment]
hm, interesting. @cduvenhorst any chance you could put that in a form of a PR? :)

**Comment by cduvenhorst** [comment]
Sure. But need some more time ...  ;-) The public HAP documentation does not describe R14 devices. Currently homekit-adk acts like a pre r10 device. (HAPAccessorySetupInfo.c)

Had coded most QR stuff in the app, but I feel it belongs in the lib.

Need to implement setupDisplay and setupNFC and understand HAPAccessorySetupInfo-functions ... will devide  the whole thing in some PRs.

**Comment by jsiegenthaler** [comment]
Why not calculate a pin or setup code or QR code from the device MAC address? The MAC address is currently displayed as the Homekit accessory serial number.  That way you have a unique device-specific code.

**Comment by Pixel-Chris** [comment]
My idea:
Add an extra Button:
„Generate random code“
After that the QR-Code and plain-text (the Code) is displayed....

Eventually this could help for the QR-Code generating:
https://developers.google.com/chart/infographics/docs/qr_codes

**Comment by cduvenhorst** [comment]
> My idea:
> 
> Add an extra Button:
> 
> „Generate random code“
> 
> After that the QR-Code and plain-text (the Code) is displayed....
> 
> 
> 
> Eventually this could help for the QR-Code generating:
> 
> https://developers.google.com/chart/infographics/docs/qr_codes

That's the app side. The homekit-adk should implement an rpc service for setup information where the current payload and code is shown. Could even include an svg element for the qr code.

**Comment by andyblac** [comment]
i come across this https://www.studiopieters.nl/esp-homekit-sdk-qr-code/ if it helps

**Comment by rojer** [comment]
we need a JS library to render QR codes

**Comment by andyblac** [comment]
> we need a JS library to render QR codes

like this https://davidshimjs.github.io/qrcodejs/ ?

**Comment by cduvenhorst** [comment]
> we need a JS library to render QR codes

I used https://github.com/nayuki/QR-Code-generator ...

**Comment by rojer** [comment]
alright, this is done and seems to be working. will test in the next release cycle.

**Comment by rojer** [comment]
![Screenshot from 2021-06-03 23-21-53](https://user-images.githubusercontent.com/531307/120719626-82144c80-c4c2-11eb-98c0-825c86bb60ec.png)

**Comment by andyblac** [comment]
nice one 👍
