### ISSUE TITLE
Temperature from Uni & DS18B20 probe? Or only from Shelly 1?

### ISSUE THREAD

**Issue by PeterALee** [mongoose-os-apps/shelly-homekit#1276]
I want to use a Shelly Uni and the DS18B20 temperature probe, and expose the measured temperature  in HomeKit. 
According to the mongoose wiki, this is possible if I use a Shelly1 and the probe, and whilst possible is not yet available with the Uni. is there any likelihood this will be possible in the near future?

**Comment by rplushh** [comment]
adding a bump to this

I know Rojer has been hired by Shelly so this is no longer maintained, but can we please get someone to fork this and add temp probe readings to the homekit firmware for this device. 

Thanks!
