### ISSUE TITLE
No automation in homekit 

### ISSUE THREAD

**Issue by heili1094** [mongoose-os-apps/shelly-homekit#1280]
Hi, since update to new homekit architecture the shelly 1 with latest firmware will not appear if i add new automation with sensor trigger. 
kindly help! I use the shelly as rain sensor.
Thx

**Comment by timoschilling** [comment]
Please post a screenshot of your Shelly config

**Comment by heili1094** [comment]
![IMG_0433](https://github.com/mongoose-os-apps/shelly-homekit/assets/73037103/400c6496-97be-4eb6-b02e-f0b6c2fce70c)
![IMG_0434](https://github.com/mongoose-os-apps/shelly-homekit/assets/73037103/4b411847-187a-4c80-b771-44c874638dd7)
![IMG_0435](https://github.com/mongoose-os-apps/shelly-homekit/assets/73037103/e0ff92bd-11d3-47d9-bfc2-4aa6708a3683)

**Comment by heili1094** [comment]
Instead of „pulse“ i normally use „Level“ for INPUT 1
