### ISSUE TITLE
Calibration fail

### ISSUE THREAD

**Issue by C51B** [mongoose-os-apps/shelly-homekit#1281]
Hi,
With 4 Shelly 2.5 with I have the same issue : calibration always fail and the movement time it set to 5 seconds for a full opening.

<img width="484" alt="Capture d’écran 2023-05-19 à 15 46 30" src="https://github.com/mongoose-os-apps/shelly-homekit/assets/134076938/5f0a3f3f-1676-45f0-a6d8-f435057e96c1">

Is it possible to configure the opening and closing time manually?

**Comment by larsilus** [comment]
I also thought, that it may had failed, when it stopped at pos 50. i just clicked open, waited for it, clicked save and everything was fine then in homekit.

**Comment by janHB28201** [comment]
i have the same problem. Will the problem be fixed?

**Comment by C51B** [comment]
No. I give up. Le 22 juin 2023 à 22:07, janHB28201 ***@***.***> a écrit :﻿
i have the same problem. Will the problem be fixed?

**Comment by timoschilling** [comment]
There is a PR with that feature, in that PR is also a beta build linked. https://github.com/mongoose-os-apps/shelly-homekit/pull/449
