### ISSUE TITLE
LED bulb stays on when Shelly1 toggled off

### ISSUE THREAD

**Issue by sam-lappage** [mongoose-os-apps/shelly-homekit#1286]
With the physical switch in the off position, the Shelly controls the LED bulb as expected. With the switch on and Shelly toggled off, the bulb is very dimly lit with a slight flicker.

The bulb is non-dimmable. I’ve also tried with a Philips Hue Bulb which flickers on and off in the same situation. 

The relay isn’t clicking on and off, it’s just the bulb

**Comment by timoschilling** [comment]
As the Shelly1 can only on or off, which only changes with the click of the relay. It sound more like you have some kind of wiring issue. If you say that the relay didn't change the state, I didn't know how the software can effect that.
