### ISSUE TITLE
Shelly 1 on 24V AC: unresponsive, but fully functional on 12V DC?

### ISSUE THREAD

**Issue by tomvredeveld** [mongoose-os-apps/shelly-homekit#1288]
Hi, 

Two months ago I connected a Shelly 1 on my Hormann Promatic 2 garage door, including a cheap Reed magnetic sensor to assign a closed or open state of the door. It worked flawlessly, until I tried to fiddle a bit with my network/wifi settings (unrelated to the Shelly), which crashed the whole network. Unfortunately, since then, the Shelly 1 can't be found anymore. Also, till this crash the wifi was not set-up properly: multiple access points on the same SSID and 2.4Ghz and 5Ghz channels on the same SSID name. 
After the crash I decided to update to a separate SSID for the 2.4Ghz for the Shelly to connect to. I unhooked the shelly 1, set-it up with a 12v DC adapter, rebooted and adjusted the Mongoose settings. Note: I did not use 'reset', because it looked fine as is.

Before hooking it up again to the garage door, I decided to enable the Shelly's stand-alone AP wifi, just to be sure.
I then installed the Shelly back into the garagedoor (of course altering the jumper setting). But with no result, the Shelly is unresponsive: cannot be found on the network and no 'stand-alone AP'. 

To conclude: on the 12v DC adapter, unhooked from the garagedoor, everything worked immediately, while connecting it back to the 23v AC garagedoor: no AP on the Shelly and it can't be found on the network. 

Does anyone have any suggestions? Could it be that I somehow cooked the 24-220 AC circuitry? Is that even possible separately from the 12v DC? 

I hope you could help me out.

**Comment by timoschilling** [comment]
If you have hardware issues, this is not the right place. 

But yes it’s possible that only the 24-230V part is broken. You could check that by wiring it to 230v
