### ISSUE TITLE
API LIST

### ISSUE THREAD

**Issue by DavideTommasin** [mongoose-os-apps/shelly-homekit#1290]
hello, I can't find a complete list of your APIs, other than the one already written in the API section in the documentation (like /rpc/Shelly.SetState or /rpc/Shelly.GetInfoExt). Is it possible to have a list of all possible calls to be made via http? Thank you

**Comment by timoschilling** [comment]
You can find a list hier in the code: https://github.com/mongoose-os-apps/shelly-homekit/blob/master/src/shelly_rpc_service.cpp#L577-L604
