### ISSUE TITLE
Power off on power threshold

### ISSUE THREAD

**Issue by askarkurymbayev** [mongoose-os-apps/shelly-homekit#1294]
Hello dear friends!
question: is it possible to implement a circuit breaker by current consumption?
for example, I put my electric scooter on charge, when charging it consumes around 120W, and at full capacity it reduces to 10W
is it possible to implement so that we can set the threshold for switching off the relay, in devices where there are electricity measurements?

**Comment by timoschilling** [comment]
At the moment you can do that via HomeKit automatisations. You need to use HomeKit apps like Eve or Home+ to create such automatisations, because the Apple Home app doesn't support it.

We have already a open feature request to support it on device.
