### ISSUE TITLE
HomeKit widget not reflecting on/off (switch state) for Shelby 1

### ISSUE THREAD

**Issue by i-am-meikle** [mongoose-os-apps/shelly-homekit#1298]
Hi, 

I have a Shelby 1 (v3) which is connected to a switch and a light. I have tried it both with and without the switch connected. 
I flashed the HomeKit fireware (which worked very painlessly 👍) and included the Shelly 1 as a Light in HomeKit. 
This all worked fine and I can see the Light in HomeKit. 

I can operate the Light from the Fireware homepage (The Shelly 1's own webserver) OK and the status of the switch is correctly reflected on the website if I manually operate the switch. 

In the HomeKit app, I can see the Shelly 1 as both a light and a switch

![image](https://github.com/mongoose-os-apps/shelly-homekit/assets/27567928/c9877764-0721-4def-9555-4d8e7d8cf1cc)

If I select the "Light" it turns on/off the light as expected.

If I select the Switch

![image](https://github.com/mongoose-os-apps/shelly-homekit/assets/27567928/1ab006d2-2ec7-4ab6-a6e0-feaef7237f1e)

When I try and toggle the switch, it switches the light on/off but always immediately returns to show the light as "off".
Is this a config problem on my side, or an issue ?

Thanks
Ian

**Comment by i-am-meikle** [comment]
Humm ... strange.
Literally just after I posted this, HomeKit crashed on my phone and when I restarted it, the Shelly 1 is now shown as a Light (not a switch). I did no changes at all.

![image](https://github.com/mongoose-os-apps/shelly-homekit/assets/27567928/0992f274-3eeb-448e-8681-a41c0759cb64)

It now works as expected.
Anyone else experience this ?

**Comment by jactmp** [comment]
Not this. But since introduction (degradation?) of new Home architecture in iOS 16 I experience some other issues. Quite often have to restart Home app (e.g. after pairing new device) to actually see the changes. Now I'm doing it every time - just in case (e.g. to avoid such problems like yours).

**Comment by timoschilling** [comment]
Solved
