### ISSUE TITLE
Edge switch support 

### ISSUE THREAD

**Issue by kmetabg** [mongoose-os-apps/shelly-homekit#13]
Shelly1/2.5 should support at least 3 main types of the switches: 
1. Momentary (Push buton)
2. Toglle (On and Off position)
3. Edge - Every change of the switch state change the output state (this is using alot's in 2-way and 3-way wiring).

**Comment by rojer** [comment]
and we do already, have you checked web interface settings? there's input mode dropdown in the switch section.

**Comment by kzyapkov** [comment]
indeed, you can close this. Dimitar wasn't looking at the latest version
