### ISSUE TITLE
New HomeKit Architecture makes Shelly unreliable

### ISSUE THREAD

**Issue by optikalefx** [mongoose-os-apps/shelly-homekit#1302]
I've read the closed issues that it shouldn't be an issue, but that's not been my experience. I've been using a Shelly1U with a light switch for a year now. I was always very happy that it worked 100% of the time.

This morning I upgraded homekit to the new arch. Immediately following, the shelly + automation (in homekit) works about 50% of the time now. 

I have a shelly on a switch that runs an automation that controls another homekit outlet. 

Has anyone else seen issues with the new homekit? I'm not sure what else it could be. All of my testing leads to the Shelly as the issue all of a sudden.

https://support.apple.com/en-us/HT213481

**Comment by timoschilling** [comment]
What’s the argument for that it is a bug on our firmware? Experience isn’t one. Issue will be reopen if you deliver one.
