### ISSUE TITLE
Shelly Vintage

### ISSUE THREAD

**Issue by sjiiang** [mongoose-os-apps/shelly-homekit#1303]
I flashed my vintage bulb with the firmware last time and it worked all fine. lately I want to reset the bulb to factory however it doesn't work nomatter how many times I turn it on and off. 
I am wondering, are there any background settings with the firmware so it can be only reset in a different way?

**Comment by timoschilling** [comment]
What do you want to achieve? Removing all settings or getting back to the original firmware?

**Comment by timoschilling** [comment]
Turn on the bulb for ~5 sec and then turn it of, repeat that 5 times. Then the wifi settings should be reseted.
