### ISSUE TITLE
Shelly 1 Garagedoor wrong status

### ISSUE THREAD

**Issue by baseship** [mongoose-os-apps/shelly-homekit#1306]
All Devices are up to date.
Since about three weeks, the Shelly1 has a problem with the gate status,
contact-sensor is in close position assembled and works fine (tested it), settings in software - normally closed.

When door is closed - status is open or blocked
When door is open - status is everytime blocked

I've tried changing the gate movement times, all to no avail...

Can someone help?

**Comment by timoschilling** [comment]
Sounds like a hardware problem with the Shelly

**Comment by baseship** [comment]
That's what I'm afraid of now, I'll replace it the next few days.
