### ISSUE TITLE
Auto off delay

### ISSUE THREAD

**Issue by 49adrien** [mongoose-os-apps/shelly-homekit#131]
Hello,

I don't understand how to put one second for the function :

<img width="361" alt="Screenshot" src="https://user-images.githubusercontent.com/65712163/92467070-4f5a5380-f1d1-11ea-9f6f-2701b173a7a6.png">

Thanks

**Comment by andyblac** [comment]
the above is correct for 1 second

DAYS : HOURS : MINS : SECONDS : MILLI-SECONDS

**Comment by 49adrien** [comment]
I found the problem :

0:00:00:01.000 no 0:00:00:01:000
