### ISSUE TITLE
Roller shutter - Delay time between open/close switch

### ISSUE THREAD

**Issue by TACiboy** [mongoose-os-apps/shelly-homekit#1318]
When the Shelly (e.g. Shelly 2.5) is used as a roller shutter, it often comes to a situation where a roller is being opened and suddenly the close signal is set. In such a situation the motor of the roller switches from opening to closing status. This happens immediately without any delay.

Unfortunately most of the shutter producers specify, that between a signal change a delay time has to be considered in order that peak currents can be avoided and capacitors have the time to unload. This rule avoids damage to the shutter motor.

Would it be possible to implement a delay time when the Shelly is being used in Roller Shutter mode? You may add a new feature "Input Delay" that can be configured as minimum number of (milli)seconds that the Shelly waits before changing the relays from opening to closing.

That would be a real cool feature and improves the safety significantly!!!

**Comment by lucatk** [comment]
Reopening - why has there been no feedback on this?
I +1 as I see it as relevant and also slightly useful in an UX sense, as right now when the roller is at say 60% and I want it to open fully, I'm tapping the shutter icon in Apple Home, but I have to quickly tap twice so it goes from closing to opening and have to hope I'm lucky so the relais/motor doesn't hiccup and dismiss the Open action.
