### ISSUE TITLE
[Flash Script] features....

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#132]
Hi guys,

For those of you that use my script would it be beneficial to add an option to flash a specific version, so you can move between versions when @rojer is releasing test versions ?

If  there is anything you would like to see please comment below.

**Comment by andyblac** [comment]
@rojer can you tweak the model id in the ShelllyInfo so it matches the Firmware file names ie

Model: Shelly2.5 to Model: Shelly25

**Comment by andyblac** [comment]
@rojer never mind I work around it.

**Comment by andyblac** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/pull/134

**Comment by andyblac** [comment]
@rojer Thinking of adding some text formatting, what you think Y/N ?

![Screenshot 2020-09-19 at 00 32 49](https://user-images.githubusercontent.com/77936/93653204-cb456e80-fa0f-11ea-9be3-30c8b35dece4.jpg)

**Comment by rojer** [comment]
flashy flasher :)
yeah, why not

**Comment by andyblac** [comment]
what you think ?
![Screenshot 2020-09-20 at 15 09 00](https://user-images.githubusercontent.com/77936/93713367-42cfe680-fb53-11ea-9f41-3caf46b99930.jpg)

**Comment by rojer** [comment]
looks ok so far

**Comment by andyblac** [comment]
@rojer thinking of adding a exclude option to the script ie `./flash_script -ae hostname` is -e ok with you ?

this would basically skip the referenced hostname when using -a. 

ie atm my shelly25 is in debug mode for you to keep an eye one with the HAP drop issue, so I don't want it to update it's fw.

**Comment by rojer** [comment]
SGTM

**Comment by rojer** [comment]
i think you can also remove DURL from output, for most users it's just noise.

**Comment by andyblac** [comment]
> i think you can also remove DURL from output, for most users it's just noise.

ye I have in the formatting commit  :smile:

**Comment by andyblac** [comment]
just working on -e, will push both soon

**Comment by andyblac** [comment]
To much ?

![Screenshot 2020-09-21 at 11 48 53](https://user-images.githubusercontent.com/77936/93758545-90eef380-fc00-11ea-9149-1fbb4d6866eb.jpg)

**Comment by rojer** [comment]
yeah, i'd say it's a bit much.
highlighting just the version numbers / status is enough, i think.
final result can be in default color

**Comment by andyblac** [comment]
ok np

**Comment by andyblac** [comment]
exclude and text formatting PR done https://github.com/mongoose-os-apps/shelly-homekit/pull/143.

**Comment by andyblac** [comment]
what do you think ?, until we can name devices in webUI, it should help identify the device. I would prefer to be able to edit device name.

![Screenshot 2020-09-21 at 14 45 45](https://user-images.githubusercontent.com/77936/93774562-4d54b380-fc19-11ea-8f9d-89c7e754e738.jpg)

**Comment by andyblac** [comment]
@rojer been thinking about all these betas, would be possible when you release beta's to release it on your server in a beta folder, then I could add a -b flag to script for 'betas' it could search if there is a beta to test?

ie
`http://rojer.me/files/shelly/beta/$lfw/shelly-homekit-$model.zip`

**Comment by andyblac** [comment]
and maybe a txt file in the root beta folder with release tag info.

ie
`http://rojer.me/files/shelly/beta/release.info`

**Comment by rojer** [comment]
yeah, i've been thinking about it myself.
i've been putting some groundwork for it, maybe will get to it for the next release cycle (i.e. after 2.2)

**Comment by andyblac** [comment]
we now have python script, it should work on all OS's requires python 3.6
