### ISSUE TITLE
ShellyPlus1 GarageDoor disconnected

### ISSUE THREAD

**Issue by tobias11-at** [mongoose-os-apps/shelly-homekit#1320]
Hello,

the Firmware generally works Fine, but After some days there is "no response" in HomeKit. The device is still connected to Wifi. Is there any Solution for that issue?

Thank you.

Tobias

**Comment by leilok** [comment]
Same here… 
With the difference that I just installed the last version from stock.

Erratic working, seems to be

**Comment by tobias11-at** [comment]
2.11.2?

**Comment by tobias11-at** [comment]
100% same behaviour here. Also same Installation.

**Comment by leilok** [comment]
Just changed today the mechanic switch, and the issue seems to be solved!!!
