### ISSUE TITLE
Support for Shelly Plus 1 Mini

### ISSUE THREAD

**Issue by alessiobulfaro** [mongoose-os-apps/shelly-homekit#1321]
Hi,
Shelly newly released mini versions of some Shelly Plus devices, such as the Shelly Plus 1 Mini.

Basically it is the same as the Shelly Plus 1 (https://shelly-api-docs.shelly.cloud/gen2/Devices/ShellyPlus1/), but has an own device model ID.

I've two test device if needed. Hope support for these devices will be added easily.

**Comment by geekpav** [comment]
Stay away from the MINI version of the Shelly Plus 1 PM if you are using Homekit... There is no way to flash the module to a Homekit firmware. One thing you can do is to use it through a Homebridge server, however it doesn't work very nicely : it appears doubled on the "Apple" Home interface. I replaced my Shelly Plus 1 PM MINI modules with ordinary Shelly Plus 1 PM, flashed to Homekit, which work seamlessly.

**Comment by timoschilling** [comment]
double of https://github.com/mongoose-os-apps/shelly-homekit/issues/1313

**Comment by djcargo** [comment]
I'm using some Shellys Mini with Home Assistant, which puts it to HomeKit and it works fine.

**Comment by DHEVAN1** [comment]
How do you make it to where it can be used in HomeKit when it's running on home assistant?

**Comment by djcargo** [comment]
I have used link from here: https://www.home-assistant.io/integrations/homekit/

There's button "Add integration to...", and this integration showed in my Settings->Devices&Services
