### ISSUE TITLE
Controlling issues

### ISSUE THREAD

**Issue by Imburdalinix** [mongoose-os-apps/shelly-homekit#1322]
So there are multiple issues I've been facing recently involving the Shelly 2.5 with HomeKit.

For starters, if the roller shutter is at about 20% you can easily control it by taping on (for example) 80%. But as soon as you tap on 100% it doesn't go up, but down. It reverts the input on a full value like 100 or 0... I made a video trying to demonstrate the problem. In the video I showed that controling the shelly inbetween 1 and 99% is working fine, but as soon as you click a MAX or MIN value, it just reverts the output. Click [here](https://www.icloud.com/iclouddrive/048juAdcv-0wAcKte0Ajngx0A#Shelly_Bug) or on the link below to view the video.

https://www.icloud.com/iclouddrive/048juAdcv-0wAcKte0Ajngx0A#Shelly_Bug

**Comment by Imburdalinix** [comment]
I would be happy to get a response ☺️

**Comment by Teimotronic** [comment]
Same problem here. Even if I slide the slideer, the roller shuttle stops at random positions.

**Comment by ramosmfilipe** [comment]
I have the same issue, slider just jumps to random positions. only "open all" and "close all" automations via homekit work properly. Please help.

**Comment by Imburdalinix** [comment]
Hello, is it possible that anybody could respond to this problem? It has been almost 3 months since this post has been made. If you could just explain how you're currently progressing instead of staying silent that would be great.

**Comment by Teimotronic** [comment]
The problem still remains

**Comment by Imburdalinix** [comment]
Okay, so I've seen that Timo Schilling has seen the video. Could you, mr. Schilling, please respond to this issue or at least give us an update? 
Thanks!

**Comment by lucassite120** [comment]
I had issues with my roller shutters too. Since Rojer leaves development of this firmware, I researched alternatives and I found this firmware: https://github.com/RavenSystem/esp-homekit-devices/wiki

It's actively developed and my shutters work like a charm. I hope this can help you.
