### ISSUE TITLE
RGBW2 / Control with Switch not possible

### ISSUE THREAD

**Issue by BA0815** [mongoose-os-apps/shelly-homekit#1323]
Hello team,
I have a problem with the button controls after flashing my shelly rgbw2.
The control works with the original software (button type edge switch).
After flashing on Shelly Homekit, the control via the wall switch does not work. The LED strip then just starts to flicker.
Switching on/off no longer works.

Is there anything to consider when flashing?
What am I doing wrong?

Electricity Europe 230V AC

**Comment by timoschilling** [comment]
Are you using the AC/DC converter (black with two wires on each side)?

**Comment by BA0815** [comment]
yes, I used the included converter.

**Comment by timoschilling** [comment]
We do not support that. Change your setting to not use that adapter or use the stock firmware

**Comment by przemekpobuta** [comment]
@timoschilling Do you plan to support that in the future?

**Comment by timoschilling** [comment]
We do not have a explicit plan to support it. But that not mean at never will happen. Maybe someday someone will implement it.
