### ISSUE TITLE
Shelly 1 wont update (file not found / invalid file signature)

### ISSUE THREAD

**Issue by 6nfanatic** [mongoose-os-apps/shelly-homekit#1327]
Hi, i have a Shelly 1 with tasmota running.
Tried to get the homekit-FW running but it just wont accept it no mather what i try.

If i try to upload the .zip through the tasmota updater it say "invalid file signature".
If i try to upload via the OTA link, it say strangely "File not found".
I tried flashing the tasmota minimal but didnt change a thing.
Then i tried to revert to the oem shelly firmware but it say "insufficient space", eventhough i am on the minimal.
From the last error i guess its not accepting the .zip, rather waits for a .ota or .bin.

**Comment by timoschilling** [comment]
We don’t give support for the update from tasmota to our firmware. I only can give you to hint: https://github.com/yaourdt/tasmota-to-mgos
