### ISSUE TITLE
Not able to add the device to homekit

### ISSUE THREAD

**Issue by markbellus** [mongoose-os-apps/shelly-homekit#1329]
I've tried several times to add the device after the firmware switch but when pairing the device says connecting then "Unable to add accessory, failed to add the accessory". 

Is there any solution for that? :(

**Comment by markbellus** [comment]
After dozens of tries like 40 or so, it has been finally added. 
If I can ask another question here after the first open it always says "Obstructed" in the home app.

Do you know how I can fix this? 
Should I install a magnetic sensor on the Shelly?

**Comment by timoschilling** [comment]
For some unknown reason it take sometimes many tries to add the Shelly to HomeKit. 

Yes you must have some kind of closing state sensor!
