### ISSUE TITLE
Shelly Motion 2 support

### ISSUE THREAD

**Issue by jmaferreira** [mongoose-os-apps/shelly-homekit#1330]
Hi.

Are there any plans to support Shelly Motion 2 (https://kb.shelly.cloud/knowledge-base/shelly-motion-2)?

Cheers

**Comment by timoschilling** [comment]
Definitely not native. Because of the CPU (non ESP) and because HomeKit over Wifi didn't work for battery devices. Maybe we make a bridge support as in #1233
