### ISSUE TITLE
Request: Relay Disable

### ISSUE THREAD

**Issue by robbinsmisc** [mongoose-os-apps/shelly-homekit#1331]
I would be interested in having an option on the device webpage to disable the relay; where the HomeKit commands are ignored and the fixed state is reported back.  We use a Shelly 1+ to control a fountain pump that should not be turned on physically in the winter.  I typically turn the breaker off for the season, but then we have an unresponsive accessory for a few months.  I can/will add a physical lockout switch inline to the pump, but a software option could be useful for various applications.

**Comment by timoschilling** [comment]
double of #1007
