### ISSUE TITLE
Shelly Plus1 not connecting after reverting to stock fw

### ISSUE THREAD

**Issue by BeigeRonin** [mongoose-os-apps/shelly-homekit#1333]
Hi. I needed to revert one of my Shellys back to the stock firmware, but in doing so, the Shelly is now just stuck in an unaccessible state. The screen just displays "Connecting to Shelly" but nothing happens. It's still connected to my Wi-Fi network.

Any ideas please?

**Comment by timoschilling** [comment]
Where do you exactly see the "Connecting to Shelly" text? Please post a screenshot.

**Comment by BeigeRonin** [comment]
The browser when I try to connect to the Shelly...

![Screenshot 2023-11-10 at 08 06 20](https://github.com/mongoose-os-apps/shelly-homekit/assets/150284284/2b4badcb-429e-4a85-85f3-9c0680b0ba1f)

**Comment by BeigeRonin** [comment]
> Where do you exactly see the "Connecting to Shelly" text? Please post a screenshot.

Hi Timo - see above. Do you have any idea what I can do with the Shelly to recover it, or should I just replace it and start again? Thanks

**Comment by timoschilling** [comment]
Sorry I have no idea.

**Comment by Ju17091** [comment]
Remove the fuse briefly. And then switch the shelly several times using the light switch until you hear a click. Shelly then returns to the factory settings and can be set up again via WifiAP
