### ISSUE TITLE
Shelly 1 unresponsive on Chamberlain garage door motor

### ISSUE THREAD

**Issue by sebw** [mongoose-os-apps/shelly-homekit#1335]
This is more a FYI for others, so I'm going to open this and close it immediately.

My Shelly 1 (gen 1) running  2.11.2 powered by a 12V DC power brick was stable for a couple of days in my office.

I replaced my garage door with a Chamberlain ML1000EV that provides a 30V DC output and decided to control the garage door with that Shelly.

After plugging to the 30V output, the Shelly was becoming unresponsive (no web UI, no ping) after a couple of minutes. When opening the garage door with the Chamberlain remote, the Shelly was coming back to life.

I reverted back to stock firmware and it was stable for a full night.

Conclusion: I went back to plugging on the 12V power brick and it's stable again.
I don't know much about electricity but from the look of it the 30V DC provided is not stable when the motor goes in standby.

**Comment by simical** [comment]
Only for Information, can be closed:
I had the same problem with my Chamberlain MV1040 EV. In a manual from Liftmaster I found the solution:

Power supply for external devices (terminal 30V)
30VDC/max 50mA
Note: For external (universal) receivers, the under 1 watt standby mode must be turned off.

P. Turning on/off the under 1 watt standby mode
The under 1W standby mode is always switched on at the factory (After the lights go off and with the garage door closed.)
Switch off under 1 watt standby:
1 Disconnect device from the mains
2 Press the UP and DOWN buttons on the back on the adjusting panel simultaneously and hold
3 Connect the device again while the buttons are still pressed
4. After about 5 seconds the opener’s light flashes 10 times as confirmation.
Note: Every time the opener is disconnected from the mains, the opener’s light flashes 10 times during reconnection to indicate that the under 1 watt standby mode is off.
Switch on under 1 watt standby: See activation
