### ISSUE TITLE
2 phones 

### ISSUE THREAD

**Issue by djurokap** [mongoose-os-apps/shelly-homekit#1342]
Hi can somebody help me, I cannot add on the second phone shelly 1 switch, I don't understand why I cannot

**Comment by timoschilling** [comment]
In fact you didn’t connect a Shelly to your iPhone, you connect it to your HomeKit Home. The iPhone is just the connection tool. You can’t add one Shelly to two homes, but you can add multiple iPhones to one Home. Read the Apple docs for that.
