### ISSUE TITLE
Feature request - Energy usage based switching

### ISSUE THREAD

**Issue by gyrospita** [mongoose-os-apps/shelly-homekit#1345]
I‘m running a Plug S on a very old but bulletproof HP laser printer. The standby usage when idle is massive, around 12W and goes up to 600W when printing. I used to have an energy usage based switching enabled on my previous smart plugs (AVM Dect200) which I‘m missing here. 

It would be great to get an automatic switching mode that shuts off the outlet when less/more than X amount of watts have been used for Y minutes, otherwise timer must be reset (when new print job comes in). I used to set „below 15W for 15 minutes, then switchoff“ to allow for incoming print jobs from cups/airprint. 

The prerequisites are already there as the plug S measures energy and allows for timer based switch off. 

Thanks!

**Comment by timoschilling** [comment]
There is already a issue for that request.
