### ISSUE TITLE
Shelly Plus Plug US Support

### ISSUE THREAD

**Issue by ukiews** [mongoose-os-apps/shelly-homekit#1348]
Could someone clarify whether the PLUS Plug US is supported?

Looks like someone asked about this before, and it was marked as completed, but the update process does not seem to work.
I am running on firmware 1.0.8. 
It also appears that the stock firmware mislabels the device as simply Shelly Plug US.

**Comment by timoschilling** [comment]
We currently didn't support any of the US Plugs.

We have a test version for the old non plus US Plug, but not for the Plus US Plug.

To clarify which one you have post a screen shot of the UI.
