### ISSUE TITLE
Shelly 2.5 Slider doesn't work properly

### ISSUE THREAD

**Issue by Flummyn** [mongoose-os-apps/shelly-homekit#1357]
Hello,

I have the problem with my Shelly 2.5 in shutter mode.
If I set it to 100% the shutter closes and at 0% it opens
1-99% everything works

Maybe someone can give me a tip

**Comment by michal-czw** [comment]
@Flummyn Try changing "Swap Outputs" (and/or "Swap Inputs" if needed) to swap open-close points. You can also change the order of wires connected to Shelly outputs ("01" and "02") but it's easier to swap outputs in the settings.
