### ISSUE TITLE
Shelly Plus series Bluetooth support

### ISSUE THREAD

**Issue by hejsiri** [mongoose-os-apps/shelly-homekit#1359]
Is it possible to add to the software support for the Bluetooth module, which is available on all Shelly PLUS series and newer devices, to allow the addition of Shelly BLU sensors such as opening sensors, motion sensors, button?

**Comment by marvinjoa** [comment]
I would also love to have bluetooth enabled, so i can use it as a bluetooth proxy.

**Comment by timoschilling** [comment]
replaced by #1233
