### ISSUE TITLE
Unable to add button actions to a Stateless Switch

### ISSUE THREAD

**Issue by brsnik** [mongoose-os-apps/shelly-homekit#1362]
When I press the switch I'd like to be able to turn on a light connected via an Ikea Hub.

<img width="531" alt="Screenshot 2024-01-26 at 10 06 07" src="https://github.com/mongoose-os-apps/shelly-homekit/assets/14618565/3fb9db7f-00ba-4fef-9c2e-dfdb76a281cb">

![IMG_5146EBD271B7-1](https://github.com/mongoose-os-apps/shelly-homekit/assets/14618565/47d890c8-254c-48d2-9e3c-850a2f8fb12c)

However I am not able to save Actions in Apple Home. Get the following errors:

![IMG_D6F5897C6FEF-1](https://github.com/mongoose-os-apps/shelly-homekit/assets/14618565/82721948-785a-4e28-a2b5-cdd5c89a0925)
![View recent photos](https://github.com/mongoose-os-apps/shelly-homekit/assets/14618565/efa6c1ba-f8cd-402a-982f-2b8891aeacab)

**Comment by timoschilling** [comment]
I expect that's a problem with your Home setup or with the Home app and not with the accessory.

What happen when you create other automatisations?

**Comment by brsnik** [comment]
When I set the type to Contact Sensor, I was able to make an automation. But not with Stateless Switch. Unfortunately Contact Sensor does't solve my problem, and I really need Stateless Switch.

Might be a Home app issue/bug. IDK.
When you say problem with my home setup what do you mean?

**Comment by brsnik** [comment]
Still having this issue...
