### ISSUE TITLE
Quick access to Lock when doorbell rings

### ISSUE THREAD

**Issue by karpitsky** [mongoose-os-apps/shelly-homekit#1365]
Hello,

Thank you for this project! 

Is there an option for quick access to unlock the door when the doorbell rings? For example:
![yyIDjVi](https://github.com/mongoose-os-apps/shelly-homekit/assets/558554/fa6c7e4d-3470-457e-9724-8ba8e7e0c32c)

I have a Shelly Uni connected to an intercom, and when I tap the "doorbell ring" notification, I'm taken to the doorbell's empty screen.
![2024-02-05 13 02 33](https://github.com/mongoose-os-apps/shelly-homekit/assets/558554/ccf89cd9-e44c-448d-a805-0ce00408c44c)

As far as I understand, I need a dummy camera to have this interface in the Home app, or maybe I'm missing some settings?

**Comment by timoschilling** [comment]
Yes you are right, you need a camera or a dummy, a shelly didn't have the capacity to provide a dummy, so we can't do that. Look for a HomeKit bridge system which may have plugins for that.
