### ISSUE TITLE
Unable to flash a shelly 1

### ISSUE THREAD

**Issue by atomtoto** [mongoose-os-apps/shelly-homekit#1367]
I tried to install the homekit firmware on my shelly 1 by flashing it with a usb adapter. The installation works, the flash ends completely, but when I reboot my shelly (by plugging it in/unplugging it), it does not appear in the list of available wifi. What can I do?

**Comment by timoschilling** [comment]
> by plugging it in/unplugging it

Are you still using the usb flash adapter? It could be possible happen that the adapter boot it in the flash mode. Try to boot it with the regular power system 230V (or what you need).

**Comment by atomtoto** [comment]
> > by plugging it in/unplugging it
> 
> 
> 
> Are you still using the usb flash adapter? It could be possible happen that the adapter boot it in the flash mode. Try to boot it with the regular power system 230V (or what you need).

Unfortunately it doesn’t work either (that I power it separately or from the adapter, moreover it is no longer in flash mode)

**Comment by timoschilling** [comment]
Can you read the logout on the TX/RX interface during and after the boot und post it here.

**Comment by atomtoto** [comment]
> Can you read the logout on the TX/RX interface during and after the boot und post it here.

Do you know a way to do that on macOS? Thanks!

**Comment by timoschilling** [comment]
The most tools that can flash a shelly, also can read the TX/RX. You can use the [mos cli tool](https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md) or espflash.
