### ISSUE TITLE
Unreachable in HomeKit from time to time

### ISSUE THREAD

**Issue by loki-sft** [mongoose-os-apps/shelly-homekit#1369]
My Shelly1 (firmware 2.11.2) is loosing connection to HomeKit from time to time. The WebUI is still working and I can reboot the device. After reboot it's available in HomeKit again.
Is there a way to reboot it every night?
Are there any logfiles I can check to identify the root cause?

**Comment by timoschilling** [comment]
We have issues like that in the past, it mostly was a connection issue between the Shelly and your HomePod or Apple TV.

**Comment by timoschilling** [comment]
In the System section is a link to the log, but you need to keep the browser open.
