### ISSUE TITLE
Support for Shelly Dimmer 2

### ISSUE THREAD

**Issue by lukenukemmp3** [mongoose-os-apps/shelly-homekit#1372]
Hey there, will it be possible to support the Shelly Dimmer 2 in a future update? Since the 1L seems to be discontinued and without a follow-up this would be very helpful as the dimmer 2 also needs no neutral line to work.

Thank you very much in advance!

**Comment by lucassite120** [comment]
HAA firmware is compatible with Shelly Dimmer 2.
https://github.com/RavenSystem/esp-homekit-devices/wiki
