### ISSUE TITLE
HomeKit server not running

### ISSUE THREAD

**Issue by sdoeker** [mongoose-os-apps/shelly-homekit#1374]
I have a new Shelly Plus 1 and have installed the HomeKit firmware. 

On the web interface under “HomeKit Settings” it says “Connections: server not running”. 

When I press setup I get the message: "undefined is not an object (evaluating 'info.code.replace')" 

and the log says: 
"184248081 mg_rpc.c:314 HAP.Setup via WS_in 192.168.178.69:59393
184748597 mgos_sys_config.c:323 Saved to conf2.json".

I have tried all available firmware versions and I always get the same error. I don't understand...

**Comment by muehlhaus** [comment]
Thank you for this fantastic project!
While it works well with Shelly 1 … I have the same problem (see above) with my Shelly plus 1.

Help would be greatly appreciated.
