### ISSUE TITLE
Shelly as a Light?

### ISSUE THREAD

**Issue by freddygl** [mongoose-os-apps/shelly-homekit#1376]
Hello, first of all I say that this firmware is wonderful, thanks for the work.
More than an incident, it is a doubt. Would it be possible, in addition to showing the shelly as a door or switch, to show it as a light?
Thank you.

**Comment by timoschilling** [comment]
Configure the Shelly as switch, then you can configure it in the home app as light. 

https://github.com/mongoose-os-apps/shelly-homekit/assets/165599/a66a60c6-b484-4782-83c3-ceb219d39954
