### ISSUE TITLE
Shelly humidity&Temperature sensors

### ISSUE THREAD

**Issue by vrpt2022** [mongoose-os-apps/shelly-homekit#1377]
HI!

Any chance of making new humidity&temperature sensors compatible with HomeKit?

https://www.shelly.com/en-pt/products/product-overview/shelly-blu-h-and-t/shelly-blu-h-and-t-mocha

https://www.shelly.com/en-pt/products/product-overview/shelly-h-and-t-gen3-matte-black/shelly-h-and-t-gen3-mocha

After trying some other brands (even with matter) none of them have the reliability of Shelly products...

Thank you

**Comment by PhleepHampster** [comment]
I see a 2022 thread.  Last response was "waiting for a test device".  It seems the Shelly 1/1PM is no longer sold in the US and newer/available Addon does not fit them anyway.  Any later updates on Addon support for the Plus versions?  Thank you.

**Comment by hmitterm** [comment]
hi, i would also appreciate Apple home support for the new Shelly H&T Gen3 device! Thanks!

**Comment by sergivillar** [comment]
> HI!
> 
> Any chance of making new humidity&temperature sensors compatible with HomeKit?
> 
> https://www.shelly.com/en-pt/products/product-overview/shelly-blu-h-and-t/shelly-blu-h-and-t-mocha
> 
> https://www.shelly.com/en-pt/products/product-overview/shelly-h-and-t-gen3-matte-black/shelly-h-and-t-gen3-mocha
> 
> After trying some other brands (even with matter) none of them have the reliability of Shelly products...
> 
> Thank you

hey, any update here? could H&T Gen 3 devices be added to homekit nowadays?
thanks
