### ISSUE TITLE
Support for Web Hooks.

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#138]
Now we have detached mode which supports single, double and long press, would be possible to add web hooks support to these actions when in normal HAP mode for "Double / Long Press", leaving single press linked to the physical switch?

What I mean by this that if enabled "Double and Long Press", would post a url request that is setup in web UI on the action of the physical switch.

**Comment by rojer** [comment]
this makes me think that we should expand functionality of inputs.
we have inputs that generate events: single, double and long press. these events can be tied to one (or more) actions, one of them would be to toggle a physical switch, turn it it on or off, another could be send a hap even (a stateless switch service will be created), or send a web hook.

**Comment by andyblac** [comment]
sounds good to me.

**Comment by rojer** [comment]
i filed https://github.com/mongoose-os-apps/shelly-homekit/issues/147 to track that and will close this one
