### ISSUE TITLE
HomeKit - shelly 1+ - impossible

### ISSUE THREAD

**Issue by ledoudou68** [mongoose-os-apps/shelly-homekit#1386]
Hi
I wanted to flash my two shelly 1 +. The first one worked well and I got the QR code at the end. For the second I can't do it. I can't get the QR code like before.
<img width="1067" alt="Capture d’écran 2024-05-05 à 20 37 31" src="https://github.com/mongoose-os-apps/shelly-homekit/assets/168991507/cdf8f64c-d7e2-41bf-b6b1-454e5856639a">

**Comment by yzalvov** [comment]
Same problem on Plus1PM for me

**Comment by lucassite120** [comment]
You can install HAA Homekit firmware on Shelly Plus devices with mgos32toHAA.
See the video: https://www.youtube.com/watch?v=06YHkRkwJE4

**Comment by markirb** [comment]
I tried to fix the problem
https://github.com/markirb/shelly-homekit/tree/gh-ci

If you feel adventurous you can try:
[shelly-homekit-ShellyPlus1PM.zip](https://github.com/mongoose-os-apps/shelly-homekit/files/15312699/shelly-homekit-ShellyPlus1PM.zip)

 (this worked on my)

[shelly-homekit-ShellyPlus1.zip](https://github.com/mongoose-os-apps/shelly-homekit/files/15312701/shelly-homekit-ShellyPlus1.zip)

(not tested)

br

**Comment by InventoryAndi** [comment]
Same for me. Seems that they did an update and now flashing does not work anymore. For the + series it is mot possible to downgrade so would be awesome if this could be fixed 🙏🏻

**Comment by markirb** [comment]
@InventoryAndi did you try the zip file from above?

**Comment by markirb** [comment]
I published a beta release under "Releases": 2.12.0-beta1 that should fix this. Feel free to try out

**Comment by jazevedodesigner** [comment]
Same problem whit me, there is a solution for that?

**Comment by markirb** [comment]
Did you try with 2.12.0-beta?

If so how do you do it?

Can you enable debug logging on Shelly fw and watch and post the log messages during upgrade please?

**Comment by jazevedodesigner** [comment]
yes I try it.

I upload the new 2.12.0-beta, but when do start update, nothing happens.

Or do I have to update it first? Because there is a newer version on shelly?

Regards

**Comment by markirb** [comment]
What is the filename? beta1 unfortunately contains zip within zip. Filename you upload has to be:

shelly-homekit-ShellyPlus1.zip

**Comment by jazevedodesigner** [comment]
I will try, and let you now.
Thank you

**Comment by InventoryAndi** [comment]
Hi. I am sorry, I was busy the last days so I was not able to test it. But seems that it works for jazevedodesigner. How can I upload the downloaded file to my shelly device? I only know the OTA method.

**Comment by markirb** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.12.0-beta2 there is a drag and drop web if in 1.3 firmware section of shelly...

**Comment by InventoryAndi** [comment]
Ok thanks. For me nothing happens. I renamed it as you wrote "shelly-homekit-ShellyPlus1.zip" and when I press Update from File, nothing happens...
<img width="899" alt="Bildschirmfoto 2024-05-21 um 12 25 52" src="https://github.com/mongoose-os-apps/shelly-homekit/assets/99717865/f9b06336-4ea0-453c-8ff7-04b35e41d982">

**Comment by sebw** [comment]
Told my cousin to get two Shelly Plus 1 (model SNSW-001X16EU) to control his garage doors. He updated from stock firmware version 1.0.7 to 1.3.2, released 3 days ago. From there, he couldn't upgrade to Mongoose. 

He was able to flash Mongoose on the second from stock firmware 1.0.7.

**Comment by markirb** [comment]
> Ok thanks. For me nothing happens. I renamed it as you wrote "shelly-homekit-ShellyPlus1.zip" and when I press Update from File, nothing happens...
> 
> <img width="899" alt="Bildschirmfoto 2024-05-21 um 12 25 52" src="https://github.com/mongoose-os-apps/shelly-homekit/assets/99717865/f9b06336-4ea0-453c-8ff7-04b35e41d982">
> 
> 

I did not say rename the file. It is called like that. If you do not have a file called like that then  there is soemthing wrong.

**Comment by InventoryAndi** [comment]
Right, sorry. I tried to upload the unzipped file. The zip file works great. Thanks for the fantastic job! Will donate

**Comment by markirb** [comment]
Thanks. If you want to donate to me personally, you can use my PayPal https://www.paypal.com/donate/?hosted_button_id=RVFA9G5VMXRX8 ; the official link currently goes to rojer, the original maintainer, who currently cannot work on the project anymore due to conflicts of interest

**Comment by InventoryAndi** [comment]
Ah sorry, I have already done it via the official link. Next time I will do it directly to you
