### ISSUE TITLE
Flash script not working

### ISSUE THREAD

**Issue by yuvalbeck** [mongoose-os-apps/shelly-homekit#139]
![Screen Shot 2020-09-19 at 20 45 57](https://user-images.githubusercontent.com/48965223/93685633-5af32780-fab9-11ea-8535-8fb0a5778319.png)

No command is working keep getting same help screen @andyblac

**Comment by andyblac** [comment]
hmm did it not ask you to install the tools ?

**Comment by andyblac** [comment]
leave with I'll look thx

**Comment by andyblac** [comment]
ok please this version if fixed I'll submit pull request

[flash_shelly.sh.zip](https://github.com/mongoose-os-apps/shelly-homekit/files/5250387/flash_shelly.sh.zip)

**Comment by yuvalbeck** [comment]
Firstly, thank you.
Yes, I would expect have a list of all devices with an update available and have an option to agree to update all at once and not press "y" each time.

I also see some issues - will send you over

**Comment by andyblac** [comment]
> Firstly, thank you.
> Yes, I would expect have a list of all devices with an update available and have an option to agree to update all at once and not press "y" each time.
> 
> I also see some issues - will send you over

Hi np, You can -y option in command line to bypass the question

**Comment by andyblac** [comment]
can I close this now ?, for any addition feature please here https://github.com/mongoose-os-apps/shelly-homekit/issues/132

**Comment by yuvalbeck** [comment]
Thank you for your help the file you sent worked

**Comment by andyblac** [comment]
thanks, has now been committed.
