### ISSUE TITLE
Newbie help, 1L

### ISSUE THREAD

**Issue by Joegarybaker** [mongoose-os-apps/shelly-homekit#1394]
Hello, some help for a confused novice would be appreciated.

Currently installed and flashed 1L working in edge mode. Fronted by a standard single switch.

I have seen that there is a switch 2 on the GUI. Can I access/use this from my physical switch to set a scene/control another HomeKit device?

id like it to turn on some RGB lighting (Aqara, not connected/wired to the Shelly in anyway).

Thanks in advance.

**Comment by markirb** [comment]
You can. This is "detatched" mode
