### ISSUE TITLE
Detached Switch doesn't show Input-Part anymore (Plus1PM)

### ISSUE THREAD

**Issue by DB2FM** [mongoose-os-apps/shelly-homekit#1395]
When using 2.12.0 Beta 3 for Shelly Plus 1PM and using "Detached" mode for the switch, the area in the configuration screen where you configure the Input is not shown anymore.

**Comment by markirb** [comment]
thanks for noticing. there's a small logic error. will be fixed in next beta

**Comment by markirb** [comment]
please try beta4 https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.12.0-beta4

**Comment by DB2FM** [comment]
Sorry, still the same behavior. No Input 1 is shown in config-page.

**Comment by markirb** [comment]
sorry. now this works:

[shelly-homekit-ShellyPlus1PM.zip](https://github.com/user-attachments/files/15843798/shelly-homekit-ShellyPlus1PM.zip)

**Comment by DB2FM** [comment]
Hi Markus,

great! Now it works :)
