### ISSUE TITLE
Issue with Shelly Plus i4 and Beta 4

### ISSUE THREAD

**Issue by pfrasun** [mongoose-os-apps/shelly-homekit#1398]
With Beta 4 Shelly Plus i4 is not working properly. There is no way to assign any actions to the switch in HomeKit, but you can assign to it Scenes using Eve app. After downgrade to Beta 3 all works as intended.

**Comment by markirb** [comment]
What is the error? I cannot reproduce this on my I4 on beta4 :/

**Comment by pfrasun** [comment]
Error is/was "Action cannot be set". After downgrade to Beta 3 and upgrade to Beta 4, I cannot reproduce this error anymore, it means all actions can be removed and added again. No idea what caused the issue and why it is suddenly gone.

**Comment by markirb** [comment]
Ok… would be strange anyway because nothing really changed on i4
