### ISSUE TITLE
Shelly rgbw2 cannot enter setup mode, not seen in home app

### ISSUE THREAD

**Issue by Mizayah** [mongoose-os-apps/shelly-homekit#1399]
Hello, 

Just need an fast tip. I have flashed device to Raven system, and configure wifi after on device. Even after power off and on i canot get to web interface of it anymore. I am still conected to Shelly RGBW2 by adapter tho. Do i need to conect it to DC12/24 to see it in homekit app and enter setup mode? 

I was sure if i power it by 3v i can see it still home app, but i dont :(
It connect to router and i can PING it.

Please help

**Comment by markirb** [comment]
Sorry this is not raven firmware
