### ISSUE TITLE
I messed up Name Server and Fixed IP

### ISSUE THREAD

**Issue by 5xPa** [mongoose-os-apps/shelly-homekit#1402]
Hi I updated my Shelly Uni to the latest version. I set the Name server to local DNS. Set fixed IP. I did not set the gateway! Now I cannot access the UNI. All my fault! 
Did a network scan the UNI is not showing!
I opened network settings on iPad hoping it would show up as access point, no joy

Is there anyway to recover my stupid mistake?

I use the UNI's to connect to outputs from my Texecom Alarm

Great work thanks

**Comment by markirb** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery#from-invalid-wifi-configuration
