### ISSUE TITLE
Roller shutter name

### ISSUE THREAD

**Issue by raphtabe** [mongoose-os-apps/shelly-homekit#1403]
Hello, when using a 2.5 or Plus 2 PM in roller shutter mode, the name in HomeKit is the Device name  and not the Window.
Very small bug, but still 🙂

**Comment by markirb** [comment]
I mean I can confirm this behavior. But you can change the name without affecting the Shelly's name.

Also the accesories name is set to windows name so I think that this is a HomeKit "issue" itself.
