### ISSUE TITLE
HomeKit Shelly 2Pm

### ISSUE THREAD

**Issue by snrnoe** [mongoose-os-apps/shelly-homekit#1405]
Hi,

i‘m actually trying to flash my 2pm Shelly’s but it’s not working. I tried to use the automatic way and the manual way but it doesn’t work. 

Any hints or ideas? 

Cheers 
![IMG_9624](https://github.com/mongoose-os-apps/shelly-homekit/assets/77935600/90fc7460-7d93-4381-8214-38281f89fcd2)
![IMG_9625](https://github.com/mongoose-os-apps/shelly-homekit/assets/77935600/a3ab713d-4615-4d78-8555-de12df1e9c7b)

**Comment by markirb** [comment]
Hi, just wait a few days. the beta is finished and there will be a release soon, then all update methods should work again.
