### ISSUE TITLE
Factory reset - can't add the device again?

### ISSUE THREAD

**Issue by HannesHomeAss** [mongoose-os-apps/shelly-homekit#1412]
Hi

Had to do a factory reset for one of my RGBW2. After factory reset I can't flash for HomeKit again.
And in current firmware from Shelly you cant choose to upgrade from file?

Any ide how to solve this?

Thanks!

**Comment by markirb** [comment]
Please see remark on main README for flashing from recent stock versions (you need to use current beta)

**Comment by HannesHomeAss** [comment]
Hi,

Use, I have tried with BETA too, but same issue.
How do i upload the current BETA when I cant choose any file within shelly GUI?

**Comment by HannesHomeAss** [comment]
![image](https://github.com/mongoose-os-apps/shelly-homekit/assets/121405352/c710e56e-2f8f-482b-85da-a076bd1f4581)

**Comment by HannesHomeAss** [comment]
Found the issue, the device needs to be changed to colour mode in stock firmware, before you can flash to HomeKit.
