### ISSUE TITLE
Shelly 2PM and AddsOn does not detect DHT22

### ISSUE THREAD

**Issue by hejsiri** [mongoose-os-apps/shelly-homekit#1414]
When AddOn is connected to Shelly 2PM, it does not detect the DHT22 sensor. In Shelly 1PM everything is fine. Temetaruta and humidity is shown in web gui and HomeKit.

**Comment by markirb** [comment]
Hi,

I think you posted this in another thread. Can you try to give more information?

The auto detection of DHT sensors is quite tricky...

**Comment by hejsiri** [comment]
Basically nothing more to say. Shelly 2PM + Addon + DHT22 does not work.

**Comment by markirb** [comment]
There are several flavors of DHT sensors on the market. Some seem to work with the current solution some apparently do not.

Can you please post details about your model?

**Comment by hejsiri** [comment]
AM2302

**Comment by markirb** [comment]
I think this is related to the other issue with Addon not working. I will try myself when I find time.

**Comment by markirb** [comment]
Hi, 

In think I found it.
Please look here:

https://github.com/mongoose-os-apps/shelly-homekit/issues/1439#issuecomment-2336710479
