### ISSUE TITLE
Shelly 1PM - historical power data lost after fw upgrade

### ISSUE THREAD

**Issue by elbartoman** [mongoose-os-apps/shelly-homekit#1421]
I upgraded to the new few without realizing that my historical power data would be lost. Is there a way to manually set it? I was not able to find a SET API in the wiki. I do have the last value in an influxDB bucket.

**Comment by markirb** [comment]
Hi, 

this is currently not possible

**Comment by elbartoman** [comment]
OK, thanks. So I have to solve this in Grafana in my dashboards.

**Comment by elbartoman** [comment]
OK, thanks. So I have to solve this in Grafana in my dashboards.
