### ISSUE TITLE
Alarm Mode

### ISSUE THREAD

**Issue by iShortOne** [mongoose-os-apps/shelly-homekit#1422]
Hi!
Thanks for your job!
One question, is it possible add the alarm feature to shelly 1?

Thanks in advance

**Comment by lucassite120** [comment]
HAA firmware currently has this feature.

**Comment by iShortOne** [comment]
> HAA firmware currently has this feature.

Thanks!

**Comment by timoschilling** [comment]
double of https://github.com/mongoose-os-apps/shelly-homekit/issues/552
