### ISSUE TITLE
Momentary Switch with Shelly Plus 1

### ISSUE THREAD

**Issue by johnmrichey** [mongoose-os-apps/shelly-homekit#1429]
I have the Shelly HomeKit setup as Momentary switch but when I get the contacts across the dry contacts of 0|I it's not acting as a momentary switch.

I have tried all the various combinations but it seems to be always the same regardless.

Any suggestions please.
![image](https://github.com/user-attachments/assets/675a55a1-8bbc-4eb7-8e96-c7e0a3b8beb1)

**Comment by johnmrichey** [comment]
I posted this to the Shelly forum as it seems this is an issue with stock 1.4.0 as well in my testing.

Shelly Plus 1 as Momentary Switch https://community.shelly.cloud/topic/1870-shelly-plus-1-as-momentary-switch/

**Comment by Sternsoldat** [comment]
HeyCan you explain what exactly happen with you O|I contact?-send from my mobile device-Am 04.08.2024 um 02:15 schrieb johnmrichey ***@***.***>:﻿
I have the Shelly HomeKit setup as Momentary switch but when I get the contacts across the dry contacts of 0|I it's not acting as a momentary switch.
I have tried all the various combinations but it seems to be always the same regardless.
Any suggestions please.
31760082-ED0C-4298-8F53-5814634BBB71.png (view on web)

**Comment by johnmrichey** [comment]
As a momentary switch which is normally open it should be open when you release the button.  When I use Garage Door type that behaves correctly and return to the open state but it forces the HAP type to Garage Door in HomeKit.

When I use Switch type Momentary the dry contacts toggle to closed and stay in the closed position, not until you press the button again do it then open.

**Comment by johnmrichey** [comment]
The voltmeter across the contacts when pressed indicates continuity and stays that way until you press the button again.

**Comment by johnmrichey** [comment]
You just need to turn on Auto Off and it works fine.

Problem solved.

**Comment by johnmrichey** [comment]
Auto Off does not make it work properly as an actual momentary switch.  Any ideas how to make this work as normally open actual momentary switch please?

**Comment by markirb** [comment]
Can you please add more detail why auto off does not work? It should be exactly what you need

**Comment by dmarthur** [comment]
@johnmrichey - I was having this same problem even after I activated the auto-off feature. I disconnected the live wire to the relay, waited 10 seconds, and reconnected it. That fixed the problem for me.
