### ISSUE TITLE
Shelly Plus 1PMMini

### ISSUE THREAD

**Issue by Godtooro** [mongoose-os-apps/shelly-homekit#1436]
Hi!
I’ve bought Shelly plus 1PMmini (not gen 3).
Comes with 1.4.0.
Do you know how can I do a downgrade to 1.3.3 to install HomeKit?

thank you for your support.

**Comment by rmmmrm** [comment]
Hello @Godtooro 

Contact shelly support, they send you the zip via email.

support@shelly.cloud

Regards

**Comment by markirb** [comment]
http://rojer.me/files/shelly/stock/1.3.3/

Plus1Mini (non gen3) is currently not supported by this firmware. Maybe soon
