### ISSUE TITLE
Shelly Plus Plug S not flashable via /update url

### ISSUE THREAD

**Issue by Sindachetto84** [mongoose-os-apps/shelly-homekit#1438]
ciao a tutti, 
non riesco più a fare il flash via OTA del mio shelly Plug S dopo reset factory. ho provato ad utilizzare tutti i downgrade del firmware ma non funziona con nessuno.
grazie per il supporto.

**Comment by ilGenu** [comment]
same here

**Comment by markirb** [comment]
Does not work is not an issue description. Provide at least logs and from which firmware you try to update.

**Comment by Sindachetto84** [comment]
> Non funziona non è una descrizione del problema. Fornire almeno i registri e da quale firmware si tenta di aggiornare.

Hi Markirb,  sorry but I don't know how to share the logs, I tried with all the downgrades available but I can't flash the HomeKit firmware.  Thanks

**Comment by markirb** [comment]
Which downgrades do you mean?

Here ist howtio get logs:
https://community.shelly.cloud/topic/1707-how-to-enable-debug-mode-on-your-shelly/

**Comment by ilGenu** [comment]
Here's the log

[diagnostics-shelly-plusplugs-debug-log-3.txt](https://github.com/user-attachments/files/16741667/diagnostics-shelly-plusplugs-debug-log-3.txt)

**Comment by markirb** [comment]
Seems like the automatic url is not yet working. Please download file manually from releases tab.

**Comment by markirb** [comment]
shoudl work now
