### ISSUE TITLE
Shelly 2pm+ updated but always disconnect 

### ISSUE THREAD

**Issue by snrnoe** [mongoose-os-apps/shelly-homekit#1440]
Hey, 

i updated my shelly 2 pm plus to firmware 1.3.3 and flashed Homekit succesfully. 
When trying to log in there is always the Homekit Page, but it shows "shelly is disconnected!" 

Tried it with 2 seperate Moduls both are showing the same error. 

Can anyone help me? 

<img width="477" alt="Bildschirmfoto 2024-08-18 um 16 21 59" src="https://github.com/user-attachments/assets/1199a9e5-f1a7-43a2-8145-64e282c2610c">

**Comment by markirb** [comment]
Please always post what you did wrong if you close the issue....

**Comment by snrnoe** [comment]
Seems, that i wasnt waiting enough
