### ISSUE TITLE
Shelly RGBW2 not shown under light sources in Homekit

### ISSUE THREAD

**Issue by WRTHacker** [mongoose-os-apps/shelly-homekit#1446]
Hello experts,
first of all many thanks that the firmware development is ongoing!!

Even with the new firmware I have the problem, that the shelly rgbw2 devices (using rgb+w mode, bridge + rgb + white devide shown in Homekit) are not shown under light sources. Any other vendor led controller device can be found in this Homekit category view. 

Is this known and intended?

Many thanks for support and best regards

**Comment by markirb** [comment]
Can you please post your complete configuration screen from web interface

**Comment by WRTHacker** [comment]
Hi, here are the screenshots:

- I use the RGB Device for the status display of my alarm system, and to display open windows
- The white device is uses as a nightligt

![Shelly_rgbw2_1](https://github.com/user-attachments/assets/584ab0d9-3abc-4e80-8c59-a1945a18b45d)
![Shelly_rgbw2_2](https://github.com/user-attachments/assets/ee6778d1-ed3d-4551-94cc-75c318ddee03)

**Comment by markirb** [comment]
Normally there is an option HAP service, can you find out why it is not shown for you

![image](https://github.com/user-attachments/assets/a6b209f1-e0ed-4c9b-af65-ef7b35040428)

**Comment by WRTHacker** [comment]
Even with an unuses RGBW2, reset configuration. There is no such Option!

**Comment by WRTHacker** [comment]
However, when I add the test device to homekit, the devices are shown unter light ... think I hade to delete ann readadd the "faulty device" ... will come back if this has helped.

However THE HAP Switch is not there ...

**Comment by WRTHacker** [comment]
After deletion and re add the devices occur unter light sources.
However, I remember, when the Homekit controller switches from one hub to another, the bridge is sometimes lost as a device. I will have to observe this with the new firmware and after the re-add.

**Comment by WRTHacker** [comment]
Please keep this open until I upgrade to 18.0.x. Typically the change of the HomeKit controller leads to the problem, like it happens during upgrades.

**Comment by WRTHacker** [comment]
After upgrading to 18.0(.1) the RGB bridge an the rgb and white device ist stable available.

=> However I have issued with my 1PM and Plus1PM: The 1PM was not reachable, than the switch disappered in Homekit, and the switch function „moved“ to the bridge. I have to remove the device an readd it. However the bridge is not there, but the single switch.

This behaviour occured even before the upgrade to V18 and the latest shelly firmware.

**Comment by WRTHacker** [comment]
The initial issue is fixed, but the above one still remains.
=> Will open another issue
