### ISSUE TITLE
Shelly Plug S - Network connection lost

### ISSUE THREAD

**Issue by Holck1971** [mongoose-os-apps/shelly-homekit#1449]
I installed the Shelly HomeKit integration. 
Actually, everything works great. 

However, if I take the Shellys off the power (power failure or similar), the modules lose their settings and network settings. 

With the original firmware this never happened to me. 

Who can solve the problem for me?

regards

Holck

**Comment by markirb** [comment]
This is a known issue, see other issues, which is already fixed in latest beta. See release section.

**Comment by Holck1971** [comment]
Ok thanks 
But where can I download this corresponding beta

**Comment by markirb** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.12.2-beta3
