### ISSUE TITLE
Advanced input actions configuration

### ISSUE THREAD

**Issue by rojer** [mongoose-os-apps/shelly-homekit#147]
It should be possible to specify multiple actions for a physical device input. Among them:
 * Control an output on the same device directly, in toggle/momentary/edge mode
 * Send a HAP event - through a Stateless Switch accessory
 * Call a web hook
 * ... more can be added later

**Comment by andyblac** [comment]
should we include #51 into this as well ?

**Comment by rojer** [comment]
that's more like advanced _output_ configuration. let's keep it separate.

**Comment by andyblac** [comment]
> that's more like advanced _output_ configuration. let's keep it separate.

ok

**Comment by rojer** [comment]
additional relevant HAP services for an input:

* contact sensor
* motion sensor
* occupancy sensor

**Comment by andyblac** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/issues/124

**Comment by andyblac** [comment]
and now that we have an API this could be used to link Shelly devices together.

**Comment by timoschilling** [comment]
@rojer do I see it right that every thing in this ticket is already implement, except "Call a web hook" which already requested in https://github.com/mongoose-os-apps/shelly-homekit/issues/70#issuecomment-735776717, so I think we can close this issue as a double of #70

**Comment by timoschilling** [comment]
Summery of #934 and #829, some users (including me) have the wish to have an mixed mode of switch and detached mode. We want to control the output for example with a singe push and exposing the long and double as stateless input to HK.

**Comment by timoschilling** [comment]
Closed because of https://github.com/mongoose-os-apps/shelly-homekit/issues/147#issuecomment-850909617
> rojer do I see it right that every thing in this ticket is already implement, except "Call a web hook" which already requested in https://github.com/mongoose-os-apps/shelly-homekit/issues/70#issuecomment-735776717, so I think we can close this issue as a double of https://github.com/mongoose-os-apps/shelly-homekit/issues/70
