### ISSUE TITLE
suggestion: add online update button

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#15]
add a button to firmware section of webif to allow ota update.

![Screenshot 2020-02-13 at 19 03 45](https://user-images.githubusercontent.com/77936/74468933-97133980-4e93-11ea-82c3-363e4faee2d7.jpg)

**Comment by rojer** [comment]
PRs welcome :)
i have to say, that web interface is not my forte, it's the barest of minimums possible.
so if you (or anyone else reading this) are good at web inrerfaces, feel free to throw away what we have now and replace it with something better, i'll gladly accept the contribution.

**Comment by andyblac** [comment]
looks like the conversation is on https://github.com/mongoose-os-apps/shelly-homekit/issues/48, so i'll close this issue.
