### ISSUE TITLE
No Input Sensor in HomeKit with Mini gen 3

### ISSUE THREAD

**Issue by tharwan** [mongoose-os-apps/shelly-homekit#1512]
I successfully connected my Shelly 1 mini gen 3 to HomeKit with firmware 2.12.2-beta.3. But I do not get the input sensor when switching to „detached“ mode.

Is this already supported?

**Comment by tharwan** [comment]
I just realized I am also not seeing the „input 1“ section in the UI.

**Comment by markirb** [comment]
You're right it somehow doesn't work. Though from the code and config it should....

**Comment by tharwan** [comment]
Anything I could do to help debugging?

**Comment by markirb** [comment]
No.
I think I found it, will be fixed soon

**Comment by markirb** [comment]
should be fixed in latest beta available in releases

**Comment by djrams10** [comment]
> I successfully connected my Shelly 1 mini gen 3 to HomeKit with firmware 2.12.2-beta.3. But I do not get the input sensor when switching to „detached“ mode.
> 
> Is this already supported?

Thank you, can you explain to me how you did to install the beta? Thanks

**Comment by tharwan** [comment]
Fixed! Thanks!

**Comment by tharwan** [comment]
@djrams10 see #1509
