### ISSUE TITLE
Shelly plus 1 pm restarting every 1-3 minutes 

### ISSUE THREAD

**Issue by SebastianStolze** [mongoose-os-apps/shelly-homekit#1513]
Hey I have a problem with a shelly plus 1 pm, which was running for 172 days without a problem but now it reset every 1-3 minutes and therefore disabling the light. I first updated to the latest firmware version, without any improvement. Reverting to the stock firmware fixed the issue for now. Is there anything I can do to fix this?

I also have a second shelly installed which is still working.

**Comment by markirb** [comment]
this sounds like a power problem. can you try to activate wifi power savings?

**Comment by SebastianStolze** [comment]
Hi thanks for the ultra fast response. My Wifi Power Savings was already set to 1 for both shellys (the working one and the disconnecting one). Should i set it to 2 or disable?

**Comment by markirb** [comment]
For Plus devices 2 is the maximum saving so try this

**Comment by SebastianStolze** [comment]
It seems to be working after downgrading to 1.3.3 firmware after some 1.4.x stock firmware struggle. I managed to update to homekit back again and with the power save setting set to 2 it is working right now. Thanks for your work and for your help. I keep the ticket open till tomorrow and close it, when I can confirm it is working.

**Comment by SebastianStolze** [comment]
It s working thanks
