### ISSUE TITLE
Shelly Gen 3 Relay not switching after upgrade

### ISSUE THREAD

**Issue by wlhrtr** [mongoose-os-apps/shelly-homekit#1517]
Just flashed from 1.3.3 to 2.12.2.
With 1.3.3 switch in wall and on web-dashboard worked.
With 2.12.2 neither the wall switch nor the dashboard switch works.

**Comment by djrams10** [comment]
> Just flashed from 1.3.3 to 2.12.2.
> 
> With 1.3.3 switch in wall and on web-dashboard worked.
> 
> With 2.12.2 neither the wall switch not the dashboard switch works. 

Same for me

**Comment by markirb** [comment]
Hi,

There seems to be something for some models so far I had only one report of this, for most it seems to work. See https://github.com/mongoose-os-apps/shelly-homekit/discussions/1499#discussioncomment-10590621

Can you please add some more details:
- the log that captures a switch event.
- does it not turn off or on? The report I had was stuck at on
- If you have: system info on stock firmware andd/or picture of the device that shows the exact model and version

**Comment by djrams10** [comment]
> Hi,
> 
> There seems to be something for some models so far I had only one report of this, for most it seems to work. See https://github.com/mongoose-os-apps/shelly-homekit/discussions/1499#discussioncomment-10590621
> 
> Can you please add some more details:
> - the log that captures a switch event.
> - does it not turn off or on? The report I had was stuck at on
> - If you have: system info on stock firmware andd/or picture of the device that shows the exact model and version
> 

Hi, here are the screenshots with the different information.

The flash is done correctly, except that at the level of ignition, extinction, it does not work.

The light remains fixed red, and when the button is turned on, we do not hear the click. Another thing also I put a switch on the Shelly and it no longer works either.

When I come back to the original firmware everything works normally.

Thanks

![image](https://github.com/user-attachments/assets/77ffb79c-3f0b-4ad6-9919-cdc58c648785)
![image](https://github.com/user-attachments/assets/d0382765-76d3-4abc-916b-a14fa84d5095)
![image](https://github.com/user-attachments/assets/eb04c124-0259-4dab-984d-f04eaa4ff720)
![image](https://github.com/user-attachments/assets/cb0103ee-c16e-49b6-8fd6-22ca5bc01459)
![image](https://github.com/user-attachments/assets/75058983-0712-4160-b3de-ad5cf0d00383)

**Comment by wlhrtr** [comment]
used for both the wall switch and dashboard toggle

for 1.4.2 (downgraded befor homekit flash)

```
Connected.
09:46:19
shelly_debug.cpp:236 Streaming logs to 192.168.31.164:64488
09:46:19
shos_dns_sd_respond:236 ws(0x3fcbc474): Announced Shelly1MiniG3-DCDA0CE356B4 any@any (192.168.31.160)
09:46:22
shos_dns_sd_respond:236 ws(0x3fcbc474): Announced Shelly1MiniG3-DCDA0CE356B4 any@any (fe80::deda:cff:fee3:56b4,2001:4bc9:1fb8:fe8a:deda:cff:fee3:56b4)
09:46:22
shos_rpc_inst.c:242 switch.toggle via WS_in 192.168.31.164:64483
09:46:26
shelly_notification:162 Status change of switch:0: {"id":0,"output":true,"source":"WS_in"}
09:46:26
shos_rpc_inst.c:242 switch.toggle via WS_in 192.168.31.164:64483
09:46:27
shelly_notification:162 Status change of switch:0: {"id":0,"output":false,"source":"WS_in"}
09:46:27
shelly_notification:162 Status change of input:0: {"id":0,"state":true}
09:46:36
shelly_notification:162 Status change of switch:0: {"id":0,"output":true,"source":"switch"}
09:46:36
shelly_notification:162 Status change of input:0: {"id":0,"state":false}
09:46:36
shelly_notification:162 Status change of switch:0: {"id":0,"output":false,"source":"switch"}
09:46:36
```

for 2.12.2
```
235916722 shelly_debug.cpp:231    No log file, sending new entries
235923761 mgos_http_server.c:180  0x3fcaf6b8 HTTP connection from 192.168.31.164:65025
240908071 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
241766239 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
242354149 shelly_main.cpp:483     Up 242.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
242638315 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
243636292 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
244642466 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
245638937 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
246640913 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
247637208 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
248635733 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
249635845 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
250354025 shelly_main.cpp:483     Up 250.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
258354021 shelly_main.cpp:483     Up 258.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
266354070 shelly_main.cpp:483     Up 266.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
269989473 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
270641902 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
271637735 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
272643096 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
274354077 shelly_main.cpp:483     Up 274.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
279836843 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
280641561 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
281639796 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
282354049 shelly_main.cpp:483     Up 282.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
282383710 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
282388981 shelly_output.cpp:67    Output 1: off -> on (RPC)
282547328 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
283571162 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
283576115 shelly_output.cpp:67    Output 1: on -> off (RPC)
283768658 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
285808829 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
286555677 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
286560627 shelly_output.cpp:67    Output 1: off -> on (RPC)
286585271 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
286638391 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
287638704 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
287819554 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
287824512 shelly_output.cpp:67    Output 1: on -> off (RPC)
287845690 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
290461361 mgos_sys_config.c:323   Saved to conf9.json
290472053 shelly_main.cpp:483     Up 290.46, HAP 0/1/16 ns 1, RAM: 203120/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
295234735 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
295639463 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
296051914 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
296056869 shelly_output.cpp:67    Output 1: off -> on (RPC)
296116612 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
296638308 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
298531332 mgos_sys_config.c:323   Saved to conf9.json
298542038 shelly_main.cpp:483     Up 298.53, HAP 0/1/16 ns 1, RAM: 203120/188456; st 41; 0.1: st:1 in_st:0 inm:1 ininv:0
301796775 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
302643118 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
303639092 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
303652391 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
303657349 shelly_output.cpp:67    Output 1: on -> off (RPC)
303682515 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
306421362 mgos_sys_config.c:323   Saved to conf9.json
306432048 shelly_main.cpp:483     Up 306.42, HAP 0/1/16 ns 1, RAM: 203120/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
312542315 shelly_input.cpp:77     Input 1: change (state 1)
312547185 shelly_output.cpp:67    Output 1: off -> on (switch)
313552488 shelly_input.cpp:77     Input 1: long (state 1)
313752501 shelly_input.cpp:77     Input 1: change (state 0)
313757347 shelly_output.cpp:67    Output 1: on -> off (switch)
314424003 mgos_sys_config.c:323   Saved to conf9.json
314434700 shelly_main.cpp:483     Up 314.42, HAP 0/1/16 ns 1, RAM: 203120/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
315006254 shelly_input.cpp:77     Input 1: change (state 1)
315011092 shelly_output.cpp:67    Output 1: off -> on (switch)
316016366 shelly_input.cpp:77     Input 1: long (state 1)
316268319 shelly_input.cpp:77     Input 1: change (state 0)
316273502 shelly_output.cpp:67    Output 1: on -> off (switch)
317540910 shelly_input.cpp:77     Input 1: change (state 1)
317545789 shelly_output.cpp:67    Output 1: off -> on (switch)
318551086 shelly_input.cpp:77     Input 1: long (state 1)
318861385 shelly_input.cpp:77     Input 1: change (state 0)
318866263 shelly_output.cpp:67    Output 1: on -> off (switch)
320240874 shelly_input.cpp:77     Input 1: change (state 1)
320245757 shelly_output.cpp:67    Output 1: off -> on (switch)
321251241 shelly_input.cpp:77     Input 1: long (state 1)
321611617 shelly_input.cpp:77     Input 1: change (state 0)
321616495 shelly_output.cpp:67    Output 1: on -> off (switch)
322436517 mgos_sys_config.c:323   Saved to conf9.json
322447229 shelly_main.cpp:483     Up 322.44, HAP 0/1/16 ns 1, RAM: 203120/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
330354020 shelly_main.cpp:483     Up 330.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
330639359 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
331639460 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
332300953 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
332305905 shelly_output.cpp:67    Output 1: off -> on (RPC)
332324604 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
332646284 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
333434464 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
333439411 shelly_output.cpp:67    Output 1: on -> off (RPC)
333458347 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
333641082 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
334434645 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
334439602 shelly_output.cpp:67    Output 1: off -> on (RPC)
334467454 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
334640159 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
335195530 mg_rpc.c:315            Shelly.SetState via WS_in 192.168.31.164:64919
335200528 shelly_output.cpp:67    Output 1: on -> off (RPC)
335220206 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
335639330 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
338439023 mgos_sys_config.c:323   Saved to conf9.json
338449711 shelly_main.cpp:483     Up 338.44, HAP 0/1/16 ns 1, RAM: 203120/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
346354021 shelly_main.cpp:483     Up 346.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
349287191 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
349643004 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
350641275 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
354354041 shelly_main.cpp:483     Up 354.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
362354030 shelly_main.cpp:483     Up 362.34, HAP 0/1/16 ns 1, RAM: 201760/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
370354993 shelly_main.cpp:483     Up 370.34, HAP 0/1/16 ns 1, RAM: 201588/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
378354057 shelly_main.cpp:483     Up 378.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
386355177 shelly_main.cpp:483     Up 386.35, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
394354142 shelly_main.cpp:483     Up 394.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
402354068 shelly_main.cpp:483     Up 402.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
410354101 shelly_main.cpp:483     Up 410.34, HAP 0/1/16 ns 1, RAM: 201760/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
418354104 shelly_main.cpp:483     Up 418.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
426354155 shelly_main.cpp:483     Up 426.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
434354160 shelly_main.cpp:483     Up 434.34, HAP 0/1/16 ns 1, RAM: 201760/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
442354100 shelly_main.cpp:483     Up 442.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
450354099 shelly_main.cpp:483     Up 450.34, HAP 0/1/16 ns 1, RAM: 203324/188456; st 41; 0.1: st:0 in_st:0 inm:1 ininv:0
451665184 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
452716087 mg_rpc.c:315            Shelly.GetInfoExt via WS_in 192.168.31.164:64919
```

**Comment by markirb** [comment]
Ok, I can see nothing from that so far can you please find out what's printed on your casing? 
Mine says 

S3SW-001X8EU, Ver1, B0124

To which voltage do you have it wired? AC / DC?

**Comment by djrams10** [comment]
> Ok, I can see nothing from that so far can you please find out what's printed on your casing? 
> 
> Mine says 
> 
> 
> 
> S3SW-001X8EU, Ver1, B0124
> 
> 
> 
> To which voltage do you have it wired? AC / DC?
> 
> 

I bought it and nothing touches on the ac / dc

![image](https://github.com/user-attachments/assets/80e8cb00-6604-465f-b4a5-f99795cd03a3)
![image](https://github.com/user-attachments/assets/84de6889-a254-4a14-9c29-32862eed8929)

**Comment by wlhrtr** [comment]
@markirb 

Wired like in this diagram:
![Shelly-1-With-External-Switch-1 2](https://github.com/user-attachments/assets/15b588fa-8aaf-435b-bd4d-46d28ebbb958)

Printed on case:
S3SW-001X8EU
Ver1 B2724

**Comment by djrams10** [comment]
For my part, the wiring is necessarily good because if I go back to the original firmware it works perfectly, and I had a Shelly 1 flasher before and everything worked well.

**Comment by djrams10** [comment]
> Just flashed from 1.3.3 to 2.12.2.
> With 1.3.3 switch in wall and on web-dashboard worked.
> With 2.12.2 neither the wall switch nor the dashboard switch works.

Exactly The Same

**Comment by markirb** [comment]
ok... nothing really different on the models.

can you try if it works with this firmware?
(this sets GPIO7 driver strength to maximum)

[fw.zip](https://github.com/user-attachments/files/17002679/fw.zip)

**Comment by wlhrtr** [comment]
> can you try if it works with this firmware? (this sets GPIO7 driver strength to maximum)
> 
> [fw.zip](https://github.com/user-attachments/files/17002679/fw.zip)

unfortunately not working on my end

**Comment by djrams10** [comment]
> ok... nothing really different on the models.
> 
> 
> 
> can you try if it works with this firmware?
> 
> (this sets GPIO7 driver strength to maximum)
> 
> 
> 
> [fw.zip](https://github.com/user-attachments/files/17002679/fw.zip)
> 
> 

It’s always the same problem unfortunately

**Comment by markirb** [comment]
I still am trying to get my head around out what can go wrong here in Hardware or in Software.
So far I have run out of ideas to try unfortunately.

**Comment by wlhrtr** [comment]
It looks like an issue with gpio pin in the firmware.
Just flashed back to stock firmware and light went on after updating without me doing anything.

**Comment by djrams10** [comment]
I don’t know what else to do to help you. Do not hesitate if you need.

**Comment by Dag0d** [comment]
Same for me with a shelly 1 pm gen 3. original firmware works fine. HomeKit firmware keeps the last state of the original firmware. relay is not clicking, nothing. 
no difference if using the website or home to control.

**Comment by markirb** [comment]
[shelly-homekit-ShellyMini1Gen3.zip](https://github.com/user-attachments/files/17019170/shelly-homekit-ShellyMini1Gen3.zip)

can you try this and see if it changes anything?

**Comment by markirb** [comment]
> It looks like an issue with gpio pin in the firmware. Just flashed back to stock firmware and light went on after updating without me doing anything.

yes. but the gpio number is correct. it wound not work on other devices like mine or tasiota if it wasn't... 
it can only be settings thereof; but nothing the other firmwares seem to use. or it could be mongoose os esp32c3 specific. but I looked through this code.

**Comment by Dag0d** [comment]
> [shelly-homekit-ShellyMini1Gen3.zip](https://github.com/user-attachments/files/17019170/shelly-homekit-ShellyMini1Gen3.zip)
> 
> can you try this and see if it changes anything?

If you could do that for the mini 1 pm gen 3 as well I would give it a try.

**Comment by wlhrtr** [comment]
> [shelly-homekit-ShellyMini1Gen3.zip](https://github.com/user-attachments/files/17019170/shelly-homekit-ShellyMini1Gen3.zip)
> 
> can you try this and see if it changes anything?

unfortunately still not working

but thank you for your continuous efforts

**Comment by djrams10** [comment]
> can you try this and see if it changes anything?

For me I have no change. I would like to point out that I am in France. Thank you for your efforts.

**Comment by danny1605** [comment]
I have the same problem

**Comment by markirb** [comment]
I think I found it.

First: it will work after you make your shelly hard reboot (cut power)

This only happens when you directly upgrade from stock. Stock seems to call gpio_hold_en before reboot. So we can unlock that after booting.

Just make a hard power cut or wait for the fix which will be coming soon.

**Comment by djrams10** [comment]
> I think I found it.
> 
> First: it will work after you make your shelly hard reboot (cut power)
> 
> This only happens when you directly upgrade from stock. Stock seems to call gpio_hold_en before reboot. So we can unlock that after booting.
> 
> Just make a hard power cut or wait for the fix which will be coming soon.

It’s okay, it works perfectly for me. Thank you again for your help.

**Comment by markirb** [comment]
If you do not want to cut power you can try this:


[shelly-homekit-ShellyMini1Gen3.zip](https://github.com/user-attachments/files/17079273/shelly-homekit-ShellyMini1Gen3.zip)

**Comment by wlhrtr** [comment]
> If you do not want to cut power you can try this:
> 
> [shelly-homekit-ShellyMini1Gen3.zip](https://github.com/user-attachments/files/17079273/shelly-homekit-ShellyMini1Gen3.zip)

just updated from 1.3.3 and it works flawlessly now 

@markirb thank you very much :)
