### ISSUE TITLE
Shelle Mini 1 Gen 3 Detached Mode, Stateless Toggle cant trigger shortcuts

### ISSUE THREAD

**Issue by DeReck16** [mongoose-os-apps/shelly-homekit#1520]
Hi Folks, 

trying to trigger my automation with a shortcut on a stateless switch via detached mode using this https://github.com/mongoose-os-apps/shelly-homekit/wiki/Stateless-Toggle-Switch wont work. 

Issue is that you cannot "convert to shortcut". There is also no workaround to create a short with an action like "Single Press" on the Shelly Switch Input 1 as this one is not exposed to automations. 

Single Press here should tigget the Shortcut (as explained in the Wiki). 

<img width="506" alt="Bildschirmfoto 2024-09-21 um 08 46 25" src="https://github.com/user-attachments/assets/3d05acf9-e363-409d-bec1-edef64c67592">
<img width="748" alt="Bildschirmfoto 2024-09-21 um 08 46 51" src="https://github.com/user-attachments/assets/6740e121-9687-493a-8d62-ec6e2584f859">
<img width="507" alt="Bildschirmfoto 2024-09-21 um 08 46 42" src="https://github.com/user-attachments/assets/39491c4f-1a61-4ff7-a99e-1faddacfd47a">
<img width="511" alt="Bildschirmfoto 2024-09-21 um 08 46 34" src="https://github.com/user-attachments/assets/6a67d54c-cce2-4813-a6e8-5d48a4bd5466">

**Comment by markirb** [comment]
Unfortunately I think we cannot do anything about this, this seems pure HomeKit issues see for example

https://github.com/mongoose-os-apps/shelly-homekit/issues/1426
