### ISSUE TITLE
Shelly Plug S Firmware: 2.12.2

### ISSUE THREAD

**Issue by KumanduS** [mongoose-os-apps/shelly-homekit#1524]
I have a Shelly Plug S running with firmware 2.12.2. I have an automation that turn off the Plug however the devices connected to the Plug are still getting energy. Using the webapplication of the device i get the same result. Toggling the Status does not cut the energy of the plug. Can you please help me solving this problem?

<img width="394" alt="CapturarShelly" src="https://github.com/user-attachments/assets/3893d931-a5cc-44ed-ad10-6ec04f8b3375">

**Comment by markirb** [comment]
Can you try reverting to stock firmware and see if it is the same?

**Comment by KumanduS** [comment]
I never try to use the original firmware. I will try do revert the firmware during the weekend and i will report back. Thanks

**Comment by KumanduS** [comment]
i reverted to stock firmware, and the problem keeps appearing. So this is not a problem of the firmware, but from the unit itself. I will try to open a ticken in shelly. Thanks for the support, you can close the thread.
