### ISSUE TITLE
REST API command to reboot Shelly 1PM Plus?

### ISSUE THREAD

**Issue by StephanReich** [mongoose-os-apps/shelly-homekit#1526]
Is it possilbe, to reboot the Shelly 1PM Plus device through the REST API 
(like the http://x.x.x.x/rpc/Shelly.SetState?id=1&type=0&state={"state":true})
![image](https://github.com/user-attachments/assets/d9b3b0d8-02b9-45c0-b860-14febdf76ffa)

With the original firmware you can call the Shelly.Reboot command.
Thanks

**Comment by timoschilling** [comment]
Yes it is: http://buero-fenster-licht.local/rpc/Sys.Reboot
