### ISSUE TITLE
Returning to a stock - test and check?

### ISSUE THREAD

**Issue by macguru341** [mongoose-os-apps/shelly-homekit#153]
Hello
Used the mos way with terminal in windows to flash the original stock firmware and I want to ask if there's a way to check if it's working before I'm selling my Shelly. I can't reconnect it into the wall.

Thanks

**Comment by rojer** [comment]
with serial connection you should be able to manage it on wifi, one thing that will not work is relays, so you won't hear it clicking when controlling from the  web interface for example.
i'd say, if it's available on wifi and you can access the stock web UI, you're good.

**Comment by macguru341** [comment]
After I've used the mos way to install the stock firmware and when trying to check my WiFi to see that I was succeed and didn't find nothing I see in the wiki that I must use the web interface as this firmware does not support pulling from remote URL like I did in mos.
How do I access the web i interface? What is the script I see and how do I use it? 
Thanks for the support

**Comment by macguru341** [comment]
Also trying to use mos with link to the downloaded file and I get "all done" but I still can't see the Shelly 1 in my iPhone WiFi

**Comment by macguru341** [comment]
![image](https://user-images.githubusercontent.com/22807164/94430492-ae8e0100-019c-11eb-952c-6480c39f7ebf.png)

![image](https://user-images.githubusercontent.com/22807164/94430511-b5b50f00-019c-11eb-9b53-fb9e0ddf8769.jpeg)

Flashing blue

**Comment by andyblac** [comment]
script is only for macOS or Linux, Windows is not supported.

**Comment by andyblac** [comment]
if the device has been refreshed with stock, it should keep all settings from HomeKit firmware (wifi etc), do you see it connected to your Router. does it have an ip ?

if not try connecting to it as an Access Point from your computer. you should see 'shelly-xxxxx' as a AP.

**Comment by macguru341** [comment]
1. I also have a Mac, should I use the script ? Is it better to use this method and not the mos way?
2. How do I trigger the access point ? Because I don't see the Shelly WiFi address in my iPhone WiFi list.

Thanks for the support

**Comment by andyblac** [comment]
> 1. I also have a Mac, should I use the script ? Is it better to use this method and not the mos way?
> 2. How do I trigger the access point ? Because I don't see the Shelly WiFi address in my iPhone WiFi list.
> 
> Thanks for the support

script only works if it is attached to your network, but you could try it

https://github.com/mongoose-os-apps/shelly-homekit/blob/master/tools/flash_shelly.sh

in terminal try `./flash_script.sh -la` this should list all found shelly devices on the network, and report what firmware is loaded. to revert to stock to `./flash_script -m revert hostname`. hostname is the one listed shown in the list.
