### ISSUE TITLE
Homkit show wrong position 

### ISSUE THREAD

**Issue by MacUser341** [mongoose-os-apps/shelly-homekit#1540]
Hello
In all my Shelly 2PM Plus the roller in homwkit shows the opposite position.
How can I fix it? 
I played with the swap outputs and input in the settings and just change the button and not the homekit position.
In the stock there's an option to change it by the way.

**Comment by markirb** [comment]
Thieves described in https://github.com/mongoose-os-apps/shelly-homekit/issues/1420

Unfortunately no fix yet
