### ISSUE TITLE
Turn AP off and after holding switch for 10sec turn AP on

### ISSUE THREAD

**Issue by maf-o** [mongoose-os-apps/shelly-homekit#155]
Hello,
I use the Shelly 1 in my stairwell to trun off the lights after 50sec when button was pushed.
The main power distributor, where shelly hangs, is out of range of Wifi so get no connection.
Would be nice if i can turn on AP after holding switch/button for 10 sec, than i can adjust behavior and after 5min automatically turn AP off until i hold for next 10sec.

**Comment by andyblac** [comment]
if you can't connect it to a WiFi AP as signal is too weak, why not just leave the device in AP mode all the time, ie don't set wifi settings, then you can just walk up to it with your phone connect to it's own AP and configure via 192.168.33.1 ?

**Comment by maf-o** [comment]
Because of environmental polution (energy and frequenzes)
I dont need an accespoint in the basement.
I dont need an accespoint where someone tries to hack in and switching my lights.

**Comment by andyblac** [comment]
I'll leave this for rojer to comment on, but imo the range of AP is very limited, and regardless if it is AP or wifi mode it still emitting as you say pollution, so sorry but that makes no sense.

**Comment by maf-o** [comment]
In Arduino IDE i can switch of the Wifi of ESP. Then there is no AP or Wifi transmission.

**Comment by andyblac** [comment]
so you basically want to disable the Wif totally. tbh I don't see this that something most people would use. but again I'll revert to @rojer on this matter.

**Comment by rojer** [comment]
i agree, this seems too niche of an application

**Comment by maf-o** [comment]
can you point me where i can do the magic myself?

**Comment by andyblac** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/tree/master/src
