### ISSUE TITLE
Shelly 1 v3 dead after swap inputs enabled

### ISSUE THREAD

**Issue by mikecitt** [mongoose-os-apps/shelly-homekit#1552]
I wanted to set up Shelly 1 as a Garage Door Opener, and during testing, I enabled the "Swap Inputs" option. After that, it became unavailable. I wasn't even able to reset it to factory settings. Do you have any suggestions?

**Comment by markirb** [comment]
Yes. Factory reset. Will be fixed in next version.

https://github.com/mongoose-os-apps/shelly-homekit/discussions/1545#discussioncomment-11058710

**Comment by mikecitt** [comment]
@markirb I did try, but as I wrote, I'm not able to reset it as well.

**Comment by markirb** [comment]
After 5 powerups it should reset itself

**Comment by mikecitt** [comment]
@markirb That’s exactly what I tried, and nothing. I’ve broken 2 devices. :(

**Comment by markirb** [comment]
One of those will work:

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery

**Comment by markirb** [comment]
Shelly 1 has no button.

Input will also not work.

So your only option is the reboot counter so 5 reboots. This should work

**Comment by markirb** [comment]
I would switch off 5 sec switch on 5 secs and repeat this 5 times or more

**Comment by markirb** [comment]
If all this does not work you need a serial interface or you get a Shelly addon...

**Comment by mikecitt** [comment]
after few random restarts it got to work! thank you so much!
