### ISSUE TITLE
Shelly Plus1PM Updaten 2.12.2 to 2.13

### ISSUE THREAD

**Issue by Sepphuber007** [mongoose-os-apps/shelly-homekit#1554]
Hello, when I want to update the Shelly to the latest version Shelly Plus1PM, I always get this error (see picture). If I try it manually to install the SW DL and it does not work because after the reboot the old one is on it again.

What can I do here?

Model: ShellyPlus1PM 
![grafik](https://github.com/user-attachments/assets/f88fd744-010b-40da-96c5-7b710d45b9d2)

many thanks
sepp

**Comment by pfrasun** [comment]
For Plus Devices Update process requires reverting to stock firmware and update to latest Shelly FW to change partitioning of memory. So steps look like following:
1. Revert to Stock
2. In shelly FW update to latest Shelly FW
3. As a last step manually update to Shelly HomeKit 2.13.0
After this procedure device **does not require** repairing in HomeKit, so you shall not loose any settings.

**Comment by markirb** [comment]
This. Or read the release notes 🙃

**Comment by Sepphuber007** [comment]
Thanks for your help, it worked
