### ISSUE TITLE
Duo GU10 White/RGBW Support

### ISSUE THREAD

**Issue by dgvinton** [mongoose-os-apps/shelly-homekit#1559]
Has anyone taken up support for the Duo GU10 White/RGBW?

I use the DUO integration.  It works perfectly!

I'm looking down the road as I have a new lighting project coming up....

Thanks,

Don

**Comment by markirb** [comment]
Im pretty sure we already support them? Did you try automatic update link?

**Comment by dgvinton** [comment]
Hi Markus,Thank you for the reply.  I’ve ordered a DUI GU10 for testing.Best regards,DonSent from my iPadOn Nov 11, 2024, at 3:21 PM, Markus Kirberg ***@***.***> wrote:﻿
Im pretty sure we already support them? Did you try automatic update link?
