### ISSUE TITLE
Input 1

### ISSUE THREAD

**Issue by Ludelag** [mongoose-os-apps/shelly-homekit#156]
I just update to version 2.1.8 and I see in the Home app input 1 not configured
Someone could please tell me how to configure input 1? and what and how to use it.

Thanks

**Comment by andyblac** [comment]
long press on the tile you should something like

![IMG_0296](https://user-images.githubusercontent.com/77936/94558976-79df7f80-0258-11eb-9a08-fb3be13f185a.jpeg)

look at actions, tap on the action you want to add, and set as a normal homekit action.

**Comment by Ludelag** [comment]
Thank you for the info, So is where I can for example wire the door magnetic sensor?, but it wont appear in the homekit as a door sensor, isn´t it?

**Comment by andyblac** [comment]
> Thank you for the info, So is where I can for example wire the door magnetic sensor?, but it wont appear in the homekit as a door sensor, isn´t it?

thats not support yet, iirc.

**Comment by Ludelag** [comment]
What is not supported? the door sensor wiring or how will it be showed in the apple homekit?

**Comment by andyblac** [comment]
Both iirc

**Comment by rojer** [comment]
the only way to represent an independent input in homekit that is currently supported is a stateless switch.

other possibilities are:
 - contact sensor
 - motion sensor 
 - occupancy sensor

this work will happen some time in the future, https://github.com/mongoose-os-apps/shelly-homekit/issues/147 will track that

**Comment by Ludelag** [comment]
If I got it, now is possible to represent it as:

contact sensor
motion sensor
occupancy sensor

**Comment by rojer** [comment]
not yet, but it might be

**Comment by Ludelag** [comment]
So, it means right now Input 1 is useless, I mean there is any action to be applied?

**Comment by andyblac** [comment]
> So, it means right now Input 1 is useless, I mean there is any action to be applied?, 

yes, any homekit device to control, that is not the shelly, ie group of lights, power socket, etc etc, ie you use the physical switch to control something else.
