### ISSUE TITLE
Shelly +PlugS can't check for Update on GitHub (2.13.1 and below)

### ISSUE THREAD

**Issue by DB2FM** [mongoose-os-apps/shelly-homekit#1564]
I have several different Shelly, all with shelly-homekit (2.13.x).
Today I started the updates on them (manually). On 2.5, PlugS, +1PM, +2PM, +1 an ColorBulb it worked like a charm.

Only the +PlugS can not find the update. The check shows only failed.
No problem I uploaded manually.
After rebooting with 2.13.2 the check still fails.

Just wanted to let you know. Might be only a small glitch ;)

Thank you for your continuous work and all the efforts you made in the past :)

**Comment by markirb** [comment]
You're right, it was not in the list. Fixed. BR
