### ISSUE TITLE
Feature Request: I/O URL Actions

### ISSUE THREAD

**Issue by tob1no** [mongoose-os-apps/shelly-homekit#1565]
Hey there! I love your work :)
The only feature I'm missing for some lights is the possibility to use I/O URL actions like button on or button off:
![image](https://github.com/user-attachments/assets/896e7841-59be-45b0-86d7-36f8917edba8)
Maybe I'm not the only one interested in this.
Also, is there a plan about an implementation for the shelly dimmer 2?
Thank you very much in advance!
BR,
tob1no

**Comment by markirb** [comment]
You are surely not the only one:

https://github.com/mongoose-os-apps/shelly-homekit/discussions/1484
