### ISSUE TITLE
Shelly 1 Gen 3 - 404 error

### ISSUE THREAD

**Issue by scparkeratproofpoint** [mongoose-os-apps/shelly-homekit#1569]
When attempting to update my Shelly 1 Gen 3 using http://192.168.8.115/ota?url=http://shelly.rojer.cloud/update I am getting a 404 error.  Any thoughts?  Gen 3 unsupported?  Yes, I updated the firmware 20241011-114449/1.4.4-g6d2a586.

Thanks in advance!

**Comment by markirb** [comment]
Gen 3 is supported but so far only the Minis

**Comment by scparkeratproofpoint** [comment]
Thanks Markus. I’ll monitor to see if or when it is supported.

Thanks - Scott
210-602-8998 mobile
________________________________
