### ISSUE TITLE
Shelly S2PMG3

### ISSUE THREAD

**Issue by agsenna** [mongoose-os-apps/shelly-homekit#1575]
is there a new firmware for shelly s2pmg3 - HomeKit?

**Comment by markirb** [comment]
Tasmota has a preliminary pinout since today

Branch is here... if you want to try:
https://github.com/mongoose-os-apps/shelly-homekit/pull/1578

try at your own risk, there really can go anything wrong. Reverting currently not possible

**Comment by markirb** [comment]
please continue here: https://github.com/mongoose-os-apps/shelly-homekit/discussions/1538
you will also find a testing version there

**Comment by agsenna** [comment]
thanks a lot!
