### ISSUE TITLE
Shelly RGBW Duo bricked after flashing

### ISSUE THREAD

**Issue by sambeesems** [mongoose-os-apps/shelly-homekit#1577]
I've flashed two new Shelly GRBW Duo's using the information on the flashing wiki:

1. Power on devices
2. Use Shelly app to connect them to my WiFi.
3. Perform OTA using the 'http://A.B.C.D/ota?url=http://shelly.rojer.cloud/update' link (I replaced the ABCD with the device's IP.
4. After this, I did see the following info:
status | "updating"
has_update | false
new_version | "20230913-111548/v1.14.0-gcb84623"
old_version | "20201008-085327/master@a3d98bb0"
beta_version | "20231107-162425/v1.14.1-rc1-g0617c15"
5. After this the devices are still showing up in my network, but navigating to their IP address now show me the old Shelly interface with the message: 'Could not fetch device settings' and 'Device unavailable'.

Any idea on how to resolve this?

**Comment by markirb** [comment]
Did you progress on this? I mean it is not bricked you just have to perform a factory reset.
