### ISSUE TITLE
Restore or read the setup code for a Shelly1 with HomeKit firmware?

### ISSUE THREAD

**Issue by aXCell-fl** [mongoose-os-apps/shelly-homekit#1589]
I have been using a Shelly 1 with the HomeKit firmware as a garage door opener for several years, but now I want to add it to another instance.
Is it possible to display or generate the HomeKit setup code again **without it being removed from the current configuration**?

**Hardware**:
Model: Shelly1
Device ID: shelly1-773007 

**Firmware**:
Version:2.13.3
Build: 20241203-191940/2.13.3-g1cb5084 

**Debug info:**
```
App: switch1 2.13.3 20241203-191940/2.13.3-g1cb5084
Uptime: 209.87
RAM: 26768 free, 21608 min free
HAP server port: 9000
HAP config number: 3
HAP connection stats: 0/1/12
HAP connections:
  192.168.178.5:59552 nc 0x3fff48ecf 0x200000 io 4 ts 0x3fff1c2c rd 3
 Total: 1
HAP sessions:
  0: s 0x3ffe9a68 ts 0x3fff1c2c o 1 st 1 ts 206173
 Total: 1

```

Is further information required?

**Comment by markirb** [comment]
This is not possible, at least not with easy measures.
