### ISSUE TITLE
Not able to update shellyuni from 20221027-121732/v1.12.1-ga9117d3

### ISSUE THREAD

**Issue by chef76** [mongoose-os-apps/shelly-homekit#1595]
Hi,

 i have done this 5 times without problem, but today i`m not able to update my shellyuni anymore.
 The answer to following request: http://A.B.C.D/ota?url=http://rojer.me/files/shelly/2.13.3/shelly-homekit-ShellyUNI.zip is {"status":"updating","has_update":false,"new_version":"","old_version":"20221027-121732/v1.12.1-ga9117d3"}

Looks like it doesn't find the new firmware?!? Or isn't it possible to update from this version?

Can somone please help me?

**Comment by markirb** [comment]
Please update to latest stock version first this should be v1.14.0-gcb84623

**Comment by chef76** [comment]
It doesn't offer me that firmware?!?

![image](https://github.com/user-attachments/assets/6e548b19-956b-43c5-9c99-49eabbc5bfb0)

**Comment by markirb** [comment]
you can try this tool: http://archive.shelly-tools.de/

**Comment by chef76** [comment]
Tranks for your help, but this doesn't work either:

http://192.168.2.144/ota?url=http://archive.shelly-tools.de/version/v1.14.0/SHUNI-1.zip

Same result:

![image](https://github.com/user-attachments/assets/1517e340-0eb9-4818-897b-8fa8def5be39)

**Comment by markirb** [comment]
Did you reset already?

**Comment by chef76** [comment]
Reset, cold start, nothing worked. Took a new one out of the box and it worked first try.

Thanks for your help!

**Comment by chef76** [comment]
After a Factory Reset and Setting it up from scratch, it offered the  new firmware version and update to    HomeKit worked 🥳
