### ISSUE TITLE
Can't flash Shelly plus 1pm with HomeKit Firmware

### ISSUE THREAD

**Issue by M4tRiX92** [mongoose-os-apps/shelly-homekit#1599]
Hi, I have several shellys installed and flashed with the HomeKit Firmware. 3 days ago I installed 2 new "Shelly plus 1 pm". Unfortunately I cannot Flash with the HomeKit Firmware.

shelly_ota.cpp:245 Aborting update: backend error while processing data: -1 (-11: PT update is req'd but unsupported by the new fw)
19:06:26
shelly_ota.cpp:172 OTA status error, 1 %
19:06:26
shelly_http_client.:606 0x3ffe281c: Finished; bytes 30240, code 200, redir 0/2, auth 0, status CANCELLED: Cancelled
19:06:26
shelly_notification:209 Event from sys: {"component":"sys", "event":"ota_error", "msg":"error", "ts":1735149986.23}

Any ideas?

Current Firmware: 1.3.3

Merry Christmas!

**Comment by markirb** [comment]
As written in readme:

Updating from stock firmware

Important: Please update to the latest stock firmware prior to converting to Shelly-HomeKit (1.4 or later on Plus Devices).
