### ISSUE TITLE
webUI beta5 issues.

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#161]
1st see below drop boxes for Shelly1 vs Shelly2.5 inconsistencies.

Shelly1
![Screenshot 2020-10-01 at 09 27 53](https://user-images.githubusercontent.com/77936/94786276-a7e3d180-03c8-11eb-9964-78aef23ca8ce.jpg)

Shelly2.5
![Screenshot 2020-10-01 at 09 27 41](https://user-images.githubusercontent.com/77936/94786247-9f8b9680-03c8-11eb-8816-10da1c9d9c59.jpg)

**Comment by andyblac** [comment]
also Model is missing on both Shelly1 / 2.5 
![Screenshot 2020-10-01 at 09 31 38](https://user-images.githubusercontent.com/77936/94786574-0d37c280-03c9-11eb-93af-8cc861021d21.jpg)

**Comment by andyblac** [comment]
hmm, OK ignore issue 1 , seems was a browser issue, looks ok now after a reboot.

**Comment by rojer** [comment]
i think (1) is due to stale style.css, eventually it gets reloaded.

re: model - oops, yeah, added a field and forgot to populate it.

**Comment by rojer** [comment]
fixed in beta6

**Comment by andyblac** [comment]
release notes for beta6 are linked to https://github.com/mongoose-os-apps/shelly-homekit/issues/5#issuecomment-701662473.  ie about beta5 ??

**Comment by rojer** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/issues/5#issuecomment-702269738

forgot to update the url, fixed now
