### ISSUE TITLE
Bad default state and button type combination

### ISSUE THREAD

**Issue by maf-o** [mongoose-os-apps/shelly-homekit#165]
Hello,
I want EDGE switch with auto off.
Everytime the Switch is hit after 50s the lights should go out.
![index](https://user-images.githubusercontent.com/60689016/94803942-53514e00-03ea-11eb-8806-ffba2eb45c1c.jpg)
any suggestion?

kind regards

**Comment by andyblac** [comment]
sorry, but that not HomeKit firmware, thats stock firmware. if you want to use stick firmware you are better off asking the question over on the Shelly Facebook page here https://www.facebook.com/groups/ShellyIoTCommunitySupport/

**Comment by andyblac** [comment]
closing this as no response from OP.
