### ISSUE TITLE
Overheating protection support

### ISSUE THREAD

**Issue by Baza207** [mongoose-os-apps/shelly-homekit#168]
I might have missed this (or maybe this is something that's done in hardware and so the firmware doesn't change much) but for devices like the Shelly 2.5 which support overheating protection, does that still work when using this firmware? Thanks in advance.

**Comment by rojer** [comment]
no, not at present

**Comment by rojer** [comment]
should be easy to add, just need to figure out the formula for the NTC.

**Comment by Baza207** [comment]
Thanks, good to know. Would love that as a feature request then, but not exactly sure how useful it is. One of those piece of mind features. 🙂

**Comment by rojer** [comment]
absolutely, we should have this.

**Comment by rojer** [comment]
implemented, will be in the next release
