### ISSUE TITLE
webUI

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#169]
just thinking about webUI and wiki, do you think it would be helpful to have a "Help" button in each section of the UI that would open a new page to the wiki of that section.

ie. 
in Switch section the word "Help" (or something else) in the top right corner that when clicked it opens a new web page the shows the "Switch Settings" section of the wiki?

**Comment by rojer** [comment]
yep, had exactly the same idea. we should have "Help" links in each section.
@schemhad can you help with that, perhaps?

**Comment by schemhad** [comment]
This should be easy, I'll take a look at it ...

**Comment by schemhad** [comment]
![help](https://user-images.githubusercontent.com/64190390/95003136-4a27d300-05dc-11eb-9bba-680777038ef8.png)

Like this?

**Comment by andyblac** [comment]
yeah, but maybe move dot so it inside white area.

**Comment by schemhad** [comment]
![preview](https://user-images.githubusercontent.com/64190390/95017958-a599a580-065c-11eb-8e1a-78efce755312.png)

**Comment by andyblac** [comment]
for me personally 1t one.

**Comment by schemhad** [comment]
I could customize and place it any way you like.

**Comment by rojer** [comment]
i like no. 3

**Comment by andyblac** [comment]
go 3 then, thats ok with me :)

**Comment by andyblac** [comment]
@rojer in `Shelly 1` could tweak ui for switch setting from `Switch 1 (Shelly SW)` to `Switch (Shelly SW)`, as there is only 1 relay.

**Comment by rojer** [comment]
integrated and released in 2.2.1

**Comment by andyblac** [comment]
> @rojer in `Shelly 1` could tweak ui for switch setting from `Switch 1 (Shelly SW)` to `Switch (Shelly SW)`, as there is only 1 relay, and same for `Input 1 (Input)` when detached is enabled.

@rojer what about this ?
