### ISSUE TITLE
Momentary button Shelly 1

### ISSUE THREAD

**Issue by Kroellie** [mongoose-os-apps/shelly-homekit#17]
Hi, I have hacked my garagedoor opener to be opened and closed with my Shelly 1. However, the mechanism works like a push button so it works like this:

Shelly on - off: garage opens
Shelly on - off: garage stop
Shelly on - off: garage closes

However this requires the homekit button to auto turn off again. The webpage of your firmware suggest a possibility in setting the mode to this: momentary. However, that doesn't work like I expected, at least, I don't see anything change at homekit level. Maybe I'm getting this wrong? I also tried Toggle, same result. 

Unfortunately homekt doesn't allow this automation: when button is on, set button to off. Otherwise that would be ok for me. Now I'm stuck with pressing twice, which has a lot of latency issues as well.

Any idea?

**Comment by rojer** [comment]
"momentary" mode is for the input, what you are after is what's called "auto off" in stock firmware and is described in #11. upvote that one, it's not that hard to do. i'll get to it eventually, or someone else may step in.
