### ISSUE TITLE
Shelly Shutters - opposite

### ISSUE THREAD

**Issue by macguru341** [mongoose-os-apps/shelly-homekit#170]
Hello
First of all I want to say thanks for your hard work to make it happen and use Shelly 2.5 as roller shutters .
I've installed on all of my shutters and in some strange way (even after a calibration I did) the status is opposite , when the shutter is open it's says in HomeKit that it's close , only in one of my shutters it shows the right status , how can I fix it?

**Comment by rojer** [comment]
sounds like you have open on output 2 and close on output 1 then. try swapping outputs - enable "swap outputs" in the web ui.

**Comment by macguru341** [comment]
Both swap are off and the actual switch is working fine. If I use the swap the actual switch will be opposite

**Comment by rojer** [comment]
so you mean physical switches operate in the right direction but home app status is reversed?

**Comment by macguru341** [comment]
Yep , exactly

**Comment by rojer** [comment]
interesting. does partial positioning fron the app work? e.g is 25% open really 25 or more like 75?

**Comment by macguru341** [comment]
Also the control in HomeKit is opposite

**Comment by macguru341** [comment]
> interesting. does partial positioning fron the app work? e.g is 25% open really 25 or more like 75?
25% open is 75%

**Comment by macguru341** [comment]
Maybe it's the calibration? In what position I need to start the calibration?

**Comment by rojer** [comment]
ok. well, then you need to swap both outputs and inputs.

**Comment by rojer** [comment]
no, you really have the device wired the opposite way. inputs are currently in sync with outputs because they are also wired backwards, so you just need to swap both.

**Comment by macguru341** [comment]
Tried it , if I swap both inputs and outputs to on position the status in HomeKit stays the same and now the actual switch isn't working

**Comment by rojer** [comment]
re-run calibration

**Comment by macguru341** [comment]
1. So it doesn't matter in what position is the shutter when I start the calibration?
2. Also off topic, if the firmware have an update it will say in HomeKit ?

**Comment by rojer** [comment]
1. yeah, you can start calibration from anywhere
2. no, it won't. there isn't (or at least i'm not aware) of any way to do that. you need to check for update manually in the web ui.

**Comment by macguru341** [comment]
Did a new calibration and still in the homekit web it's says 89% and also in HomeKit Aldo it's 11% open 🤷🏻‍♂️![image](https://user-images.githubusercontent.com/22807164/95001000-8fdd9f00-05ce-11eb-96b5-14366982ef3a.png)

**Comment by rojer** [comment]
weird. ok, when calibrating, does it go to open position first, then close? this is how it's supposed to be.

**Comment by macguru341** [comment]
No
It's first close and than open
Also the buttons in the web interface are opposite

**Comment by rojer** [comment]
what happens if you enable both swap inputs and swap outputs? don't forget to press "save" button.

**Comment by macguru341** [comment]
Well, one of my shutters was fixes and now it's ok if I swap both input and output but my second one lost connection now and I can't reach it , the web isn't loading and the actual switch isn't working as well, what can I do?

**Comment by macguru341** [comment]
Hope you can help retrieve connection to my porch shutters as it's seems offline and my WiFi is going to kill me!!! She always says that all of this smart home things will kill one of the shutters ...please help 😏

**Comment by rojer** [comment]
hm, that's the 3rd case reported of this, see #171 
unfortunately, i currently have no idea what the cause is...
it looks like i will need to have one of these devices sent to me so i can examine.

**Comment by rojer** [comment]
can you tell how it happened? was it moving at the time it became unreachable?

**Comment by macguru341** [comment]
I played with the swap on and off and pressed save and than it become like that

**Comment by macguru341** [comment]
Ao it means the Shelly is dead ?

**Comment by rojer** [comment]
i take it you tried turning power off and on for it, right?
after power is applied, you should see LED blinking. do you see any activity on the LED?

**Comment by andyblac** [comment]
to me it sounds like they are caught in a boot loop, but as @rojer says without connecting one to serial it hard to tell.

**Comment by rojer** [comment]
yeah. i suspect filesystem corruption, but no way to confirm or fix without a serial connection, unfortunately

**Comment by macguru341** [comment]
I will replace the unit today

**Comment by rojer** [comment]
can you send the bad one to me?

**Comment by macguru341** [comment]
Sure , send me your address to my email : ofir341@gmail.com

**Comment by rojer** [comment]
ok, i believe we have this resolved. 2.2.1 was released that fixes #171 and swapping addressed your initial issue.
