### ISSUE TITLE
problem with files

### ISSUE THREAD

**Issue by Qubi-B** [mongoose-os-apps/shelly-homekit#173]
I cant find a way to flash multiple files to shelly. how to do that ? (how to flash this firmware, or can i download it in one file ?) I searched on yt and google but i found nothing.. :( help pls

**Comment by rojer** [comment]
i honestly have no idea what you're talking about. flash multiple files? why?
please explain.

**Comment by andyblac** [comment]
oh, I think I understand you, you don't, you flash the ZIP file to the shelly. 

make sure when you download the file, you don't have your web browser auto unzipping the file.

**Comment by rojer** [comment]
yeah, what @andyblac said. with update being done from the UI, you also don't need to download anything anymore.
