### ISSUE TITLE
WebUI: Phone-friendly layout

### ISSUE THREAD

**Issue by rojer** [mongoose-os-apps/shelly-homekit#177]
Right now layout is not very phone-friendly, we get breaks in awkward places between elements.
@schemhad could you help tune the layout so it looks nice on the phone? making buttons smaller to make them fit, fixing the header, etc.

**Comment by schemhad** [comment]
Sure, I'll take a look...

**Comment by Rappelsack** [comment]
I just have to take this thread here to say a big (!!!) thank you. Awesome what ure doing here. My whole house is now automated with shelly and your software.

@all other guys out there: give a donate!

**Comment by rojer** [comment]
@Rappelsack thank you for your kind words!

**Comment by andyblac** [comment]
pull request here https://github.com/mongoose-os-apps/shelly-homekit/pull/380 thanks to @ZeevoX

**Comment by andyblac** [comment]
@ZeevoX any reason you closed the pull request ?

**Comment by ZeevoX** [comment]
@andyblac because HTML `<table>` should not be used purely as a means to layout document content, and instead for presenting tabular data. I am going to re-do the layout using `<div>`s and CSS.

**Comment by rojer** [comment]
fixed by #488
