### ISSUE TITLE
Home Add Accessory doesn't work.

### ISSUE THREAD

**Issue by fd007** [mongoose-os-apps/shelly-homekit#179]
After entering setup code I get following response.

Unable to Add Accessory -  An unknown error occurred.

Some Ideas?

**Comment by andyblac** [comment]
> After entering setup code I get following response.
> 
> Unable to Add Accessory - An unknown error occurred.
> 
> Some Ideas?

entering where webUI or HomeKit ?, also what code was used ? some simple codes like 111-11-111 or not valid in homekit.

**Comment by fd007** [comment]
1. Entering in HomeKit.
2. I don't use invalid code.

**Comment by andyblac** [comment]
maybe code was used before, try reset button in HomeKit section in webUI, codes are only valid once iirc.

**Comment by fd007** [comment]
Silly question, but can you give hint how to open Homekit webUI?

**Comment by andyblac** [comment]
> Silly question, but can you give hint how to open Homekit webUI?
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Device-webUI
https://github.com/mongoose-os-apps/shelly-homekit/wiki/HomeKit-settings

**Comment by andyblac** [comment]
did it help ?

**Comment by fd007** [comment]
No, it did not - unfortunately.

Is it possible that Apple disable adding device to Homekit after Homekit setup code have been changed for several times?

Is there some way how to reset is again?

Thx!

**Comment by andyblac** [comment]
You reset it in webUI reset HomeKit

**Comment by fd007** [comment]
No, what I mean is that Apple block the device, after setup code has been reseted in webUI several times?

**Comment by andyblac** [comment]
> No, what I mean is that Apple block the device, after setup code has been reseted in webUI several times?

no they don't

**Comment by andyblac** [comment]
are you using. mesh wifi?, I have herd that can cause issues with homekit.

**Comment by fd007** [comment]
Yeah, that could it be. Thanks for this Idea!

**Comment by rojer** [comment]
right, i've reset and re-added device many times, they don't get banned or anything.
pressing "reset" in homekit section completely wipes homekit state, including unique device id, after that it should definitely appear in the list of devices to add.

**Comment by andyblac** [comment]
> right, i've reset and re-added device many times, they don't get banned or anything.
> pressing "reset" in homekit section completely wipes homekit state, including unique device id, after that it should definitely appear in the list of devices to add.

I think his issue is mesh wifi, and multicast

**Comment by andyblac** [comment]
you get his sorted ?

**Comment by rojer** [comment]
closing as stale
