### ISSUE TITLE
Roller shutter Shelly 2.5 without physical switches

### ISSUE THREAD

**Issue by Whiterabbit64** [mongoose-os-apps/shelly-homekit#182]
I intend to use the Shelly 2.5 with my roller shutters equiped with Somfy motors but without physical switches. They are driven via a Nice radio remote controller as they are also equiped with a Nice TT1N radio receiver.

What would be the best settings in the Shelly 2.5 ? (Detached, single, etc.)

**Comment by rojer** [comment]
if you set it to "detached", this will create two additional tiles in the home app that will be of no use to you.
if you don't intend to use shelly inputs for anything, the mode doesn't really matter - just leave them physically unconnected.
