### ISSUE TITLE
Shelly 2.5 support power measurement in HomeKit?

### ISSUE THREAD

**Issue by Tomer51m** [mongoose-os-apps/shelly-homekit#185]
Hi, I noticed in the wiki that it is stated that power measurement is supported in the Shelly 2.5 for HomeKit.
I can't see any anything in my Home app on my iPhone, so I am not really sure if it means the support is in the Home app or the web UI of the Shelly device (which I'm pretty sure already showed power consumption).
Regards.

**Comment by andyblac** [comment]
not in homekit, just in webUI

**Comment by rojer** [comment]
yes, there is no way to expose it in homekit, unfortunately. we show it in the web ui.
