### ISSUE TITLE
Shelly HT

### ISSUE THREAD

**Issue by schemhad** [mongoose-os-apps/shelly-homekit#186]
It would be very nice if we could support Shelly HT. Maybe this could be similar to the Power Measuring?

**Comment by andyblac** [comment]
> It would be very nice if we could support Shelly HT. Maybe this could be similar to the Power Measuring?

is HT bluetooth ?

**Comment by schemhad** [comment]
It's an Shelly1 with Humidity and Temperature Sensor. 

https://shelly.cloud/knowledge-base/devices/shelly-ht/

The Sensor could also bought seperate. 

https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312

**Comment by andyblac** [comment]
ok, wifi, I can't see that battery lasting a week on HomeKit, as it will drain battery as it keep checking connectivity.

**Comment by schemhad** [comment]
But the AddOn Module could run on every Shelly 1 & PM or the retail H&T Module on USB.

**Comment by andyblac** [comment]
> But the AddOn Module could run on every Shelly 1 & PM or the retail H&T Module on USB.

ye I was talking about H&T on battery.

**Comment by rojer** [comment]
yes, this can be done

**Comment by rojer** [comment]
HAP has accessories for temperature and humidity sensors, shouldn't be hard to add.
ideally, we'd auto-detect the sensor on startup so no UI changes would be necessary.

**Comment by MilanBacaCz** [comment]
is there any documentation how to auto detect the temperature and other sensors?

**Comment by Ludelag** [comment]
> yes, this can be done

Dear @rojer does it means will be done it?

**Comment by rojer** [comment]
eventually yes

**Comment by Ludelag** [comment]
> eventually yes

that will be nice

**Comment by rojer** [comment]
looked into this. addon provides a 1-wire bus with output on gpio0 and input on gpio3 (uart0 rx).
output is connected to input (via isolator).
so this can be used for 1-wire sensors or simply as an extra input.

**Comment by Pixel-Chris** [comment]
Will this be usable for the second sensor for the opened position of the garage door opener with a Shelly 1?  (Then I don’t need to power a Shelly 2.5 with an extra power supply)

**Comment by rojer** [comment]
@Pixel-Chris this is indeed possible. the add-on contains circuitry that provides proper isolation for the input.

**Comment by Pixel-Chris** [comment]
Ok 
I must order that addon 😉

**Comment by Ludelag** [comment]
I will for sure also order one and be ready for tasting

**Comment by Ludelag** [comment]
Thank you @andyblac, You already linked my issues in here nevertheless I will write them again to make it easier to read directly:
@rojer and @andyblac I just wonder if there is a support to use the Shelly 1 together with Shelly H & T as thermostat which could appear as a thermostat in the Home app? It will enable controling the heating by schedules using automation. Thank you.
![99046641-57e55680-2593-11eb-977d-04ea578d11d3](https://user-images.githubusercontent.com/69207063/99542725-ae4afe80-29b2-11eb-8fe6-f589550d6a9a.jpg)

**Comment by Ludelag** [comment]
planning to add Shelly-Homekit the Add-on of shelly?

https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312

Thank you.
![81262242_10220337751536450_1385881776282402816_n](https://user-images.githubusercontent.com/69207063/99542933-e4887e00-29b2-11eb-8589-98506e886993.jpg)
![82279151_10220337799137640_2205997702620119040_n](https://user-images.githubusercontent.com/69207063/99542954-e8b49b80-29b2-11eb-933f-e34f5a28d63d.jpg)

**Comment by SilvioMigu** [comment]
Hello

Temperature Sensor AddOn for Shelly 1/1PM, do you think you can do it soon?
Thanks

**Comment by rojer** [comment]
sorry, no ETA.

**Comment by SilvioMigu** [comment]
Sorry, but what do you mean "no ETA"?

**Comment by andyblac** [comment]
"Estimated Time of Arrival"

**Comment by SilvioMigu** [comment]
This of being new, in this things, is what happens ...
We are always learning.

**Comment by andyblac** [comment]
> This of being new, in this things, is what happens ...
> We are always learning.

no one knows everything, the world would be a boring place to live.

**Comment by SilvioMigu** [comment]
I also like to share what I'm doing so that I can help each other ...

I have three temperature sensors here in my water cylinder.
Maybe there is a better way to use shellys in this area

My problem here, is that the temperature sensor Addon from shelly, has 3 wires and the sensors that I have in the cylinder, are 2 wires.
I'm still not sure how to connect the sensor ...
![IMG_4691](https://user-images.githubusercontent.com/67691682/102605405-237a3280-411d-11eb-9681-005be1b76742.jpg)
![IMG_4688](https://user-images.githubusercontent.com/67691682/102605423-29701380-411d-11eb-8da2-d774b3ec4b13.jpg)

**Comment by Pixel-Chris** [comment]
Some free timeslots left for this?

**Comment by rojer** [comment]
been thinking about this lately, actually. shouldn't b too difficult, it might just happen.

**Comment by SilvioMigu** [comment]
I am looking forward to seeing the final result...

**Comment by Ludelag** [comment]
What Will be interesting is to be able to make a thermostat with Shelly 1 and add on

**Comment by bjornand1** [comment]
I would be very interested in support for the Temp Sensor Addon - the plan is to use the sensor to measure the water temperature in our fish tank and turn on/off the aquarium lights based on the temp.

**Comment by Baddy-HIP** [comment]
Hello to all and thanks for the great opportunity to integrate Shelly into HomeKit!!!

When will the addon be integrated? I am looking for a solution to control my sauna and some terrarium. Since I already control everything with Shelly switches, it would be great if I could measure and control the temperature as well.

**Comment by bjornand1** [comment]
Hi, @Baddy-HIP ´, notice that this plugin, https://github.com/metbosch/homebridge-http-temperature#readme, actually works very well for the temp sensor!

**Comment by Baddy-HIP** [comment]
Thank you for your information!
I tried using home bridge and  had many issues. So I would prefer a solution to implement it directly in HomeKit

**Comment by Pixel-Chris** [comment]
I would use it for a second sensor for the garage door mode.

**Comment by timoschilling** [comment]
I removed Temperature AddOn from title because it's supported now.

**Comment by markirb** [comment]
I just noticed, in the meantime there was this commit for the driver from Allterco :smile: so the way to supporting HT got shorter
https://github.com/mongoose-os-libs/dht/commit/35a6ffc29152c7944b2552150f2039f44c142cfa

**Comment by vrpt2022** [comment]
Good morning,
I would like to know if support for add-on and Shelly 1 is just for sensor DS18B20 or DHT22 is also supported. I tried the shelly 1 with add-on and DHT22 (AM2302 sensor) and neither through Web interface/home app I'm able to see any information regarding the add-on/sensor. (I can see both, humidity and temperature through native Shelly firmware...)

In the case of not being supported at the moment, do you think would it be possible to give support?

Thanks in advance for your help.

**Comment by markirb** [comment]
It is not supported currently, as written in the documentation. Otherwise this issue would not exist anymore :)

I have a HT at home now but little time...

**Comment by vrpt2022** [comment]
> It is not supported currently, as written in the documentation. Otherwise this issue would not exist anymore :)
> 
> I have a HT at home now but little time...

Thanks for the answer.... waiting for it :D

**Comment by vrpt2022** [comment]
Good afternoon,

Any update regarding this?

Thank you

**Comment by markirb** [comment]
sorry, not from me so far

**Comment by vrpt2022** [comment]
Good morning,

Any update regarding the H&T sensor?

Thank you

**Comment by markirb** [comment]
Mhh, did some lines already, but not there yet.
Have to finish my tax returns first unfortunately after that I home I find some time.

**Comment by vrpt2022** [comment]
Good afternoon,
I’ve seen the PR advancements, but there is any update regarding this? 
Thank you!

**Comment by markirb** [comment]
Not yet, the two things mentioned in the PR still exist, and I haven't found a way around the first one. So If anyone can help, it would be much appreciated

**Comment by vrpt2022** [comment]
Hi,

apologies if this is no appropriate, I have absolutely no idea about coding, but found in this project a reference about integration of DHT sensors in HomeKit, could this be of any help?

https://github.com/RavenSystem/esp-homekit-devices

https://github.com/RavenSystem/esp-homekit-devices/wiki/Temperature-and-Humidity-Sensors

**Comment by markirb** [comment]
There is no general issue, generally the implementation works already. 

But somehow it has hiccups on startup. This needs an oscilloscope and time to debug...

**Comment by timoschilling** [comment]
@pfeifix I think you misunderstood some things. What you wrote sound like you have a Shelly 1 or 1PM and now you expect that you can use it with a DHT? If so, we don’t support the DHT at the moment only the DS18B20. Where did you read that we support DHT, give me a link please. The second thing is this issue is about the [Shelly HT](https://www.shelly.cloud/en-de/products/product-overview/shelly-h-and-t-white) and not about the DHT sensor. Support for the DHT sensor is in progress #1110 and the thermostat support you ask for is in #895 requested.

**Comment by pfeifix** [comment]
@timoschilling: Thanks for the update! 
Indeed I meant the DS18B20 (not the DHT) which is what I have bought.
So you say the pure temperature sensor accessory is already built-in in the latest firmeware of the Shelly 1? That would be great.

I am looking forward to the release of the thermostat support as tracked by https://github.com/mongoose-os-apps/shelly-homekit/issues/895)](https://github.com/mongoose-os-apps/shelly-homekit/issues/895).

**Comment by vrpt2022** [comment]
Good evening!

Any update?

Thanks!
