### ISSUE TITLE
Garagedoor setup

### ISSUE THREAD

**Issue by tohmc** [mongoose-os-apps/shelly-homekit#189]
Hi,

Is it possible to add a mode that activates two outputs on Shelly 2.5?
One output to open the garage and one to close the Garage?
My garage have separate inputs to open and close.

Thanks
Tohmc

**Comment by rojer** [comment]
yes, it's possible.

**Comment by tohmc** [comment]
Can you explain how to do it please ?
👍

**Comment by rojer** [comment]
well, what i meant was - it's _feasible_. needs some code changes to make it _possible_. :)

**Comment by tohmc** [comment]
Do you think you can add this feature?
It would be very nice ;-)

**Comment by rojer** [comment]
please test this firmware: http://rojer.me/files/shelly/2.3.1-beta2/

set "output mode" to "dual", connect output 1 to close input of the controller, output 2 to open.
let me know if it works.

**Comment by tohmc** [comment]
Thanks!

Great work!
I will try on weekend!

**Comment by rojer** [comment]
btw, what type of a controller do you have?

**Comment by rojer** [comment]
released 2.3.1 with this change, let me know if it doesn't work.

**Comment by tohmc** [comment]
Sorry I had no time this weekend to Test.

Thanks for the great work.
If it doesn’t work I will inform you.

Regards

**Comment by tohmc** [comment]
I have an marantec Highline 15
It’s close to the comfort series
