### ISSUE TITLE
Shelly 1L support?

### ISSUE THREAD

**Issue by Tomer51m** [mongoose-os-apps/shelly-homekit#192]
Hi guys! 
I there a rough ETA for Shelly 1L support for HomeKit?
Thanks!

**Comment by Tomer51m** [comment]
Not yet. planning to buy a few next month. will let you know.
I have another question, but I will open a new issue so others can find it quickly.

**Comment by rojer** [comment]
so, it's not yet released, expected in mid November. i think it will be easy to add support, but i need one to test. feel like getting one for me to work with?

**Comment by andyblac** [comment]
what will people use them for ? as there only 5amp.

**Comment by rojer** [comment]
that's plenty for any light, pretty much. led lights use milliamps.

**Comment by Tomer51m** [comment]
> so, it's not yet released, expected in mid November. i think it will be easy to add support, but i need one to test. feel like getting one for me to work with?

Sure! I will get a few next month. I have my current order stuck in customs 🤦‍♂️. Once its released I will buy few L1’s to try.

**Comment by rojer** [comment]
ok, i'm sufficiently curious that i pre-ordered a couple for myself. will take a look when they arrive.

**Comment by andyblac** [comment]
> ok, i'm sufficiently curious that i pre-ordered a couple for myself. will take a look when they arrive.

last time i ordered "in stock" items direct from shelly they took over a month to arrive, that why i do not purchase from shelly.cloud.

**Comment by pivale** [comment]
for portugal, there are several electronic stores that have next day delivery. I either order from https://mauser.pt/ or https://www.castroelectronica.pt/ depending on stock availability.

**Comment by Pixel-Chris** [comment]
> what will people use them for ? as they're only 4amp. ok for single use devices like lights, tv, etc

You need no NEUTRAL wire! that‘s the benefit

**Comment by andyblac** [comment]
ye i know.

**Comment by andyblac** [comment]
rumours are Shelly are working on a 2L 😄

**Comment by rojer** [comment]
please help test 2.6.0-beta - https://github.com/mongoose-os-apps/shelly-homekit/issues/291
