### ISSUE TITLE
GarageDoor wiring

### ISSUE THREAD

**Issue by 49adrien** [mongoose-os-apps/shelly-homekit#195]
Hello,

On this picture, the wiring is not really clear, 12VDC is supported ? 110-230VAC ? 24-60VDC ?

![GarageDoor-Shelly1](https://user-images.githubusercontent.com/65712163/96042514-cdafb280-0e6d-11eb-94a5-26c759c5fd21.png)

Thanks

**Comment by Whiterabbit64** [comment]
You must use a low DC voltage power supply in this configuration. DON’T use AC.

**Comment by 49adrien** [comment]
Can you explain me why ?

**Comment by elgalera** [comment]
You can use 12Vdc or a voltage from 24Vdc to 60Vdc. Remember set the jumper according to input voltage.

The magnetic contact sensor only can operates with DC voltage. You can not use AC with this type of sensor.

You can find the correct configuration of SW in the following link:
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Garage-Door-Opener-Settings

**Comment by 49adrien** [comment]
This contact sensor support AC ?

[](https://www.aliexpress.com/item/4000890440801.html)

**Comment by Whiterabbit64** [comment]
It’s dangerous to power a such device with « high voltage ». If there’s an issue with it you could get hurt through the door which is probably metallic.

**Comment by 49adrien** [comment]
I have found this product :

[https://fr.aliexpress.com/item/32966599687.html](https://fr.aliexpress.com/item/32966599687.html)

**Comment by Whiterabbit64** [comment]
Do what you want, but I’ll never take a such risk. It’s better to work in low voltage and to add a small 24 DC power supply which costs few Euros.

**Comment by 49adrien** [comment]
Ok thanks.

**Comment by 49adrien** [comment]
Ok thanks.
