### ISSUE TITLE
Shelly & Hue

### ISSUE THREAD

**Issue by RaSoDo** [mongoose-os-apps/shelly-homekit#196]
Hi, 
I have a Problem and need Help:

Setup:
- Hue lamp on continuous current
- Shelly 1 as Dummy. Connected L, N, SW,
- Switch Connected L and SW to the Shelly

Situation:
Implementation in HomeKit working fine. SW ON & OFF working fine.

Problem:
Edge Setting not working because of not using the I,O.
When I switch on the lights by SW and let Siri do lights off command I have to press my switch 2 Times to turn on the light again.

Question:
Is there a way to create a stateless switch in HomeKit or solve this anyway?

Best regards 

Dominik

**Comment by andyblac** [comment]
put you shelly in "Detached" mode, this will create a stateless switch in HomeKit.

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Switch-Settings

**Comment by RaSoDo** [comment]
> put your shelly in "Detached" mode, this will create a stateless switch in HomeKit.
> 
> https://github.com/mongoose-os-apps/shelly-homekit/wiki/Switch-Settings

Thx for the reply. That is correct, but you can only associate One Action if you choose 
Toggle, on = off = single-> lights on / or off (The if is missing... if light off turn on.... if light on turn it off)
Or you have
Toggle, on = single, off = double -> Then you have Two actions. ON & OFF, it is a better implementation for hue lights, but dose not solve the Problem.

Did I miss something?

**Comment by rojer** [comment]
if you just want to turn the hue on and off, sounds like toggle with single and double should be the answer, no? associate hue on with single, hue off with double and it should act like a toggle switch for hue.

**Comment by andyblac** [comment]
it statelss, you do the IF within homekit. create a Shortcut automation for it, i do the same for my Shades. like below.

![IMG_0312](https://user-images.githubusercontent.com/77936/96116023-bc9f8980-0edf-11eb-8557-786e251cc621.jpeg)
![IMG_0313](https://user-images.githubusercontent.com/77936/96116572-929a9700-0ee0-11eb-8e19-8bf032409ec7.jpeg)
![IMG_0314](https://user-images.githubusercontent.com/77936/96116583-975f4b00-0ee0-11eb-8645-e7696636561a.jpeg)

**Comment by RaSoDo** [comment]
> it statelss, you do the IF within homekit. create a Shortcut automation for it, i do the same for my Shades. like below.
> 
> ![IMG_0312](https://user-images.githubusercontent.com/77936/96116023-bc9f8980-0edf-11eb-8557-786e251cc621.jpeg)
> ![IMG_0313](https://user-images.githubusercontent.com/77936/96116572-929a9700-0ee0-11eb-8e19-8bf032409ec7.jpeg)
> ![IMG_0314](https://user-images.githubusercontent.com/77936/96116583-975f4b00-0ee0-11eb-8645-e7696636561a.jpeg)

Thats it!!!!
Didn't scrolled down to shortcuts!

Thank you very much!!!!

**Comment by andyblac** [comment]
np, glad you got it sorted.

**Comment by rojer** [comment]
@andyblac very nice! consider adding it to the wiki for stateless switch, maybe

**Comment by andyblac** [comment]
yeah, I Plan on doing a "How Too" section within HomeKit.

**Comment by andyblac** [comment]
1st one added https://github.com/mongoose-os-apps/shelly-homekit/wiki/Stateless-Toggle-Switch
