### ISSUE TITLE
help flashing

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#2]
hi,

my Shelly 1 does not have original firmware on it, I purchase from Voltio.cz it has custom HomeKit firmware, I would like to test your firmware, could you help me flash via https://github.com/espressif/esptool ? or do know a better way to refresh your firmware on a Mac via FTDI (Serial header) ?

Thanks
Andy.

**Comment by kzyapkov** [comment]
You can flash the Shelly1 over a wired connection using mos. Download and install mos following these instructions: 

https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md

You can then use mos to flash the shelly-homekit-Shelly1.zip file. It may be a good idea to first dump your current flash contents, so you can go back to the Voltio.cz-provided firmware if needed.

**Comment by andyblac** [comment]
ok got it installed, just waiting for my FTDI tool to be delivered, could you explain how to dump firmware ?, I'm new to all this

**Comment by rojer** [comment]
once you've connected the serial port and put the device into boot-loader mode (by driving gpio0 low), to dump entire flash:

```
$ mos flash-read --platform esp8266 --esp-baud-rate 921600 flash.bin
```

this should produce a 2M flash.bin file.

to flash this (or any other Mongoose OS-based) firmware:

```
$ mos flash --esp-baud-rate 921600 shelly-homekit-Shelly1.zip
```

to later flash it back:

```
$ mos flash-write --platform esp8266 --esp-baud-rate 921600 0 flash.bin
```

mos will use the first available serial port, which is usually the correct one. but if you have multiple in your system, add `--port PORT` to each command, where PORT is the name of the serial port of the FTDI adapter - one of the COMx devices on Windows, /dev/ttyUSBx on Linux, etc.

**Comment by andyblac** [comment]
really appreciate all the help, when you say boot-loader mode (by driving gpio0 low), how do I do that ?

**Comment by rojer** [comment]
ok, i will write up detailed instructions with pictures tonight

**Comment by andyblac** [comment]
thanks a lot, you got a PayPal for donations?

**Comment by rojer** [comment]
i am not accepting donations at this time, but thanks for offering!

**Comment by rojer** [comment]
@andyblac see [here](https://github.com/mongoose-os-apps/shelly-homekit/blob/master/docs/flashing.md).

**Comment by andyblac** [comment]
Thanks

**Comment by bugfixer1992** [comment]
Hello,
I am experiencing a problem when trying to flash the shelly-homekit-Shelly1.zip
mos flash --esp-baud-rate 921600 shelly-homekit-Shelly1.zip
leads to an error message. "Image 0x1fc000 overlaps with system params area (16384 @ 0x1fc000)"
Does anyone have an idea how to fix this?
Thanks o lot in advance!

**Comment by timoschilling** [comment]
Maybe this wiki pages will help:
- https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development
- https://github.com/mongoose-os-apps/shelly-homekit/wiki/Serial-connection

**Comment by bugfixer1992** [comment]
Thank you for the fast answer, @timoschilling.
I followed the wiki and get the same mistake again.
"mos flash http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip"
leads to the error
"Image 0x1fc000 overlaps with system params area (16384 @ 0x1fc000)"
I attached a screenshot for further investigation.
![homekitError](https://user-images.githubusercontent.com/54179038/106778410-3d78c180-6646-11eb-8a94-b80cc0c0d2e9.PNG)
Do you have any further idea? 

Thanks :-)

**Comment by andyblac** [comment]
maybe @rojer can offer some assistance here ?

**Comment by rojer** [comment]
this looks like old mos utility version what does `mos --version` report?

**Comment by bugfixer1992** [comment]
Thanks a lot @rojer!!!!!
My version was
![mos version old exe](https://user-images.githubusercontent.com/54179038/106809506-0d441980-666c-11eb-93ec-aaebf70682ae.PNG)
when I downloaded the new mox.exe everything works like a charm. 
![mos version new exe](https://user-images.githubusercontent.com/54179038/106809563-1fbe5300-666c-11eb-9ba0-8fc46c4c6269.PNG)
Thank you sooooo much! You all made my day!

**Comment by rojer** [comment]
any time :)

**Comment by Bodie2005** [comment]
> really appreciate all the help, when you say boot-loader mode (by driving gpio0 low), how do I do that ?

You were successful to change voltio.cz firmware? I can't start my Shelly1 with voltio.cz to boot-loader mode.

**Comment by andyblac** [comment]
> > really appreciate all the help, when you say boot-loader mode (by driving gpio0 low), how do I do that ?
> 
> You were successful to change voltio.cz firmware? I can't start my Shelly1 with voltio.cz to boot-loader mode.

i have reflashed a few voltio.cz devices to this firmware via serial with no issues.

**Comment by Bodie2005** [comment]
I have changed USB / serial from CH340 chipset to FDTI FT232 and I can start in boot-loader mode now. But unfortunately if I try dump flash I have error: 

$ mos flash-read --platform esp8266 --esp-baud-rate 921600 flash.bin
Using port /dev/cu.usbserial-A50285BI
Opening /dev/cu.usbserial-A50285BI @ 115200...
Connecting to ESP8266 ROM, attempt 1 of 10...
  Connected, chip: ESP8266EX
Running flasher @ 921600...
  Flasher is running
Reading 2097152 @ 0x0...
Error: /private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/common/slip.go:54: invalid SLIP starting byte: 0xff
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/flasher_client.go:400: flash read failed @ 0xd00
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/read_flash.go:52: failed to read 2097152 @ 0x0
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash_read.go:97: 
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/main.go:198: flash-read failed
exit status 1
Command completed.

Could anybody help me? I am using Mac.

**Comment by andyblac** [comment]
what version of mos ?

**Comment by rojer** [comment]
this looks like baud rate is too high. try removing `--esp-baud-rate 921600` or setting `--esp-baud-rate 0`

**Comment by Bodie2005** [comment]
> what version of mos ?

Serial console
2.19.1~brew

**Comment by Bodie2005** [comment]
> this looks like baud rate is too high. try removing `--esp-baud-rate 921600` or setting `--esp-baud-rate 0`

Hello rojer, unfortunately the same issue:

mos flash-read --platform esp8266 --esp-baud-rate 0 flash.bin
Using port /dev/cu.usbserial-A50285BI
Opening /dev/cu.usbserial-A50285BI @ 115200...
Connecting to ESP8266 ROM, attempt 1 of 10...
  Connected, chip: ESP8266EX
Running flasher @ 0...
  Flasher is running
Reading 2097152 @ 0x0...
Error: /private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/common/slip.go:54: invalid SLIP starting byte: 0x30
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/flasher_client.go:400: flash read failed @ 0x800
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/read_flash.go:52: failed to read 2097152 @ 0x0
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash_read.go:97: 
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/main.go:198: flash-read failed
exit status 1
Command completed.

--------------

$ mos flash-read --platform esp8266 flash.bin
Using port /dev/cu.usbserial-A50285BI
Opening /dev/cu.usbserial-A50285BI @ 115200...
Connecting to ESP8266 ROM, attempt 1 of 10...
  Connected, chip: ESP8266EX
Running flasher @ 921600...
  Flasher is running
Reading 2097152 @ 0x0...
Error: /private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/common/slip.go:54: invalid SLIP starting byte: 0x00
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/flasher_client.go:400: flash read failed @ 0x200
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/read_flash.go:52: failed to read 2097152 @ 0x0
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash_read.go:97: 
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/main.go:198: flash-read failed
exit status 1
Command completed.

**Comment by Bodie2005** [comment]
> this looks like baud rate is too high. try removing `--esp-baud-rate 921600` or setting `--esp-baud-rate 0`

Hello rojer, unfortunately the same issue:

mos flash-read --platform esp8266 --esp-baud-rate 0 flash.bin
Using port /dev/cu.usbserial-A50285BI
Opening /dev/cu.usbserial-A50285BI @ 115200...
Connecting to ESP8266 ROM, attempt 1 of 10...
  Connected, chip: ESP8266EX
Running flasher @ 0...
  Flasher is running
Reading 2097152 @ 0x0...
Error: /private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/common/slip.go:54: invalid SLIP starting byte: 0x30
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/flasher_client.go:400: flash read failed @ 0x800
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash/esp/flasher/read_flash.go:52: failed to read 2097152 @ 0x0
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/flash_read.go:97: 
/private/tmp/mos-20210208-36530-1bwv7ue/mos-9bf406d90c65fca0b377220940735015dcfbb76c/cli/main.go:198: flash-read failed
exit status 1
Command completed.

--------------

**Comment by Bodie2005** [comment]
> this looks like baud rate is too high. try removing `--esp-baud-rate 921600` or setting `--esp-baud-rate 0`

Hi rojer. It looks, that problem was with USB-C (I am using original Apple USB C to USB A), it doesn't work. At the end I have tried my old Air with native USB A 
![IMG_2797](https://user-images.githubusercontent.com/75204188/108810038-815a4900-75aa-11eb-9cf5-5f6c9a23b0bb.jpeg)
and I can dump original firmware + add new. 
![IMG_2796](https://user-images.githubusercontent.com/75204188/108810076-9636dc80-75aa-11eb-8498-e6e27163e14c.jpeg)

Thank you for you patience and help.

**Comment by Bodie2005** [comment]
> what version of mos ?

Thank you andyblac for you patience and help. It is working now.

**Comment by simonfield76** [comment]
With my interface I need to disconnect and reconnect usb after any command.

Read fw disconnect and reconnect usb
Erase disconnect and reconnect usb
Flash like above

I’ve seen many people using this trick and it always went through.



Inviato da iPhone

Il giorno 23 feb 2021, alle ore 07:43, Bodie2005 <notifications@github.com> ha scritto:

﻿

what version of mos ?

Thank you andyblac for you patience and help. It is working now.

**Comment by simonfield76** [comment]
Ah sorry I didn’t see that you were using a Mac this hint was for windows users

Inviato da iPhone

Il giorno 23 feb 2021, alle ore 09:37, simone campo <concierge-bentley@hotmail.it> ha scritto:

﻿ With my interface I need to disconnect and reconnect usb after any command.

Read fw disconnect and reconnect usb
Erase disconnect and reconnect usb
Flash like above

I’ve seen many people using this trick and it always went through.



Inviato da iPhone

Il giorno 23 feb 2021, alle ore 07:43, Bodie2005 <notifications@github.com> ha scritto:

﻿

what version of mos ?

Thank you andyblac for you patience and help. It is working now.
