### ISSUE TITLE
Flash script does not work

### ISSUE THREAD

**Issue by Drugantix** [mongoose-os-apps/shelly-homekit#210]
i get this when i run the script :

alessio@MBP-di-Alessio tools % ./flash_shelly.py -a        
Failed to lookup version information
alessio@MBP-di-Alessio tools % ./flash_shelly.py -la
Failed to lookup version information
alessio@MBP-di-Alessio tools %

**Comment by andyblac** [comment]
same issue reported here https://github.com/mongoose-os-apps/shelly-homekit/issues/149#issuecomment-709910514 please try this command.

**Comment by andyblac** [comment]
i'll add script to wiki and write it up thx, please report if it does indeed fix your issue.

**Comment by Drugantix** [comment]
I solved it in the way you suggested but I used Install Certificates.command present in the installation package of python3. Thank you.
