### ISSUE TITLE
Shelly 1 Garage Door status blocked 

### ISSUE THREAD

**Issue by Draf76** [mongoose-os-apps/shelly-homekit#218]
Hi, I have a quick question. When I setup a Shelly 1 as garage door opener, the status is after closing always showing up as “stopped” on the website and in HomeKit with exclamation mark instead of closed. There is nothing attached to the Shelly by now. What am I doing wrong?

![CCFA546B-6CC9-4281-8A6A-0DEE5BC40F33](https://user-images.githubusercontent.com/73346506/97010294-7c768180-1545-11eb-9fef-b94a538407b0.jpeg)
![6262E424-3860-4469-B50C-57D9C8936B9B](https://user-images.githubusercontent.com/73346506/97010306-813b3580-1545-11eb-9095-8dfd462b0012.jpeg)

**Comment by rojer** [comment]
this is "obstruction detected" condition.
garage door opener requires a "fully closed" contact sensor. because nothing is attached to your shelly yet, we don't get the fully closed confirmation after 15 seconds (movement time) and assume that door could not be fully closed.

**Comment by Draf76** [comment]
What sensor would you recommend for this? Would it have to be connected to the Shelly then?

**Comment by rojer** [comment]
See wiring diagram here - https://github.com/mongoose-os-apps/shelly-homekit/wiki/Garage-Door-Opener-Settings

Anything that activates when the door is closed will do. "Activates" could be open or close the circuit, both are supported and can be selected with "close sensor type" option.

note that i do not own a garage door opener myself, but others have posted suggestions on https://github.com/mongoose-os-apps/shelly-homekit/issues/142.
