### ISSUE TITLE
Request: Inverted (Reversed) SW input

### ISSUE THREAD

**Issue by jsiegenthaler** [mongoose-os-apps/shelly-homekit#220]
The Shelly1 has the ability to set the SW input type to **Reverse inputs** (which is simply inverted input state)

The Shelly1 with mongoose has only Input Mode = Momentary, Toggle, Edge and Detached.
It does not have Reverse (Inverted)

I have a situation where one bathroom has induced voltage on the wiring due to a switchboard right behind the wiring.
I managed to reduce the induced voltage, but it resulted in the input being inverted (reversed).

Not a problem on a Shelly1 with normal Shelly firmware, but it is a problem for the Mongoose OS.

Any chance of adding a Reversed Input Mode (you could also call it Inverted)?
Logically, it would be very simple to implement...

**Comment by rojer** [comment]
sounds reasonable. to make sure i understand correctly: your input is normally conductive and interrupts teh circuit when activated (button pressed)?

**Comment by jsiegenthaler** [comment]
Hi @rojer 
I mean this:
Normal mode:   SW ON = Relay ON, SW OFF = Relay OFF
Reversed mode:   SW OFF = Relay ON, SW ON = Relay OFF

**Comment by rojer** [comment]
yeah, ok. it's definitely doable.

**Comment by lucaspinelli85** [comment]
I need this inverted function too!

**Comment by lucaspinelli85** [comment]
> Hi @rojer
> I mean this:
> Normal mode: SW ON = Relay ON, SW OFF = Relay OFF
> Reversed mode: SW OFF = Relay ON, SW ON = Relay OFF

Can it be add? Thanks

**Comment by lucaspinelli85** [comment]
Solution?
If you want a reverse mode you have to choose if you want swipe input or output or both (like shelly 2.5!)
Could you add this shelly 2.5 feature in shelly 1/1PM?
![image](https://user-images.githubusercontent.com/74553551/99394809-c6058280-28df-11eb-8f1d-7fd45ca94080.png)

**Comment by lucaspinelli85** [comment]
The result is this, i take like exemple a sensor nc but could be everything....
![image](https://user-images.githubusercontent.com/74553551/99394956-0ebd3b80-28e0-11eb-9952-c5e5b8395041.png)

**Comment by lucaspinelli85** [comment]
what do you say @rojer ? This needs for normally closed input working reverse like a sensor alarm and normally closed output working reverse like my irrication central that swithed off at close circuit and switched on at open circuit!

> The result is this, i take like exemple a sensor nc but could be everything....
> ![image](https://user-images.githubusercontent.com/74553551/99394956-0ebd3b80-28e0-11eb-9952-c5e5b8395041.png)

**Comment by rojer** [comment]
yes, it makes sense, we should do it.

**Comment by rojer** [comment]
@lucaspinelli85 ok, so actually what you are asking is different, you are asking for a feature to report switch as off when it's actually on (relay is on), as well as to have ability to invert the input (normally open / normally close).
this also has nothing to do with what "swap inputs" and "swap outputs" does on shelly 2 and 2.5: in that case, swapping inputs means use SW1 pin to control (logical) switch 2 and vice versa, and swapping outputs means logical switch 1 will control O2 instead of O1 and vice versa.
so, i am going to implement the inverting input part, for inverting output state reported to homekit please file a separate issue.

**Comment by rojer** [comment]
please help test 2.6.0-beta - https://github.com/mongoose-os-apps/shelly-homekit/issues/291
