### ISSUE TITLE
Small Typos in Wiki: I can fix them if you're OK with that

### ISSUE THREAD

**Issue by jsiegenthaler** [mongoose-os-apps/shelly-homekit#223]
Hello Great Mongoose Shelly-HomeKit Team

This is a fantastic project and I'd like to help in any small way I can.

I have started doing so by correcting very small English typos in the Wiki, hope you don't mind.
I am an electronics engineer with many decades of programming experience and now working as a database admin.
I have a brain that sees each and every error very quickly, and a desire to have everything correct. Some people call me a pedantic b*§tard.
But I'm really good at testing.

I already identified and fixed a couple of small Wiki Typos just now, hope I'm not stepping on your toes.
https://github.com/mongoose-os-apps/shelly-homekit/wiki
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Setup
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery

**Comment by andyblac** [comment]
sure, more help the better 😄

**Comment by andyblac** [comment]
close the tickets, when your done.

**Comment by rojer** [comment]
yes, we'll take all the help we can get.
welcome!

**Comment by jsiegenthaler** [comment]
Done, fixed a whole heap of typos
