### ISSUE TITLE
Question: Must every device have a unique pairing code?

### ISSUE THREAD

**Issue by jsiegenthaler** [mongoose-os-apps/shelly-homekit#225]
Trying to add a 2nd Shelly1 device to my network

Gave it the same pairing code as the first device.

HomeKit cannot find it.... must every pairing code be unique?

If so, how will I know what pairing codes have already used in my network? 
Must I keep a written log somewhere?

**Comment by andyblac** [comment]
no, it is not nessersary.

**Comment by jsiegenthaler** [comment]
Thanks. Got it paired.
