### ISSUE TITLE
Shelly 2.5 both relay states in one tile

### ISSUE THREAD

**Issue by andlem74** [mongoose-os-apps/shelly-homekit#227]
IIRC in an earlier release of July, both relay states of my Shelly 2.5 could be controlled by one single tile showing two switches. This seems to be no longer possible with the current release 2.3.1. I can group the two relays and have only one switch that presumably acts on both relays or not group them and have individual tiles. Is this intended or am I missing something?

**Comment by rojer** [comment]
same as #226, files 8 minutes earlier.
short answer: no, you are not missing something, it was a deliberate change but yes, we can make previous organization an option.
