### ISSUE TITLE
Garage door function not mentioned on the start page

### ISSUE THREAD

**Issue by Pixel-Chris** [mongoose-os-apps/shelly-homekit#229]
On the start page (https://github.com/mongoose-os-apps/shelly-homekit) the garage door functionality is not mentioned.

**Comment by jsiegenthaler** [comment]
Thanks

Added to https://github.com/mongoose-os-apps/shelly-homekit/wiki
README.md needs updating, shall I?

**Comment by rojer** [comment]
@jsiegenthaler ues, please send a PR

**Comment by jsiegenthaler** [comment]
@rojer. Done

**Comment by rojer** [comment]
merged, thank you!
