### ISSUE TITLE
Lost Connection to Cloud / Amazon

### ISSUE THREAD

**Issue by nightout80** [mongoose-os-apps/shelly-homekit#23]
Hi There,

thanks for providing the Home Kit Version. After updating my Shelly-1, I lost connection to the Shelly Cloud as well as to Amazon Alexa. Also via iOBroker the connection isn't possible any more. Is it a part of the home kit compatibility that any other services are offline?

Thanks,
Bastian

**Comment by andyblac** [comment]
no, it home kit only. more secure this way.

**Comment by rojer** [comment]
cloud connections are not supported in this firmware.
i wouldn't necessarily rule out adding support, but it's not there at the moment.

**Comment by rojer** [comment]
i'm going to close the issue, if you'd like to see specific feature please file another request.
