### ISSUE TITLE
Shelly 1 and 2.5 as light mode

### ISSUE THREAD

**Issue by BlancoDeMallloca** [mongoose-os-apps/shelly-homekit#230]
Thanks for the great work with this firmware. 

Could you please enable the light mode for Shelly 1 and 2.5? This would change the icon in HomeKit. Settings are the same as in Switch Mode.

**Comment by andyblac** [comment]
You can you do this in HomeKit it self

**Comment by rojer** [comment]
yeah, device has not control over that.

**Comment by BlancoDeMallloca** [comment]
Oh cool. Did not know that. Thanks for the fast response and once again great work!
