### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nk-gx** [mongoose-os-apps/shelly-homekit#232]
Hi,
At the first page: Firmware is compatible with stock and can be uploaded via OTA (Watch a 2 minute video), for more info take a look at the flashing wiki **here**.
"**here**" points to a broken link. 

Also: Reverting to stock firmware is also supported see **here**.

**Comment by andyblac** [comment]
thanks PR submitted https://github.com/mongoose-os-apps/shelly-homekit/pull/233
