### ISSUE TITLE
Temperature in °F not in °C

### ISSUE THREAD

**Issue by BlancoDeMallloca** [mongoose-os-apps/shelly-homekit#234]
Thanks for the update. 

The displayed temperature is °F and not as displayed °C. 

For example one of my Shelly 2.5 displays 71°C but it is approx 22°C or 71°C when using an old fashion thermometer. 

For international use it would be great to choose between °F and °C

**Comment by rojer** [comment]
no-no,  this is system temperature, not ambient. it really is 71 degrees inside the package.

**Comment by andyblac** [comment]
beat me to it, i was just aboutto say no way the devcie can be 22c 😄

**Comment by andyblac** [comment]
updated system setting wiki to mention this fact.
