### ISSUE TITLE
Enhancements in logging

### ISSUE THREAD

**Issue by pivale** [mongoose-os-apps/shelly-homekit#236]
Hey,

I have several issues that are occurring but I would like to be able to find them first in the logs and submit them properly.
The problem is, with two kids around the house, it's hard to run to the logs and find the situation once it occurs.

If we could improve the logging, I think it would make it easier on everyone to identify and report problems.

My suggestion for that would be:
- Change the log timestamp to something human readable, or clarify how to read it
- Allow to configure a local address where all accessories could dump their own log in a continuous away (without rotation).

Is this something we could implement?

**Comment by marcus-aa** [comment]
Syslog would be nice....

**Comment by timoschilling** [comment]
The timestamps are msec since boot, a remote logging can already be configured: https://mongoose-os.com/docs/mongoose-os/userguide/debug.md#debug-configuration-settings-quick-reference
