### ISSUE TITLE
Missing "Input Mode" in Shelly Plug

### ISSUE THREAD

**Issue by Leo-W536** [mongoose-os-apps/shelly-homekit#238]
Hello, 
a big Thanks for the great job integrating shellys in homekit. 

In ShellyPlug I am missing the option to choose Input Mode like shown in wiki:
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Switch-Settings

Thank you for fixing!
![shelly_plug](https://user-images.githubusercontent.com/73061724/97414323-1fdbe380-1904-11eb-99f0-bb0c4f39cfd3.JPG)

**Comment by andyblac** [comment]
there is no input mode for devices like plugs that have no external inputs

**Comment by andyblac** [comment]
I have updated the wiki, to reflect this.

**Comment by Leo-W536** [comment]
But the Shelly Plug has an InputButton!

**Comment by andyblac** [comment]
ok, then this one is for @rojer, i was going off git comits https://github.com/mongoose-os-apps/shelly-homekit/commit/4bdf776d1667662cbfeb44c19d53924267ad3e54

**Comment by andyblac** [comment]
> But the Shelly Plug has an InputButton!

is it not just always the same type though? ie push button ?

**Comment by rojer** [comment]
it has a button, but that's not the input the "input mode" section is about.
making the button control the plug is a good idea though.

**Comment by rojer** [comment]
yes, it's a push button. single press of external button should toggle output.

**Comment by andyblac** [comment]
> it has a button, but that's not the input the "input mode" section is about.
> making the button control the plug is a good idea though.

ye, maybe just force to Momentary ?

**Comment by rojer** [comment]
fixed. short press of the physical button on shellies will now toggle the switch state.
on devices with more than one switch configure, it will cycle them through all possible combinations.

**Comment by Leo-W536** [comment]
Thank you for fixing! Works perfect for Shelly Plug. 

For Shelly Plug S it must be the same. I tried with FW 2.5.0 but it's not working yet. 

Please fix it for Plug S too! 
Thank you...

**Comment by rojer** [comment]
@Leo-W536 done, will be in the next release
