### ISSUE TITLE
automata kikapcsolás Shelly1

### ISSUE THREAD

**Issue by cskallo** [mongoose-os-apps/shelly-homekit#242]
Már egy ideje követem a Shelly HomeKit garcía t.
Nem vagyok programozo s nem igazán értem az automata kikapcsolás  idö beállitását
ha 10másodpercet szeretnék azt miép lehet?.

**Comment by Marcusyo** [comment]
If google translater worked right you want to know how to set the auto off delay to 10 seconds.
I attached a file where i made the settings for that. you can copy that for yourself

the format for the time is **D:HH:MM:SS.sss**
Day Hour Hour Minute Minute Second Secons millisecond millisecond millisecond

![10 seconds delay auto off](https://user-images.githubusercontent.com/73487066/97558613-a237d680-19dc-11eb-9b54-d1354e8f62c5.JPG)

**Comment by rojer** [comment]
@cskallo  we are all from different countries here and official language of the communication is english.
please be respectful of other members and do your part and take the time to express your issue so others can understand.
