### ISSUE TITLE
Shelly Plug S Timer function

### ISSUE THREAD

**Issue by Marcusyo** [mongoose-os-apps/shelly-homekit#243]
Is there a way to implement a timer function for the Shelly Plug S based on the timezone where the plug is used?
At the moment I dont have a Homepod, apple TV or Ipad to controll my homekit devices from outside or use some automatic stuff.
I want to buy the homepod mini as soon its available to do more stuff in homekit.

**Comment by rojer** [comment]
complex automations are out of scope for this project precisely because in homekit they are supposed to be handled by controllers,  so you'll need to get yourself an ipad, a homepod or a tv.
