### ISSUE TITLE
Blinds/Shutter roller "stop" mode

### ISSUE THREAD

**Issue by juansf99** [mongoose-os-apps/shelly-homekit#249]
Hi,
The latest updates to **Shelly 2.5** for roller Shutter mode have been working very good. (Actually I have v2.4.0)
When try to crate an Scene in the EVE app, an option appears called: "hold position".
I have tried to create an Scene called "stop", with the intention of stopping the movement of the blinds, but I only get them to stop for 1 second or less, then continue with the movement they were making, up or down.
Would it be possible to stop the blind in some way while moving by Siri voice command?

Anyway, Great Job!
JASF

**Comment by andyblac** [comment]
can this be closed ?

**Comment by juansf99** [comment]
No solution? close...
