### ISSUE TITLE
Shelly 2 stock firmware. 

### ISSUE THREAD

**Issue by laurynas-V** [mongoose-os-apps/shelly-homekit#25]
Please provide shelly 2 stock firmware for Reverting to stock.

**Comment by kzyapkov** [comment]
This project is not affiliated with Allterco -- you should direct your question to Shelly support (forum, facebook, email, etc.)

Latest Shelly2 firmware can be downloaded from http://api.shelly.cloud/firmware/SHSW-21_build.zip
