### ISSUE TITLE
WebUI „Log“ Text-Link not usable

### ISSUE THREAD

**Issue by Pixel-Chris** [mongoose-os-apps/shelly-homekit#250]
Hi,
There is an overlay from the „Debug Log“ Button on the „Log“ text-link.

So when I want to open the Log the Debug Log is switched off.

Shelly 2.5 and Shelly 1

Browser: Safari (iPhone IOS 14)

**Comment by pivale** [comment]
This also happens to me on Firefox for Mac (78.4.0esr (64-bit))

**Comment by rojer** [comment]
fixed, will be in the next release
