### ISSUE TITLE
New Feature: Write Power Consumption to local storage

### ISSUE THREAD

**Issue by pivale** [mongoose-os-apps/shelly-homekit#253]
Hey there,

One cool new feature would be to write the Power Consumption statistics from the supported shellys to a local (or remote) storage.
We could have a text field in the web ui to configure it.

This would be really net to track consumptions and even start building alerts on it to find appliances that have problems.

Let me know if I can help/clarify.

**Comment by rojer** [comment]
we can start by persisting them across reboots.

**Comment by timoschilling** [comment]
Closed in favour of #362 which describes the HomeKit part too.
