### ISSUE TITLE
Shelly 1 not connect to HomeKit

### ISSUE THREAD

**Issue by javi-w** [mongoose-os-apps/shelly-homekit#258]
Hi guys,

I follow the normal process (I already did in other Shelly devices) but, after update the firmware, when I have to add the Shelly 1 to HomeKit, take a lot of time "Connecting the Accessory" and finally appear the message "Unable to Add Accessory""Accessory is not reachable".

Would you know how can I solve this issue?

Thanks in advance.

**Comment by andyblac** [comment]
start here, read the linked ticket, it sounds like network issues.

**Comment by andyblac** [comment]
are you still having issues ??

**Comment by andyblac** [comment]
as i have no reply I'll close this ticket, @javi-w please reopen if you still need help.
