### ISSUE TITLE
Make SNTP Server changeable 

### ISSUE THREAD

**Issue by Pixel-Chris** [mongoose-os-apps/shelly-homekit#259]
Hello, I would like to have an option, where I can change the SNTP server to my local one (router).
Is that possible?

Best regards PixelChris

**Comment by andyblac** [comment]
ye, this would be nice, don't really like using `time.google.com`

**Comment by buckmelanoma** [comment]
Agreed.  As a workaround I have time.google.com set to a local NTP server on my local DNS server.

**Comment by rojer** [comment]
the change should made upstream, mongoose os should be getting SNTP server form DHCP lease, if present

**Comment by buckmelanoma** [comment]
Thanks!  I added my local server as a DHCP option and can confirm it gets picked up and used (chronyc clients).

**Comment by Pixel-Chris** [comment]
Not all routers support to set an additional dhcp option... you can only enable a time server but you need to configure the clients to use this.

**Comment by rojer** [comment]
this is now done upstream, will be in the next release.
upstream changes:

https://github.com/mongoose-os/esp-idf/commit/b708237311b8be74ca1b34bfd1e5915e1192a64f
https://github.com/cesanta/mongoose-os/commit/815aaffe2b19a4e5db9147f20b90dabb6b25b4df
https://github.com/mongoose-os-libs/sntp/commit/77765613c8720d5a22be23bd410d1465c4606581
https://github.com/mongoose-os-libs/lwip/commit/2cff4ac32b5c9c4d4481123d99b29c59a84afc6c
