### ISSUE TITLE
Shelly Powermeter consumption reading.

### ISSUE THREAD

**Issue by Domo-Dana** [mongoose-os-apps/shelly-homekit#26]
Hello, is a development planned to have the consumption data read by the Plug-S as on the Shelly Cloud app?

Thank you.

**Comment by rojer** [comment]
the question is how to expose this info in the Home app?

**Comment by Domo-Dana** [comment]
> the question is how to expose this info in the Home app?

Exactly, I hadn't thought of this point. :-/

**Comment by Domo-Dana** [comment]
The Shelly Plug S socket is well recognized and controllable with Homekit, however the automation mode does not seem to act on it. Did you have the same problem ?

**Comment by andyblac** [comment]
only 3rd party apps like EVE can show this data.

**Comment by cschildhorn** [comment]
Perhaps this helps. 

https://gist.github.com/gomfunkel/b1a046d729757120907c

**Comment by Rappelsack** [comment]
I wrote this feature request: https://github.com/mongoose-os-apps/shelly-homekit/issues/452

I do not understand why this should be placed in this post, but again:
This feature would be great.

**Comment by andyblac** [comment]
> I wrote this feature request: #452
> 
> I do not understand why this should be placed in this post, but again:
> This feature would be great.

it about getting power consumtion data in to HomeKit, so you can create an automation to do what you describe.

**Comment by Rappelsack** [comment]
No. I do not request power consumption in homekit.

Just a setting simmilar to the: switch off after xx minutes:
![64DC4EF3-70CE-462D-8680-70EEC9DDB4A0](https://user-images.githubusercontent.com/67721205/106355418-029a2500-62f8-11eb-98aa-f36a7663ac4c.jpeg)

Like this.

**Comment by andyblac** [comment]
I'll reopen, post this info in the issue, i'll let rojer decide if it something he wants to code.

**Comment by timoschilling** [comment]
That is only supported as a characteristic of a valve. I will work on that after #433 is merged.

**Comment by Fireball-AT** [comment]
My use case would be to trigger an action if e.g. the washing machine is finished. I would refer to the power consumption in stand-by over a certain timeframe.

**Comment by Rappelsack** [comment]
Why this is closed? :-(

Still waiting for this to use the shelly plug s to reduce the standby consumption of my TVs, etc.

**Comment by andyblac** [comment]
> Why this is closed? :-(
> 
> Still waiting for this to use the shelly plug s to reduce the standby consumption of my TVs, etc.

will be in next build via https://github.com/mongoose-os-apps/shelly-homekit/pull/690
