### ISSUE TITLE
Automations are not triggered

### ISSUE THREAD

**Issue by jobl1978** [mongoose-os-apps/shelly-homekit#260]
I bought two Shelly1 and flashed them to 2.4.0. One in edged mode (light) and one in momentary mode (light). Everything is working fine. I can switch on and off my lights from Home App and with physical switches. In my last test I created a automation where light two should be turned on automatically if light one is turned on. I turned light one on but light two doesn’t turn on. It looks that light two doesn’t receive an event from HomeKit. I tried another automation (turn light on at 5pm) and it also did not recognize to turn on the light. With latest firmware 2.5.0-beta2 same behavior. If I program this scenarios only with philips hue lights it works fine. I use the latest update 14.2 on all of my Apple devices.

**Comment by andyblac** [comment]
no issues here with shelly homekit and automations. what are you using as a hub?, homepod or appletv ?, i had nothing but issue when using AppleTV's as Hubs.

anyway, it sounds like HomeKit issue not firmware.

**Comment by jobl1978** [comment]
> no issues here with shelly homekit and automations. what are you using as a hub?, homepod or appletv ?, i had nothing but issue when using AppleTV's as Hubs.
> 
> anyway, it sounds like HomeKit issue not firmware.

I use an Apple TV HD as hub

**Comment by andyblac** [comment]
> > no issues here with shelly homekit and automations. what are you using as a hub?, homepod or appletv ?, i had nothing but issue when using AppleTV's as Hubs.
> > anyway, it sounds like HomeKit issue not firmware.
> 
> I use an Apple TV HD as hub

try rebooting it, but i would say thats your issue. they are notorious for being bad hubs. do yourself a favour, try a homepod mini.

**Comment by jobl1978** [comment]
> > > no issues here with shelly homekit and automations. what are you using as a hub?, homepod or appletv ?, i had nothing but issue when using AppleTV's as Hubs.
> > > anyway, it sounds like HomeKit issue not firmware.
> > 
> > 
> > I use an Apple TV HD as hub
> 
> try rebooting it, but i would say thats your issue. they are notorious for being bad hubs. do yourself a favour, try a homepod mini.

I already rebooted it. Didn’t solve my problem. It’s my plan to buy a HomePod mini when they will be available here starting 16th of November. Hopefully this will solve my issue.

**Comment by andyblac** [comment]
pre-orders are open, got 2 on order, but del time has slipped to 1st dec.

**Comment by jobl1978** [comment]
I can’t preorder it, because HomePods are not sold in Austria from Apple. I have to buy one in Germany (Munic). But anyway, I’ve tried it now with an iPad as hub and I can’t believe it, but it works now perfectly!!! Thanks for your input!!!

**Comment by rojer** [comment]
thank Andy! i'm only curious what's the difference with Hue, what is it about it that makes ot work fine with tv while shelly doesn't? @jobl1978 can you double-check again? i'll report this to ADK developers if this is the case.

**Comment by andyblac** [comment]
> thank Andy! i'm only curious what's the difference with Hue, what is it about it that makes ot work fine with tv while shelly doesn't? @jobl1978 can you double-check again? i'll report this to ADK developers if this is the case.

IMO prob due the fact that Hue has a hardwired bridge that has been setup for some time, and the AppleTV has had time register it, AppleTV's are well known to be flakey to act as Hubs, they need time to settle down, after registering new devcies , scenes, automations, if he left it for a day or two, it would probably have start working.

**Comment by jobl1978** [comment]
Im not sure if it was the iPad that solves this issue. I wasn‘t able to remove the Apple TV as an Hub. Apple TV as Hub was deactivated but in Home App is was always shown as connected and the iPad shown in Standby. The only way was to delete my Home and create a new Home and reconnect the two shellys to it. I will now try to delete my Home again, activate the Apple TV and reconnect my shellys.

**Comment by andyblac** [comment]
> Im not sure if it was the iPad that solves this issue. I wasn‘t able to remove the Apple TV as an Hub. Apple TV as Hub was deactivated but in Home App is was always shown as connected and the iPad shown in Standby. The only way was to delete my Home and create a new Home and reconnect the two shellys to it. I will now try to delete my Home again, activate the Apple TV and reconnect my shellys.

i have 3 AppleTV's, i have homekit disabled on all of them, as if i enable it, it screws up my automations. I have 2 HomePod's as Hub, with 2 HomePod mini's on order. HomeKit also needs a minimum of 5 minuets to detect Hub changes, ie if you power one off it needs 5 mins at minimum to detect it is off, and switch to Standby. Just keep that in mind.

**Comment by andyblac** [comment]
@rojer i have added a few tips to the WiKi https://github.com/mongoose-os-apps/shelly-homekit/wiki/Trouble-Shooting#issues-with-automations

**Comment by pivale** [comment]
I'm using an Apple TV as a hub and it seems to be working fine except for presence automations (when someone enters or leaves home...)

**Comment by andyblac** [comment]
@jobl1978 did you sort your issue ? still require help, or i close this ticket ?

**Comment by jobl1978** [comment]
> @jobl1978 did you sort your issue ? still require help, or i close this ticket ?

Everything is working fine now. You can close the issue.
