### ISSUE TITLE
A big PROBLEM!!!

### ISSUE THREAD

**Issue by Nikola1236** [mongoose-os-apps/shelly-homekit#261]
Good morning I am writing to you from Europe and I had some problems with the program that you created all 7 as a team. 
First of all as soon as I configured my shelly 2.5 with Apple HomeKit the same devices that I had in the app on purpose shelly said offline device BUT on the HomeKit app were working and now we would like to go back as before only with the app Shelly because we noticed that we are not comfortable with Apple HomeKit so here is the question
How can I go back to the beginning without Apple HomeKit but only with Shelly?
I look forward to an answer from you with affection _Nikola1236_

**Comment by andyblac** [comment]
open the device in a web browser, scroll to the bottom of the page, click on 'Revert' button.

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Device-webUI
https://github.com/mongoose-os-apps/shelly-homekit/wiki/System-Settings

**Comment by Nikola1236** [comment]
it's okay?

it's okay?

**Comment by Nikola1236** [comment]
http://www.mediafire.com/file/59zl1vbcckvvwya/2020-11-08_20-57-48.mkv/file
In this way?

**Comment by Nikola1236** [comment]
> open the device IP in a web browser, scroll to the bottom of the page, click on 'Revert' button.
> 
> https://github.com/mongoose-os-apps/shelly-homekit/wiki/Device-webUI
> https://github.com/mongoose-os-apps/shelly-homekit/wiki/System-Settings

http://www.mediafire.com/file/59zl1vbcckvvwya/2020-11-08_20-57-48.mkv/file
In this way?
andyblac

**Comment by andyblac** [comment]
yes, now just refresh page. it should be back on stock firmware.

**Comment by Nikola1236** [comment]
> yes, now just refresh page. it should be back on stock firmware.

Not working _SAD_

**Comment by andyblac** [comment]
what you mean not working ?

**Comment by Nikola1236** [comment]
> what you mean not working ?

the revert button doesn't work and I can't see anything on shelly

**Comment by andyblac** [comment]
so when you reload the webpage it is still on homekit firmware ?

**Comment by Nikola1236** [comment]
> so when you reload the webpage it is still on homekit firmware ?

exact and now the only way I have is to change all shelly 2.5 / 1

**Comment by andyblac** [comment]
are you Mac OS or windows ?

**Comment by andyblac** [comment]
does the device have internet access ?

**Comment by Nikola1236** [comment]
> are you Mac OS or windows ?

Windows

**Comment by Nikola1236** [comment]
> does the device have internet access ?

Yes have internet access

**Comment by andyblac** [comment]
i'm not sure why it did not work, just tested here and reverted fine. @rojer any suguesstions ?

**Comment by rojer** [comment]
nope. @Nikola1236 when you power the device off and on, do you see and LED activity?

**Comment by Nikola1236** [comment]
> nope. @Nikola1236 when you power the device off and on, do you see and LED activity?

Yes i see the led that turns on and off a certain number of times now I don't remember many times but it seems to me twice that it turns on and off

**Comment by rojer** [comment]
ok, so it's at least somewhat alive. if the LED stays off after that, it means it connected to wifi successfully. do you know its ip address? you could check list of active clients on your wireless router

**Comment by andyblac** [comment]
if i understood him correctly, he says it stuck on homekit fw, and can still access the webUI.

**Comment by andyblac** [comment]
@Nikola1236 still a problem ?

**Comment by andyblac** [comment]
@Nikola1236 do you still need help? else i'll close this ticket.

**Comment by andyblac** [comment]
closing as no reponce from OP.
