### ISSUE TITLE
Flashing from 2.5.0 beta back to 2.4.0 failed

### ISSUE THREAD

**Issue by jobl1978** [mongoose-os-apps/shelly-homekit#262]
My Shelly isn’t reachable after flashing back now from LAN. Is there any possibility to bring it to AP mode? Turn Power off/on and switching 5 times to hard reset the Shelly doesn’t work anymore.

**Comment by andyblac** [comment]
try this https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery

**Comment by andyblac** [comment]
i presume this is the shelly 2.5 ?, if so it has a button back of device press and hold the button for 10 seconds while the device is on

**Comment by jobl1978** [comment]
No it’s a shelly1

**Comment by andyblac** [comment]
Then try the on / off 10 times, it sounds like config in 2.5 changed and maybe incompatible with 2.4 @rojer ?

**Comment by jobl1978** [comment]
I got it back it changed the IP Adress and was not reachable from the Home App anymore. After resetting the HomeKit settings and using a new Code it was able to reconnect.

**Comment by andyblac** [comment]
can i close this now ?

**Comment by jobl1978** [comment]
> can i close this now ?

Yes
