### ISSUE TITLE
Missing shelly_input_pin.hpp

### ISSUE THREAD

**Issue by nliviu** [mongoose-os-apps/shelly-homekit#264]
```
make Shelly1
...
In file included from /home/liviu/mos/shelly-homekit/src/shelly_noisy_input_pin.cpp:18:
/home/liviu/mos/shelly-homekit/src/shelly_noisy_input_pin.hpp:20:10: fatal error: shelly_input_pin.hpp: No such file or directory
   20 | #include "shelly_input_pin.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~
```
It looks like the class `InputPin` was removed from `shelly_input.hpp` and `shelly_input.cpp` in https://github.com/mongoose-os-apps/shelly-homekit/commit/8898bce2dc7757eb4e2692fb1130682f6fc50fa2.

**Comment by rojer** [comment]
yep, forgot to add when committing 8898bce2dc7757eb4e2692fb1130682f6fc50fa2
fixed now

**Comment by nliviu** [comment]
Thanks!
