### ISSUE TITLE
Revert after flashing wrong firmware

### ISSUE THREAD

**Issue by SebReuter** [mongoose-os-apps/shelly-homekit#266]
Hi,

I accidentally flashed a shelly25 (original firmware) with the shelly1 (shelly-homekit) firmware. 

Now only one switch is available (but this one works pretty well :))
The device can be accessed and configured via its IP-addredd

I would like to flash the shelly25 but the following things do not work:
1) "Revert to stock"-functionality flashes the original shelly1 firmware 
2) "Update from file"-functionality crashes with "-13 Aborted by event handler"
3) http://IP/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip results in "Not found"

It would be great if flashing of the wrong firmware would be blocked. 

Do you have any suggestions what I should try to flash the shelly25 firmware over the air?

**Comment by andyblac** [comment]
download the shelly2.5 firmware and upload it via the webUI.

here https://github.com/mongoose-os-apps/shelly-homekit/releases
and here
https://github.com/mongoose-os-apps/shelly-homekit/wiki/System-Settings

**Comment by SebReuter** [comment]
It fails with
shelly_main.cpp:692     Wrong app name 'switch25'

**Comment by andyblac** [comment]
looks like only option then is reflash via serial. unless @rojer has any ideas ?

**Comment by rojer** [comment]
i'm surprised it was even possible to flash from stock with the wrong app name.
but anyhow now that we're here... it's possible to recover, i'll build you special firmware to flash.

**Comment by SebReuter** [comment]
wow thank you. 

I was just thinking to disable the check in OTABeginCB(int ev, void *ev_data, void *userdata). Build Shelly1, flash it and then flash shelly25 over it.

What is your approach?

**Comment by rojer** [comment]
yep, exactly that. if you are comfortable with building firmware yourself, please go ahead.

**Comment by SebReuter** [comment]
will give it a try.

**Comment by SebReuter** [comment]
Worked like a charm. Thank you guys for your help.

This project is awesome - and so is your work. Thank you!

**Comment by rojer** [comment]
cheers!
