### ISSUE TITLE
Shelly 2 = Shelly Dimmer 2? HK for Dimmer?

### ISSUE THREAD

**Issue by Rappelsack** [mongoose-os-apps/shelly-homekit#267]
Hi there.

Just a short one: is the shelly 2 HK FW compatible with the shelly dimmer 2 (the yellow dude).
If not are u planning or already have a beta version available?

kind rgds.

**Comment by rojer** [comment]
No, "Shelly 2" is the deprecated version of a dual-switch device, replaced by Shelly 2.5
Dimmer is not currently supported, work on it is ongoing - https://github.com/mongoose-os-apps/shelly-homekit/issues/14
