### ISSUE TITLE
Shelly H & T together with Shelly 1 working as one device to control heating 

### ISSUE THREAD

**Issue by Ludelag** [mongoose-os-apps/shelly-homekit#268]
@rojer and @andyblac I just wonder if there is a support to use the Shelly 1 together with Shelly H & T as thermostat which could appear as a thermostat in the Home app? It will enable controling the heating by schedules using automation.   Thank you. 
![124212663_10158198962538052_6682819915813303057_n](https://user-images.githubusercontent.com/69207063/99046641-57e55680-2593-11eb-977d-04ea578d11d3.jpg)

**Comment by andyblac** [comment]
add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/186 i'll close this ticket, please report in the other ticket thanks.

**Comment by Ludelag** [comment]
ok
