### ISSUE TITLE
Shelly 1PM power consumption

### ISSUE THREAD

**Issue by ellavas** [mongoose-os-apps/shelly-homekit#27]
Hi,

I have installed the shelly homekit firmware on a Shelly 1PM. 
It works well but I can't find power consumption.

Would it be possible to add this feature ?

Thanks a lot.

**Comment by ellavas** [comment]
related to https://github.com/cesanta/mongoose-os/issues/531#issuecomment-605852246

**Comment by ellavas** [comment]
I’ve ported the Arduino HLW8012 power meter sensor library.

It's working fine with the Shelly 1PM.
You can have a look here:

https://github.com/ellavas/mongoose-lib-hlw8012

**Comment by edgarclerigo** [comment]
Hi guys,

Whats the current status of this ? Anyone with this firmware is not able to see any data about the power consumption, even on the Eve App ?

**Comment by rojer** [comment]
current state: not supported, no ETA

**Comment by Dag0d** [comment]
Is this something you've been working on? Would love to see that feature.
For the other power measurement Shelly devices which are already supported, do you expose the power consumption to the eve app?

**Comment by rojer** [comment]
power measurement is only supported on shelly 2.5 at the moment and is only surfaced on the web UI because there is no service or characteristic defined in the HAP protocol for such measurements.

**Comment by ellavas** [comment]
@Dag0d you can have a look to the library I have ported. It works fine on shelly 1PM.

https://github.com/ellavas/mongoose-lib-hlw8012

**Comment by rojer** [comment]
thanks @ellavas this is handy! i'll take a look

**Comment by freddair** [comment]
@rojer why not exposing power consumption to the eve app which would allow homekit automations like detecting when a washing machine / dish washer / water boiler is ready... would be really handy

**Comment by rojer** [comment]
Added support for power management for 1PM, Plug and PlugS.
Please help test by installing http://rojer.me/files/shelly/2.7.0-alpha4/ - you should see power figures in the web UI.
I am especially interested in accuracy, as I only have one of each of the device and cannot tell if coefficients hold across different samples. In theory, 1PM and PlugS should be the same, but mine differ by about 10%

**Comment by andyblac** [comment]
> Added support for power management for 1PM, Plug and PlugS.
> Please help test by installing http://rojer.me/files/shelly/2.7.0-alpha4/ - you should see power figures in the web UI.
> I am especially interested in accuracy, as I only have one of each of the device and cannot tell if coefficients hold across different samples. In theory, 1PM and PlugS should be the same, but mine differ by about 10%

whats the minimum power draw required, i have mine just turning the indicator light on a fused spur, but it does not detect any power consumption.

![IMG_0400](https://user-images.githubusercontent.com/77936/101241083-186dde00-36eb-11eb-900a-0d9fd4e46792.jpeg)

![Screenshot 2020-12-05 at 11 09 45](https://user-images.githubusercontent.com/77936/101241037-ac8b7580-36ea-11eb-9730-86650d3223a6.jpg)

**Comment by rojer** [comment]
that's definitely under 1 watt, you won't see anything.
i'd say any kind of accurate reading is from 10W.

**Comment by Dag0d** [comment]
did you make the power measurement values already persistent to create charts and so on?

**Comment by rojer** [comment]
no

**Comment by Dag0d** [comment]
okay thanks, I wondered why this wasn't working, I will continue testing this on my 1PM, till now it seems to run great. this evening I will have time to double check the power consumption measurements.
if it is off, should we think about a calibrating process?

**Comment by rojer** [comment]
correct

**Comment by Dag0d** [comment]
I´ve tested it a bit further, this firmware shows approx 1 watt more than the original firmware, if I double check with a multimeter, the multimeter value is exactly between this value and the value of the original firmware. I would be fine with that

**Comment by rojer** [comment]
thank you! indeed, that is acceptable. probably just a matter of rounding.

**Comment by rojer** [comment]
this is done

**Comment by masterc09** [comment]
I've got updated Shelly PlugS with latest shelly-homekit firmware to trigger a scene depending on power consumption like mentioned above from @freddair 

> @rojer why not exposing power consumption to the eve app which would allow homekit automations like detecting when a washing machine / dish washer / water boiler is ready... would be really handy

Can somebody confirm this functionality? I tried to access the value for power consumption via controller app with no luck, even not in eve app. If this should work could somebody give me a short instruction please? Thanks.

**Comment by timoschilling** [comment]
@masterc09 this issue is only about the measurement, that providing to HomeKit isn’t part of this issue. There is a other issue about that.

**Comment by masterc09** [comment]
@timoschilling Thanks, now I got it.

**Comment by ingenierodevops** [comment]
Do you hace an y idea to make a workaround to this? 
maybe launch a web call  or similar to HomeKit from the device configured in the web ui

I saw in homebridge someone used light sensor element to import power measurement. Can this be a good idea?
