### ISSUE TITLE
How to reboot SW1 automatically after x days?

### ISSUE THREAD

**Issue by Sindbad5** [mongoose-os-apps/shelly-homekit#273]
Is there any way to do it?
Maybe it could be a feature for the webUI ?!

**Comment by rojer** [comment]
what problem are you trying to solve?

**Comment by Sindbad5** [comment]
It seems that after some days (I don't know how many days) the Shelly isn't any more recognized by HomeKit but the Shelly is still reachable with webUI. After rebooting the SW1 all works fine. The last uptime was 36 days but after roundabout 25 days it wasn't anymore reachable with Home-App. So I thought an automatic reboot could be a workaround.

**Comment by andyblac** [comment]
duplicate ticket, please report your issue here https://github.com/mongoose-os-apps/shelly-homekit/issues/129
