### ISSUE TITLE
Problem. Please help

### ISSUE THREAD

**Issue by moonloopsun** [mongoose-os-apps/shelly-homekit#274]
Hi guys. Great project. 
I installed the Shelly 2.5 for my Rolls. 
They worked fine before. 
When i try to calibrate the motor is getting into a loop of toggling up down every second. And the wall switch doesn’t work anymore. Than when i press open or close the rolls open only a few centimeters. 
Please help. We can’t open the rolls now or close it...   
the open / close time should be 35 seconds
Each direction..
thanks

**Comment by pivale** [comment]
I had a similar problem (only descended a few centimeters each time) after an upgrade. I suspect something went wrong.

I suggest:
1. activate logs in webui, test again calibrate and try to function. Collect logs and send here please.
2. reboot and redo step 1 and check if it solved.
3. revert firmware back to stock and reinstall again latest version of shelly-homekit (this solved for me)

**Comment by SilvioMigu** [comment]
Hi
I wanted to try to put a 2.5 shelly on the Rolls, but I still haven't seen a connection and configuration scheme.
Do any of you have a scheme?

**Comment by Draf76** [comment]
![Jalousie_Shelly2 5](https://user-images.githubusercontent.com/73346506/103079894-12c23480-45d5-11eb-9194-d3767f5fd606.png)

**Comment by SilvioMigu** [comment]
Thank you for the answer. 
I've already ventured to install and it's that way it works, thank you![image](https://user-images.githubusercontent.com/67691682/103083340-11dcd300-45d4-11eb-9434-899e13135d24.jpeg)

**Comment by torto-85** [comment]
> Hi guys. Great project.
> I installed the Shelly 2.5 for my Rolls.
> They worked fine before.
> When i try to calibrate the motor is getting into a loop of toggling up down every second. And the wall switch doesn’t work anymore. Than when i press open or close the rolls open only a few centimeters.
> Please help. We can’t open the rolls now or close it...
> the open / close time should be 35 seconds
> Each direction..
> thanks

Hey,
did you solved the problem? I have the same too!
Cheers, Torto

**Comment by andyblac** [comment]
@pivale can you offer any assistance ?

**Comment by pivale** [comment]
> I had a similar problem (only descended a few centimeters each time) after an upgrade. I suspect something went wrong with the version upgrade.
> 
> I suggest:
> 
>     1. activate logs in webui, test again calibrate and try to function. Collect logs and send here please.
> 
>     2. reboot and redo step 1 and check if it solved.
> 
>     3. revert firmware back to stock and reinstall again latest version of shelly-homekit (this solved for me)

@torto-85 , have you tried these steps?
I had a similar problem and after revert to stock and reinstall homekit I got it to back to work

**Comment by andyblac** [comment]
still need help ?

**Comment by torto-85** [comment]
Hi, thanks for your suggestion (sorry @pivale: I didn't see your comment yet). I follow #404. Manual calibration seems a solution for me. Because I use one shelly to control more than one roller shutter the auto-calibration won't work for me.

**Comment by andyblac** [comment]
so i can close this ?, can always reopen later is thing change.

**Comment by torto-85** [comment]
> so i can close this ?, can always reopen later is thing change.

Yes, that‘s fine for me.
