### ISSUE TITLE
Activation switch mode

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#278]
Hi, in original firmware there is a "activation switch" mode, that use for motion sensor when any inputs turns "ON" and resets auto off times (instead, in normal mode, when auto off is running, the input turn "OFF" and stop auto off times).
Could you add it in HomeKit firmware?
In my case instead I need also the auto off timer start when input turn "OFF" (not start when input turn "ON"), pratically when toggle is ON, switch is ON, but when toggle go OFF the switch KEEP ON for an auto off timer, after tath it go OFF. It remain ON after toggle off.
Could you add both version? "Activation switch"(input reset timer) and "Keep on" (remain ON after toggle off).
Thanks!

**Comment by lucaspinelli85** [comment]
![Uploading 99290910-e7f6fa80-2836-11eb-94d3-c66adfe57adb.jpg…]()

**Comment by lucaspinelli85** [comment]
![99290910-e7f6fa80-2836-11eb-94d3-c66adfe57adb](https://user-images.githubusercontent.com/74553551/99312107-d412bf00-285d-11eb-9bb2-d4d7b7b6bc2c.jpg)

**Comment by rojer** [comment]
thank you for the detailed description!
this makes sense and is easy to do.

**Comment by lucaspinelli85** [comment]
Thanks for helpful and hope it went add soon both the option!

**Comment by lucaspinelli85** [comment]
> thank you for the detailed description!
> this makes sense and is easy to do.

When do you think it could be add in the firmware?

**Comment by rojer** [comment]
please help test 2.6.0-beta - https://github.com/mongoose-os-apps/shelly-homekit/issues/291
