### ISSUE TITLE
Shelly Button compatibility

### ISSUE THREAD

**Issue by DavRin** [mongoose-os-apps/shelly-homekit#280]
Good morning, is it possible add the homekit compatibility on the shelly button (no homebridge)?

Thank you for your fantastic work

**Comment by lucaspinelli85** [comment]
Inside the button there is a shelly1/1PM... Button is just a wrap...

**Comment by lucaspinelli85** [comment]
Instead could be interesting the compatibility with the new BUTTON1 2020 (wireless instead wired). I don't know what there is inside (if the same shelly1 or something difference). @andyblac or @rojer do you know? And if it is already homekit compatible?
https://shelly.cloud/products/shelly-button-1-smart-home-automation-device/

**Comment by andyblac** [comment]
and if your talking about Button1 add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/104

**Comment by lucaspinelli85** [comment]
ok, so we can conclude that it is compatible with button (wired) and **not** compatible with button1 (wireless), right?
![image](https://user-images.githubusercontent.com/74553551/99537620-31b52180-29ac-11eb-970d-197fe2d493a9.png)

**Comment by andyblac** [comment]
yes, button is just a shelly1.
