### ISSUE TITLE
Shelly Ad-on in Shelly 1 to trigger a boiler or connect to a Thermostat

### ISSUE THREAD

**Issue by Ludelag** [mongoose-os-apps/shelly-homekit#281]
Dear all, there is any closer planning to add Shelly-Homekit the Add-on of shelly? 

https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312

Thank you.

![82279151_10220337799137640_2205997702620119040_n](https://user-images.githubusercontent.com/69207063/99527972-e5fb7b80-299d-11eb-8879-56f4b4b5d40a.jpg)
![81262242_10220337751536450_1385881776282402816_n](https://user-images.githubusercontent.com/69207063/99527978-e85dd580-299d-11eb-9229-2a7b86084c7d.jpg)

**Comment by lucaspinelli85** [comment]
you read my mind...

**Comment by andyblac** [comment]
duplicate ticket https://github.com/mongoose-os-apps/shelly-homekit/issues/186 please add your support on that one.
