### ISSUE TITLE
Shelly1 disappeared after updating firmware

### ISSUE THREAD

**Issue by benpems** [mongoose-os-apps/shelly-homekit#284]
Hi,

I used the following url http://192.168.0.103/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip

Where 192.168.0.103 is the address of the shelly 1. It seemed to do the update however when I try to access through the url afterwards I get no response.  I also can't see it attached the router. 

Any ideas?

**Comment by rojer** [comment]
do you see any LED activity?

**Comment by benpems** [comment]
No, I didn't know the Shelly 1 had an LED. I can't see anything anyway

**Comment by benpems** [comment]
I turned the power on and off and I can now access it. Not sure what happened

**Comment by rojer** [comment]
oops, sorry - indeed, shelly1 does not have an led.

it's weird, but i'm glad you got it sorted.
