### ISSUE TITLE
Firmware does not change??

### ISSUE THREAD

**Issue by j55marshall** [mongoose-os-apps/shelly-homekit#287]
Hi guys the instructions look so simple,  however I have tried everything including installing Mongoose HTTP server and no difference.

My browser goes to a page like this:

{"status":"updating","has_update":false,"new_version":"","old_version":"20190329-090914/master@b49f177f"}

Nothing seems to happen,  I have a steady ping hitting the device and it never reboots just sits on stock firmware?
Thanks

**Comment by andyblac** [comment]
update stock firmware 1st, that too old. then retry.

**Comment by j55marshall** [comment]
Ok thanks but when I check it says that it is update to date see attached
<img width="782" alt="Screen Shot 2020-11-22 at 12 02 14 PM" src="https://user-images.githubusercontent.com/73529243/99910171-988f4f00-2cba-11eb-88db-bd04cbdf7609.png">

**Comment by rojer** [comment]
interesting. what device is this?

**Comment by j55marshall** [comment]
Shelly1 PM

**Comment by j55marshall** [comment]
Ok got a bit further here.   The device was attached to one of my TINY pcs WIFI direct.   I have joined to my actual main WIFI network and then I did get an option to upgrade the FW.

Now it appears I am on the latest FW,  you can see many more stock config options.

I then went to the OTA link and this is what I get:

LINK
http://192.168.0.70/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1PM.zip

PAGE:
{"status":"updating","has_update":false,"new_version":"20200827-070450/v1.8.3@4a8bc427","old_version":"20200827-070450/v1.8.3@4a8bc427"}

Still on the stock FW :/. so close!!  :)

**Comment by j55marshall** [comment]
WOW got it!

<img width="616" alt="Screen Shot 2020-11-22 at 12 36 00 PM" src="https://user-images.githubusercontent.com/73529243/99910976-59173180-2cbf-11eb-9448-bd84925b3110.png">

**Comment by j55marshall** [comment]
I guess had to be more patient for it to take thanks everyone

**Comment by andyblac** [comment]
glad you got it sorted, flashing can take 30 seconds
