### ISSUE TITLE
Request: Inverted (Reversed) SW output

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#290]
#220

**Comment by lucaspinelli85** [comment]
Like the inverted inputs I need the inverted outputs

![](https://user-images.githubusercontent.com/74553551/99394956-0ebd3b80-28e0-11eb-9952-c5e5b8395041.png)

**Comment by lucaspinelli85** [comment]
Principally difference from inverted inputs is in the app, that show me inverted state of relay rather show me inverted state of switch when relay and switch are inverted!

**Comment by rojer** [comment]
this one i'm not so sure about. give me a use case for this.

**Comment by rojer** [comment]
um... no, i don't like the idea after all.

**Comment by tvarohp** [comment]
I see you have talked about invert ouputs, but I do not see solution. Do you have any soulution for Shelly 1 and shelly PM for THAT?
Use case: I have No and Nc valves. I use only buttons in apps.(I have no switches on inputs connected) I need to unify buttons to show ( on= all NC and NO are OPEN, and wise versa) could you suggest me the solution for that?
