### ISSUE TITLE
RPC call for garage opener not implemented. 

### ISSUE THREAD

**Issue by svn2208** [mongoose-os-apps/shelly-homekit#299]
Hi,
I am using a Shelly-1 as GarageOpener via Homekit and it works great. The downside, if I am outside I want to use a VPN and RPC call to open the garage. 
Sadly I discovery, that the code is not allowing that.

Only switches, outlets or locks are allowed. Is there special reason ?

    switch (c->type()) {
      case Component::Type::kSwitch:
      case Component::Type::kOutlet:
      case Component::Type::kLock: {
        ShellySwitch *sw = static_cast<ShellySwitch *>(c);
        sw->SetState(bool(state), "web");
        mg_rpc_send_responsef(ri, nullptr);
        return;
      }

**Comment by rojer** [comment]
not really, just didn't have the need.

**Comment by svn2208** [comment]
Is it possible to add this in a future version?

**Comment by rojer** [comment]
yes, makes sense

**Comment by rojer** [comment]
in fact, you can send a "toggle" command via RPC like so:

```
curl http://shelly1-test.local/rpc/Shelly.SetConfig -d '{"id": 1, "type": 5, "config": {"toggle": true}}
```
