### ISSUE TITLE
Update to the newest Firmware

### ISSUE THREAD

**Issue by Simon1505** [mongoose-os-apps/shelly-homekit#300]
Hallo guys,

Great Job. But I have a Problem. I want to update my Shelly HomeKit Firmware to the latest one. How can I do this. I downloaded the Zip and drop it in the Update Field and click to update. After that I see this text "-1 Archived file size is unknown". How can I fix it? Thanks for your help.

**Comment by Simon1505** [comment]
Ok I´ve found the fault.

**Comment by rojer** [comment]
since version 2.5 you can update from the web ui directly.

but the problem with updating from zip is that Mac OS messes with the zip file behind the scenes. make sure you upload exactly the file that was downloaded, not recompressed one.
