### ISSUE TITLE
Make the Update Alert a link to the System.Update section

### ISSUE THREAD

**Issue by jsiegenthaler** [mongoose-os-apps/shelly-homekit#303]
Today I clicked the **Update** Alert icon on the top of the Shelly1 internal webpage expecting it to be a button and it to start the update process or take me to the update section.

It doesn’t.

But then I thought: it looks like a button and I clicked it because I though it was a button.

So why not make it a button, or a clickable link to take you to the Update line in the System section?
That should be easily doable with relative URL linking within the same page...

**Comment by rojer** [comment]
@ZeevoX should be an easy one
