### ISSUE TITLE
Homekit Firmware for Shelly RGBW2?

### ISSUE THREAD

**Issue by MainU1** [mongoose-os-apps/shelly-homekit#305]
Hello, is there a homekit firmware for the Shelly RGBW2?
I'm struggling with that and i dont want to use homebridge.

kind regards

**Comment by jobl1978** [comment]
No currently not, but I would also be happy if one exists some day ;-). I think @rojer is currently working to get the Dimmer2 running for HomeKit.

**Comment by andyblac** [comment]
yeah he is, but as he blow up his laptop, it caused a delay, and he is very busy with other projects atm.

**Comment by andyblac** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/issues/72
