### ISSUE TITLE
Choose Mode for Statless Switch in Detached Input Mode

### ISSUE THREAD

**Issue by crazylenni** [mongoose-os-apps/shelly-homekit#307]
Hi,
i used a shelly1 in a circuit like the following picture.
[https://forum.creationx.de/index.php?attachment/2470-shelly1-einausschalter-png/](url)

I want to power my ceiling lamp continuously, so i want the shelly relay on all the time. To control the lamp i want to use the switch connected to the shelly.
I use the HAP-Mode _Disabled_ and the Input-Mode _Detached_. My Problem is, that the stateless switch (created by choosing _Detached_) only fire its automation, when the switch is turning on, not off.
Is there a way to choose the Mode for the Stateless Switch, so it gets triggered every time the input changes? If not, this is a feature request.

Thank you!
Lenni

**Comment by jobl1978** [comment]
You have a "switch->shelly->lamp" relationship right? Set the shelly to HAP Type "switch" and input mode to "momentary" or "toggle", depends on which kind of switch you have connected to the Shelly. In the Home App you choose "light" as accessory type for this device. With this configuration you can turn on/off the light from HomeKit and can program automations triggered by light state events (on/off).
