### ISSUE TITLE
Wipe all configuration

### ISSUE THREAD

**Issue by rudyemm** [mongoose-os-apps/shelly-homekit#308]
Is there a way to fully wipe a Shelly 2.5 without physical access to it? I would like to perform the reset described in Recovery > From crash looping or otherwise misbehaving firmware:

In this mode device wipes all its configuration, HAP and WiFi and reverts back to AP mode. Bare-bones web interface will be available at http://192.168.33.1/ when connected to the device's AP, it allows uploading new firmware (can be HomeKit or stock).

... but I do not want to open up the wall to gain access to the Shelly. I would like to wipe all the config that survive factory resets such as HomeKit pairing, etc. Thanks!

**Comment by rojer** [comment]
there isn't a way right now, but i think it makes sense to add it.

**Comment by andyblac** [comment]
yeah, rojer and i discussed this the other day.

**Comment by andyblac** [comment]
the question remained how to do it ?

**Comment by rojer** [comment]
it's easy actually, RPC + button in the web ui

**Comment by rojer** [comment]
@andyblac what we discussed was how to trigger it physically on shelly1, since it has no physical button.

**Comment by rudyemm** [comment]
That’s great!

Will this type of reset go back to the stock firmware? Or stay on HomeKit?

**Comment by rojer** [comment]
no, that would need to be done separately.

**Comment by rudyemm** [comment]
Do you know, is there a similar function in the stock FW to wipe all config? Even when doing a factory reset in the stock FW, it seems the config remains.

**Comment by rudyemm** [comment]
Is this feature something that can be incorporated into the coming builds? 🙏

**Comment by rojer** [comment]
at some point - sure

**Comment by rojer** [comment]
fixed - added a "Reset" button to the system section, it wipes all the configuration and reboots the device into AP mode.
