### ISSUE TITLE
1PM: Is overheating protection still working after OTA?

### ISSUE THREAD

**Issue by tsdrummer** [mongoose-os-apps/shelly-homekit#31]
The same question is for the over consumption check. 

Thanks

**Comment by rojer** [comment]
no, not at present. for now, your 1PM turns into a 1, becoming a dumb switch with HomeKit support.

**Comment by MilanBacaCz** [comment]
is there a plan to implement it?

**Comment by rojer** [comment]
#168

**Comment by rojer** [comment]
should do it for all devices, it turns out they all have an NTC resistor connected to the ADC pin.
