### ISSUE TITLE
Web UI Changes over RPC

### ISSUE THREAD

**Issue by Rithord** [mongoose-os-apps/shelly-homekit#312]
Hello,

Just wondering if anyone can give some advice on how to get MOS tool to work. 

Trying to achieve this command successfully for re-upload:
mos --port ws://x.x.x.x.local/rpc put fs/index.html.gz

I have been trying to update the html web layout of the shelly homekit page and would like to upload it back to the server to make those changes. I have been trying for hours to get MOS Tool working on Windows/Mac and Linux but I'm not having any luck with the instructions that were given in the development section.

Has anyone else done this on their local network yet?

Thanks in advance!

**Comment by rojer** [comment]
`ws://x.x.x.x.local/rpc` - this looks wrong. use either ip address, `ws://x.x.x.x/rpc` or the .local name, in which case it's `ws://YYY.local/rpc` where YYY is the device name configured in the UI

**Comment by Rithord** [comment]
Thank you for suggesting that, my trouble is actually getting the MOS tool to respond to a RPC call or command. I installed via the instructions that Mongoose OS provides for Windows installations but I was not successful in getting it to work or to communicate with my Shelly.

Any advice here? 

Thank you again!

**Comment by rojer** [comment]
please post the command and output you get

**Comment by Rithord** [comment]
![mos](https://user-images.githubusercontent.com/44822497/100864897-9c4c7e00-34d1-11eb-83b2-dcdbe63d3ac9.png)

**Comment by rojer** [comment]
forget gui, use command line.

**Comment by andyblac** [comment]
at top, you have not chosen port / board type.

**Comment by andyblac** [comment]
> forget gui, use command line.

i was just going to say that too.

**Comment by Rithord** [comment]
Is that just using GIT command line?

**Comment by Rithord** [comment]
Sorry guys about my lack of knowledge with this

**Comment by Rithord** [comment]
> forget gui, use command line.

Hi @rojer, just wondering if you are able to give some advice on how to go about what you mentioned with the command line?
