### ISSUE TITLE
Add Backup WiFi AP to WiFi Settings.

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#313]
stock firmware has the ability to add a Backup WiFi SSID, this could come in handy.

**Comment by andyblac** [comment]
Also, I was thinking would it be possible to get the device to revert to AP mode, if wifi signal drops for a period of time ?, and get it periodically check for the associated AP’s to see if they are back online ?

**Comment by rojer** [comment]
as discussed on gitter: yes to multiple aps, no to automatic ap.

**Comment by rojer** [comment]
closing in favor of #501
