### ISSUE TITLE
serial flash without resetting settings

### ISSUE THREAD

**Issue by timoschilling** [mongoose-os-apps/shelly-homekit#315]
Is it possible to flash the firmware via serial connection without resetting the wifi and HomeKit settings?

I'm currently work on an support for the shelly rgbw2 and have the problem that I need to resetup the devise after each flash.

**Comment by rojer** [comment]
first, i advise using OTA with commit_timeout for development, i do it myself all the time.
but it is possible to avoid reconfiguring all the time when reflashing over serial - just add the files you need (config.json, kvs.json) to the `fs` directory without checking in. they will be picked up during fs image build.
