### ISSUE TITLE
option to disable inputs

### ISSUE THREAD

**Issue by timoschilling** [mongoose-os-apps/shelly-homekit#318]
This feature request targets the i3, but maybe also useful for all devises with switches in detached mode.

I would like to have an option to disable an input in the web ui, to hide them from HomeKit. The reason for this is that I have may i3 installed in my house but all of them only with 1-2 inputs in use. This results in many unused inputs in the Home app. Disabling the unused inputs would be help to keep the overview clean.

**Comment by rojer** [comment]
you are in luck, this is already implemented together with motion sensor mode (#294), i'll push test versions soon.

**Comment by rojer** [comment]
please try 2.7.0 test version - https://github.com/mongoose-os-apps/shelly-homekit/issues/294#issuecomment-738405359

**Comment by timoschilling** [comment]
Works as expected, nice, tanks!
