### ISSUE TITLE
Script multiple calibration roller shutter

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#326]
Hi, is there a script that calibrates all shelly roller shutter? Is it necessary to calibrate or it work the same? Thanks

**Comment by andyblac** [comment]
No, I'll have a chat with @rojer to see if this is even possible.

So atm you will have to do them one by one.

**Comment by lucaspinelli85** [comment]
I must to do it or not necessary? Can i do only in webui or can i one by one from script, url, anything without enter in webui?

**Comment by andyblac** [comment]
i am not totally familiar with roller shutter mode, but, from what i understand yes, it must be done, and it can only be done from the webUI.

**Comment by andyblac** [comment]
see here https://github.com/mongoose-os-apps/shelly-homekit/wiki/Roller-Shutter-Settings for info.

**Comment by andyblac** [comment]
can i close this issue now ?, as it can not be done via a script and mst be done via the webUI.
