### ISSUE TITLE
Disconnections during gate operations

### ISSUE THREAD

**Issue by simonfield76** [mongoose-os-apps/shelly-homekit#327]
Hi I've noted a strange behaviour of a shelly 1 set as garage.

Wifi connection is not too strong even if I have placed a new access point 3 meters far.

Any case it remains very stable al the time. (Rssi between -73 and -69)

Once I activate the opening of the gate the shelly goes offline and it is not reachable until full closing of the gate.

The same behavior is also confirmed from the access point statistics where the ip of the shelly seems restarting at the opening.

Not a big issue but usually if i open the gate and repress the button the gate does not finish the opening and immediately close

![image](https://user-images.githubusercontent.com/75778600/101752905-53e51f80-3ad2-11eb-9862-fc53bd188c48.jpeg)

**Comment by MichaelVdheeren** [comment]
Think my issue is similar. If I disable my WiFi (rely on 4G), then I can control my Shelly1 which is configured as a light, but not a Shelly1 which is configured as a garage door opener. If I am on WiFi it works again but indeed it seems to be showing unresponsive for a while.

**Comment by andyblac** [comment]
is this still an issue in 2.7.3 ?

**Comment by andyblac** [comment]
closed as no reply
