### ISSUE TITLE
Trigger Gargage Door Through HTTP

### ISSUE THREAD

**Issue by tayfunceylan** [mongoose-os-apps/shelly-homekit#334]
Is there a way to trigger a garage door through an http request like the [/rcp/Shelly.SetSwitch](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development#API) example for Switches?

\- Tayfun

**Comment by tayfunceylan** [comment]
I am sorry. I posted this too early. 
Actually i found [this](https://github.com/mongoose-os-apps/shelly-homekit/issues/299#issuecomment-743950165) post. So i was able to trigger the garage with a GET reqeusted and nested Object: 

`http://host/rpc/Shelly.SetConfig?id=1&type=5&config=%7B%22toggle%22%3Atrue%7D`

**Comment by hfagelnour** [comment]
this does not work anymore. any thoughts?
