### ISSUE TITLE
Temperature add-on Shelly1

### ISSUE THREAD

**Issue by Tins612** [mongoose-os-apps/shelly-homekit#340]
Hello, are you planning to implement the temperature add-on for the Shelly1? I would like to switch the Shelly on when a certain temperature is reached. However, not via the Shelly app but via Homekit. Can someone help me there?

greeting

**Comment by simonfield76** [comment]
I need the same as I would like to place it inside my server rack to use it as a connected thermostat, specially for the summer period!

Inviato da iPhone

Il giorno 14 dic 2020, alle ore 10:20, Tins612 <notifications@github.com> ha scritto:

﻿

Hello, are you planning to implement the temperature add-on for the Shelly1? I would like to switch the Shelly on when a certain temperature is reached. However, not via the Shelly app but via Homekit. Can someone help me there?

greeting

**Comment by svn2208** [comment]
You mean the internal temperatur sensor? This most probably won't work  (=> #265)

**Comment by andyblac** [comment]
duplicate closing https://github.com/mongoose-os-apps/shelly-homekit/issues/186

**Comment by Tins612** [comment]
no, I mean the external module where a temperature sensor can be terminated.

https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312

**Comment by andyblac** [comment]
@Tins612 please add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/186
