### ISSUE TITLE
icon faucets showers sprinklers?

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#341]
Hi, where i can set the mode type for visualize in app homekit icon of faucets showers sprinklers?
![image](https://user-images.githubusercontent.com/74553551/102206590-2b439800-3ecd-11eb-8879-25915577a855.png)

**Comment by andyblac** [comment]
Accessory type would need adding.

**Comment by andyblac** [comment]
add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/43 i'll close this one.

**Comment by lucaspinelli85** [comment]
Ok!

**Comment by danny1605** [comment]
please add sprinklers Type. Thx

**Comment by andyblac** [comment]
> please add sprinklers Type. Thx

this issue is closed add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/43
