### ISSUE TITLE
Led disable to current savings/lowering of temperature...

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#342]
Yes, it is very little, perhaps irrelevant, but in original firmware there is an option to disable the led status.
Is it simple to integrate it in webui?
The devive is locked up, not visible from the outside, it is useless to have the led on which is not needed...

**Comment by rojer** [comment]
the default is to have LED off if device is connected to wifi and paired with a HAP controller, so it should be off for most of the time
is that not the case?

**Comment by lucaspinelli85** [comment]
You are right, sorry!

**Comment by lucaspinelli85** [comment]
Not in Shelly PlugS, blue led blinking, red led on when power on...

**Comment by rojer** [comment]
ok, you're right. could be done, but it's so minor i don't know if it even deserves an option.
the amount of current drawn by the LED is miniscule. there may be an argument about light pollution but... meh, i don't know.
i'll let this one simmer and gather support. if you are reading this and want this to happen, please speak up.

**Comment by lucaspinelli85** [comment]
it's just the hassle of always seeing the LED lit in the plug even when it is not active ...

**Comment by pivale** [comment]
It might be a problem for people with one in a bedroom during the night.
Some people have trouble sleeping with the faintest light...

**Comment by chstoll** [comment]
It would be nice to get an option to disable the red LED of the PlugS. In some of my scenes the red LED is just a little disturbing, So +1 ...

**Comment by timoschilling** [comment]
+1

**Comment by Spy-1** [comment]
+1
