### ISSUE TITLE
MAC adress of Shelly via web UI

### ISSUE THREAD

**Issue by BlancoDeMallloca** [mongoose-os-apps/shelly-homekit#343]
Hi all,

once again thanks for the great firmware. 

Is there any chance to view the MAC adress of Shelly via the web UI?

Is it the serial number in  HomeKit?

Thanks

**Comment by andyblac** [comment]
yes.

**Comment by BlancoDeMallloca** [comment]
> yes.

Please tell me more

**Comment by BlancoDeMallloca** [comment]
> yes.

Thanks. Topic can be closed.
