### ISSUE TITLE
Shelly door/windows2 

### ISSUE THREAD

**Issue by claudio50** [mongoose-os-apps/shelly-homekit#344]
Any possibility to get support for Shelly door/window2 ?

Shelly1 and Shelly2.5 run perfectly.

**Comment by BlancoDeMallloca** [comment]
Seems to be a duplicate to Shelly Sensors support [#124](https://github.com/mongoose-os-apps/shelly-homekit/issues/124)

**Comment by andyblac** [comment]
> Seems to be a duplicate to Shelly Sensors support [#124](https://github.com/mongoose-os-apps/shelly-homekit/issues/124)

thanks.
