### ISSUE TITLE
Projector Screen setup

### ISSUE THREAD

**Issue by Draf76** [mongoose-os-apps/shelly-homekit#354]
Hi there, 

I am setting up a projector screen and want to control it using a Shelly 2.5 with your HK firmware. 
It is set to Roller Shutter. 
The problem is when I try to calibrate it, it lets the screen completely out and not only to a certain point. So I can't define how far the screen opens. Is there a way to manually calibrate/set it? 

Thanks for your help.

**Comment by leilok** [comment]
Just replied to you in my thread!!!

Hope I can help you!!!
