### ISSUE TITLE
New Router / Problem to switch WiFi to new network

### ISSUE THREAD

**Issue by Mikerosoft90** [mongoose-os-apps/shelly-homekit#358]
hello,

how do I get the shelly 25 into my new network? 
I no longer come to the web interface of the shelly to change the wlan settings. 
I have already reset the Shelly and this is also displayed as a WLAN network. In the official Shelly app I can not add the 25 and I always get an error message.

I hope you can help me :)

**Comment by simonfield76** [comment]
Is there a way to assign a static IP address?

Inviato da iPhone

Il giorno 23 dic 2020, alle ore 07:54, Mikerosoft90 <notifications@github.com> ha scritto:

﻿

hello,

how do I get the shelly 25 into my new network?
I no longer come to the web interface of the shelly to change the wlan settings.
I have already reset the Shelly and this is also displayed as a WLAN network. In the official Shelly app I can not add the 25 and I always get an error message.

I hope you can help me :)

**Comment by Mikerosoft90** [comment]
hello simon,

thanks for your reply.

do you mean that i should connect to the shelly (ap mode) and then assign a static ip? Would that help me?

**Comment by BlancoDeMallloca** [comment]
If you are able to connect to the Shelly AP the IP for the web interface should be http://192.168.33.1/
In the web interface you should be able to enter the new WiFi Settings

**Comment by andyblac** [comment]
@Mikerosoft90 still an issue ?

**Comment by rojer** [comment]
closing in favor of #501
having multiple wifi configurations will allow for smooth migration of networks.
