### ISSUE TITLE
Device name lost after upgrade to new 2.7.0 firmware

### ISSUE THREAD

**Issue by jsiegenthaler** [mongoose-os-apps/shelly-homekit#359]
I just upgraded my Shelly1s form 2.6.1 to 2.7.0 and noticed that the device name gets lost.
The device name reverted to shelly1-xxxxx where xxx is I think the mac address

It would be very user-friendly if the device name could be preserved during a firmware update

**Comment by andyblac** [comment]
kept name here ok, on all my devices.

**Comment by jsiegenthaler** [comment]
Strange, lost it on both mine this morning. Observed on first one, wasn't sure, so watched second update closely and sure enough, name was lost. I am using 2 x Shelly1.

**Comment by Stundenplan7b** [comment]
Hello, witch Firmeware did you habe before you update to 2.7?

Maybe 1.x?? I remember an information from rojer from the past. As he switch from 1.x to 2.x firmware this issue can happen!

**Comment by rojer** [comment]
> It would be very user-friendly if the device name could be preserved during a firmware update

indeed we try our best to preserve user settings during upgrades. there were only a few intentional cases where user settings were not migrated, where doing so would be too complicated and impact deemed low.

which version you were upgrading from?

**Comment by jsiegenthaler** [comment]
I had 2.6.1. Went from that to 2.7.0

**Comment by Stundenplan7b** [comment]
Today i make the Update from 23 Shellys. 7 one's and 16 Shelly 2.5. Some with 2.5.0 and some with 2.6.1.

Change the Name on the Website and HomeKit?

**Comment by andyblac** [comment]
was names ok updating to 2.7.3 ? or is this still an issue ?

**Comment by jsiegenthaler** [comment]
Hi

Upgrading 2.7.1 to 2.7.3 last night occurred without any issues. You can
close this ticket.

**Comment by andyblac** [comment]
thx
