### ISSUE TITLE
AP Mode not working?

### ISSUE THREAD

**Issue by Kroellie** [mongoose-os-apps/shelly-homekit#36]
Hi, my shelly 1 flashed with your firmware lost it's wifi connection. Now when I reset the Shelly 1 using 5 times on/off, I hear the clicking sound from the shelly, but no AP is presented. What could be wrong, or what can I do?

**Comment by andyblac** [comment]
iirc it is 10 on/off to reset in this firmware

**Comment by rojer** [comment]
as long as you can hear relays clacking rapidly, it means it switched to AP mode.
as to why you can't see the AP - i have no idea...
serial console output would help.

**Comment by burton58** [comment]
I have the same issue with two shelly 2.5's. I reseted both (power off, 10x on/off) and got the lights flickering. But I do not see any WIFI that matches Shelly. Or is there a specific Wifi name/pw?

Tried it multiple times but without success

**Comment by andyblac** [comment]
is this still an issue ?

**Comment by andyblac** [comment]
I'll close this ticket, please reopen if still an issue.

**Comment by fichtelmann** [comment]
I reactivate a shelly 2.5 today after a long time. Does not appear inside my configured Wifi. So I reset the device (5x switch). Hear the relais sound. But I can find the shelly AP to configure it new. Try it also with 2 more resets -> no success. Try the rest button on the back for 10 seconds. Relais were clicking. Still no success. Can't find the AP network. What shall I do ?

**Comment by raj47i** [comment]
Same Problem for me, for two of my 2.5s
