### ISSUE TITLE
Calibration never finishes on a long canopy / blind - when it takes above 90s to open

### ISSUE THREAD

**Issue by michaelnozbe** [mongoose-os-apps/shelly-homekit#360]
Amazing work on this firmware! Thanks so much! However, there’s an issue when the canopy/blind is really big. The calibration never finishes.

I have 4 Shellys 2.5 installed in typical window blinds and no problem there.

But I also have 3 Shellys 2.5 installed on three of my terraces connected to the canopies covering them. Two of them work great, but one terrace is really big and the canopy takes lots of time to open and/or close. Above 90 seconds.

I’ve tried to calibrate this canopy but it never finishes. It opens. It closes. And then it opens 1% and stops. Reports back the time but the “calibration button” still shows like it’s calibrating. (Screenshot attached)

Can I do anything to send you a debug report or something to help out?
![556BDD17-0174-42BE-89E4-7144994C3E07](https://user-images.githubusercontent.com/944380/103074463-f1a81680-45c9-11eb-806f-877d243de7eb.jpeg)

**Comment by andyblac** [comment]
@pivale can you help out ?

**Comment by pivale** [comment]
Not sure if I can help...

@rojer is there any kind of timeout or max run time for the calibration process?

**Comment by andyblac** [comment]
i'l close this one, no reponce from OP,  maybe take a look here https://github.com/mongoose-os-apps/shelly-homekit/issues/404
