### ISSUE TITLE
Can I flash Shelly 2.5 from HomekitBG to this firmware?

### ISSUE THREAD

**Issue by michaelnozbe** [mongoose-os-apps/shelly-homekit#361]
Before I knew better and bought standard Shellys, I bought one Shelly 2.5 from Amazon with HomeKitBG firmware.

Suffice to say, the HomeKitBG firmware is not really good and I cannot update it or do anything with it.

Can I somehow flash this one Shelly and upload this firmware? Is it possible?

**Comment by andyblac** [comment]
Only via serial lead connection https://github.com/mongoose-os-apps/shelly-homekit/wiki/Serial-connection

**Comment by michaelnozbe** [comment]
Thanks. I guess this is too complicated for me. Don’t have the necessary cables and skills. Thanks.
