### ISSUE TITLE
Using flash-shelly.py as part of mgos-to-tasmota

### ISSUE THREAD

**Issue by yaourdt** [mongoose-os-apps/shelly-homekit#367]
I would like to adapt `flash-shelly.py` for use with [mgos-to-tasmota](https://github.com/yaourdt/mgos-to-tasmota). 

Instead of forking a single file as subrepository into another repository, I would rather just copy the file and credit you as original authors in the project's README. Apache 2.0 is compatible to GPLv3, so the license will remain unchanged. Is that ok for you?

**Comment by andyblac** [comment]
as long as you leave the copyright info etc in the file header i'm good.

**Comment by yaourdt** [comment]
that goes without saying. ok, cool, thanks!
