### ISSUE TITLE
Shelly Duo Support

### ISSUE THREAD

**Issue by hughfr4nc15** [mongoose-os-apps/shelly-homekit#369]
Hello,

I have several Shelly Relay Switches running flawlessly with your firmware. (thanks for that!)
Today I bought some Shelly Duo bulbs and it would be great if you guys released your firmware for them... would love to have native Homekit on those too. Any plans for that?

Thanks in advance and Happy Holidays!

**Comment by ari-ido-999** [comment]
Hello, supporting shelly bulbs will be excellent

**Comment by zeltak** [comment]
would also love this!

Z

**Comment by berkus** [comment]
Coming from #579, would also love to see lightbulbs support!

**Comment by appliko** [comment]
Buongiorno, any update on Duo and Vintage bulbs support ?

**Comment by hughfr4nc15** [comment]
Hello. Is there any planned release date for bulb support?
Thanks in advance!

**Comment by juangamnik** [comment]
I would appreciate support too. Especially for the Shelly duo rgbw gu10… since the homebridge plug-in I currently use, does not support white colors, so that you can only use the color LEDs, which are not as bright (using 1.5W instead of the 4.7W of the white color).

**Comment by GizaButler83** [comment]
Same here, can only control RGB in Homekit. White Channel is now working correctly and can only be used via shelly App/Browser GUI

**Comment by timoschilling** [comment]
Will be implement in #885

**Comment by rojer** [comment]
pushed in 2.11.0-alpha9, please help test it (#868).
