### ISSUE TITLE
Lock switch

### ISSUE THREAD

**Issue by hfagelnour** [mongoose-os-apps/shelly-homekit#376]
how to use the shelly 1 as lock with a contact sensor to show the door status in the home app? just like the garage door but lock instead? anyone?

**Comment by jsiegenthaler** [comment]
Use as a normal device and send url calls to the Webhooks plugin on homebridge

**Comment by hfagelnour** [comment]
So using the official firmware and homebridge is a must? Can’t be don’t using this firmware here?

**Comment by rojer** [comment]
it's not possible and i don't think it will be. "lock" gadget in HAP doesn't work that way.

**Comment by jsiegenthaler** [comment]
Whichever firmware you want as long as you can send http calls when the switch input is activated
