### ISSUE TITLE
Shelly2.5: Power measurement support

### ISSUE THREAD

**Issue by RRostron** [mongoose-os-apps/shelly-homekit#38]
good evening

i flashed the latest builds to my shellys ,  but on the shelly2.5s that i have, its not showing the power usage on SW1, it stays on 0w,  SW2 seems to work ok as that gives a reading.

**Comment by rojer** [comment]
yep, you're right. stupid last minute bug on my part, fix incoming.

**Comment by RRostron** [comment]
thanks rojer, 
another thing i noticed is on one of the shellys SW2 it shows a  negative - reading

**Comment by rojer** [comment]
i noticed this on one of my devices too, except in that case SW1 is negative while SW2 is positive. absolute values seem correct but the sign is not. not sure why, will take a look.

**Comment by rojer** [comment]
ok, i pushed 1.7.1 for shelly 2.5, please update

**Comment by RRostron** [comment]
hi rojer

that works thanks!
