### ISSUE TITLE
Shelly gets out of sync in HomeKit 

### ISSUE THREAD

**Issue by ursusHU** [mongoose-os-apps/shelly-homekit#382]
This is more or less a question. With the latest firmware (2.7.0) I get the issue that the status of the switch isn’t appearing correctly in HomeKit, and therefore also automations are failing. It is not a common problem, but appearing time to time. Should I look for an external cause, or anyone else experiencing this?

**Comment by andyblac** [comment]
how many ios devices do you have in the home ?

**Comment by ursusHU** [comment]
2 Phones only

**Comment by simonfield76** [comment]
In my experience it looks like a wifi issue.

Inviato da iPhone

Il giorno 25 gen 2021, alle ore 09:54, ursusHU <notifications@github.com> ha scritto:

﻿

2 Phones only

**Comment by andyblac** [comment]
@ursusHU for automations you need a homekit hub, do this help, can i close this issue ?

**Comment by ursusHU** [comment]
@andyblac I have hubs. You asked about ios devices (Phones)
Anyway with The current version I don’t experience the issue.
