### ISSUE TITLE
Temperature Sensor AddOn for Shelly 1/1PM

### ISSUE THREAD

**Issue by GianluSandro** [mongoose-os-apps/shelly-homekit#383]
This add-on for shelly 1/1pm it really cool! It's possible improve the feature to the firmware.
Thanks

[https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312](url)

**Comment by simonfield76** [comment]
I’m waiting this too. ☺️☺️

Inviato da iPhone

Il giorno 4 gen 2021, alle ore 06:28, GianluSandro <notifications@github.com> ha scritto:

﻿

This add-on for shelly 1/1pm it really cool! It's possible improve the feature to the firmware.
Thanks

https://shop.shelly.cloud/temperature-sensor-addon-for-shelly-1-1pm-wifi-smart-home-automation#312<url>

**Comment by andyblac** [comment]
duplicate issue, please add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/186

**Comment by GianluSandro** [comment]
sorry it my first post I don't see the old post @andyblac

**Comment by andyblac** [comment]
yeah, no worries 😄
