### ISSUE TITLE
Can't use it through internet

### ISSUE THREAD

**Issue by D3vEm** [mongoose-os-apps/shelly-homekit#386]
Hi, i can't  use this firmware on my shelly 1 v3 trought internet or mobile data. Everytime, i have to connect to my wifi and then activate the shelly on home app. When i use my phone on mobile data the toogle on the Home says an error (not response). Can u help me? Thank u

**Comment by andyblac** [comment]
what homekit hub do you have ?

**Comment by D3vEm** [comment]
I have just the Shelly. Do must I have an hub to work it on internet? Like Hassio ecc.?

**Comment by andyblac** [comment]
yes, to work online (without wifi) you need a HomeKit Hub (AppleTV, iPad, HomePod)
