### ISSUE TITLE
Max 9 HomeKit Connections

### ISSUE THREAD

**Issue by johannes4576** [mongoose-os-apps/shelly-homekit#387]
Hello Shelly friends, 

I have a complete HomeKit Home, with a few Shellys. But I have often the maximum from 9 connections to the device. Is this a limit from the hardware or a limit from the HomeKit Firmware?

Thanks :)

**Comment by andyblac** [comment]
> Hello Shelly friends,
> 
> I have a complete HomeKit Home, with a few Shellys. But I have often the maximum from 9 connections to the device. Is this a limit from the hardware or a limit from the HomeKit Firmware?
> 
> Thanks :)

iirc it a limit on RAM on the device.

**Comment by johannes4576** [comment]
Ah okay, thanks.
