### ISSUE TITLE
Shelly 2.5 Cycle Mode Switch

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#391]
In original firmware there is a cycle mode switch, it is useful to command 2 lights with 1 button with this cycle at every press change: 1on 2off, 1off 2on, 1on 2on, 1off 2off... and again!
Is it possible to implementate to HK Firmware? Thanks!
<img width="246" alt="image" src="https://user-images.githubusercontent.com/74553551/103827259-e4366600-5078-11eb-86ac-a9565e70e412.png">

**Comment by kx3kx3kx3** [comment]
see issue #194

**Comment by lucaspinelli85** [comment]
I think it can be useful to many
