### ISSUE TITLE
UI bug with selecting text in inputs

### ISSUE THREAD

**Issue by timoschilling** [mongoose-os-apps/shelly-homekit#392]
Way to reproduce:
1. Open UI of a devise (tested with PlugS, i3 and 2.5)
2. Select the text of a text input for example devise name
3. wait one or two second and the text will be deselected

This happens until the first change in the inputs happens, after that selected text keeps selected.

**Comment by andyblac** [comment]
yeah, noticed this too, but if you go to end of the text field it stays there, and allows you to edit the field with no issues.

**Comment by timoschilling** [comment]
Same happens if you place the cursor inside the text, it will jump to the end of the input after a short moment.

**Comment by timoschilling** [comment]
Yes there is a work around but I would like to report this to make users more happy.

**Comment by andyblac** [comment]
it is probably due to the new UI update with auto refresh, i have no idea if is a bug or normal behaviour.

**Comment by rojer** [comment]
yes, we should not be updating elements if there is active selection and/or value hasn't changed.
@ZeevoX please take a look
