### ISSUE TITLE
SW2 in shelly2.5 for general switch in multi roller shutter

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#398]
Hi!
Much spent, those who have more shutters in their home also have a general physical command to raise and lower them all at the same time.
By installing the shellys, this physical command is no longer usable and you are forced to make a scene in the home app.
The problem is that by doing so you are connected to the wifi network and for any network problem, the scene is not executed and it may happen that some shutters are not controlled.
To overcome this problem it is necessary to have a physical button that, regardless of the wifi network, executes the command directly in the shelly.
My proposal is to use SW1 for local shutter command (open, stop, close, stop) and SW2 for general command connected to all shellys to open / close all shutters simultaneously.
any suggestions?
I attach diagram
![image](https://user-images.githubusercontent.com/74553551/104157153-e38c2f80-53ea-11eb-93f3-967bcbf13ca5.png)

**Comment by andyblac** [comment]
still need help, or can this be closed ?
