### ISSUE TITLE
Shelly 2, roller shutter mode

### ISSUE THREAD

**Issue by bka-git** [mongoose-os-apps/shelly-homekit#40]
I tried to setup up a shelly 2 device in roller shutter mode. But it seems to that both switches are not interlocked.

I used following image:
http://x.x.x.x/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly2.zip 

Did I miss something?

**Comment by andyblac** [comment]
because it is not supposed atm. https://github.com/mongoose-os-apps/shelly-homekit/issues/5
