### ISSUE TITLE
Tips & Tricks

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#400]
If you guys have any "Tips & Tricks" please feel free to add them to the wiki page here https://github.com/mongoose-os-apps/shelly-homekit/wiki/Tips-&-Tricks or in this issue.

Thanks
Andy.

**Comment by bano1971** [comment]
Hello Andy,

Thank you for your answers. I am updating the device and with my former MacBook Air (2014) it worked fine.
Now with my Macbook M1 (2020) it doesn’t anymore…
(Don’t be fooled by the ZIP file, that was the only one that I could select, but the system didn’t accept that) I know I have to select something out of the ZIP file, but everything is uncheckable.
I remembered this one the last time and I unchecked the box.
Still it did not work and I even went deeper into the system and unchecked the box in Archive Utility, which states “ even unpack if possible”. 

Still no effect.

I read your answer about terminal, but that is something I don’t understand.
I know were terminal is and via Github I used it to install a raspberry Pi, but as you describe in the previous e-mail about a script, I don’t even know how to navigate to the extracted file or to the pylon script.
I have no idea how to use the terminal…… ;-(




Is there something else I an do?

Bano
