### ISSUE TITLE
Single button issue

### ISSUE THREAD

**Issue by marienaz** [mongoose-os-apps/shelly-homekit#406]
My alarm is an always openiswitch like my garage door opener... So when I setup shelly 1 as a normal switch (edge or any type, I have o toggle the button 2x before alarm is activated or deactivated.  

If I set the shelly connected to alarm as a "garage door opener it functions 100%, but that in homekit the icon shows garage doors.. Is there any way the garage door opener "settings" as on the homekit firmware can be copied but shows as a switch or something else?

**Comment by andyblac** [comment]
please explain more, have you tried "Momentary" switch type.

**Comment by marienaz** [comment]
> please explain more, have you tried "Momentary" switch type.

I have tried it but still nothing, i can here the switch closing, but it has to open again.. so when i toggle the momentary switch again, then the circuit opens and the alarm is activated.. the alarm works in the same manner as the garage door opener..
the system is looking for a impulse (contacts shorting for a small period of time) .

**Comment by andyblac** [comment]
ok, try setting a auto off to 1 second, that should open the relay after second,

**Comment by marienaz** [comment]
> ok, try setting a auto off to 1 second, that should open the relay after 1 second,

Hi Andy thanx for the help, i tried that allready, but then the switch goes back to the off position so i never know if its really on or off

**Comment by andyblac** [comment]
try with the following

![Screenshot 2021-01-17 at 12 02 18](https://user-images.githubusercontent.com/77936/104839822-a5e04880-58bb-11eb-8130-b6857b2f3e15.jpg)

it should make the switch open = relay closed, switch closed = relay open.

**Comment by marienaz** [comment]
> try with the following
> 
> ![Screenshot 2021-01-17 at 12 02 18](https://user-images.githubusercontent.com/77936/104839822-a5e04880-58bb-11eb-8130-b6857b2f3e15.jpg)
> 
> it should make the switch open = relay closed, switch closed = relay open., it will work best with a push button type switch aka Momentary switch.
> 
> so when you push the button it opens the relay, and when you release it, it closes the relay aka ON.

Nope... then i have to toggle the switch on and off before the alarm is activated... and again on and off to deactivate alarm...

**Comment by andyblac** [comment]
> > try with the following
> > ![Screenshot 2021-01-17 at 12 02 18](https://user-images.githubusercontent.com/77936/104839822-a5e04880-58bb-11eb-8130-b6857b2f3e15.jpg)
> > it should make the switch open = relay closed, switch closed = relay open., it will work best with a push button type switch aka Momentary switch.
> > so when you push the button it opens the relay, and when you release it, it closes the relay aka ON.
> 
> Nope... then i have to toggle the switch on and off before the alarm is activated... and again on and off to deactivate alarm...

and with auto off enabled ?

**Comment by marienaz** [comment]
auto off does not seem to work at all with this settings..

**Comment by andyblac** [comment]
hmmm what time did you set it to ? it starts as soon as you press, so if your still holding after timeout it will not be activated, so do not set to short.

**Comment by andyblac** [comment]
are you using a toggle switch aka rocker? or a push button ?

**Comment by marienaz** [comment]
i use a button similar to the remote of a garage door opener.. but im trying this with the homekit software, so if tried the toggle switch on the firmware web interface and on my iphone.. auto off I tried 500ms and 5 seconds

**Comment by andyblac** [comment]
ok your correct i have just tested auto off with "Activation" does not work, can you set to "Momentary" but leave "Inverted" and "Auto Off". enabled
 try that .

**Comment by marienaz** [comment]
then it works but the switch state changes on and back off again... so i cant see on the homkit icon whether its on or off..  ...
so alarms is off, I click the button and when it auto off's the alarm is actavated, but then the switch still shows off...

**Comment by andyblac** [comment]
ok then create a new ticket, asking for an "Inverted relay" option, and when describing say you would like the HomeKit icon to show as ON when the relay is OPEN (OFF), and HomeKit icon to show as OFF when relay is CLOSED (ON).

**Comment by marienaz** [comment]
The garage door opener function works 100% on the alarm button shelly, but then it shows a garage door in homekit instead of a switch...

**Comment by andyblac** [comment]
> The garage door opener function works 100% on the alarm button shelly, but then it shows a garage door in homekit instead of a switch...

yes, that fuction has those options, you just need then adding to SWITCH. link the issue to this discussion.

**Comment by marienaz** [comment]
Open a ticket? same as this issue ? or where do I open a request or ticket?

**Comment by andyblac** [comment]
> Open a ticket? same as this issue ? or where do I open a request or ticket?

yes sorry, Issue, i call them Tickets as in support tickets. open a new Issue asking for the above. and link it to this issue.

**Comment by andyblac** [comment]
i'll do it for you.

**Comment by andyblac** [comment]
are you using a Shelly1 ?? in low voltage or as dry contact relay ?

**Comment by marienaz** [comment]
Its a shelly 1 yes... on 12v

**Comment by andyblac** [comment]
thought so..

**Comment by andyblac** [comment]
add you support to the issue i created for you.

**Comment by andyblac** [comment]
i'll close this issue,
