### ISSUE TITLE
Automated code review for shelly-homekit

### ISSUE THREAD

**Issue by gingerDevilish** [mongoose-os-apps/shelly-homekit#41]
Hi!
I am a member of the team developing **monocodus** — a service that performs automatic code review of GitHub pull requests to help organizations ensure a high quality of code.
We’ve developed some useful features to the moment, and now we’re looking for early users and feedback to find out what we should improve and which features the community needs the most.

We ran **monocodus** on a pre-created fork of your repo on GitHub https://github.com/monocodus-demonstrations/shelly-homekit/pull/1, and it found one potentially overcomplicated function. I hope that this information will be useful to you and would be happy to receive any feedback here or on my email alena@monocodus.com

Most of all, though, we need some feedback from you on what kinds of checkers could potentially benefit your project, if readily available in a user-friendly manner.

If you want to try our service, feel free to follow the link: https://www.monocodus.com
The service is entirely free of charge for open source projects. Hope you'll like it :)

**Comment by rojer** [comment]
wow, github spam.
