### ISSUE TITLE
PlugS - How to disable LED Light Control

### ISSUE THREAD

**Issue by Spy-1** [mongoose-os-apps/shelly-homekit#411]
How to diable Wi-Fi status light,
or/and disable Power On state light?

**Comment by timoschilling** [comment]
I would like to have the disable Power On state light as well.

**Comment by Spy-1** [comment]
As i wrote above!

**Comment by rojer** [comment]
dup of #342 , please add your support there.

**Comment by andyblac** [comment]
> dup of #342 , please add your support there.

i'm slipping, missed this one 😄
