### ISSUE TITLE
Wiki about development css outdated?

### ISSUE THREAD

**Issue by timoschilling** [mongoose-os-apps/shelly-homekit#414]
I'm right that [this](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development#web-ui-development) information from the wiki is outdated and should be changed?
>make fs/*.gz && \
  mos --port ws://shelly25-test.local/rpc put fs/index.html.gz && \
  mos --port ws://shelly25-test.local/rpc put fs/style.css.gz

It should be
>make fs/*.gz && \
  mos --port ws://shelly25-test.local/rpc put fs/index.html.gz
  
Same for some other places where `fs/style.css.gz` can be removed.

**Comment by rojer** [comment]
updated the wiki, thanks!
