### ISSUE TITLE
Alle shelly Produkte hängen sich nach 26 Tagen auf!

### ISSUE THREAD

**Issue by moda21** [mongoose-os-apps/shelly-homekit#419]
Habe das Problem, nach genau 26 Tagen hängen sich alle Geräte auf.
Das heißt ich muss sie immer per hand über die ip Neustarten.
Könnt ihr eine Funktion in das script machen, damit alle Geräte einmal Neustarten?
Vielen Dank schonmal für die Hilfe!!!!

**Comment by andyblac** [comment]
we would prefer to fix the issue, rather than code work arounds, this sound this bug https://github.com/mongoose-os-apps/shelly-homekit/issues/129 , please contact @rojer if you are will to enable remote bebug logging for him to get logs to see whats happening. i'll close this issue.
