### ISSUE TITLE
other Shelly devices?

### ISSUE THREAD

**Issue by ReCruxo** [mongoose-os-apps/shelly-homekit#421]
Hi to all. The question is mainly for the authors - is there a chance for HomeKit in other Shelly devices?
Regards and sorry for offtopic

**Comment by timoschilling** [comment]
There are already some open issues for requests for Dimmer and RGBW. Take a look and search, if no issue exist for your devise create an explicit request for your devise.

**Comment by andyblac** [comment]
i'll close this, as it has been answered by @timoschilling thx
