### ISSUE TITLE
Update /ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly2.zip

### ISSUE THREAD

**Issue by stefan312312** [mongoose-os-apps/shelly-homekit#424]
I want to have Apple homekit on my shelly dimmer 2.

When I enter the following link x.x.x.x/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly2.zip

I get the error below:
{"status":"updating","has_update":false,"new_version":"20210115-103951/v1.9.4@e2732e05","old_version":"20210115-103951/v1.9.4@e2732e05"}

**Comment by pivale** [comment]
Dimmer and Dimmer 2 are not supported yet, that is probably why it's not working (that link it's for shelly 2)

You can give your support and pitch for tackling it next here:
https://github.com/mongoose-os-apps/shelly-homekit/issues/14

**Comment by andyblac** [comment]
thanks @pivale, closed as duplicate.
