### ISSUE TITLE
Shelly 1 with door sensor

### ISSUE THREAD

**Issue by FXGPV** [mongoose-os-apps/shelly-homekit#430]
Hello, as there is already the garage door with magnetic sensor for informing status, it is possible to add a second option for dor/windows with magnetic sensor? this of course would only repost the current state and not any action per self. Thanks

**Comment by andyblac** [comment]
you can already do this in 2.7.2, 

1st chnage your shelly1 to INPUT MODE to "Detached", and then in the new setting that should appear "INPUT1" chnage HAP TYPE to "Contact Sensor"

![Screenshot 2021-01-24 at 11 07 02](https://user-images.githubusercontent.com/77936/105628472-1693e180-5e35-11eb-9904-14a1ada9e59d.jpg)

it should give you this in HomeKit
![IMG_0455](https://user-images.githubusercontent.com/77936/105628500-375c3700-5e35-11eb-8eae-7c9c46540ff3.jpeg)

**Comment by FXGPV** [comment]
perfect... thank you very much

**Comment by andyblac** [comment]
can i close this issue ?
