### ISSUE TITLE
Shelly 2.5 Rollershutter % wrong

### ISSUE THREAD

**Issue by Marcusg562** [mongoose-os-apps/shelly-homekit#431]
Hi,

I‘ve calibrated my roller shutter several time. But when I say 50% of the window the roller stops at position is 50 but it‘s not in the middle of the window. Even if I calibrate the Shelly more often I‘ve the same issue. My middle is somewhere around position 77.

Any ideas how to solve this?

Best regards and thanks for your great work!
Marcus

**Comment by andyblac** [comment]
duplicate issue, see here https://github.com/mongoose-os-apps/shelly-homekit/issues/204
