### ISSUE TITLE
Issues and Labels - PLEASE READ

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#434]
Guy's when creating an issue, please tag the device with the correct Device Label, and if any other labels seem approiate please tagged them to it.

**Comment by andyblac** [comment]
you can also now click on a label to see ALL issues in that label, please check no issue has been submitted before creating a new issue
thanks

**Comment by rojer** [comment]
nice! thanks Andy!

**Comment by andyblac** [comment]
@everyone please make sure when creating issues, you 1st check no existing exists, by clicking on the label associated with your issue, they maybe be an exisitng issue that could help you out.

for example there are loads of issues on Roller Shutters, as i dont have one or have used the setup i can't help, but it seems to me that the vast majority of them are all about the same issue "Calibration".

can people with Roller Shutters try to help people out in those issues.

oh, and please try to remeber to assing "Labels" when creating issues, 
Thanks.
