### ISSUE TITLE
webUI: relay button control.

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#435]
@ZeevoX  suggestion for webUI for relays On / Off indicator, could you remove the on / off text and align the button up, and turn button GREEN button with ON text when ON, and BLUE button with OFF text, instead on ‘Turn On’ / ‘Turn Off’ ??, I think it would be more intuitive that way
 
This bit
https://files.gitter.im/5f786ddbd73408ce4ff09679/Fsro/Screenshot-2021-01-20-at-20.35.45.jpg

Or even BLUE ON / GREY OFF buttons

**Comment by andyblac** [comment]
@timoschilling  maybe you take this one too ??

**Comment by timoschilling** [comment]
Maybe, if I find some time in the future, I currently working on rgbw2 support.

I think gray isn't a good color for a button, it looks like disabled, maybe green / red.

**Comment by andyblac** [comment]
how does this look ?

![Screenshot 2021-02-11 at 23 12 46](https://user-images.githubusercontent.com/77936/107711134-0b5b0580-6cbf-11eb-91c8-91f1dd5719b2.jpg)

**Comment by ZeevoX** [comment]
Aesthetically looks good for sure, however, not sure this is the clearest in terms of user interface. The status is not "Turn off", and because of the green colour it adds even further confusion as to whether it is currently "turned off" or whether pressing the button should turn it off.
Since this is a binary selection between on/off, could we have something similar to the toggle switches? (also in the screenshot you posted) – we could make them wider with on/off text in the middle to make it super clear.

**Comment by andyblac** [comment]
I'll have a go 😄

**Comment by rojer** [comment]
agree with Timothy here - green to turn off is confusing. and replacing with toggle switch is a good idea as well, i like it.

**Comment by andyblac** [comment]
![Screenshot 2021-02-12 at 00 00 53](https://user-images.githubusercontent.com/77936/107714573-6bed4100-6cc5-11eb-9c72-b465e0efafd9.jpg)

**Comment by andyblac** [comment]
and with power meters
![Screenshot 2021-02-12 at 00 13 42](https://user-images.githubusercontent.com/77936/107715475-3fd2bf80-6cc7-11eb-89e9-44aea3a4fb26.jpg)

**Comment by andyblac** [comment]
or
![Screenshot 2021-02-12 at 00 17 08](https://user-images.githubusercontent.com/77936/107715655-af48af00-6cc7-11eb-8d9d-bfc668942a6e.jpg)

**Comment by pivale** [comment]
I like these last two concepts most.
It's consistent with apple, homekit and with the rest of the UI that already had those toggles.

**Comment by andyblac** [comment]
ye, me too now, atm i have an issue where the status is not auto updating, if i change the power state in HomeKit, it is not auto refresh, works if i manually refresh page.

still learning html5 and JS. 😄

**Comment by andyblac** [comment]
PR submitted https://github.com/mongoose-os-apps/shelly-homekit/pull/486
