### ISSUE TITLE
Unable to Update a single Shelly 1

### ISSUE THREAD

**Issue by freddair** [mongoose-os-apps/shelly-homekit#437]
This Shelly 1 otherwise works alright and my 6 other Shellies (1/1L/1PM) updated just fine...

Log:

315453175 mgos_ota_core.c:587     begin: waiting for user
315469786 mgos_ota_core.c:587     begin: waiting for user
315481456 mgos_ota_core.c:587     begin: waiting for user
315492687 mgos_ota_core.c:587     begin: waiting for user
315502976 mgos_ota_core.c:587     begin: waiting for user
315514114 mgos_ota_core.c:587     begin: waiting for user
315524383 mgos_ota_core.c:587     begin: waiting for user
315534570 mgos_ota_core.c:587     begin: waiting for user
315544756 mgos_ota_core.c:587     begin: waiting for user
315555979 mgos_ota_core.c:587     begin: waiting for user
315569251 mgos_ota_core.c:587     begin: waiting for user
315619663 mgos_ota_core.c:587     begin: waiting for user
315630204 mgos_ota_core.c:587     begin: waiting for user
315642388 mgos_ota_core.c:587     begin: waiting for user
315652660 mgos_ota_core.c:587     begin: waiting for user
315662849 mgos_ota_core.c:587     begin: waiting for user
315673581 mgos_ota_core.c:587     begin: waiting for user
315686509 mgos_ota_core.c:587     begin: waiting for user
315697772 mgos_ota_core.c:587     begin: waiting for user
315708279 mgos_ota_core.c:587     begin: waiting for user
315718474 mgos_ota_core.c:587     begin: waiting for user
315731892 mgos_ota_core.c:587     begin: waiting for user
315743065 mgos_ota_core.c:587     begin: waiting for user
315789163 mgos_ota_core.c:587     begin: waiting for user
315799470 mgos_ota_core.c:587     begin: waiting for user
315811082 mgos_ota_core.c:587     begin: waiting for user
315825272 mgos_ota_core.c:587     begin: waiting for user
315835495 mgos_ota_core.c:587     begin: waiting for user
315845701 mgos_ota_core.c:587     begin: waiting for user
315856261 mgos_ota_core.c:587     begin: waiting for user
315866476 mgos_ota_core.c:587     begin: waiting for user
315877988 mgos_ota_core.c:587     begin: waiting for user
315888414 mgos_ota_core.c:587     begin: waiting for user
315898970 mgos_ota_core.c:587     begin: waiting for user
315909166 mgos_ota_core.c:587     begin: waiting for user
315920393 mgos_ota_core.c:587     begin: waiting for user
315966090 mgos_ota_core.c:587     begin: waiting for user

![image](https://user-images.githubusercontent.com/63143560/105810154-b921a100-5faa-11eb-8dcf-fa7089d7d7f5.jpeg)![image](https://user-images.githubusercontent.com/63143560/105810165-bd4dbe80-5faa-11eb-9be4-773c2d1dc964.jpeg)

**Comment by andyblac** [comment]
i'll leave this one for @rojer

**Comment by rojer** [comment]
device won't accept update if it's in "doing something" mode. that includes auto-off timer. do you use auto-off and is it active at this time?

**Comment by freddair** [comment]
Yes this Shelly uses auto-off timer and obviously it was the issue. Thanks for pointing that out. I wasn't aware that the timer was still active even after reboots... maybe it would be helpful if we would get a corresponding warning / error message when trying to start an update. Thank you @rojer !

**Comment by timoschilling** [comment]
Maybe we should disable the update button with a note if auto-off is on.

**Comment by freddair** [comment]
Also it would be helpful to expose the countdown timer visible in the switch auto-off section

**Comment by andyblac** [comment]
> Maybe we should disable the update button with a note if auto-off is on.

imo, no, only if auto-off is 'running', just having the option enabled does not harm, most of my devcies have it enabled, and i have never run into an issue updating.

**Comment by timoschilling** [comment]
sorry if it's running, updated my post

**Comment by andyblac** [comment]
@freddair would you like to create a issue for this feature request ?, i will then close this issue.

**Comment by freddair** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/issues/444

Done, this may be closed.
