### ISSUE TITLE
Shelly 2.5 as roller shutter - calibration doesn´t work propper

### ISSUE THREAD

**Issue by joha1971** [mongoose-os-apps/shelly-homekit#445]
Hello, this is my 3rd shelly 2.5 which i want to use as roller shutter in homekit. The firts two are working very well with the SW version 2.7.1. The calibration ran well without issues. 
Now i wanted to install the 3rd shelly 2.5 which has issues in the calibration session. This shelly downloaded the SW version 2.7.3. This is my issue:
If i start the calibration, the shelly will NOT close the roller. It goes a few centimeter up and down, up and down. A couple of times. The time frame which will be identified is approx. 1 sec. I have the feeling that the calibration starts with the wrong relay output. First up and then down. But my feeling can be wrong.
My attention was to downgrade the SW to 2.7.1 because the other two are working well with this SW. But unfortunately this wasn´t successful. 
With the original SW it works. Now i run the roller shutter as 2 switcher in homekit.
Is it a software bug? I need help. Thank you
regards Jochen

**Comment by joha1971** [comment]
Additional information: Here are my log. The calibration mode worls always for 1.08 sec. Then he is ready. That menas that the roller never shuts down completly.

132383880 shelly_output.cpp:56    Output 1: off -> on (move)
132393452 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
132420113 shelly_hap_window_c:544 P = 0.00 -> 0.00
132430119 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
132622250 shelly_hap_window_c:331 WC 1: Cur pos 7.31 -> 16.56, P = 0.00
132689663 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
133021441 shelly_output.cpp:56    Output 1: on -> off (moving)
133031458 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
133140532 mgos_sys_config.c:232   Loading conf2.json
133164370 mgos_sys_config.c:232   Loading conf3.json
133297926 mgos_sys_config.c:174   Saved to conf9.json
133309157 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
133327187 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
133425340 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
133524520 shelly_output.cpp:56    Output 2: off -> on (move)
133534613 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
133624732 shelly_hap_window_c:544 P = 0.00 -> 0.00
133634742 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
133676832 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
133725979 shelly_output.cpp:56    Output 2: on -> off (moving)
133735961 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
133845826 mgos_sys_config.c:232   Loading conf2.json
133869680 mgos_sys_config.c:232   Loading conf3.json
134004459 mgos_sys_config.c:174   Saved to conf9.json
134015708 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
134032953 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
134131014 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
134230269 shelly_output.cpp:56    Output 1: off -> on (move)
134240310 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
134330571 shelly_hap_window_c:544 P = 0.00 -> 0.00
134340582 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
134431633 shelly_output.cpp:56    Output 1: on -> off (moving)
134441659 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
134550886 mgos_sys_config.c:232   Loading conf2.json
134574706 mgos_sys_config.c:232   Loading conf3.json
134709491 mgos_sys_config.c:174   Saved to conf9.json
134720738 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
134740507 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
134761706 mgos_mongoose.c:66      New heap free LWM: 17264
134777287 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
134875259 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
134974482 shelly_output.cpp:56    Output 2: off -> on (move)
134984529 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
135074810 shelly_hap_window_c:544 P = 0.00 -> 0.00
135084842 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
135175915 shelly_output.cpp:56    Output 2: on -> off (moving)
135186895 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
135294928 mgos_sys_config.c:232   Loading conf2.json
135318774 mgos_sys_config.c:232   Loading conf3.json
135452655 mgos_sys_config.c:174   Saved to conf9.json
135463912 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
135481622 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
135579630 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
135678919 shelly_output.cpp:56    Output 1: off -> on (move)
135689965 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
135706014 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
135779219 shelly_hap_window_c:544 P = 0.00 -> 0.00
135789255 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
135881678 shelly_hap_window_c:331 WC 1: Cur pos 46.16 -> 53.47, P = 1.03
135890815 shelly_output.cpp:56    Output 1: on -> off (moving)
135900819 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
135998878 mgos_sys_config.c:232   Loading conf2.json
136022765 mgos_sys_config.c:232   Loading conf3.json
136156979 mgos_sys_config.c:174   Saved to conf9.json
136168253 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
136185967 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
136284055 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
136383275 shelly_output.cpp:56    Output 2: off -> on (move)
136393404 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
136483513 shelly_hap_window_c:544 P = 0.00 -> 0.00
136493551 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
136584631 shelly_output.cpp:56    Output 2: on -> off (moving)
136594655 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
136619377 shelly_main.cpp:543     Up 136.61, HAP 0/0/12 ns 0, RAM: 21528/37616; st 57; 4.1: c:1 mp:0.00 mt_ms:1081 cp:46.07 tp:50.00 lemd:0 lhmd:0
136675504 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
136718669 mgos_sys_config.c:232   Loading conf2.json
136742543 mgos_sys_config.c:232   Loading conf3.json
136876907 mgos_sys_config.c:174   Saved to conf9.json
136888185 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
136907366 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
137005388 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
137104606 shelly_output.cpp:56    Output 1: off -> on (move)
137114954 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
137204902 shelly_hap_window_c:544 P = 0.00 -> 0.00
137214952 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
137305992 shelly_output.cpp:56    Output 1: on -> off (moving)
137316074 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
137424613 mgos_sys_config.c:232   Loading conf2.json
137448487 mgos_sys_config.c:232   Loading conf3.json
137582865 mgos_sys_config.c:174   Saved to conf9.json
137594150 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
137638489 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
137679102 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
137736543 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
137836463 shelly_output.cpp:56    Output 2: off -> on (move)
137847448 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
137935979 shelly_hap_window_c:544 P = 0.00 -> 0.00
137946038 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
138037177 shelly_output.cpp:56    Output 2: on -> off (moving)
138048163 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
138155891 mgos_sys_config.c:232   Loading conf2.json
138179773 mgos_sys_config.c:232   Loading conf3.json
138342616 mgos_sys_config.c:174   Saved to conf9.json
138354844 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
138372972 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
138471785 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
138570260 shelly_output.cpp:56    Output 1: off -> on (move)
138580324 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
138670416 shelly_hap_window_c:544 P = 0.00 -> 0.00
138680484 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
138723546 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
138771646 shelly_output.cpp:56    Output 1: on -> off (moving)
138781718 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
138890234 mgos_sys_config.c:232   Loading conf2.json
138915058 mgos_sys_config.c:232   Loading conf3.json
139049723 mgos_sys_config.c:174   Saved to conf9.json
139061441 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
139104383 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
139202548 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
139301725 shelly_output.cpp:56    Output 2: off -> on (move)
139311809 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
139402132 shelly_hap_window_c:544 P = 0.00 -> 0.00
139413146 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
139503153 shelly_output.cpp:56    Output 2: on -> off (moving)
139513207 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
139621369 mgos_sys_config.c:232   Loading conf2.json
139646207 mgos_sys_config.c:232   Loading conf3.json
139814115 mgos_sys_config.c:174   Saved to conf9.json
139825415 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
139843571 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
139869725 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
139967607 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
140066915 shelly_output.cpp:56    Output 1: off -> on (move)
140078064 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
140167231 shelly_hap_window_c:544 P = 0.00 -> 0.00
140177310 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
140368047 shelly_output.cpp:56    Output 1: on -> off (moving)
140379143 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
140491120 mgos_sys_config.c:232   Loading conf2.json
140515031 mgos_sys_config.c:232   Loading conf3.json
140645124 mgos_sys_config.c:174   Saved to conf9.json
140657378 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
140676730 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
140731095 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
140829704 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
140928578 shelly_output.cpp:56    Output 2: off -> on (move)
140938657 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
141029140 shelly_hap_window_c:544 P = 0.00 -> 0.00
141039226 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
141131065 shelly_hap_window_c:331 WC 1: Cur pos 58.19 -> 50.88, P = 0.00
141229900 shelly_output.cpp:56    Output 2: on -> off (moving)
141240012 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
141352876 mgos_sys_config.c:232   Loading conf2.json
141376784 mgos_sys_config.c:232   Loading conf3.json
141531305 mgos_sys_config.c:174   Saved to conf9.json
141542627 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
141560674 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
141658732 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
141676379 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
141758005 shelly_output.cpp:56    Output 1: off -> on (move)
141769129 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
141858741 shelly_hap_window_c:544 P = 0.00 -> 0.00
141897310 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
142059266 shelly_output.cpp:56    Output 1: on -> off (moving)
142070351 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
142182518 mgos_sys_config.c:232   Loading conf2.json
142206431 mgos_sys_config.c:232   Loading conf3.json
142336733 mgos_sys_config.c:174   Saved to conf9.json
142349000 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
142388528 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
142486829 shelly_hap_window_c:322 WC 1: State: idle -> move (0 -> 20)
142585876 shelly_output.cpp:56    Output 2: off -> on (move)
142596102 shelly_hap_window_c:322 WC 1: State: move -> rampup (20 -> 22)
142675419 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
142697356 shelly_hap_window_c:544 P = 0.00 -> 0.00
142708410 shelly_hap_window_c:322 WC 1: State: rampup -> moving (22 -> 23)
142788544 shelly_hap_window_c:342 WC 1: Tgt pos 50.00 -> 49.31 (fixup)
142797733 shelly_output.cpp:56    Output 2: on -> off (moving)
142807772 shelly_hap_window_c:322 WC 1: State: moving -> stop (23 -> 24)
142910034 mgos_sys_config.c:232   Loading conf2.json
142933948 mgos_sys_config.c:232   Loading conf3.json
143092289 mgos_sys_config.c:174   Saved to conf9.json
143103620 shelly_hap_window_c:322 WC 1: State: stop -> stopping (24 -> 25)
143121000 shelly_hap_window_c:322 WC 1: State: stopping -> idle (25 -> 0)
143680278 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
144619922 shelly_main.cpp:543     Up 144.61, HAP 0/0/12 ns 0, RAM: 20480/37616; st 57; 4.1: c:1 mp:0.00 mt_ms:1081 cp:49.31 tp:49.31 lemd:0 lhmd:0
145676870 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
146692499 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
147695476 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
148672787 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
149696073 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
150675876 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
151486761 mg_rpc.c:305            Shelly.SetConfig via WS_in 192.168.178.86:57677
151496617 shelly_rpc_service.:223 SetConfig ok, 0
151529561 mgos_sys_config.c:232   Loading conf2.json
151553493 mgos_sys_config.c:232   Loading conf3.json
151685091 mgos_sys_config.c:174   Saved to conf9.json
152619389 shelly_main.cpp:543     Up 152.61, HAP 0/0/12 ns 0, RAM: 21568/37616; st 57; 4.1: c:1 mp:0.00 mt_ms:1081 cp:49.31 tp:49.31 lemd:0 lhmd:0
153103093 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
153686379 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
154690093 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
155671104 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
156674697 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
157686260 mg_rpc.c:305            Shelly.GetInfo via WS_in 192.168.178.86:57677
158582616 mgos_http_server.c:180  0x3fff667c HTTP connection from 192.168.178.86:57703
158595219 mgos_http_server.c:180  0x3fff67ec HTTP connection from 192.168.178.86:57704
161745621 shelly_debug.cpp:203    Tailing
168618690 shelly_main.cpp:543     Up 168.61, HAP 0/0/12 ns 0, RAM: 21272/37616; st 57; 4.1: c:1 mp:0.00 mt_ms:1081 cp:49.31 tp:49.31 lemd:0 lhmd:0
176618709 shelly_main.cpp:543     Up 176.61, HAP 0/0/12 ns 0, RAM: 21272/37616; st 57; 4.1: c:1 mp:0.00 mt_ms:1081 cp:49.31 tp:49.31 lemd:0 lhmd:0
184618620 shelly_main.cpp:543     Up 184.61, HAP 0/0/12 ns 0, RAM: 21272/37616; st 57; 4.1: c:1 mp:0.00 mt_ms:1081 cp:49.31 tp:49.31 lemd:0 lhmd:0

**Comment by joha1971** [comment]
Hi all,
is noboby able to support my issue? Now i have replaced my shelly 2.5 against a new one. But the issue is still the same. The curton down mode works only for 1,08 sec. and shelly thinks it´s closed, which is not. One additional information. I have two roller shuter motor connected to one switch. Could this be the problem? May be that the current flow is too high?
Need support. I am lost. Thank you.

**Comment by andyblac** [comment]
have checked the other roller shutter isues, maybe they could help ?

**Comment by joha1971** [comment]
Of course you are right. I saw that there is already an open issue with the same issue. I also saw that there is a request for an extention to use the roller shutter with typing in a calibration time manually. now i will wait until this issue is fixed and a new firmware will be released. Thank you

**Comment by andyblac** [comment]
ok, i'll close this issue as duplicate. thx
