### ISSUE TITLE
Timer functionality (staircase timer)

### ISSUE THREAD

**Issue by amaridev** [mongoose-os-apps/shelly-homekit#45]
I use my shelly as staircase timer. Light is turned on with activation and turned off after a preset time. This setting is available in the stock firmware. I'd be really glad if this feature could be added. :)

**Comment by andyblac** [comment]
there is a pull request that adds this feature, we are just waiting for it to be pulled.

**Comment by rojer** [comment]
yeah, this looks like #11 
i need to have another look at the PR and we should be there.

**Comment by andyblac** [comment]
> yeah, this looks like #11
> i need to have another look at the PR and we should be there.

thanks looking forward to it.
