### ISSUE TITLE
Shelly2 Auto on

### ISSUE THREAD

**Issue by Marcusg562** [mongoose-os-apps/shelly-homekit#454]
Hey guys, has anyone the same issue? Every morning my Shelly turn on at an specific time. There is no HomeKit automation set and the initial stage is for both switches off. Any ideas?

**Comment by simonfield76** [comment]
Could you give more details?



Inviato da iPhone

Il giorno 31 gen 2021, alle ore 09:45, Marcusg562 <notifications@github.com> ha scritto:

﻿

Hey guys, has anyone the same issue? Every morning my Shelly turn on at an specific time. There is no HomeKit automation set and the initial stage is for both switches off. Any ideas?

**Comment by Marcusg562** [comment]
What exactly do you wanna know? 

HAP Type: Switch
Input Mode: Toggle
Inverted input: off
Initial State: off
Auto Off: off

Version: 2.7.3 (build 20210124-130626/2.7.3-g883914a-master)

**Comment by rojer** [comment]
there is nothing in the device that can possibly cause this, there is no scheduling functionality at all.

**Comment by andyblac** [comment]
He has a poltergeist, playing games with him 😄

**Comment by Marcusg562** [comment]
> there is nothing in the device that can possibly cause this, there is no scheduling functionality at all.
> 
> if you unpair the device from homekit, does it still do it?

I will test it tomorrow - since this only happens in the morning

**Comment by Marcusg562** [comment]
It seems as this issue was caused by an Eve Button in my Homekit
