### ISSUE TITLE
Homekit shows Shelly 2.5 as a bridge

### ISSUE THREAD

**Issue by petergPRG** [mongoose-os-apps/shelly-homekit#455]
Since update to 2.73 my Homekit shows a shelly2.5 as a bridge. Correct?

**Comment by simonfield76** [comment]
Always been recognized as bridge at least from my first installation with 2.6

Inviato da iPhone

Il giorno 31 gen 2021, alle ore 10:03, petergPRG <notifications@github.com> ha scritto:

﻿

Since update to 2.73 my Homekit shows a shelly2.5 as a bridge. Correct?

**Comment by andyblac** [comment]
yes, correct behaviour.

**Comment by rojer** [comment]
yes, bridge accessory configuration is used as a means of exposing independent services (such as independent detached inputs). there is no bridging taking place, as such.
