### ISSUE TITLE
Problem using Shelly 2.5 and 1 outside my house.

### ISSUE THREAD

**Issue by theflexa1** [mongoose-os-apps/shelly-homekit#457]
Hello to everyone.

I can´t reach my Shllies from 4G... I can with wi-fi but I cannot reach them by 4G....

Is there something I am doing wrong?

**Comment by andyblac** [comment]
do you have a homekit hub ?

**Comment by theflexa1** [comment]
I have an Ipad, an Apple TV and a Homepod....

The strange thing... is that I set another Shelly 1 1 month ago... and i works with 4G...
Really rare...

**Comment by andyblac** [comment]
should be no reason why then, check in home app that at least one hub is connected,

**Comment by theflexa1** [comment]
I´ve already check that!

Conected is the status, but... I cannot think about what it´s wrong. In the photo you can see two Shelly 1. One instaled 1 month ago, the other today. Same process... (I think I did the same...)

![Captura de pantalla 2021-01-31 a las 17 10 13](https://user-images.githubusercontent.com/78312412/106390130-3142f900-63e7-11eb-9df8-65937780809b.png)

**Comment by theflexa1** [comment]
The only strange thing I have done is changing the name of the device....
![Captura de pantalla 2021-01-31 a las 17 15 04](https://user-images.githubusercontent.com/78312412/106390281-e5448400-63e7-11eb-8d69-9171037f6604.png)
![Captura de pantalla 2021-01-31 a las 17 14 55](https://user-images.githubusercontent.com/78312412/106390283-e5dd1a80-63e7-11eb-8331-1edb2f29ded3.png)

**Comment by theflexa1** [comment]
No, this last thing is not the problem.... I´ve just tested... no way to make it work outside the wi-fi :(

**Comment by theflexa1** [comment]
More info:

I hace reset the firmware to original. The shelly app let me control the Shelly 1 and 2.5 from the app runing 4G. So the issue must be on the 2.7.3 of the new firmware of homekit...

If someone know how to fix this... just write hehe

**Comment by andyblac** [comment]
can you enable debug log please, then reboot device, open log clicking on log link in webui on a pc/Mac, wait few mins for clients and hubs to connect. then try on 4g and copy paste log to a file and post here.

**Comment by theflexa1** [comment]
The debug log... where can I access that in the homekit software?

**Comment by theflexa1** [comment]
![Captura de pantalla 2021-01-31 a las 21 03 25](https://user-images.githubusercontent.com/78312412/106396373-c655ea00-6407-11eb-9816-057ac039f368.png)
This is the log you ask me :)

**Comment by simonfield76** [comment]
In the web server pointing the ip address of the shelly in the browser

Inviato da iPhone

Il giorno 31 gen 2021, alle ore 20:56, theflexa1 <notifications@github.com> ha scritto:

﻿

The debug log... where can I access that in the homekit software?

**Comment by andyblac** [comment]
look for the ip of the main hub, does it get a connection ?

**Comment by theflexa1** [comment]
> look for the ip of the main hub, does it get a connection ?

The main hub... you mean the Apple TV?

**Comment by andyblac** [comment]
> > look for the ip of the main hub, does it get a connection ?
> 
> The main hub... you mean the Apple TV?

tbh i wpuld disable homekit on appletv imo you will get nothing but problems, as you said you have homepod use that.

**Comment by theflexa1** [comment]
I´m going to test that. ;)


> > > look for the ip of the main hub, does it get a connection ?
> > 
> > 
> > The main hub... you mean the Apple TV?
> 
> tbh i would disable homekit on appletv imo you will get nothing but problems, as you said you have homepod use that.

**Comment by andyblac** [comment]
here is mine
![IMG_0463](https://user-images.githubusercontent.com/77936/106396629-0cf41600-6401-11eb-9a68-aea8c40ded81.jpeg)

**Comment by andyblac** [comment]
> I´m going to test that. ;)
> 
> > > > look for the ip of the main hub, does it get a connection ?
> > > 
> > > 
> > > The main hub... you mean the Apple TV?
> > 
> > 
> > tbh i would disable homekit on appletv imo you will get nothing but problems, as you said you have homepod use that.

it can take 5 mins for a hub to change status, so give it time after disabling appletv, check in home app for a disabled status, then find the connected hub ip, make sure it gets a connection in the shelly log.

**Comment by andyblac** [comment]
can this be closed ?

**Comment by theflexa1** [comment]
Yes ! It was the apple tv

Atentamente, 

Álvaro Domínguez.

**Comment by ma-jkl** [comment]
Hi, can you tell me how did you fix it? I have the same issue. Michal
