### ISSUE TITLE
Shelly1 no response in Homekit

### ISSUE THREAD

**Issue by petergPRG** [mongoose-os-apps/shelly-homekit#46]
I have included a total of three Shelly1 in HomeKit. I have assigned a fixed IP to all devices and all devices are reachable under their IP. Two run without problems with SW version 1.3.3 ( 20200217-232831/1.3.3-g518dd07-master )
One Shelly always loses contact in HomeKit. This Shelly has the SW version 1.7.0 (20200331-194631/1.7.0-ga963921-master)
When I reboot this Shelly via the web browser he is accessible in HomeKit. After the first (sometimes second) switching via HomeKit the connection is lost.
Is there a way to flash this shelly to the 1.3.3 version?

**Comment by andyblac** [comment]
download the 1.3.3 FW from releases, open the web page on the shelly scroll down to Firmware, chose the FW zip file and update.

**Comment by petergPRG** [comment]
Thanks for answer. I tried this, but when I install the shelly HomeKit "flash" with the command: Shelly1: http://A.B.C.D/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip
I have again the 1.7.0

**Comment by andyblac** [comment]
ye it grabs the latest he has hosted, that diff to git builds

**Comment by andyblac** [comment]
get fw from here https://github.com/mongoose-os-apps/shelly-homekit/releases to upload manually.

**Comment by petergPRG** [comment]
Thx Andy, I downloaded the file, but I can't upload it to the shelly over the web interface. any Idea?

**Comment by andyblac** [comment]
should be ale to 
![Screenshot 2020-04-12 at 15 52 14](https://user-images.githubusercontent.com/77936/79071808-96e9bb80-7cd5-11ea-89e2-59ec020625b2.jpg)

see at bottom of page, click on upload, choose zip file click ok

**Comment by petergPRG** [comment]
yep, successful , thanks a lot

**Comment by andyblac** [comment]
np, glad you managed.

**Comment by RedPlumber** [comment]
Same issue here, after updating few original shelly to fw 1.9 I often lose connection to the device in homekit. That's very frustrating. I updated one of the devices to 1.9.1 but it does not work.

**Comment by andyblac** [comment]
is this still an issue ?

**Comment by rojer** [comment]
this predates all the fixes that went into 2.0, @petergPRG please upgrade and reopen if this is still an issue.
