### ISSUE TITLE
Previous firmware download place?

### ISSUE THREAD

**Issue by ursusHU** [mongoose-os-apps/shelly-homekit#460]
Where can I found the previous version 2.7.2? Sorry, if it is obvious, but I was looking for it but couldn’t find it.
The restart feature was more reliable for me in that version.

**Comment by rojer** [comment]
attached to github releases - https://github.com/mongoose-os-apps/shelly-homekit/releases
or on my server here - http://rojer.me/files/shelly/

**Comment by andyblac** [comment]
or github https://github.com/mongoose-os-apps/shelly-homekit/releases
