### ISSUE TITLE
Request to extend the Shelly range, No Issue

### ISSUE THREAD

**Issue by joha1971** [mongoose-os-apps/shelly-homekit#463]
Dear developers,
i have a request to extent the range of shelly. What about the shelly DW? This is the door/windows contact to control the status. I can imagine that a lot of users are interested in. What do you think? How complex is it for you? Hope it´s not too complex.

**Comment by andyblac** [comment]
hi, nice idea, but already suggested, add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/124
