### ISSUE TITLE
Add option to only active the Auto Off, if light was turned on via REST API

### ISSUE THREAD

**Issue by socialsubs** [mongoose-os-apps/shelly-homekit#466]
Hi, 
II know this request is similar to [#209](https://github.com/mongoose-os-apps/shelly-homekit/issues/209), but I would like to know whether it is not easier, in this case, to enter an auto-off timer directly into the URL of the REST API command.

I'd like to use the new "Shelly Motion" sensor to turn on the lights when sensor detects motion and set an auto-off timer in the same REST API command of a Shelly-Homekit switch.

**Comment by andyblac** [comment]
i'll close this, and add it to the other issue, just to mke it easier to follow.

**Comment by andyblac** [comment]
@socialsubs i have updated #209 please add your supported to it thx.
