### ISSUE TITLE
Improve update  mode

### ISSUE THREAD

**Issue by AnakinSpain** [mongoose-os-apps/shelly-homekit#467]
Will be possible to improve the way to update. I am not usually turn on my mac. 

Could it be possible? 

Maybe from one shelly to others...

**Comment by andyblac** [comment]
sorry what do you mean?

**Comment by andyblac** [comment]
from stock to this firmware ? or update this firmware to latest ?, all can be done on your phone.

**Comment by AnakinSpain** [comment]
Update to latest. 

From my phone I enter every static IP in my browser and update from web gui. But I have 15 shellys

**Comment by andyblac** [comment]
unforunatly there is no other way without your mac, with your mac there is a script that update all of them at once.

**Comment by andyblac** [comment]
ok you could also try it on https://pyto.app, i managed to get it to run

![IMG_0481](https://user-images.githubusercontent.com/77936/107126404-9dba6e00-68a7-11eb-808d-6ca389264db8.jpeg)

it not free but only 2.99 for basic version, and free for 3 day to trial it.

**Comment by andyblac** [comment]
i'll close this issue, as not much can be done.
