### ISSUE TITLE
Does this firmware work with shelly uni?

### ISSUE THREAD

**Issue by Ioan-Popovici** [mongoose-os-apps/shelly-homekit#479]
I want to make a temperature and humidity switch with two channels out of it.
Is it possible to make it homekit compatible?

**Comment by timoschilling** [comment]
Not at the moment but I will work on it in the next weeks.

**Comment by Ioan-Popovici** [comment]
Thanks. No rush, I can use 2 shelly 1PMs, this was just an interesting idea. I want to control the temp and humidity in my fridge. I also have the shelly temp and humidity sensor so I can use that.

Thank you for you awesome work!

**Comment by juanfal** [comment]
It would be fantastic shelly-homekit would work with shellyuni.  I've been struggling with shelly1 to read a LED from a AirConditioning wired remote control without interference and its just what shellyuni can do out of the box!!!

**Comment by one4many** [comment]
Is it ready yet? ;-)
I would love to see support for the Uni as I have a few projects lined up for the garden (valves for the sprinkler etc).

**Comment by rojer** [comment]
nope, not yet

**Comment by tohmc** [comment]
Hi, it would be great if the UNI will have the garagedoor Funktion like Shelly 2.5.

many news on the implementation?

**Comment by juanfal** [comment]
It would be really nice to have at least a template for it.  I understand it is quite open, and you can do crazy and not standard HomeKit recognisable things with it, but it is a pity having it out of the game.  If there were a template using it as a simple switch, say, and leaving comments where to tickle with it… It would be more than great

**Comment by BadWolf42** [comment]
Hi, any news regarding this issue?
Thanks for your great work, I appreciate!

**Comment by hfagelnour** [comment]
Up, plssssss

**Comment by daitarn31974** [comment]
Interested too but it seems stuck

**Comment by chef76** [comment]
Me toi

**Comment by antaron1973** [comment]
@timoschilling: The Shelly Uni is really the only Shelly I can use for my use case. The HomeKit firmware is an extraordinary achievement and works great with my other Shelly 1. Is it possible also to support Shelly Uni?
Thanks, Maik.

**Comment by MongooseFan** [comment]
I've purchased a Shelly UNI in order to interface with a Somfy IO transmitter (Izymo Transmitter) via dry contacts. It would be great if you guys supported the UNI! Thanks!

**Comment by chef76** [comment]
You can use the dry contacts of the uni by Homekit Automation with http-request. Works perfekt!

**Comment by MongooseFan** [comment]
Thanks, chef76. Could you provide more information? I don't understand what you mean exactly...   😕

**Comment by chef76** [comment]
https://www.shelly-support.eu/forum/index.php?thread/775-collection-of-http-commands/

You can create an dummy-switch with hkknx and trigger an homekit automation, that calls the http request
