### ISSUE TITLE
Suggestions for improving the Shelly 1 with Push button 

### ISSUE THREAD

**Issue by Cyrille556** [mongoose-os-apps/shelly-homekit#485]
#Hello ,
I am using a Shelly1 with two push buttons with a 5 minute Auto OFF, how can I use the push buttons only to turn on the light and restart the 5 minutes of auto OFF?

**Comment by andyblac** [comment]
change input mode to activation

![Uploading Screenshot 
2021-02-12 at 14.51.09.jpg…]()

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Switch-Settings
• Activation: use it for motion sensor, any input turns "ON" and resets Auto OFF timer.

**Comment by Cyrille556** [comment]
thank you so much! it works very well !
