### ISSUE TITLE
update badge does not auto update correct status

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#487]
the update badge does not auto show hide on auto refresh
Ie

1. when on 2.7.2
2. open webUI
3. used tools/flash-shelly.py to update, but you can confirm by have 2 webui windows open, one to update, one to show status bug.
4. after device reboot
5. webui still shows “update”
6. refresh page
7. update badge gone

**Comment by andyblac** [comment]
on reading the update code it seem it was done this way on purpose, @ZeevoX any reason that you only check once on manual page load ?

**Comment by ZeevoX** [comment]
otherwise we were pinging rojer.me every second, it was slowing the autorefresh service down

**Comment by andyblac** [comment]
ah ok, makes sense, i'll close this one then

**Comment by rojer** [comment]
i think it makes sense to perform an update check if the version reported by the device has changed.
i.e. if Shelly.GetInfo returns a version different from the one that it was on the first update, UI should reset the update check timestamp and reload itself

**Comment by andyblac** [comment]
@rojer like this https://github.com/mongoose-os-apps/shelly-homekit/pull/496

**Comment by timoschilling** [comment]
@andyblac this is no longer reproducible for me. I think it was fixed as someone implemented a UI reload after device reboot. I would like to close this and the related pr, what do you think?

**Comment by andyblac** [comment]
@timoschilling sure of you think it's fixed.
