### ISSUE TITLE
SHELLY 2.5 DUAL HOMEKIT SETTINGS

### ISSUE THREAD

**Issue by bolagnaise** [mongoose-os-apps/shelly-homekit#49]
I am using a shelly 2.5 on a dual light switch in my lounge room. The problem i have is that you can only assign both switches to a single room, and one switch is for my outdoor light. It would be awesome if we could assign each switch their own homekit code and add them as individual switches for individual rooms in the home app.

**Comment by andyblac** [comment]
reported here https://github.com/mongoose-os-apps/shelly-homekit/issues/18

**Comment by bolagnaise** [comment]
Ok, so i guess my only option is to add another shelly 1 to the circuit to control the outdoor light. Thanks for info.

**Comment by rojer** [comment]
yeah, that's #18. not so easy to solve unfortunately, due to lack of memory.
