### ISSUE TITLE
Improve Development Documentation

### ISSUE THREAD

**Issue by juangamnik** [mongoose-os-apps/shelly-homekit#493]
I would like to add some developer documentation  describing the architecture in the wiki a llittlebit (so that one does not have to read the complete mongoose os docs but gets a good idea of how it works).

@rojer what do you think?

**Comment by andyblac** [comment]
sure go for it. any help maintaining wiki i'd be greafull.

**Comment by juangamnik** [comment]
I wait for the frontend rewrite with this too as this will influence the documentation.

**Comment by louis49** [comment]
I am very interested and could make contributions. I am new to home automation and with MOS. Do you have a list of things to cover before you start to be able to help yourself?
Thank you

**Comment by andyblac** [comment]
start here https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development
