### ISSUE TITLE
Change Web UI to use WebSocket for RPC

### ISSUE THREAD

**Issue by rojer** [mongoose-os-apps/shelly-homekit#50]
Mongoose OS supports RPC over WebSocket.
We should open a channel and keep it open to make RPC more efficient. This will also allow regular updates of power readings and other status without sending HTTP request each time.

**Comment by rojer** [comment]
challenges:
 * ensure connection is re-established as necessary (e.g. when device reboots)
 * when applying new state updates, do not stomp over pending changes to fields made by the user.

**Comment by rojer** [comment]
https://github.com/mongoose-os-libs/wifi-setup-web-ui can be used for inspiration

**Comment by shellyrgbw** [comment]
> Mongoose OS supports RPC over WebSocket.
> 
> We should open a channel and keep it open to make RPC more efficient. This will also allow regular updates of power readings and other status without sending HTTP request each time.

**Comment by shellyrgbw** [comment]
> https://github.com/mongoose-os-libs/wifi-setup-web-ui can be used for inspiration

**Comment by juancitomadrid** [comment]
I can work in UI.
Let me know needs.

**Comment by rojer** [comment]
good job @ZeevoX thank you very much!
UX is much better now

**Comment by andyblac** [comment]
@rojer any chance of beta release ?

**Comment by rojer** [comment]
i don't intend to cut 2.8 just for this, so we won't call it a beta, but it makes sense to cut a build that can be tested.
i think we should just have latest build always available

**Comment by rojer** [comment]
i filed an issue for this - https://github.com/mongoose-os-apps/shelly-homekit/issues/379

meanwhile, i've manually cut a one-off - http://rojer.me/files/shelly/2.7.0-latest/
