### ISSUE TITLE
Reverse status in HomeKit

### ISSUE THREAD

**Issue by kamilpop** [mongoose-os-apps/shelly-homekit#507]
I have several Shelly 2.5 installed as blind control on the window and a sun awning. In HomeKit, these are displayed as active or open when retracted. But this should be inactive (gray). How can I change it?

![ED18C038-E596-48D2-AFFB-B40C8F890EED](https://user-images.githubusercontent.com/79114494/107991865-c80ed880-6fd7-11eb-9cb6-7db485020a72.png)

![B8CF25A7-BF56-4F35-B0DE-D29A45FDA0F0](https://user-images.githubusercontent.com/79114494/107991946-f7254a00-6fd7-11eb-8c3a-e73804c3da25.png)
![8968076E-1618-42AD-B946-FE829D405DA5](https://user-images.githubusercontent.com/79114494/107991952-f987a400-6fd7-11eb-9c3b-f19e7cefd8b1.png)

**Comment by andyblac** [comment]
have you tried swap outputs ?

**Comment by jankornblum** [comment]
This is great! Thanks for this really excellent and helpful firmware at all :)
