### ISSUE TITLE
URLs are offline

### ISSUE THREAD

**Issue by denbec** [mongoose-os-apps/shelly-homekit#522]
http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip produces a 404.

**Comment by rojer** [comment]
seems to be working just fine for me, and i can see requests in the logs from other users.
can you run `curl -v http://rojer.me/files/shelly/shelly-homekit-Shelly1.zip` from the terminal and paste output here?

**Comment by timoschilling** [comment]
I can confirm a 404

**Comment by rojer** [comment]
ah, ipv6... ok, will take a look

**Comment by timoschilling** [comment]
Yes it's IP6 problem, `curl --ipv4` works

**Comment by rojer** [comment]
ok, missing listener spec in the server config, fixed. this wasn't a real problem as devices are ipv4-only anyway.

**Comment by timoschilling** [comment]
Devices are ipv4 right, but updates are happen from the UI and the browsers are using ipv6.

**Comment by rojer** [comment]
ah, you are right. anyway, thanks @denbec  for reporting and @timoschilling for confirming, this is now fixed.
