### ISSUE TITLE
Shelly1 FW support of external GPIO temperature sensor

### ISSUE THREAD

**Issue by col-tom** [mongoose-os-apps/shelly-homekit#526]
All - Do we support currently the GPIO adon for these external sensors in **HomeKit and for shutdown**:

* DS18B20 temperature sensors or
* DHT22 temperature + humidity sensors

Thanks

**Comment by simonfield76** [comment]
Sorry for my question but the two sensors are now supported?

Inviato da iPhone

Il giorno 22 feb 2021, alle ore 08:33, Tom <notifications@github.com> ha scritto:

﻿

All - Do we support currently the GPIO adon for these external sensors in HomeKit and for shutdown:

  *   DS18B20 temperature sensors or
  *   DHT22 temperature + humidity sensors

Thanks

**Comment by andyblac** [comment]
clising duplicate, please add support here. https://github.com/mongoose-os-apps/shelly-homekit/issues/186
