### ISSUE TITLE
wrong wifi password during setup

### ISSUE THREAD

**Issue by ThibaultH9** [mongoose-os-apps/shelly-homekit#527]
Hello,
when configuring wifi for my module I must have made a mistake when writing the password. Result I no longer see my module on my wifi network.
How can I do ?

excuse me for my english.

**Comment by andyblac** [comment]
see here https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery

**Comment by ThibaultH9** [comment]
@andyblac Thanks you :)

**Comment by andyblac** [comment]
> @andyblac Thanks you :)

get it fixed ?

**Comment by ThibaultH9** [comment]
yes ;)
