### ISSUE TITLE
Shelly1/25 didn't reboot automatically

### ISSUE THREAD

**Issue by jobl1978** [mongoose-os-apps/shelly-homekit#528]
I had several Shelly devices that show "no response" in Home App. The web ui shows 0 pending and 0 active connections for those devices. In the change log of 2.7.2 there is an entry that devices will automatically reboot if there is no connection at least for 5 minutes what not happened. After rebooting those Shellys manually they worked again.

**Comment by andyblac** [comment]
thats wifi connection, not hap connection, report the issue here https://github.com/mongoose-os-apps/shelly-homekit/issues/129
