### ISSUE TITLE
REST API toggle

### ISSUE THREAD

**Issue by JCalvi** [mongoose-os-apps/shelly-homekit#533]
I can get on and off to work but how do I toggle?

http://shelly1-test.local/rpc/Shelly.SetState?id=1&type=0&state=%7b%22state%22%3atrue%7d turns on
http://shelly1-test.local/rpc/Shelly.SetState?id=1&type=0&state=%7b%22state%22%3afalse%7d turns off

http://shelly1-test.local/rpc/Shelly.SetState?id=1&type=0&state=%7b%22toggle%22%3atrue%7d does not work

http://shelly1-test.local/rpc/Shelly.SetState?id=1&type=0&state=%7b%22state%22%3atoggle%7d does not either

Stock firmware has... http://192.168.0.40/relay/0?turn=toggle

**Comment by andyblac** [comment]
don't think @rojer has coded toggle for statefull switch, only statless, i guess your using a monentary input on a statefull switch ?

**Comment by JCalvi** [comment]
Switch is wired as edge so can be turned on/off from physical as well as web access.

web access is linked to remote control button via htpc so I can turn a light on/off via the wall switch or the remote.

**Comment by JCalvi** [comment]
Note: this could also be a repeat of https://github.com/mongoose-os-apps/shelly-homekit/issues/461 as I suspect he had the same desire and similar use case as me.

**Comment by EmmieFromTheBlock** [comment]
@rojer Would be awesome to have a toggle function via rest api for the type 0 switch!

**Comment by andyblac** [comment]
this is/will be required once lights bulb support are added too.

**Comment by JCalvi** [comment]
@roger any plans for adding this feature? 
I am still on stock firmware for now and not complaining, just like to know if its on your radar to be done and I should wait or whether I need to consider other options.

**Comment by timoschilling** [comment]
I think it will be come, I’m also interested to implement it for my self, but no estimation for now

**Comment by JCalvi** [comment]
Thanks Timo, I’ll wait then.
