### ISSUE TITLE
Change IP settings with GUI

### ISSUE THREAD

**Issue by Alfniator** [mongoose-os-apps/shelly-homekit#534]
My Shelly does not install the update OTA, reading in the GitHub learns me that this possibly fails because I have set up the shelly with a static IP (i dont know, but i cant check anywhere...)

Reading in de GitHub learns me that I only can see and edit the ip-adres settings through console commands... I do not fully understand how that works, so I was thinking: why can't we edit such settings through the GUI? Then I do not have to use console commands.

**Comment by andyblac** [comment]
see here https://github.com/mongoose-os-apps/shelly-homekit/issues/501
