### ISSUE TITLE
detached input switch state

### ISSUE THREAD

**Issue by slobodam32** [mongoose-os-apps/shelly-homekit#54]
Hi,

is possible to see state of detached physical input switch (SW input on shelly device) in Home app?

Thanks

**Comment by rojer** [comment]
this is #9 
in short: yes, it is possible. patches welcome, or wait until i have the time.

**Comment by slobodam32** [comment]
thanks for answer, i'll wait on your update

**Comment by smarthome-fan** [comment]
+1 me too

**Comment by smarthome-fan** [comment]
> thanks for answer, i'll wait on your update

+1 me too
