### ISSUE TITLE
Need to reboot

### ISSUE THREAD

**Issue by GHanthorn** [mongoose-os-apps/shelly-homekit#541]
When using with home assistant works great except 1 issue, after about 20 days the Homekit Firmware gets sluggish (don't know why) but a simple reboot fixes it. Could you update the Python Script tools to include a force reboot so one command can reboot all devices (vs going into the WebUI for each shelly one at a time). Thanks!

**Comment by andyblac** [comment]
please see https://github.com/mongoose-os-apps/shelly-homekit/issues/129
