### ISSUE TITLE
Setting a Shelly 2.5 as a Valve 

### ISSUE THREAD

**Issue by homekitguy** [mongoose-os-apps/shelly-homekit#544]
Hello i want to show my Shelly as a valve in HomeKit but i can’t choose it. What should i do???
![IMG_2100](https://user-images.githubusercontent.com/80318133/110446139-23a42180-80bf-11eb-850c-cc7378dba5df.jpeg)

**Comment by timoschilling** [comment]
Are you using 2.7.X or 2.8.0-alphaX? Valve is only supported in 2.8, but not officially released yet, there is a alpha available, but be careful installing it, there are some connection issues.

**Comment by homekitguy** [comment]
Yeah its 2.7 will the 2.8 support doorbell? Because i saw it here too: https://github.com/mongoose-os-apps/shelly-homekit/wiki/Input-Switch-Settings

**Comment by andyblac** [comment]
> Yeah its 2.7 will the 2.8 support doorbell? Because i saw it here too: https://github.com/mongoose-os-apps/shelly-homekit/wiki/Input-Switch-Settings

yes, i updated wiki a liitle too soon, we thought 2.8 would not be so long in testing, sorry for confusion.

**Comment by homekitguy** [comment]
Okay thank you ☻
