### ISSUE TITLE
Shelly 2.5 Homekit disconnected

### ISSUE THREAD

**Issue by Padrew46** [mongoose-os-apps/shelly-homekit#545]
Hello, 
I managed to install moongoose firmware to my Shelly 2.5 and add it to the Apple Homekit, but immediately it disconnects even from the Shelly app. When I revert back to original firmware, it communicates well.

I tried to find the solution here, but without luck. Could you please advice what to do?
Thanks.
Patrik

**Comment by andyblac** [comment]
shelly APP is not supported by this firmware.

**Comment by andyblac** [comment]
button in hk ?

**Comment by Padrew46** [comment]
Yes, tried to set up as garage door in UI and also as a switch, both not working

**Comment by andyblac** [comment]
can enable deug log, click on log link, try the button in hk and post log here.
