### ISSUE TITLE
Installing On RavenSystems Home Accessory Architect

### ISSUE THREAD

**Issue by pskow** [mongoose-os-apps/shelly-homekit#554]
Hello!
Is there any way to install this software to Shelly 2.5 with installed HAA?
Is there any way to do it without physical access to the device without flashing with cables?

**Comment by timoschilling** [comment]
> Don't worry about using a non-SSL web server, because all necessary files are signed and verified by hardcoded public key of firmware.

From the [HAA wiki](https://github.com/RavenSystem/esp-homekit-devices/wiki/Installation#using-a-custom-server-for-ota-updates), so sounds like it's not possible, as we can't generate signed code without there private key.

But flashing via cables shouldn't be a problem.
