### ISSUE TITLE
Shelly2.5 pitch connector

### ISSUE THREAD

**Issue by louis49** [mongoose-os-apps/shelly-homekit#558]
Hello, to connect the Shelly 2.5, which Pitch connector do you recommend? Are we at 1mm pitch? I did not find a 6 pin 1mm male connector. Do you have a link to an existing product please?

**Comment by louis49** [comment]
Finally found : [B07TS2KPW7](https://www.amazon.fr/shelly-2-5-Adpter/dp/B07TS2KPW7 )
I ordered it, I will update the Wiki ([Serial-connection](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Serial-connection)) when I have verified that it works well

**Comment by andyblac** [comment]
i tried that did not work for me, others say it does.

**Comment by timoschilling** [comment]
Has worked for me, but depending on your device you need to cut off or move one pin.

**Comment by louis49** [comment]
[B07TS2KPW7](https://www.amazon.fr/shelly-2-5-Adpter/dp/B07TS2KPW7) Works for me

**Comment by louis49** [comment]
Wiki updated
