### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by nk-gx** [mongoose-os-apps/shelly-homekit#559]
![Screenshot 2021-03-12 at 11 17 03](https://user-images.githubusercontent.com/72701663/110919819-594a4400-8325-11eb-9099-7a51dba3fac2.png)

Hi, the year in copyright is still 2020.

**Comment by col-tom** [comment]
just let's put `new Date().getFullYear()`

**Comment by rojer** [comment]
let's just remove the year, it's not required anyway.
