### ISSUE TITLE
flash-script extension for device reboot

### ISSUE THREAD

**Issue by jobl1978** [mongoose-os-apps/shelly-homekit#564]
Would be nice to have an option to only reboot all/selected devices. Its not comfortable to find out ip address first and reboot them manually from the web ui if reboots are required.

**Comment by jobl1978** [comment]
Oh sorry I saw this feature already exists :-D
I will close it

**Comment by andyblac** [comment]
np, yes, you can reboot all with `-v` or just give script hostname or ip, you can evengive it multiple hostnames / ip's

`././flash-shelly.py --reboot -a`
`././flash-shelly.py --reboot hostname`
`././flash-shelly.py --reboot hostname1 hosname2 192.168.3.55`

hope this helps.
