### ISSUE TITLE
Shelly Motion Sensor working with Shelly 1 and 1L on HomeKit

### ISSUE THREAD

**Issue by burneyboy2002** [mongoose-os-apps/shelly-homekit#568]
Hi All

I've been messing with the shelly motion sensor, and have been trying to integrate into my Homekit Shelly Relays, but as you all know the motion sensor as of writing this does not yet accept HomeKit with out a work around i.e. hoobs etc.

I stumbled across a URL that works with in the motion sensor for switching shelly on and off on the Wiki of this page.

As you all know the motion sensor is battery powered so as of yet cannot be added to the list of devices at present that can be re-flashed with this custom firmware.

I found that using a script on this page: [Wiki API](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development#API) that I was able to change a few bits n bobs and get it to talk to my shelly 1L to switch my hall way lights on.

Once on this page go to: **You can call these in a web url as follows:** section and there is a pre drafted script under: **For GET requests, construct args from query string, for example, this will turn on the switch relay.**

Once you copy the script below the above heading you need to edit it slightly by adding you shelly IP address or .local address into the appropriate part at the start (shelly1-test.local)

Script below:
http://shelly1-test.local/rpc/Shelly.SetState?id=1&type=0&state=%7b%22state%22%3atrue%7d

after you have edited it in a appropriate app or program (I used notes on a Mac) got to your Shelly Motion Sensor address (sometimes you have to wake the motion sensor up) and go to the URL/Action Sections, once in there you have all sorts of options, the 2 I've used is Motion Detected and End of Motion Detected. Now you need to check the Enabled part of the tab, and insert your script and save. once saved go to Sensor Control box and click on a save button as this will update the shelly motion.

to switch off a shelly at the end of motion tab use the same script but change at the end.
http://shelly1-test.local/rpc/Shelly.SetState?id=1&type=0&state=%7b%22state%22%3afalse%7d
as you may see at the end I've changed **atrue** to **afalse** and remember to check your enabled tab.

once saved go to Sensor Control box and click on a save button as this will update the shelly motion.

The shelly motion does have blind time minimum of 1 minute (Shelly Motion firmware: 20210226-072307/v1.1.0@f31e1d2b) so if you pass by again it will not send another command for the set time (Mine was 1 min) but if you use it with End of Motion Detected url it will start the timer once again but will not send another command to the Shelly Relay, but if you have switches on the SX/SW parts and hit the on/off/toggle switch it won't react for 1 min or how long blind time is set up due to the blind time of the sensor, also if you have a timer set up it may switch of after the timer time (Not had time to play with that part yet)
 
hope this helps some of you and I'm happy for the Admins or Mods to correct / update as appropriate.

**Please note: there may be a  few seconds or so delay between sensor noticing motion and the command been sent to the shelly. So may not be as fast as the shelly own OS reacting.**

**Comment by andyblac** [comment]
if you want to add screen grabs etc, and do step by step instructions i'll add to wiki, 

here one i did for stateless switch https://github.com/mongoose-os-apps/shelly-homekit/wiki/Stateless-Toggle-Switch
