### ISSUE TITLE
Shelly 2.5 lost

### ISSUE THREAD

**Issue by ari-ido-999** [mongoose-os-apps/shelly-homekit#569]
Hello,

All of my shelly's lost connection yesterday. I upgraded all but one to the latest version and that solved the problem. However one shelly 2.5 did not upgrade , I clicked on Reset and now I can't see it im my network. How do I find the device ?

**Comment by andyblac** [comment]
if you reset device you need to connect to it via AP mode, you should see `Shelly25-xxxxxx`  (xxxxxx being part of it;s MAC address) and re-setuo the devcie.
