### ISSUE TITLE
Serial number issue

### ISSUE THREAD

**Issue by JacVid** [mongoose-os-apps/shelly-homekit#57]
Hello,

I'm trying this very interesting firmware (thanks a lot for the job), and after flashing (fw 1.8), I'm wondering if it could be possible to display the MAC address of the device instead of "000000" for the Serial Number (in the Home App information of the device) ?

Thanks.

**Comment by rojer** [comment]
sure, can be done.
makes sense to use mac if `device.sn` is not set explicitly.

**Comment by felixmueller** [comment]
1 up for displaying the MAC address als serial number 👍

**Comment by rojer** [comment]
will be picked up in the next release.
