### ISSUE TITLE
Shelly1 "garage door opener" - chatter of close sensor

### ISSUE THREAD

**Issue by ingski** [mongoose-os-apps/shelly-homekit#571]
I'm using a Shelly1 in garage door opener mode with the "Close Sensor" set to "Normally Closed". 
When I'm closing the garage door the close sensor reports twice, i.e. HomeKit receives a sequence of
- closed
- opened
- closed

instead of just a single "closed".
I assume that this is eventually caused by a mechanical issue with a chatter of the sensor itself.

It would be great if the firmware could be modified so that after a status change of the close sensor  has been discovered it would re-check 500ms (or better a configurable time) later and only send out the change notification if the status change still persists.

-
Ingo

**Comment by Whiterabbit64** [comment]
Check the sensor’s magnet position. I had the same kind of issue and solved it by repositioning the magnet.

**Comment by ingski** [comment]
The magnet is located directly opposite of the sensor.

**Comment by joddye2** [comment]
We talk about this problem in the [448](https://github.com/mongoose-os-apps/shelly-homekit/issues/448) issue. But there is no solution yet

**Comment by andyblac** [comment]
@joddye2 thx I'll close as duplicate.
