### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by paolodesalvatore** [mongoose-os-apps/shelly-homekit#575]
I experience continuous disconnections with the Shelly 1, and the only way to reconnect it is to disconnect and reconnect the power.  The Wi-Fi connection is good, and with the original firmware I don't have this problem.

**Comment by MattAydin** [comment]
I have the same. Also to add, I have a multiple story house. Any ideas why this happens?

**Comment by rojer** [comment]
does any of you use UniFi access points?

**Comment by trolli-ch** [comment]
Yes, i also have connectivity issues. And I have UI Access Points.
On which build is 2.9.0 based ? 1.10.3 ?

Thanks !

**Comment by timoschilling** [comment]
> On which build is 2.9.0 based ? 1.10.3 ?

Shelly HomeKit uses the same base OS (MongooseOS) as the stock firmware, but is not based on stock.

**Comment by trolli-ch** [comment]
I had real strange issues with my network (UI AP) and the shellies in my house. After moving to stock 10.3 it seems to be better now.
