### ISSUE TITLE
Shelly 1 SW garage opener issue

### ISSUE THREAD

**Issue by Trasmontinho** [mongoose-os-apps/shelly-homekit#577]
Hi, 

I've already comented in an other issue related to the status of the door which is not raising well (with some logs). I'm raising this issue due to the fact that I've measured a strange thing. 

If you look at the wiring in the diagram below, If I wire my sensor status like this, I've seen that I measure a continuous 35vdc at the OGI interface. It's like the shelly was outputing in the SW interface the power to my output. for your information I'm using the latest version of the software and I'm acting as garage door opener.

![image](https://user-images.githubusercontent.com/53441739/111747533-b4cd8200-888f-11eb-85ee-e008b4a472dc.png)

I'd like to help more but I'm sadly not a C++ developper (more python one).

Regards, 

Sam

**Comment by MrSimpa** [comment]
Hi, older issue, but I currently have the same problem with Shelly One gen4, connected in the same way, but I can't get the status from the OGI port in Shelly.
