### ISSUE TITLE
Shelly Lightbulb support

### ISSUE THREAD

**Issue by berkus** [mongoose-os-apps/shelly-homekit#579]
[These](https://shop.shelly.cloud/shelly-duo-gu10-wifi-smart-home-automation#362) lamps are also connectable  to  shelly cloud and I suppose have controllers similar to already supported devices.

Is support for those planned?

**Comment by timoschilling** [comment]
It's already on the way (currently local testing) for color bulb, vintage and duo each in E27 and GU10 versions.

**Comment by berkus** [comment]
Yay, thanks!

**Comment by andyblac** [comment]
add you support here, closing as duplicate
