### ISSUE TITLE
Shelly 1L SNTP DNS hardcoded?

### ISSUE THREAD

**Issue by wawoodwa** [mongoose-os-apps/shelly-homekit#583]
Hello, was working on my environment today and took a look at the logs:

```
9377549 mgos_sntp.c:98          SNTP query to time.google.com
40602088 shelly_main.cpp:560     Up 40.59, HAP 0/4/12 ns 4, RAM: 22504/38464; st 44; 0.1: st:1 in_st:1 inm:1 ininv:0; 6.2: svt:6 inv:0 
48602056 shelly_main.cpp:560     Up 48.59, HAP 0/4/12 ns 4, RAM: 22504/38464; st 44; 0.1: st:1 in_st:1 inm:1 ininv:0; 6.2: svt:6 inv:0 
49184938 mongoose.c:12067        Failed to resolve 'time.google.com', server 8.8.8.8
```

Looks like the Mongoose OS SNTP is also hardcoded for Google DNS?  We are passing a valid DNS server. The firmware is able to check and download updates with our correct DNS server passed through DHCP. Any thoughts?

**Comment by rojer** [comment]
there was a brief time where DNS option from DHCP response was not honored and default server was being used all the time as a fallback. this was fixed in https://github.com/mongoose-os-libs/lwip/commit/70235bcde0b56f9c67e8da1123ef3046c5d54c36 and will be included in the next release.
