### ISSUE TITLE
Default IP address

### ISSUE THREAD

**Issue by sagistn** [mongoose-os-apps/shelly-homekit#585]
Does anyone knows the default IP address of Homekit Shelly after restoring to defaults? Tried the stock's default (192.168.33.1), it's not it.

**Comment by andyblac** [comment]
thats the correct default address.

**Comment by sagistn** [comment]
Weird, not working.

**Comment by andyblac** [comment]
hmm strange your sure your connected to it's AP ?

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Device-webUI

**Comment by sagistn** [comment]
Yes, of course. I see its SSID and connect to it, but no response from it.

**Comment by andyblac** [comment]
one for @rojer

**Comment by rojer** [comment]
what ip address do you get from the ap?
check wifi connection properties.

**Comment by sagistn** [comment]
169.254.231.44
Looks like the DHCP server is not coming up.
