### ISSUE TITLE
"Roaming" feature

### ISSUE THREAD

**Issue by mrmaximas** [mongoose-os-apps/shelly-homekit#586]
How about "roaming" feature like in latest stock firmware? May be for backup APN too?
Thanks!

**Comment by timoschilling** [comment]
That feature is already there, it's a function of the mongoose os it self, you can find the documentation [here](https://mongoose-os.com/docs/mongoose-os/api/net/wifi.md#configuration)

**Comment by mrmaximas** [comment]
i don't this features in the web interface.

**Comment by rojer** [comment]
we need a UI for multiple APs, yes.

**Comment by timoschilling** [comment]
This feature from the stock firmware, is it from shelly or from mongoose?
![](https://files.gitter.im/602138496da0373984616d97/kt19/Screenshot-2021-04-23-at-22.42.46.jpg)
If it's from mongoose, which config value is it?

**Comment by rojer** [comment]
no, actually. this is specific to stock fw.

**Comment by rojer** [comment]
it makes sense as a feature of the wifi lib.

**Comment by timoschilling** [comment]
ok, then I think this issue is a double of #501

**Comment by rojer** [comment]
no, it's a different one. #501 is about alternate configuration, this one is about seeking a better AP.

**Comment by rojer** [comment]
AP roaming is implemented, roaming threshold is set at -75. i think -65 stock setting is too aggressive.
