### ISSUE TITLE
regular expressions strings

### ISSUE THREAD

**Issue by juanfal** [mongoose-os-apps/shelly-homekit#589]
Only a minor aesthetic, yet perhaps can be more

    hostcheck = re.search(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", host)

shouldn't regexp string be prefixed by **r** so the backslashes are preserved?

Another:

     logger.trace(f"\n…

inserts a newline before the string, doesn't it?

**Comment by andyblac** [comment]
> Only a minor aesthetic, yet perhaps can be more
> 
> ```
> hostcheck = re.search(r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", host)
> ```
> 
> shouldn't regexp string be prefixed by **r** so the backslashes are preserved?
> 
it does make any differance to result:
```
andrews-mbp-wifi:tools andrewblackburn$ ./flash-shelly.py 192.168.3.45
hostcheck: <re.Match object; span=(0, 12), match='192.168.3.45'>

Host: http://192.168.3.45
Device Name: Hall Spots
Model: ShellyDimmer2
Firmware: Stock 1.10.0 ➜ HomeKit Not available

Devices found: 1 Upgradeable: 0 Flashed: 0 Failed: 0
andrews-mbp-wifi:tools andrewblackburn$ ./flash-shelly.py 192.168.3.45
hostcheck: <re.Match object; span=(0, 12), match='192.168.3.45'>

Host: http://192.168.3.45
Device Name: Hall Spots
Model: ShellyDimmer2
Firmware: Stock 1.10.0 ➜ HomeKit Not available

Devices found: 1 Upgradeable: 0 Flashed: 0 Failed: 0
```

> Another:
> 
> ```
>  logger.trace(f"\n…
> ```
> 
> inserts a newline before the string, doesn't it?

yes, it would, but it then messes with line numbers and trace logging, it easier to read logs if new lines have own code line.

**Comment by andyblac** [comment]
as `r` will only help, i'll add it to next update.

**Comment by andyblac** [comment]
done, `r'xxx'` will be in next update, thx for sugestion.

**Comment by andyblac** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/pull/590

**Comment by juanfal** [comment]
Thank you! I am only just trying to dig enough into the firmware (!) to make Shelly 1 read not a switch on/off but a led from an Air Conditioner wall control panel… uf!!

Thanks

**Comment by andyblac** [comment]
np, keep em coming 😄
