### ISSUE TITLE
Naming Shelly Devices...

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#59]
i have a few shelly devices now, and it starting to get confusing when i open the GUI on a device. Could we allow naming the device in the GUI, or at least display the HomeKit device name in GUI ?

**Comment by rojer** [comment]
the Home app does not propagate name changes from to the device. Name is a read-only characteristic. what we can do is add ability to change the name we present to the Home app, so if you set it from web UI and do not override in the Home app, it will change in both. would that work?

**Comment by andyblac** [comment]
i manually change HomeKit accessory names anyway, as long as we can give a name the device in WEB UI, so i can tell what device I am in, that's enough for my needs.

**Comment by rojer** [comment]
sure, that can be done.

**Comment by rojer** [comment]
we already have a config option for it, even (`swX.name`). it's just a matter of surfacing it in the ui.

**Comment by rojer** [comment]
committed a simple solution. device needs to be rebooted for the name change to be picked up by the ios device (can be done from the web interface).
