### ISSUE TITLE
Temperature Sensor Add-on 

### ISSUE THREAD

**Issue by bjornand1** [mongoose-os-apps/shelly-homekit#591]
Hi, hope someone can help me understand how the Shelly 1 Temp Sensor Addon works. I have a Shelly 1 flashed with HomeKit firmware. If I connect a temp sensor, will I be able to see the measurements from the sensor in HomeKit? Or where else will they show up?

**Comment by andyblac** [comment]
not atm, add your support here https://github.com/mongoose-os-apps/shelly-homekit/issues/186
