### ISSUE TITLE
Shelly 2.5 in roller shutter mode but with Valve HAP

### ISSUE THREAD

**Issue by mrmaximas** [mongoose-os-apps/shelly-homekit#593]
It is possible to impelement this feature for Shelly 2.5?
For example to control three-wire motorized electric ball valve like this https://www.aliexpress.com/item/4000257182106.html

**Comment by timoschilling** [comment]
No that's not possible, Valve in HAP doesn't support a percentage value, it only supports on / off.

**Comment by andyblac** [comment]
@timoschilling thx i'll close.
