### ISSUE TITLE
HK firmware add to HB or Google Home compatibility

### ISSUE THREAD

**Issue by MrMysakovich** [mongoose-os-apps/shelly-homekit#598]
Hi, 

any way to add this Shelly 1 with HK firmware to Homebridge or Google Home? I like HomeKit firmware because of having option to set valve, lock, garage door etc. Shelly plugin for HB for stock fw don’t have these options.

**Comment by timoschilling** [comment]
about Homebridge the answer is here: https://github.com/mongoose-os-apps/shelly-homekit/issues/599

**Comment by timoschilling** [comment]
the Google Home request is a double of https://github.com/mongoose-os-apps/shelly-homekit/issues/345

**Comment by andyblac** [comment]
thx
