### ISSUE TITLE
Toggle switch

### ISSUE THREAD

**Issue by bulyshko** [mongoose-os-apps/shelly-homekit#6]
Hello, 

Original Shelly firmware had an option to choose "Button type". Can you please add "Toggle switch" support? e.g. Shelly should change state on every button hit.

Thanks

**Comment by andyblac** [comment]
already in I asked for that https://github.com/mongoose-os-apps/shelly-homekit/commit/3fa6854b4822f825bb5bc71720f3f6072de3c4aa

**Comment by rojer** [comment]
it is in fact the default. but point taken - we should match all the modes.

**Comment by bulyshko** [comment]
Yes, I have seen that change, but for some reason it doesn’t work for me.

**Comment by andyblac** [comment]
haven't had chance to test it yet, waiting for flashing leads to arrive should be Monday.

**Comment by rojer** [comment]
ok, done, pushed 1.2.0

**Comment by bulyshko** [comment]
Thanks for adding more modes. I can confirm that now everything works as expected.
