### ISSUE TITLE
Shelly1L stop working after update (v.2.8)

### ISSUE THREAD

**Issue by phramos** [mongoose-os-apps/shelly-homekit#603]
Hello,

I have one Shelly1L installed with Neutral to control one light. It was working fine until I update the firmware to use 2.8 version (the previous one was 2.7.3 build 20210124-130547/2.7.3-g883914a-master). After the update, the Shelly 1L was working as expected but few minutes ago, when I turned the lights on using my homepod the light is not turning off anymore (not even if I toggle the switch). Can anyone kindly help me with this issue or guide me to downgrade back to the 2.7 version? Thanks

**Comment by timoschilling** [comment]
which `2.8` are you using? `2.8.0`, 2.8.1` or `2.8.2`. It should be listed in the accessory settings in the home app.

**Comment by phramos** [comment]
Hey timoschilling, thanks for your fast reply. Since I updated earlier today I am using the version 20210315-093718/2.8.2-gc0f7426-master.

Thanks

**Comment by andyblac** [comment]
can you here a click from the shelly when using either switch or hk, it sounds like, the relay is stuck, it can happen on Shelly1L, you may need to give the device a knock

**Comment by andyblac** [comment]
> Whowwww It works! But as soon as I close the switch box it happens again. Is there anything that I can do to avoid this behavior? Many thanks

did it not happen on 2.7.3 ?,

**Comment by andyblac** [comment]
you can revert to 2.7.3 by downloading zip here https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.7.3 and uploading it via webui

**Comment by phramos** [comment]
No. This has never happened before. I will try your suggested solution. Thanks

**Comment by phramos** [comment]
I applied the previous version and the issue still happen. Probably there is a phisical issue with my Shelly 1L. Thanks andyblac, for the help. I am going to close the thread.

**Comment by andyblac** [comment]
try it on stock, if still happens (prob will it a known fault on some) report it to shelly.
