### ISSUE TITLE
Shelly DW Senzor

### ISSUE THREAD

**Issue by ma-jkl** [mongoose-os-apps/shelly-homekit#606]
Hi all,

is here any software HomeKit  for Shelly DW Senzor? I want to install it outside to the door fence to see the fence status because of children. 
Thank you very much.
Michal

**Comment by andyblac** [comment]
see here https://github.com/mongoose-os-apps/shelly-homekit/issues/124

**Comment by ma-jkl** [comment]
Thank you Andy. So still waiting :)
