### ISSUE TITLE
auto off config issue

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#61]
i have a pre-exiting auto off config of 1hr, when i try to change the Switch name that is now allowed in v1.9.0, is reports an issue with auto off config.

i have tried disabling, and re-enabling, but now it wont enable for an 1hr (01:00:00.000)

![Screenshot 2020-04-23 at 14 23 55](https://user-images.githubusercontent.com/77936/80104780-8e17a600-856f-11ea-8c28-4756fba769d9.jpg)
![Screenshot 2020-04-23 at 14 23 47](https://user-images.githubusercontent.com/77936/80104791-9243c380-856f-11ea-950e-fda8e2c91ff9.jpg)

it seems you have to enter 01:00:00.010. for it to save, looks like the check is not also checking HH, MM or SS.

**Comment by tsdrummer** [comment]
Thanks for reporting, I have the same issue.
I think it’s a JavaScript validation thing.

**Comment by andyblac** [comment]
thanks @rojer

**Comment by rojer** [comment]
pushed 1.9.1
