### ISSUE TITLE
version number not correct in homekit

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#62]
as you can see in screenshots below, web ui shows correct version 1.9.1, but homekit showing 1.8

![Screenshot 2020-04-23 at 20 16 08](https://user-images.githubusercontent.com/77936/80140341-b5866700-859f-11ea-8fc2-f55273e83f83.jpg)
![Screenshot 2020-04-23 at 20 16 26](https://user-images.githubusercontent.com/77936/80140344-b7e8c100-859f-11ea-9c45-78cdc1126dab.jpg)

but if i build it myself and upload that fw, it shows in homekit correct.

**Comment by rojer** [comment]
does not repro for me.
home app may not have updated the version when you were looking.

**Comment by andyblac** [comment]
![Screenshot 2020-04-23 at 20 22 03](https://user-images.githubusercontent.com/77936/80140870-83293980-85a0-11ea-93e3-5814f99a5f5c.jpg)
![Screenshot 2020-04-23 at 20 24 25](https://user-images.githubusercontent.com/77936/80140877-86242a00-85a0-11ea-8107-9f2f6786eed3.jpg)

**Comment by rojer** [comment]
version string reported on web ui and sent to ios app are literally the same.

**Comment by andyblac** [comment]
> does not repro for me.
> home app may not have updated the version when you were looking.

i have been on 1.9.0 since yesterday ???, it was still showing 1.8, until i built it myself ?

**Comment by rojer** [comment]
well, i flashed the firmware to my unit before uploading to the site and it shows 1.9.1 in both web ui and home app.

**Comment by andyblac** [comment]
from github resources ?

**Comment by rojer** [comment]
the same zip file, yes. technically, it was just before it became github resource :)

**Comment by andyblac** [comment]
hmmm, i'll try reflashing fw file github again.

**Comment by andyblac** [comment]
well, sorry but it back as 1.8

![Screenshot 2020-04-23 at 20 30 40](https://user-images.githubusercontent.com/77936/80141383-617c8200-85a1-11ea-8800-486fb666749f.jpg)

**Comment by rojer** [comment]
no, it is definitely 1.9.1. i unpacked it and ran strings on the binary:
```
[rojer@nbd ~/shelly-homekit master]$ unzip ~/Downloads/shelly-homekit-Shelly1-1.9.1.zip
[rojer@nbd ~/shelly-homekit master]$ strings switch1-1.9.1/switch1.bin | grep 1.9.1
1.9.1
20200423-164607/1.9.1-geb66659-master
```

**Comment by andyblac** [comment]
yeah, as webui is correct, but as you can see HomeKit is showing 1.8

**Comment by rojer** [comment]
i don't know, it's a mystery.
in fact, i tried downgrading my device and it stops working in the home app. i actually remember reading that ios will not allow downgrades, so it stops communicating if version is below 1.9.1 in my case.

**Comment by andyblac** [comment]
it worked here, strange

**Comment by andyblac** [comment]
can you try flashing the above ?

**Comment by rojer** [comment]
updated shelly1 with your file - worked.
![IMG_20200423_204615](https://user-images.githubusercontent.com/531307/80142961-f7191100-85a3-11ea-8a77-f38efa79e9b3.jpg)
![IMG_20200423_204750](https://user-images.githubusercontent.com/531307/80142984-fe401f00-85a3-11ea-8d08-466b3a832e8e.jpg)

**Comment by andyblac** [comment]
strange, maybe HomeKit is caching FW ?

**Comment by andyblac** [comment]
i'll keep an eye on it, with your next release.

**Comment by schemhad** [comment]
Could you please try an hardreset of the shelly (power off, power on, switch 5 times) and flash the latest release again? I can not find the fault you indicate with my iPad 4 and Shelly1 ...

**Comment by andyblac** [comment]
tried that already, i'll try fw 1.9.2 from github once it is released
