### ISSUE TITLE
best roller shutter

### ISSUE THREAD

**Issue by Ludelag** [mongoose-os-apps/shelly-homekit#621]
Hello people,

What will be the best roller shutter for the Shelly 2.5 Mongoose-shelly-homekit firmware? could be this a good one JE50/20ELMSH?

Thank you

**Comment by AnakinSpain** [comment]
I have installed this JULIUS MAYER JM35-100

**Comment by Ludelag** [comment]
How is your experience so far with this roller shutter?

**Comment by AnakinSpain** [comment]
It works fine and full comptibility with Shelly 2.5

**Comment by Ludelag** [comment]
Thank you, I will order one to try.
