### ISSUE TITLE
Autoupdate

### ISSUE THREAD

**Issue by Thotty1986** [mongoose-os-apps/shelly-homekit#625]
Not an Issueu but a question.
Is there a funktion that the Shellys will update Automatic ?
Or ist there a batch for my Windows PC or Raspberry ?

Thanks a lot for your work :)

**Comment by andyblac** [comment]
There is a script you can use in your Linux it is located in the tools folder in the gut

**Comment by rojer** [comment]
it's not possible to do auto-update due to licensing restrictions, but Andy's script does a great job of mass update.

**Comment by andyblac** [comment]
@Thotty1986 take a look here https://github.com/mongoose-os-apps/shelly-homekit/wiki/Flashing#Script
