### ISSUE TITLE
Auto reboot

### ISSUE THREAD

**Issue by Marcusyo** [mongoose-os-apps/shelly-homekit#629]
Every now and then my shellys have no connection to homekit but i can reach then over the web interface. When i reboot them they work just fine. Could you inplement an option for an auto reboot like every day at xx o clock or once a week at xx o clock. I have this problem a lot with my shelly 1 garage opener when im comming home from work and cant open my garage via carplay cause the shelly has no connection to homekit. Iphone is already connected to wifi at this point. Got an homepod mini as my main homekit point.

**Comment by timoschilling** [comment]
Your problem sounds like an issue which is fixed in 2.9.0-alpha2, please try that version.

**Comment by andyblac** [comment]
sounds like duplicate issue https://github.com/mongoose-os-apps/shelly-homekit/issues/129

**Comment by rojer** [comment]
yes, if "a while" is 25 days, then this is it.

**Comment by rojer** [comment]
no need to try alpha, fix will be in 2.9.0, just wait for that and update.
