### ISSUE TITLE
Can't seem to update shelly2.5 OTA

### ISSUE THREAD

**Issue by peterpeter9999** [mongoose-os-apps/shelly-homekit#631]
Hey guys, I'm not able to get the OTA firmware install to work. Do I need to factory reset the shelly and then connect to the shelly wifi? I tried that as well. The update shows like it is starting but it never updates. Please help!

**Comment by timoschilling** [comment]
1. Connect the shelly to your wifi
2. Update to the latest stock version
3. open http://A.B.C.D/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly25.zip

**Comment by peterpeter9999** [comment]
1. done
2. done
3. When navigating to http://192.168.33.1/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly25.zip it never loads.

**Comment by peterpeter9999** [comment]
![Screen Shot 2021-04-15 at 2 37 10 PM](https://user-images.githubusercontent.com/82616095/114941507-1d107480-9df8-11eb-876f-a58d853d1a51.png)

**Comment by AnakinSpain** [comment]
Check ip Shelly and  change it

**Comment by timoschilling** [comment]
192.168.33.1 is normally only the IP in the AccessPoint mode, I would expect that it has a different IP in your Wifi, take a look on your router maybe it has a host list where you can find the IP.

**Comment by peterpeter9999** [comment]
Ok, found the IP address. 

Shows updating but never updates? 
![Screen Shot 2021-04-15 at 5 18 00 PM](https://user-images.githubusercontent.com/82616095/114954070-97e48a00-9e0e-11eb-8a7f-f4734df44dc5.png)

**Comment by peterpeter9999** [comment]
That was it! Found the IP using network analyzer app. Thanks guys!
