### ISSUE TITLE
Garage Door + Shelly1 Status with no contact sensor

### ISSUE THREAD

**Issue by pbanane** [mongoose-os-apps/shelly-homekit#634]
Hi,

I use a Rademacher SX5 garage door motor in combination with a shelly 1 v3 with your version 2.8.2. 
I and O is connected to the Rademacher, N + L to 230v abs SW is not connected. 
So far everything works fine incl the HomeKit integration. 

My pain point is the correct status. 
the close sensor status is set to “normally closed”. Movement time is set to 10. Tested it it 20 and 30 seconds. Real Closing time of the garage door is about 22 seconds. 

As said the door opening/closing works fine but when closing the status switches to “stopped”.  I don’t no why. The door always closes completely independent of the movement time. 
the Rademacher has no physical switch it is just used with a radio Sender and has now open/close sensor. 

have I overseen anything? 

Are there any recommendations for a contact sensor? 

Thanks for your feedback!

**Comment by timoschilling** [comment]
The problem is that you can’t use our firmware without having a close switch. What you describe is expected behavior. You need a close switch for a clean work process, otherwise we can’t determine the close state.
