### ISSUE TITLE
shelly RGB (2.9.0-alpha3)- initial state:ON - not working after the power is off and back on

### ISSUE THREAD

**Issue by Va5a** [mongoose-os-apps/shelly-homekit#645]
First, thank you for now supporting Shelly RGB! I'm testing it and it works great. 

One thing: after you turn off the electricity and then turn it back on, shelly "forgets" the last setting (at least brightness is reset to 0%). To test it - set initial state: on, select color /brightness of your choice. then disconnect it from power. When connected again, it won't turn on (at least brightness will be set to 0%). Hope this is useful.

**Comment by timoschilling** [comment]
@jobl1978 can you please take a look

**Comment by jobl1978** [comment]
@Va5a Did you set "Initial state" to "last"?

**Comment by timoschilling** [comment]
@jobl1978 I can reproduce it, Initial state => last works, but Initial state => on not

**Comment by jobl1978** [comment]
> @jobl1978 I can reproduce it, Initial state => last works, but Initial state => on not

I will have a look on it

**Comment by jobl1978** [comment]
@timoschilling @Va5a Problem found and fixed -> #649

**Comment by Va5a** [comment]
Wow. That was fast!! Thank you :)
