### ISSUE TITLE
Siren Icon Apple HomeKit 

### ISSUE THREAD

**Issue by Chpedro93** [mongoose-os-apps/shelly-homekit#646]
Hi everyone, 
I’m trying to connect a Shelly 1 to an outdoor siren with an automation created with motion sensors.
It’s possible to put the Shelly connected to the siren and when enabled showing a siren icon in the homekit?
Thanks.

**Comment by timoschilling** [comment]
Should be possible, I will take a look

**Comment by timoschilling** [comment]
The only way to get a siren icon in homekit is to use a "alarm system", but an alarm system isn't mate for your use-case, you can't set the "alarm triggered" state from homekit to the alarm system, only the alarm system can say that it is triggered. A homekit alarm system is mode to represent a alarm system controller in homekit not to represent a siren.

**Comment by Chpedro93** [comment]
Thanks for the answer, so to be able to do it I need a control panel right?

**Comment by andyblac** [comment]
add support here https://github.com/mongoose-os-apps/shelly-homekit/issues/552

**Comment by timoschilling** [comment]
For your case you should simply use one of the hap types which is supported by the shelly1.
