### ISSUE TITLE
Output mode "dual" in garage door

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#647]
can anyone tell me how it works and what it is for? thank you

**Comment by timoschilling** [comment]
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Garage-Door-Opener-Settings

**Comment by lucaspinelli85** [comment]
I have read the guide but it does not say what I am looking for!!
<img width="306" alt="image" src="https://user-images.githubusercontent.com/74553551/116138141-baab5400-a6d4-11eb-87e4-0a7dfb75e8a2.png">

**Comment by timoschilling** [comment]
Sorry my fault!

Single is for the wiring you can see in the picture under https://github.com/mongoose-os-apps/shelly-homekit/wiki/Garage-Door-Opener-Settings#shelly-2-or-25 if your garage door has one input for toggle, dual is if your garage door has two inputs, one for closing and one for opening.

**Comment by lucaspinelli85** [comment]
ok thanks!
