### ISSUE TITLE
UI didn't changed after mode change

### ISSUE THREAD

**Issue by timoschilling** [mongoose-os-apps/shelly-homekit#648]
Tested with a 2.5, I expected same problem on all shelly with different mode support.

If I use a fresh flashed 2.5 and select the garage door opener mode, I still see the the UI for the two switches, even after a reload it still keeps the switch UI and not the gdo UI. After a reboot I see the gdo UI.

Tested with 2.8.2 and 2.9.0-alpha3

**Comment by lucaspinelli85** [comment]
When programming settings, you have to first set HomeKit code, after you can change mode setting and it works!

**Comment by rojer** [comment]
fixed, will be in the next release.
