### ISSUE TITLE
Possible Regression: HAP Device type "lock" showing up as Switch in homekit.

### ISSUE THREAD

**Issue by arnoldad** [mongoose-os-apps/shelly-homekit#654]
Hi, I'm running the following on Shelly 1

Version: 2.8.2
Build: 20210315-093656/2.8.2-gc0f7426-master

The following settings are on the shelly.

<img width="499" alt="Screen Shot 2021-04-28 at 7 19 16 PM" src="https://user-images.githubusercontent.com/5604896/116494906-b27b2200-a856-11eb-953f-ce8b57958a4a.png">

However in homekit, I can only set the device type to Fan, Light, or Switch, but not Lock.

Am I missing something? I was able to get another shelly 1 showing up as a lock a few weeks ago - so i wonder if this may be a regression.

**Comment by arnoldad** [comment]
I should add that IOS 14.4.2. And these are the options I get when adding the device.

![B3ACE20B-3E10-4AC4-BEF9-7FF2191FD8B4_1_105_c](https://user-images.githubusercontent.com/5604896/116495460-c8d5ad80-a857-11eb-8c1b-3b67cc4c1afd.jpeg)

Also THANK YOU for your work on this!

**Comment by andyblac** [comment]
look further down in UI to "HAP Service Type" change it to "Lock"

https://github.com/mongoose-os-apps/shelly-homekit/wiki/Switch-Settings

**Comment by arnoldad** [comment]
@andyblac My screenshot shows HAP Service Type field has value Lock.=) Am I missing anything? Thanks for the docs. link I read it thoroughly.

**Comment by arnoldad** [comment]
Update: I needed to reset the homekit server. Previously I had removed the homekit accessory from the Home, this did not help. After using the shelly web interface to reset the homekit server and restarting it (same pairing code) I was able to add the device as a lock type accessory.
