### ISSUE TITLE
NO RESPONSE when is several days on

### ISSUE THREAD

**Issue by AnakinSpain** [mongoose-os-apps/shelly-homekit#656]
Hello. 

I have been observed that the devices are several days ON it change to NO RESPONSE. 

Two days ago, it happened with all shelly 2.5 because I have an electricity for that. Then I reboot every devices and it works again. 

Now, It is happening with my shelly 1 “lamp”

![24389250-7733-42C4-A86C-737D719D0CCA](https://user-images.githubusercontent.com/4932853/116513781-5fdb4d80-a8ca-11eb-8f42-58e8fd1278ea.png)
![EC270F72-01CF-4ED0-8915-B9476B6818A7](https://user-images.githubusercontent.com/4932853/116513803-68cc1f00-a8ca-11eb-9f19-7de60279bad4.png)

**Comment by timoschilling** [comment]
Will be fixed in 2.9.0, feel free to test the beta take a look into #617
