### ISSUE TITLE
Shelly 1pm offline

### ISSUE THREAD

**Issue by torschus** [mongoose-os-apps/shelly-homekit#657]
Hi,

Unfortunately my shelly went offline in the app and can‘t be restarted. In the browser i can see that the device is on. FW is version 2.8.2. Any help possible?

BR

**Comment by timoschilling** [comment]
Sound like a know and in 2.9.0 fixed bug. Can you restart the shelly via browser UI?

**Comment by torschus** [comment]
Didn‘t change something. I rebooted the app, the shelly and the fritz!box. Still the same problem!

**Comment by timoschilling** [comment]
Reset the HAP pearing

**Comment by torschus** [comment]
Done - didn‘t help...

**Comment by timoschilling** [comment]
@torschus which app are you using? The Apple Home App or the Shelly App?
