### ISSUE TITLE
Interaction with other HomeKit devices

### ISSUE THREAD

**Issue by gonzague** [mongoose-os-apps/shelly-homekit#66]
Hey guys
I don't know if it just me .. : I have a Shelly 2.5 running your firmware (thanks for that by the way).

It is powering a mirror's light in my bathroom. The bathroom contains a movement sensor (Philips Hue) and a Hue Tap.

In HomeKit, you can say "if button one of the Hue Tap is press" do "this". Or "if a movement is detected" do "this". I tried linking : if a movement is detected, turn on the mirror (with the Shelly) to no avail.

Is it expected / Can it be fixed somehow? :)

Thanks a lot

**Comment by andyblac** [comment]
you'll need to do an automation in HomeKit to turn on Shelly2.5 switch if movement is detected.

"A Sensor Detects something"
![IMG_0299](https://user-images.githubusercontent.com/77936/80816257-1842b880-8bc7-11ea-92dd-2d3e0a08d023.jpeg)

choose the sensor.
![IMG_0300](https://user-images.githubusercontent.com/77936/80816271-2264b700-8bc7-11ea-925c-2af7b471cac5.jpeg)
![IMG_0301](https://user-images.githubusercontent.com/77936/80816283-285a9800-8bc7-11ea-8c24-43d3ad84dd09.jpeg)

choose what to turn on
![IMG_0302](https://user-images.githubusercontent.com/77936/80816287-2d1f4c00-8bc7-11ea-8e44-39192a48bd6c.jpeg)


end up with something like
![IMG_0303](https://user-images.githubusercontent.com/77936/80816292-30b2d300-8bc7-11ea-9b90-5ffd2765f544.jpeg)

**Comment by gonzague** [comment]
Hey Andy, thanks that's what I had done but it wasn't working and .... mystery of Apple, I went into my bathroom .. and it started working all of a sudden. thanks!!

**Comment by gonzague** [comment]
It is unstable though.. It worked and now doesn't work anymore. I'll investigate

**Comment by andyblac** [comment]
what hub are you using ?, if you have an HomePod, i recommend to use that rather than AppleTV's, ATV's are not reliable.

**Comment by gonzague** [comment]
I'm using an Apple TV :-( crap haha

**Comment by andyblac** [comment]
Yeah ATV’s since iOS 12 are the worst 🙁

**Comment by cuttymello** [comment]
I have the exact same problem using an iPad as hub.. It just doesn't work

**Comment by andyblac** [comment]
yeah, HomePod seems to be the best option atm.
