### ISSUE TITLE
Shelly 1 

### ISSUE THREAD

**Issue by cskallo** [mongoose-os-apps/shelly-homekit#668]
hi
garage door sign does not work, does not respond to the sensor.
indicates a closed state after opening?

**Comment by timoschilling** [comment]
Can you post a screenshot of your garage door settings please

**Comment by cskallo** [comment]
Status : closed
Closee Sensor : Normáll Closed
Movement Time 30
Pulse Time 300

**Comment by cskallo** [comment]
could someone add a setting for the shelly 1 status signal?
