### ISSUE TITLE
Tipo dispositivo HomeKit 

### ISSUE THREAD

**Issue by gegge2** [mongoose-os-apps/shelly-homekit#67]
Grazie per ottimo lavoro svolto fino ad ora . Chiedo se sia possibile scegliere dalla pagina html di configurazione il tipo di dispositivo che viene mostrato in HomeKit  ( luce ,presa , contatto ,irrigazione , garage .) mostrare per Shelly PM consumi .grazie

**Comment by schemhad** [comment]
Non al momento. Ma abbiamo problemi aperti per entrambi gli argomenti (tipo & consumi).

**Comment by schemhad** [comment]
Could be close, identical to #55 & #27

**Comment by rojer** [comment]
closing in favor of #55
