### ISSUE TITLE
Scheduled Rebooting

### ISSUE THREAD

**Issue by Nenarion** [mongoose-os-apps/shelly-homekit#670]
Hi, awesome work! Just wanted to suggest a feature to plan reboots Daly or weekly to avoid connection issues.

Thanks and keep it up

**Comment by andyblac** [comment]
been asked for before, wont happen, prefer to fix any issues for the reason to reboot, do you have any ?

**Comment by timoschilling** [comment]
If you have issues, which version do you use currently?

**Comment by Nenarion** [comment]
Well sometimes the shutters are not responding in the Home app and I have to reboot them. I noticed it happens often when a new update was found.

**Comment by timoschilling** [comment]
There can't be a relation between your error and new updates, the devices didn't check for updates, only the UI does it in your browser. 

Your problem sound like a bug we fixed in 2.9, it happens after 25 days uptime. So please update and report when it happens next time.

**Comment by Nenarion** [comment]
Oh I understand the 25 days uptime could be my issue yes. I just updated all of them to 2.9. So thanks 

Cheers
