### ISSUE TITLE
Shelly Plug S time warning

### ISSUE THREAD

**Issue by me61ic** [mongoose-os-apps/shelly-homekit#676]
Hi everybody, just posting in case someone knows what would be the best option to have an ios notification when the power in a Shelly Plug S has been on for more than a certain time, say 10 mins for example. Would this be possible? If so, how?

Thanks in advance

**Comment by timoschilling** [comment]
You can achieve that with HomeKit automations. How this is done is not related to shellys its a general HomeKit issue so I would suggest you to google for it or ask in HomeKit related user groups.
