### ISSUE TITLE
Reset a shelly 1 in the System menu

### ISSUE THREAD

**Issue by Kelmis13** [mongoose-os-apps/shelly-homekit#677]
I accidentally reset a shelly 1 in the System menu. Now the shelly is no longer accessible via the IP.

**Comment by timoschilling** [comment]
The reset Button in the system section resets the WiFi credentials. Take a look for a WiFi named shelly1-xxxx and open 192.168.33.1 and resetup the WiFi credentials

**Comment by Kelmis13** [comment]
> The reset Button in the system section resets the WiFi credentials. Take a look for a WiFi named shelly1-xxxx and open 192.168.33.1 and resetup the WiFi credentials

That worked fine - thank you very much!
After entering the wrong Wifi name (upper case / lower case), I had to manually reset the Shelly again. Power off/on and 5 x push the switch.
