### ISSUE TITLE
Can't restore original firmare

### ISSUE THREAD

**Issue by josleng** [mongoose-os-apps/shelly-homekit#68]
Hi, I Have installed the firmware 1.9.1 but doesn't work with Alexa, only with Apple HomeKit. I would like to restore the original firmware. I downloaded the original firmware, but when I go to the ip adress of the shelly on my browser and I try to upload the original firmware the site tell me: -1 Archived file size is unknown.

how I can restore it via web?

thank you!

**Comment by rojer** [comment]
probably same as #58.
apparently, Mac OS, ever helpful, will extract ZIP files for your convenience.
that's nice and all, but the ZIP files it creates are not suitable for mos as update packages (long story).
make sure you upload _exactly_ the file you downloaded, not the one you created yourself.
