### ISSUE TITLE
2.5PM switch status via REST API / GET?

### ISSUE THREAD

**Issue by thncode** [mongoose-os-apps/shelly-homekit#683]
How can I request this / is this possible?

cheers,
 Thomas

**Comment by timoschilling** [comment]
It’s possible /rpc/Shelly.GetInfoExt there you find `components[0][“state”]`

**Comment by thncode** [comment]
thx a lot - where is this documented???

**Comment by timoschilling** [comment]
Looks like it’s not documented at the moment. The rest of the api docs are here https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development#API

@andyblac would you like to improve the wiki there?

**Comment by thncode** [comment]
sorry, one more question: is relay state toggle possible as well?

**Comment by andyblac** [comment]
> sorry, one more question: is relay state toggle possible as well?

unfortuantly no, the api does not have a toggle action.

**Comment by andyblac** [comment]
> thx a lot - where is this documented???

try something
```
andrews-mbp-wifi:tools andrewblackburn$ curl -s http://andys-bedroom-sw.local/rpc/Shelly.GetInfoExt | jq  --raw-output '.components[0].state'
false
```

**Comment by timoschilling** [comment]
I think we can close this for now, question is answered and google feature request has his own issue somewhere
