### ISSUE TITLE
Doorbell not supported by HomeKit 

### ISSUE THREAD

**Issue by Dabr422** [mongoose-os-apps/shelly-homekit#684]
Hi, I’ve tried to configure my latest Shelly for doorbell mode and get it to work. Sort of…
The unit shows as two parts, a switch and a doorbell. If I close the input circuit I get a notification as intended. But the doorbell part shows in HomeKit as “not supported”. What am I doing wrong? I attach a screen dump of my HomeKit page and the config of the Shelly. I’m running v2.9.0. Thanks

Daniel

![5EF8BEE7-A1BE-4C7D-9D03-26215A14F593](https://user-images.githubusercontent.com/75532572/118711939-736e3a00-b820-11eb-9a4a-cb7b84fa851a.jpeg)
![B5E3D90A-E357-4741-A1F8-04F7623F7C14](https://user-images.githubusercontent.com/75532572/118712031-926ccc00-b820-11eb-8184-b188778aad59.png)
![C408AE0E-454E-45FA-9199-A228AB2FD3B2](https://user-images.githubusercontent.com/75532572/118712039-939df900-b820-11eb-8a26-3caa515f3568.png)

**Comment by jsiegenthaler** [comment]
That's the way it is. A simple Doorbell will provide notifications, but is not supported (any more). Only video doorbells are supported. If you have a raspberry pi and Homebridge, use camera-ffmpeg to make a video doorbell using a gif or still image as the video part. That's what I do.

**Comment by Dabr422** [comment]
Thanks for for quick reply. I suspected it was like that but it’s good to get it confirmed.
