### ISSUE TITLE
Shelly Dimmer 2 Support

### ISSUE THREAD

**Issue by guymorgen88** [mongoose-os-apps/shelly-homekit#688]
Hi all,

Is Shelly Dimmer 2 support?
I saw the table  "Summary of supported devices and features" but I'm not sure if it's 100% ok.

And btw, if it's not supported, is there any other device similar to the shelly that support Homekit?
Thanks for your help

**Comment by timoschilling** [comment]
The Dimmer2 is not supported at the moment, feature request is in #14. 

Simulator device, depends on your needs. If you need to dimm 110-240V there is no alternative. If you can dimm 12-24V you can use the RGBW2 which is supported. Or you use one of the Shelly bulbs which will be supported in the next 1-2 month.

**Comment by guymorgen88** [comment]
Hey Tim, 

I need a dime for 110-240V. Any estimation when will the Dimmer 2 be supported?

**Comment by timoschilling** [comment]
No

**Comment by sg-generix** [comment]
> The Dimmer2 is not supported at the moment, feature request is in #14.
> 
> Simulator device, depends on your needs. If you need to dimm 110-240V there is no alternative. If you can dimm 12-24V you can use the RGBW2 which is supported. Or you use one of the Shelly bulbs which will be supported in the next 1-2 month.

Hello, thank you for great support @timoschilling 
Do you have idea when will be ready the support of shelly bulbs?
