### ISSUE TITLE
Shelly 1 HomeKit Settings 

### ISSUE THREAD

**Issue by rtat1701** [mongoose-os-apps/shelly-homekit#691]
Hello everybody,

 Shelly 1 can no longer be added in HomeKit.
 HomeKit Settings no longer accepts setup codes.

 Did you have that too?
 What can this be?
 thanks

**Comment by BlancoDeMallloca** [comment]
Try to reset Shelly HomeKit Settings and set a new HomeKit code. This solved my problem two days ago.

**Comment by rtat1701** [comment]
I have already done that.  but not possible.
