### ISSUE TITLE
Shelly 1L stuck in Loading screen

### ISSUE THREAD

**Issue by Jasko65** [mongoose-os-apps/shelly-homekit#696]
Hello, 

i did a mistake! Instate of entering the WIFI PW in right section I put in the security one. So my shelly is stuck in UI with the loading screen. I tried to reset it with "--local -file SHSW-L.zip" but it always says "unrecognized arguments: --local -file". So is there any chance to reset it without internet or to get it out loading screen?

BG

**Comment by andyblac** [comment]
> Hello,
> 
> it a mistake! Instate of entering the WIFI PW in right section I put in the security one. So my shelly is stuck in UI with the loading screen. I tried to reset it with "--local -file SHSW-L.zip" but it always says "unrecognized arguments: --local -file". So is there any chance to reset it without internet or to get it out loading screen?
> 
> BG

to use local file it's `--local-file xxxx.zip`

**Comment by Jasko65** [comment]
> > Hello,
> > it a mistake! Instate of entering the WIFI PW in right section I put in the security one. So my shelly is stuck in UI with the loading screen. I tried to reset it with "--local -file SHSW-L.zip" but it always says "unrecognized arguments: --local -file". So is there any chance to reset it without internet or to get it out loading screen?
> > BG
> 
> to use local file it's `--local-file xxxx.zip` (no space between --local and -file), but it will still require access to the shelly via the IP address, the only way to refresh without using an IP is to flash via serial connection.

I have access via its own wifi but without internet connection. I can communicate with 192.168.33.1 but via Terminal it won't find it.

**Comment by andyblac** [comment]
can you login UI when on own wifi ?

**Comment by Jasko65** [comment]
No it shows me it is loading. And i can't do anything. I also tried to restart it but without success.

**Comment by andyblac** [comment]
ok, it seems the only way is to refresh by serial

**Comment by andyblac** [comment]
do you not get the password prompt ?

**Comment by Jasko65** [comment]
Okay. Thank you for your support!

**Comment by rojer** [comment]
> I can communicate with 192.168.33.1

when you open http://192.168.33.1/ does the UI load?

**Comment by Jasko65** [comment]
> do you not get the password prompt ?

no
> > I can communicate with 192.168.33.1
> 
> when you open http://192.168.33.1/ does the UI load?

no it just tells me it is loading

**Comment by Jasko65** [comment]
I just found a solution for me. I held the reset button. Now it seems working

**Comment by rojer** [comment]
great, thanks

**Comment by rojer** [comment]
if you ever need to recover a device, it's documented here - https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery
