### ISSUE TITLE
Valve not available as accessory in automations 

### ISSUE THREAD

**Issue by rhvs** [mongoose-os-apps/shelly-homekit#702]
Hi! Maybe a bug maybe not… I can’t find if it’s usually available for “official” HomeKit valves, but when I select a Shelly 2.5 as a valve - it does not appear in the automations tab as an accessory to be controlled/included in automations. That does work when I select it as a switch or fan.

**Comment by timoschilling** [comment]
It's not a bug, I would call it a missing feature in the Home app. Please read https://github.com/mongoose-os-apps/shelly-homekit/issues/43#issuecomment-800751433 for a workaround.
