### ISSUE TITLE
Homekit shows Gate door Blocked

### ISSUE THREAD

**Issue by TonyJacobi** [mongoose-os-apps/shelly-homekit#704]
I have installed the Shelly 1 to my gate opener. When I open the gate in Homekit, it shows opening and then "Opened". When I close the gate, the gate is closing and when it is closed, Homekit shows "Blocked" and in the Gate icon the status "Open" (while the gate is closed) and an orange exclamation mark.

I already changed the moving time, did not help. 

Any help on this issue is highly appreciated. TIA.

<img width="239" alt="Schermafbeelding 2021-06-12 om 10 59 11" src="https://user-images.githubusercontent.com/85753821/121771041-4423c200-cb6d-11eb-9af3-cbfef5ab21e3.png">

**Comment by timoschilling** [comment]
Maybe your close sensors is misconfigured or didn't work well.

**Comment by TonyJacobi** [comment]
Indeed Timo, changing it into normally open instead of normally closed, even though the switch is NC, solved the problem.

thanks!
