### ISSUE TITLE
2 of my shelly 2.5 went dead after i switched state to `edge` any clue?

### ISSUE THREAD

**Issue by zeltak** [mongoose-os-apps/shelly-homekit#709]
Hi all

after today switching 2 of my shelly 2.5 to `edge` in the switch mode i cant connect to them any more or ping them

any clue? is this a known issues?

any advice would be appreciated!

best

Z

**Comment by rojer** [comment]
just tested - works fine, no issues.
try powering the device off and on. if it doesn't come back, try recovery procedures - https://github.com/mongoose-os-apps/shelly-homekit/wiki/Recovery#from-crash-looping-or-otherwise-misbehaving-firmware

**Comment by zeltak** [comment]
thx @rojer 

the recovery procedure you referred to helped me get things back up and running

thx

Z
