### ISSUE TITLE
shelly 1PM can't update OTA 

### ISSUE THREAD

**Issue by Tomer51m** [mongoose-os-apps/shelly-homekit#71]
Hi,
I am trying to update my Shelly 1PM but for some reason it will not update. 
I tried reseting few times and changing wifi networks.

It looks like it's trying and the LED is blinking, but at the end of the process I go to the shelly IP address and see the old firm working perfectly.

This is the response I get when trying to update:
`{"status":"updating","has_update":false,"new_version":"20200312-124223/v1.6.1@112262fd","old_version":"20200312-124223/v1.6.1@112262fd"}`
new version and old version are the same, but no homeKit support 🤷‍♂️

any help with be appreciated.

**Comment by andyblac** [comment]
what OTA url are you using ?

**Comment by Tomer51m** [comment]
http://A.B.C.D/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly1PM.zip
Changing the A.B.C.D to the IP of the shelly on my network.

**Comment by andyblac** [comment]
hmm, the only issue i have had when try to use OTA, is if the shelly does not have access to a working internet / DNS. make sure your shelly has outside access, some people firewall their IoT network.

**Comment by Tomer51m** [comment]
How can I check if it has internet access?
I do have firewall. I will try to disable it.

**Comment by andyblac** [comment]
is this still an issue ?

**Comment by andyblac** [comment]
@rojer OP has not responded maybe close it ?

**Comment by rojer** [comment]
yes, @Tomer51m please reopen if it's still an issue
