### ISSUE TITLE
color effects

### ISSUE THREAD

**Issue by djtasies** [mongoose-os-apps/shelly-homekit#711]
Hola a todos.
Muchisimas gracias por vuestro trabajo, ya tengo toda la casa con shelly1 , shelly2.5 y shellyRGBW2.
He visto que alguien consigue crear efectos de luz con otra app y creando una escena en homekit, te dejo el link: https://www.youtube.com/watch?v=2vgsBaVcC_Q

Seria esto possible Rojer?

Muchas gracias!

**Comment by timoschilling** [comment]
> Hello everybody.
> Thank you very much for your work, I already have the whole house with shelly1, shelly2.5 and shellyRGBW2.
> I have seen that someone manages to create light effects with another app and creating a scene in homekit, I leave you the link: https://www.youtube.com/watch?v=2vgsBaVcC_Q
> 
> Is this possible Rojer?
> 
> Thank you!
