### ISSUE TITLE
Support magnetic sensor as add-on on Shelly 1 for Garage door mode

### ISSUE THREAD

**Issue by vistalba** [mongoose-os-apps/shelly-homekit#713]
I use Shelly 1 with garage door mode for my 24VDC garage door.
Shelly is powered by the 24VDC from the motor unit directly.
I added on magnetic contact to detect when door is closed.
Now I want to add another magnetic contact to also get open state with Shelly 1 Add-on.
As I can see this isn't supported in the UI. (Or at least it doesn't show up on my test shelly).

Any Plans to make this possible?

So the SW is the "closed" state sensor and the Add-on sensor will report the open state like Shelly 2.5 does?

**Comment by timoschilling** [comment]
I think thats an interesting feature.

**Comment by vistalba** [comment]
Yes. I can't use Shelly 2.5 as it isn't "potentialfrei" so the options I have at the moment is:

- Use Shelly 2.5 with a additional relais
- Use Shelly 1 with just one contact sensor 

I do not like both of them. Then I saw, that this Add-on with magnetic contact is already implementet in Shelly stock firmware. So here we are :D

**Comment by Pixel-Chris** [comment]
+1   Add-on support !!!  for shelly 1

**Comment by Pixel-Chris** [comment]
Is there some time for that left?

**Comment by Pixel-Chris** [comment]
See #186 also

**Comment by daitarn31974** [comment]
+1 here too.
I would like to have the opportunity to use addon on a shelly1 so that I would be able to use them as contact sensors for home doors running Shelly with 220V and not running power on the magnetic sensor. Actually it is possible only in 12/24V but I do not want to deploy 5/6 transformers around home

**Comment by lucaspinelli85** [comment]
+1 !!!

**Comment by Pixel-Chris** [comment]
Is that working now?

**Comment by timoschilling** [comment]
It will work when this issue is closed.

**Comment by Pixel-Chris** [comment]
Temperature add-on is not the same?

**Comment by timoschilling** [comment]
@Pixel-Chris it's the same hardware add on, but on the software side that are two different things.

**Comment by marcus-aa** [comment]
This would be a great door opener feature. Two sensors, one dry relay.  Exactly what most door openers need.

**Comment by Pixel-Chris** [comment]
Maybe the next…? 😉

**Comment by markirb** [comment]
this is now in a PR, where you can find a Testing version for Shelly1, if someone wants to try it out https://github.com/mongoose-os-apps/shelly-homekit/pull/967

**Comment by vistalba** [comment]
@markirb How do I get the ZIP file to flash the Shelly?

**Comment by markirb** [comment]
upload on webinterface

**Comment by vistalba** [comment]
Lol, you get me wrong. Sorry for that. Where can I dpwnload the ZIP to flash it?

**Comment by markirb** [comment]
Haha I wondered 😂 https://github.com/mongoose-os-apps/shelly-homekit/pull/967#issuecomment-1321210345
