### ISSUE TITLE
Shelly device with multiple accessories and serial numbers

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#716]
It seems that each accessory within a single device should be using a unique serial number.

![image](https://user-images.githubusercontent.com/77936/124270715-7b660d00-db34-11eb-903e-d00b3711ccf9.png)

Can we add add '-?' ? being the accessory ID, to the main serial number for each accessory?

This should help with compatibility with other HomeKit apps

**Comment by rojer** [comment]
i guess we can amke it even more fancy, e.g. `${model}-${mac}-${aid}`
it's simple enough, would you like to give it a go yourself?

**Comment by andyblac** [comment]
Atm I have no computer I had to return my new iMac as lan port was faulty, won't get replacement till 2 August

**Comment by rojer** [comment]
ah, i see. no problem, made the change myself.
serial number will now include -${aid} at the end. i decided no to include model, after all.

**Comment by rojer** [comment]
pushed 2.9.2-beta1
