### ISSUE TITLE
Vintage bulbs firmware

### ISSUE THREAD

**Issue by appliko** [mongoose-os-apps/shelly-homekit#719]
Hi,
are Vintage bulbs in the pipeline ?

**Comment by timoschilling** [comment]
Yes

**Comment by appliko** [comment]
Do there is any date ?

**Comment by appliko** [comment]
Hi, apologize for refreshing. Any update on Vintage Bulbs support ?
Ideally, also the DUO (that should be so similar to the rgbw)
Thanks !

**Comment by timoschilling** [comment]
Will be implement in #885

**Comment by rojer** [comment]
pushed in 2.11.0-alpha9, please help test it (#868).
