### ISSUE TITLE
JSON-Endpoint for Prometheus

### ISSUE THREAD

**Issue by Subnet-Zero** [mongoose-os-apps/shelly-homekit#722]
Hi,

i use the JSON-Endpoint in the firmware with a JSON-Exporter to monitor the switch-state by prometheus.

URL: http://IP-address/rpc/Shelly.GetInf

`path: $.components.initial`

This information is no longer available (it was removed by an update, i think).
Could you bring this information back to this endpoint? That would be awesome. ♥️

Thanks,
Jan

**Comment by andyblac** [comment]
Try http://ip-address/rpc/Shelly.GetInfoExt

**Comment by Subnet-Zero** [comment]
Great, thanks.
