### ISSUE TITLE
Roaming RSSI in web interface

### ISSUE THREAD

**Issue by bmpalmeida** [mongoose-os-apps/shelly-homekit#724]
Hello all,

First let me say that this new version completely solved the problems i was having with Asus routers. everything is stable and connected.

It will be possible, by any chance, to have the Roaming RSSI configurable in the web interface? -80 dBm in some cases is too high to go to the correct hotspot.

Thanks

**Comment by timoschilling** [comment]
We can add that option. 

Until then you can set it via `mos` cli.

**Comment by rojer** [comment]
what do you want it set to? i'm open to adjusting the default if it's like -78

**Comment by 5xPa** [comment]
How do I set it using mos cli?

**Comment by bmpalmeida** [comment]
> what do you want it set to? i'm open to adjusting the default if it's like -78

In my case I would go -70. Because I have a 3 stories house, with a router each floor. And  I’m having the Shellies at around -75 connected to the wrong floor and they don’t roam. 

But this is definitely and enhancement. , because right now the system is really stable and all the nodes are connected. I will explorer mos cli to fine tune it. 

Thanks again for this great work!!!

**Comment by rojer** [comment]
honestly, -75 is a perfectly fine signal level, so i won't make it a default.
but if you insist...

```
$ mos --port ws://192.168.11.103/rpc config-set wifi.sta_roam_rssi_thr=-75
Getting configuration...
Setting new configuration...
```

substitute ip address of your device, of course.
you can explore other configuration options with `config-get` but be careful, you may get device to not boot.
adding `--try-once` is a good safety measure when playing with config - it will apply the change only for next reboot.
