### ISSUE TITLE
Problems by flashing my Shelly 2 Dimmer

### ISSUE THREAD

**Issue by pfulu** [mongoose-os-apps/shelly-homekit#725]
Hey, 

first of all, I think this possibility of HomeKit integration is great, thank you for this!

But unfortunately I have a few problems! I just started to flashing my Shellys and got some problems with the Shelly 2. When flashing the Shelly1 and Shelly2.5 everything went as planned. But if I was flashing the Shelly 2.5 nothing happened (look attachment)! 

Can you help me with this problem? Thanks in advance!

Best regards
Philipp

![sc_shelly25](https://user-images.githubusercontent.com/87203219/125117647-d1b3ec80-e0ee-11eb-97bd-17b858c2b692.PNG)

**Comment by timoschilling** [comment]
Shelly Dimmer 2 isn’t supported yet, we support Shelly 2 that’s a outdated pre version of the 2.5.
