### ISSUE TITLE
Installation version error

### ISSUE THREAD

**Issue by Jaguaza** [mongoose-os-apps/shelly-homekit#73]
Device to flash:
Shelly 1

flashing url:
http: //A.B.C.D/ota? url = http: //rojer.me/files/shelly/shelly-homekit-Shelly1.zip

Version after flashing:
Shelly HomeKit FW 1.9.1

After flashing a device shelly_1 returns version 1.9.1, having to download the relase 2.0.0 zip and update manually.

**Comment by rojer** [comment]
2.0.0 is a pre-release, i haven't pushed the binaries to the default download locations yet, waiting for users to test the new features.
