### ISSUE TITLE
Rgbw2 color on poweron

### ISSUE THREAD

**Issue by saddiego** [mongoose-os-apps/shelly-homekit#730]
Hi, i have rgbw2 and strip led rgbw, i want to set white color on poweron, and before i change color, its possible? Thanks

**Comment by timoschilling** [comment]
Yes with a scene

**Comment by andyblac** [comment]
Think he means default on colour

**Comment by timoschilling** [comment]
Yes with a scene or with a automatization depending on what you exactly want to do

**Comment by saddiego** [comment]
You can help me with scene? Thanks
