### ISSUE TITLE
Occasionally Manual Switch Input doesn’t change Output State

### ISSUE THREAD

**Issue by AndrewJLockhart** [mongoose-os-apps/shelly-homekit#732]
Hi,
I have Shelley’s all over the house flashed with the HomeKit firmware. Usually it works amazingly well.
But occasionally when I flick the manual switch the state of the light does not change and I have to flick it again.

I have normal (toggle switches) and the mode is set to Edge Detection. Is anyone else seeing this behaviour?

Regards

**Comment by jonasman** [comment]
Same issue in PM2.5, input mode: toggle
