### ISSUE TITLE
Cant update shellys 1 or 2.5

### ISSUE THREAD

**Issue by jorgerray** [mongoose-os-apps/shelly-homekit#733]
16 shellys don't work after 2.9.2 update

**Comment by rojer** [comment]
which version were they running before? clarify "don't work" - do external buttons still work? what LED indication do you see?

**Comment by jorgerray** [comment]
2.9.1 to 2.9.2
I cant see led status or external buttons

**Comment by rojer** [comment]
try powering them off an on again.
other than thjat, i'll need some info to go on.

by external i mean switches - if you have extern switch connected to shelly ythat controls ouput, does that still work?

**Comment by jorgerray** [comment]
After upgrading from 2.9.1 to 2.9.2 only one shelly 1 shows the QR code in the settings.
When I try to update them again, I download the 2.9.1 zip but I only get a flash from the web and it doesn't update.
I have already tried to leave them without electricity and turn them on but have not achieved anything. In the iOS Home application I have at 16 shellys with no response.
I have not modified anything on my Wi-Fi network.
No extern switch connected to shellys
How do I get the thjat?
Thanks

**Comment by jorgerray** [comment]
After uninstall every shelly from Home and unpair and pair again, everything works.
Thanks

**Comment by timoschilling** [comment]
I noticed a similar issue with the QR setup on updated devices. All devices had as hap code under 2.9.1. After the update I clicked setup to get a QR code. Then I wasn’t able to pair via QR, clicking reset and then again setup solved the problem for me

**Comment by rojer** [comment]
actually, that's a bug. we shouldn't be showing "setup" when device is already paired, only "reset" should be displayed in that case.
i'll have a look later.

**Comment by rojer** [comment]
fixed in 2.9.3
