### ISSUE TITLE
Wireless doorbell

### ISSUE THREAD

**Issue by cappadanna** [mongoose-os-apps/shelly-homekit#735]
Hi. I'm trying to connect an Aqara wireless mini switch (zigbee) and have it trigger a Shelly 1 that would control a doorbell chime via its relay. I've set the Shelly up using doorbell HAP mode. I have the Aqara switch controlling the relay but is there any way to have the Aqara switch to also trigger "Input 1 - doorbell" so I also get the doorbell notification in the home app?

**Comment by timoschilling** [comment]
That’s not possible
