### ISSUE TITLE
Shellyi3 - problem to revert

### ISSUE THREAD

**Issue by slaw47** [mongoose-os-apps/shelly-homekit#744]
When I try to revert is come message:
Error downloading: TypeError: Origin http://192.168.68.78 is not allowed by Access-Control-Allow-Origin

The original file also not exist.

**Comment by rojer** [comment]
can you attach a screenshot? i'm not sure where you can see that message

**Comment by slaw47** [comment]
Hello,

Please find it under Revert button

Pozdrawiam / Best regards
Slawomir Wilinski

**Comment by slaw47** [comment]
Hello,

When I try download the Stock firmware from the official URL's below, and upload via web interface.:

I received the screen like print screed.

Pozdrawiam / Best regards
Slawomir Wilinski

**Comment by rojer** [comment]
i don't see any images. i think you are responding by email and github doesn't add attachments.

**Comment by bikejoco** [comment]
Hi,

I also will revert to the original Shelly Firmware. But I get the following Error:
<img width="481" alt="Bildschirmfoto 2021-07-26 um 11 57 49" src="https://user-images.githubusercontent.com/65533701/126970753-aebe922c-13d8-4de0-a257-7f30f452f1a8.png">
How can I fix this Problem? In the Router-Settings (FritzBox 7530) the Shelly is allowed to connect to the internet.

Thanks for Help

JOHANNES

**Comment by slaw47** [comment]
Please find attachments: 
![Zrzut ekranu 2021-07-26 o 11 50 29](https://user-images.githubusercontent.com/6368613/126971361-ee6b1cd6-a54c-4322-90ee-90b24ba4524c.png)
![Zrzut ekranu 2021-07-26 o 11 25 46](https://user-images.githubusercontent.com/6368613/126971363-bc9bd693-1517-487c-a54f-f64e3f6342d7.png)

**Comment by rojer** [comment]
firmware is actually fetched by your browser and then uploaded to shelly. the browser must be able to fetch `https://rojer.me/files/shelly/stock/XXX.zip` (XXX being the stock model) and then upload to the device.
what browser are you using?

**Comment by rojer** [comment]
hm, offical API endpoint does not provide firmware for shelly i3, i don't see SHIX3-1 in the JSON document. weird.

**Comment by slaw47** [comment]
Safari 14.1.2 (15611.3.10.1.5, 15611)

**Comment by bikejoco** [comment]
I use Firefox 89.0.2 on MacOS

**Comment by slaw47** [comment]
the other one Shelly Switch1 I can to download, the Shelly i3 not

**Comment by rojer** [comment]
right, there's no official stock fw for i3 for some reason, i am investigating.

**Comment by bikejoco** [comment]
> right, there's no official stock fw for i3 for some reason, i am investigating.

THANKS

**Comment by rojer** [comment]
i found 1.10.4 in my archive and put it up. you should be able to revert now.

**Comment by rojer** [comment]
i believe this is fixed, feel free to reopen if not.

**Comment by slaw47** [comment]
All is OK, thank you
