### ISSUE TITLE
Same problem shelly1-homekit #539

### ISSUE THREAD

**Issue by SanchoCZ** [mongoose-os-apps/shelly-homekit#745]
Hi, 
I have the same problem. Deleting Homekit didn't help. Can there be something in the Apple TV settings? Other certified accessories are displayed on both Wi-Fi and LTE.

App: switch1 2.9.3 20210714-205744/2.9.3-g2f89855-master
Uptime: 5330.76
RAM: 24244 free, 14856 min free
HAP server port: 9000
HAP config number: 103
HAP connection stats: 0/2/12
HAP connections:
  192.168.1.156:49354 nc 0x3fff5a94f 0x200000 io 7 ts 0x3fff51ac rd 6
  192.168.1.204:60563 nc 0x3fff52e4f 0x200000 io 7 ts 0x3fff5b8c rd 2487
 Total: 2
HAP sessions:
  0: s 0x3ffef4d0 ts 0x3fff5b8c o 1 st 1 ts 5324315
  1: s 0x3ffef810 ts 0x3fff51ac o 1 st 1 ts 5324192
 Total: 2

192.168.1.204 is iMac IP
192.168.1.156 is iPhone

Thank you very much for any help

**Comment by timoschilling** [comment]
Do you have an HomePod, Apple TV or iPad at your home, which is setup as home hub?

**Comment by timoschilling** [comment]
I think your problem is in your HomeKit setup and not on your Shelly. The Shelly has no knowledge about outside WiFi access, that’s only done by the home hub. 

Possible other problem we found in a similar issue: if a other accessory or bridge response to slow it can be happen that a other accessory (the Shelly) will not be updated 

I close this issue because it’s not a Shelly issue

**Comment by SanchoCZ** [comment]
I have an Apple TV. What can be in the HomeKit settings if I control other accessories (vocolinc) outside the home network?Why don't they just see Shelly's devices?

**Comment by timoschilling** [comment]
For example your Apple TV didn’t have a connection to your Shelly only your iPhone and your Mac have one

**Comment by SanchoCZ** [comment]
should the Apple TV IP address appear in that log?

**Comment by andyblac** [comment]
Yes the AppleTV hub IP should be listed

**Comment by SanchoCZ** [comment]
I have this log when I am logged in via LTE


App: switch1 2.9.3 20210714-205744/2.9.3-g2f89855-master
Uptime: 133658.28
RAM: 24452 free, 14160 min free
HAP server port: 9007
HAP config number: 7
HAP connection stats: 0/0/12
HAP connections:
 Total: 0
HAP sessions:
 Total: 0

**Comment by SanchoCZ** [comment]
![Uploading F23197AD-07B7-4137-B199-957C5F5EDE3E.jpeg…]()

**Comment by SanchoCZ** [comment]
![1A948ECC-803E-4D24-B51A-27E70EDD2F66](https://user-images.githubusercontent.com/88033235/127444440-deeba3ec-3214-4485-82c5-3d93b872365c.jpeg)

**Comment by SanchoCZ** [comment]
I put Apple TV in the factory settings, I removed the Home application. He set everything up again. The result is the same :-(

**Comment by timoschilling** [comment]
Maybe you didn’t setup you Apple TV as home hub. If your Apple TV isn’t connected to the Shelly that’s is definitely the problem. The Apple TV acts as proxy to your home. Read the apple support pages about how to setup.

**Comment by timoschilling** [comment]
About your VOCO device: is it WiFi or Bluetooth based?

**Comment by SanchoCZ** [comment]
WiFi
https://www.vocolinc.eu/support/english-tutorials/vocolinc-powerstrip-vp3

**Comment by SanchoCZ** [comment]
Is this right?
![CA41C86D-1C37-459A-B077-27D6CB250E4D](https://user-images.githubusercontent.com/88033235/127470600-095a17be-6956-4498-8290-b9c36c320adf.jpeg)

**Comment by andyblac** [comment]
yes, as this firmware dose not have the official license from Apple.

**Comment by andyblac** [comment]
make sure you have HomeKit support enabled on your AppleTV.

**Comment by SanchoCZ** [comment]
This settings? 

![62404E9F-84E7-43E1-B22A-F984386640A0](https://user-images.githubusercontent.com/88033235/127474774-0bbdf96e-6f47-40c7-b8be-1556b070212c.jpeg)

My Home is connected

**Comment by SanchoCZ** [comment]
I was connected via cable.  when I disconnected the cable, I entered the data for wifi and it works.  you also don't have a cable connected?  I have a dual band modem
