### ISSUE TITLE
Problems adding Shelly to HomeKit - Firmware version 2.9.3

### ISSUE THREAD

**Issue by hluhring** [mongoose-os-apps/shelly-homekit#748]
When I try adding my first Shelly 1 to HomeKit, I get the message "Unable to Add Accessory -- Failed to add the accessory."  I'm using the Home app on my iPhone. Both the iPhone and Shelly 1 are on a 2.4 GHz Wifi network on a Verizon G3100 router. There is no mesh wifi network involved. 

On the web UI, in the HomeKit Settings section, I click on Setup. This gives me a QR code. I aim my iPhone camera at this. It brings up the Home app. I click "Open in Home". It shows that it is a switch. I click "Add to Home". I choose my home. It says "Uncertified Accessory". I click "Add Anyway". It says "Connecting to Switch". 

And now it works!!  It didn't used to!!  I tried it several times, and it would not add the accessory. Just before composing this message, I rebooted the Shelly 1. And now it works. I'll go ahead and submit this in case it helps someone else.

**Comment by Xaruqui** [comment]
Hi there, happened exactly the same to me. Wouldn't connect to HK until rebooting.

Thanks for sharing.

**Comment by rojer** [comment]
is this with 2.9.5 or still 2.9.3?

**Comment by Xaruqui** [comment]
Sorry I didn’t mention it. Latest 2.9.5

Congratulations for your work, I fucking love it!


> El 2 ag 2021, a les 22:29, Deomid Ryabkov ***@***.***> va escriure:
> 
> 
> is this with 2.9.5 or still 2.9.3?
>

**Comment by rojer** [comment]
setting up pairing involves some expensive operations that sometimes cause the device to miss a few AP beacons and wifi connection to get dropped as a result, may need a couple tries before it's successful.

**Comment by hluhring** [comment]
> is this with 2.9.5 or still 2.9.3?
> […](#)

2.9.3

**Comment by rojer** [comment]
after some extensive work, i managed to reduce the amount of time device is unreponsive during pairing setup and improved pairing success rate significantly, at least in my setting. it still occasionally fails but it's much better tahn before. this will be released in the next version.

**Comment by Xaruqui** [comment]
Many thanks. This is highly appreciated.
