### ISSUE TITLE
FAN device request.

### ISSUE THREAD

**Issue by Jaguaza** [mongoose-os-apps/shelly-homekit#75]
Petition:
Fan device.

Utilities:
For shelly controlled fans we can declare them as such even if their function is only on / off. Although possibly with new shelly devices you can add intensity etc. But for now with an on / off is enough.

**Comment by rojer** [comment]
if anyone feels like doing this before i get to it, here's an example change - https://github.com/mongoose-os-apps/shelly-homekit/commit/1ef5e0c5dd5f1032905e8ef14d5c6b104b77f6bd

**Comment by Jaguaza** [comment]
@rojer Sorry for disturbing you.
We have the fan with swicht Mode for on/off
![IMG_2673](https://user-images.githubusercontent.com/46264854/82158944-53154380-988b-11ea-92c5-9d6bc3e18e35.PNG)

Its not necesary either fan device because i think there is not a shelly device who can emulate a fan's remite control, It were a Nonsense.
We can Close this issue and if you want se can open other to plan the garage's device, because It Will be very used whith a shelly 1 by so many users.
![descarga](https://user-images.githubusercontent.com/46264854/82158952-5e686f00-988b-11ea-93cc-87f1d4c06588.jpg)

**Comment by Jaguaza** [comment]
@rojer ???

**Comment by rojer** [comment]
i still think it makes sense to add a fan device.

**Comment by Jaguaza** [comment]
> i still think it makes sense to add a fan device.

If you see it meaningfully, go against more devices better.  I can only say thank you.

I told Dimi if i could get contac whit you. I am spanish facebook's oficial support groups administrator.
As you think i can help you, Take on me.

**Comment by felixmueller** [comment]
Just a quick thought: isn't it true that every Outlet in HomeKit can be set as a Fan in the device settings (Show as:)?

**Comment by Jaguaza** [comment]
> Just a quick thought: isn't it true that every Outlet in HomeKit can be set as a Fan in the device settings (Show as:)?

Yes and no.  In switch you just change the icon, but the device is still a switch.  The Fan device in addition to an on and off can be associated with intensity or power of the fan spin.

**Comment by andyblac** [comment]
just the Shelly's allow the ability to control the voltage ?, thought they where just on/off and controlling the speed of a fan requires a voltage regulator ?

**Comment by rojer** [comment]
all characteristics of the fan service except "active" are optional. we will not be able to provide speed control, but that's fine.

**Comment by andyblac** [comment]
is the really required when you can simply choose "FAN" in HomeKit switch type settings ?

![IMG_0288](https://user-images.githubusercontent.com/77936/93712259-b15d7600-fb4c-11ea-8c4c-5eb000fe9d3a.jpeg)

**Comment by rojer** [comment]
yep, i think that's enough
