### ISSUE TITLE
Changing HAP type on Shelly i3 is not reflected in UI until after reboot

### ISSUE THREAD

**Issue by marcus-aa** [mongoose-os-apps/shelly-homekit#751]
When changing HAP type it immediately changes back to the previous setting when pressing Save. Even reloading the page still shows the previous type. But after a reboot the newly selected type is shown. Changing it again shows the same problem and requires a new reboot.

Firmware 
Version: 2.9.3
Build: 20210714-205939/2.9.3-g2f89855-master

**Comment by marcus-aa** [comment]
BTW, why is it called "shellyix3" in its ID??

**Comment by timoschilling** [comment]
shellyix3 is the internal name of the shelly

**Comment by timoschilling** [comment]
double of #648

**Comment by marcus-aa** [comment]
Similar, but not identical.  2.5 works fine when changing HAP type but does not update UI when changing main mode (or to detached input), but the mode select box IS changed.

On i3, the Hap type select box reverts by itself to old setting.

**Comment by rojer** [comment]
fixed, will be in the next release.
