### ISSUE TITLE
Upgrade Shelly 2.5 to 2.9.4 looses Switch 2

### ISSUE THREAD

**Issue by Obikela88** [mongoose-os-apps/shelly-homekit#755]
Hi
I started to update my Shelly's 2.5 with the latest update 2.9.4.
After 5 updates, I noticed, that the switch-names are gone as well as the complete section of Switch 2.
Please fix asap.

**Comment by MilanBacaCz** [comment]
same here

**Comment by rojer** [comment]
ugh, last-minute cleanups are always a bad idea... sorry about that, fixing.

**Comment by rojer** [comment]
pushed 2.9.5
