### ISSUE TITLE
Automation menu is missing

### ISSUE THREAD

**Issue by SanchoCZ** [mongoose-os-apps/shelly-homekit#759]
Hi, I have several Shelly devices logged in to HomeKit.  In automation, I don't offer me the option for Arrive or Leave.  Will it work in the future? 
![DDF1A204-0257-42E7-A6FE-1AA47E823F60](https://user-images.githubusercontent.com/88033235/127856280-5e767d5d-843f-4ccf-b8be-b11656a18d29.jpeg)

**Comment by andyblac** [comment]
do you have location allowed for homeKit in settings ?

**Comment by SanchoCZ** [comment]
Yes I have
![316177D8-6C9E-4445-9F5C-E0CBA05F979F](https://user-images.githubusercontent.com/88033235/127864573-f5a5a121-e4ba-48e5-95d2-426460cdb40b.png)

**Comment by timoschilling** [comment]
As @andyblac already said, isn’t not a issue with this firmware. HomeKit accessories didn’t have any knowledge about automatization's. That why I will close this issue. Please read the Apple documentation for help. 

But one hint: the HomeApp says it’s related to the find my iPhone settings. So maybe you need to enable find my iPhone to you that feature.
