### ISSUE TITLE
Switch 1 and 2.5: can’t add them to Home

### ISSUE THREAD

**Issue by Whiterabbit64** [mongoose-os-apps/shelly-homekit#76]
Hi.

I’ve just received My shelly 1 and 2.5 switches and moved them to homekit firmware 2.0.1.
I’ve fixed to each of them a code and once done I’ve tried to add them to Home on my iPhone but they are not detected even if I use the option to enter the code manually. 
Any solution yo have them reconized by Home ?

Thanks.

**Comment by Whiterabbit64** [comment]
Problem solved.

Apparently the switch didn't like my dual band WiFi network. I had to setup a dedicated 2.4GHz SSID for it and connect the iPhone on it too. The switch came up immediately in Home after that.

**Comment by Jaguaza** [comment]
👏🏻👏🏻👏🏻👏🏻👏🏻
