### ISSUE TITLE
option to disable inputs for childlock

### ISSUE THREAD

**Issue by Leo-W536** [mongoose-os-apps/shelly-homekit#761]
Hi, 
is it possible to create a "childlock button" to lock the phyical switch? Until now my workaround is to set "Input Mode" to "Detached" an disable both inputs, like this
![grafik](https://user-images.githubusercontent.com/73061724/128007881-cfaf5949-1289-4731-b9eb-66858a7e6d5a.png)

Thanks in advance!

**Comment by timoschilling** [comment]
His workaround breaks automatizations. 
I have the same use case and my current workflow is a Shelly one which controls the power line of the switch of a i3. 

I would like to reopen this as a feature request

**Comment by rojer** [comment]
why would it break automations?

**Comment by timoschilling** [comment]
Ah ok it’s make not the case for a 2.5 in with Switches, but it is for a i3 with state less inputs. The inputs disappear from HK, so the automatisation is broken

**Comment by rojer** [comment]
so yes, i think the original issue was disabling inputs of a switch, and putting them to detached and then disabling the detached components is the way to go.

**Comment by timoschilling** [comment]
I would say no! Your way is a permanent way. I only want that from time to time to prevent the kids playing with the switches. 
With your way I need to reconfigure the switch each day. With a disable option I can simply toggle without breaking the HomeKit setup

**Comment by Leo-W536** [comment]
> I would say no! Your way is a permanent way. I only want that from time to time to prevent the kids playing with the switches. 
> 
> With your way I need to reconfigure the switch each day. With a disable option I can simply toggle without breaking the HomeKit setup. 
> 
> Even the original post requested a "childlock button"

Yes, that's the reason I was thinking about. Easily disable/enable the switches from time to time.
