### ISSUE TITLE
Shelly 2.5 temperature is very hot

### ISSUE THREAD

**Issue by bastian1387** [mongoose-os-apps/shelly-homekit#765]
Hey there,
i have 4 Shelly 2.5 as roller shutter and the temperature is over 80 Celcius.

![image](https://user-images.githubusercontent.com/88796646/129081875-5d87de63-d64d-436a-8121-41e93a15359c.png)

![image](https://user-images.githubusercontent.com/88796646/129082230-8202b5ea-6dc2-4118-866d-0b69ed74708d.png)

![image](https://user-images.githubusercontent.com/88796646/129082037-9967c95d-2efa-43fb-8184-22a79492adb2.png)

![image](https://user-images.githubusercontent.com/88796646/129082081-44fe3dd9-f65f-449d-8127-3c8fd8452fb1.png)

**Comment by doronkeren** [comment]
Same for me (fw version 2.9.5)
![image_123986672](https://user-images.githubusercontent.com/6460316/129566766-42c32398-52c7-4154-a49e-a864537acb95.JPG)

**Comment by timoschilling** [comment]
@doronkeren 60-70 is an expensive range

**Comment by rojer** [comment]
this is still ok, it's quite normal for electronics to get to 70 and up.
i am noting reports that the readings are higher for homekit fw than stock, but it could be because if a different temperature conversion curve we use for the NTC.
anyway, the actual readings are not that abnormal, it's ok.
