### ISSUE TITLE
Ability to change DNS (server) settings

### ISSUE THREAD

**Issue by fcercwer3** [mongoose-os-apps/shelly-homekit#768]
It would be nice to be able to change the DNS settings, could this be implemented?

**Comment by timoschilling** [comment]
Thats already possible if you use the [mongoose os cli](https://mongoose-os.com/docs/mongoose-os/quickstart/setup.md).
`mos --port ws://<HOST>/rpc config-set wifi.sta.nameserver=8.8.8.8`

**Comment by andyblac** [comment]
or script with ` --dns a.b.c.d`

**Comment by rojer** [comment]
> It would be nice to be able to change the DNS settings,

y tho?
literally the only thing DNS is used for is to resolve NTP server address. i don't want to overload the UI.

**Comment by rsalesas** [comment]
I'm trying to limit WAN access, what does it try to resolve?

**Comment by timoschilling** [comment]
@rsalesas we use time.google.com for ntp

**Comment by timoschilling** [comment]
DNS config is now added, you can load a test build here https://github.com/mongoose-os-apps/shelly-homekit/actions/runs/4028908761, at the button of the page is a releases files which includes build for each shelly.
