### ISSUE TITLE
Can't Add Device to HomeKit Failed with OSStatus code

### ISSUE THREAD

**Issue by Steifo** [mongoose-os-apps/shelly-homekit#769]
Hello,
Can't Add Device  to HomeKit (Shelly 2.5 or Shelly 1) Failed with OSStatus code -6764 (kCountErr)

Does anyone has an idea?
![IMG_2922](https://user-images.githubusercontent.com/89046925/129633060-59d55a32-7f84-4e39-a824-980dc4fd6720.jpg)

**Comment by rojer** [comment]
can you open device log (link in the system section) and perform pairing ith the log open? then post the contents here.

**Comment by Steifo** [comment]
![Bildschirmfoto 2021-08-18 um 09 02 34](https://user-images.githubusercontent.com/89046925/129852985-270c702e-bd24-4d26-a81f-86812c945212.png)

**Comment by Steifo** [comment]
I hope you mean that log

**Comment by rojer** [comment]
a number of stability improvements have been made, please try 2.10 beta - #773

**Comment by rojer** [comment]
hm. no idea, tbh, logs don't show anything unusual.
is it just this device or multiple?
and is it only this iDevice, or all of them?

**Comment by Steifo** [comment]
My other devices are working but I am not able to add any new device to HomeKit anymore with that firmware.

**Comment by timoschilling** [comment]
@Steifo is it still an issue?
