### ISSUE TITLE
Remove one of the two relays from Homekit

### ISSUE THREAD

**Issue by prrtzt** [mongoose-os-apps/shelly-homekit#77]
Hi,

One of my Shellies only uses 1 of the relays, but both show up in Homekit.

I am wondering if it would be possible to add an option to hide one of the switches from Homekit?

Thanks!

**Comment by col-tom** [comment]
Just move them to (dummy) room, e.g. _unused_

**Comment by prrtzt** [comment]
That's what I've been doing, but it's not very clean :)

**Comment by Jaguaza** [comment]
> Hi,
> 
> One of my Shellies only uses 1 of the relays, but both show up in Homekit.
> 
> I am wondering if it would be possible to add an option to hide one of the switches from Homekit?
> 
> Thanks!

Why don't you unify the relays in hk as a single device?

**Comment by prrtzt** [comment]
If you do that, then you cannot turn the light on and off in a single click. When you click on the device, it shows two switches, including the unused one.

Same issue if you ask Siri. If I say, turn off Wardrobe, it answers "There are more than one, you can ask me to turn off a specific one, or all".

Overall, it' is not very clean.

**Comment by ursusHU** [comment]
> Same issue if you ask Siri. If I ask "turn off the Bedroom", Siri will answer "There are more than one, you can ask me to turn off a specific one, or all".Did you try turn off bedroom lights ? It works well for me (shelly, plug (set as light), bedside lamp etc. is turned off)

**Comment by freddair** [comment]
You can “group” devices together so that they act as a single device both for Siri and the Home app.

**Comment by andyblac** [comment]
shelly 2.5 is a single device with 2 switches, grouping won't help.

**Comment by freddair** [comment]
What dou you mean by “it won’t help”? I just tried it out and it works as expected. You only see one switch. I included screenshots to show what I’ve done.![image](https://user-images.githubusercontent.com/63143560/83966379-35e7f980-a8ba-11ea-93cd-23a18d12b091.png)![image](https://user-images.githubusercontent.com/63143560/83966383-3b454400-a8ba-11ea-9fec-4613fe0e6ac3.png)![image](https://user-images.githubusercontent.com/63143560/83966388-4009f800-a8ba-11ea-8c4c-8df129e600d5.png)![image](https://user-images.githubusercontent.com/63143560/83966390-439d7f00-a8ba-11ea-9598-a0ac8fc68ddd.png)![image](https://user-images.githubusercontent.com/63143560/83966393-47c99c80-a8ba-11ea-86f3-f16736cfb2bb.png)

**Comment by andyblac** [comment]
the OP wants to hide the 2nd switch, as it not used, how does grouping help ?

**Comment by freddair** [comment]
The second switch is hidden within the group, which is shown as a single switch. It’s just a possibility, everyone can decide for their own if it suits their needs.

**Comment by Jaguaza** [comment]
I do not see it necessary, having the grouping of devices in homekit, it is a utility that right now I do not see necessary.

**Comment by rojer** [comment]
this is possible, switches can be disabled and will not appear in homekit, we just need to expose a control for this.

**Comment by andyblac** [comment]
this is now completed in https://github.com/mongoose-os-apps/shelly-homekit/releases/tag/2.1.7, just select "Disabled" in switch type.

![Screenshot 2020-09-19 at 11 19 21](https://user-images.githubusercontent.com/77936/93664891-15f3d480-fa6a-11ea-8aae-44647de865f9.jpg)

**Comment by andyblac** [comment]
@rojer think this one can be closed as well.

**Comment by rojer** [comment]
yep, this one is done, released in 2.1.7
