### ISSUE TITLE
Shelly 2.5 Garage door opener like roller cutter mode

### ISSUE THREAD

**Issue by PADE86** [mongoose-os-apps/shelly-homekit#781]
Thanks for your great work!
I use Shelly 2.5 in roller shutter mode for my garage door. (It is like a roller shutter)
Is it possible to make a change that it is displayed as garage door opener in HomeKit?
This would be a benefit for CarPlay!

Thanks in advance!

**Comment by timoschilling** [comment]
Double of #669
