### ISSUE TITLE
New device

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#788]
Is possible flash the new device?
- shelly plus 1pm
- Shelly plus 1
- Shelly 4 pro pm

**Comment by andyblac** [comment]
no, these devices are not yet supported, as they use ESP32

**Comment by rojer** [comment]
shelly-homekit could be easily modified to build for esp32 but there's no need: the plan is to have official homekit support for the next gen devices (in fact, i'm helping making that happen).

**Comment by andyblac** [comment]
let hope they do some retro fit version then, as DIN Rail version are pretty useless in UK.

**Comment by rojer** [comment]
it's impossible to get esp8266-based device homekit certified by apple, so there's no chance for official homekit firmware on current generation devices.

**Comment by andyblac** [comment]
> it's impossible to get esp8266-based device homekit certified by apple, so there's no chance for official homekit firmware on current generation devices.

I meant ESP32 versions of the retro fit aka Shelly1, Shelly2.5

**Comment by rojer** [comment]
ah, that i don't know.
