### ISSUE TITLE
Switch 1 : no control without direct WiFi access

### ISSUE THREAD

**Issue by Whiterabbit64** [mongoose-os-apps/shelly-homekit#79]
Hello.

My HomeKit hub is my HomePod so all my homekit accessories are accessible even if I'm not connected to my wifi. Except the Shelly 1. Is that a normal behavior ?

**Comment by rojer** [comment]
Shelly only has wifi access

**Comment by Whiterabbit64** [comment]
Yes I know, but I use my HomePod as a hub to remotely control all my home kit devices whern I'm away from home.
So as the Shelly is integrated in my HomeKit setup whay can't I control it remotely through the hub ?

**Comment by rojer** [comment]
i see. i don't know, tbh.

**Comment by andyblac** [comment]
@Whiterabbit64 shelly still requires a link between HomePod and Shelly, and as shelly only has wifi,  it will loose link if WiFi drops.

**Comment by Whiterabbit64** [comment]
I don’t get the point. When I leave home, my Homekit equipment and my wifi remain powered.
So I can control remotely all of them. The Shelly is still connected to the Wifi and the HomePod.

The only device that I can’t control is the Shelly because in home application it appears offline.

**Comment by Whiterabbit64** [comment]
Problem solved.
The issue was with the HomePod. I’ve moved it to a less complex and more compatible Wifi network.

**Comment by andyblac** [comment]
glad you got it sorted :)
