### ISSUE TITLE
Support for the new shelly-plus-1

### ISSUE THREAD

**Issue by andreaseu** [mongoose-os-apps/shelly-homekit#791]
I'm currently planning to outfit my entire apartment with Shelly's. I just saw that there is a Plus 1 listed on the shelly website. Will there be an update for the Homekit project in the next days/weeks?
https://shelly.cloud/shelly-plus-1/

**Comment by rojer** [comment]
these devices will have official homekit support eventually, no need for alternative firmware.

**Comment by andreaseu** [comment]
Where did you get this information? I could not find anything in this regard.

**Comment by rojer** [comment]
i am helping with the implementation.
i am not allowed to share specifics regarding dates etc but i can tell you that the work is ongoing.
