### ISSUE TITLE
Plus series support

### ISSUE THREAD

**Issue by ARumberg** [mongoose-os-apps/shelly-homekit#800]
Hi,

Will the new Shelly Plus series be supported in the near future?

Thanks.

**Comment by timoschilling** [comment]
Not by this firmware, but Shelly announces HomeKit support for stock firmware

**Comment by rojer** [comment]
yes, there will be official homekit support and yours truly is helping make it happen. stay tuned.
but meeting all the official requirements and passing apple certification will not be easy, so it will take some time.

**Comment by LMMAMP** [comment]
For one person that is not very experienced in this coding themes, will there be a solution for shelly plus 1 easy to use like the ones you did for shelly 2.5 and others?
Thanks!

**Comment by timoschilling** [comment]
I will try to build a online flash tool

**Comment by LMMAMP** [comment]
> I will try to build a online flash tool

Great! Any reason to not having included the sensors in the past (motion sensor and door/window 2 sensor)?

Thanks!

**Comment by mkuerten** [comment]
I'm willing to give the alpha a go. I included the Shelly 1 Plus with the Shelly Beta app. Then I copied the command above in the terminal window of Mac OS. But I get this: -bash: $: command not found.

**Comment by rojer** [comment]
> I'm willing to give the alpha a go. I included the Shelly 1 Plus with the Shelly Beta app. Then I copied the command above in the terminal window of Mac OS. But I get this: -bash: $: command not found.

omit the `$`, it's there just to illustrate command prompt. i think in modern mac os with zsh it's actually `%`.

**Comment by mkuerten** [comment]
Sorry, stupid novice error. Probably one more: The first command runs well, but with the second ("curl -F file=@shelly-homekit-ShellyPlus1.zip http://192.168.1.57/update") I get "curl: (26) Failed to open/read local data from file/application". 

Thanks for your help!

**Comment by timoschilling** [comment]
have you downloaded the firmware file before?
`curl -O http://rojer.me/files/shelly/2.11.0-alpha1/shelly-homekit-ShellyPlus1.zip`
you need to run both commands in the same directory.

**Comment by mkuerten** [comment]
First I ran this:
curl -O http://rojer.me/files/shelly/2.11.0-alpha1/shelly-homekit-ShellyPlus1PM.zip
I got this:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1606k  100 1606k    0     0  3516k      0 --:--:-- --:--:-- --:--:-- 3516k
Then I ran this:
curl -F file=@shelly-homekit-ShellyPlus1.zip http://192.168.1.57/update
They were run from the exact same prompt.

**Comment by rojer** [comment]
can you run `ls -l shelly-homekit-ShellyPlus1.zip` in the same session? this is weird.

**Comment by mkuerten** [comment]
I ran both again in a new terminal window and now it worked. Thanks for your help!!!

**Comment by rojer** [comment]
great. let me know what your experience with the firmware is.

**Comment by mkuerten** [comment]
It's brilliant! I have set it up in the home app and there it works like any other Shelly so far. Thanks so much again!

**Comment by Naveto** [comment]
I have installed seven Shelly 1 plus and they work perfectly.
The only problem I find is that if you leave AP mode enabled, there is no way to disable it from the shelly-homekit interface.

Great job.

**Comment by LMMAMP** [comment]
Hello, 
I really don't know much about this and i have tried to go with the plus 1 but didn't succeed...
1) I went to the windows powershell (i think i don't have the terminal )
2) Typed  " % curl -O http://rojer.me/files/shelly/2.11.0-alpha1/shelly-homekit-ShellyPlus1.zip " and it gave me this error:
"ForEach-Object : Parameter cannot be processed because the parameter name 'O' is ambiguous. Possible matches include:
-OutVariable -OutBuffer.
At line:1 char:8
+ % curl -O http://rojer.me/files/shelly/2.11.0-alpha1/shelly-homekit-S ...
+        ~~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.ForEachObjectCommand"

Is it possible to guide me a little bit here?

Thanks

**Comment by LMMAMP** [comment]
I have dropped the "%" .
Now the message is the following:
"cmdlet Invoke-WebRequest at command pipeline position 1
Supply values for the following parameters:
Uri:  "

**Comment by timoschilling** [comment]
@LMMAMP are you using Windows? The commands are only for Linux and Mac. 

Sorry I don’t habe the knowledge for Windows to help you

**Comment by LMMAMP** [comment]
> @LMMAMP are you using Windows? The commands are only for Linux and Mac.
> 
> Sorry I don’t habe the knowledge for Windows to help you

Hello,

yes , I am using windows . Don’t have a Mac and don’t have Linux installed anywhere .

but I used the development for the Shelly 1 and the 2.5 and worked great . 

I am only having problems  in this new series app.

thanks

**Comment by ARumberg** [comment]
You can download curl for windows, and run the same commands in CMD.

**Comment by LMMAMP** [comment]
> You can download curl for windows, and run the same commands in CMD.
> […](#)

Thanks! I downloaded and succeed in moving 7 shelly plus1 pm to the HomeKit. Looks good!

**Comment by LMMAMP** [comment]
> drop the `%`, it just indicates command prompt.

No working . Moved 7 shelly plus 1. Looks good . Thanks !

**Comment by LMMAMP** [comment]
> > drop the `%`, it just indicates command prompt.
> 
> No working . Moved 7 shelly plus 1. Looks good . Thanks !

Is something projected for the sensors of Shelly ( door / window 2  and motion )? Thanks again !

**Comment by timoschilling** [comment]
see #124 & #693

**Comment by LMMAMP** [comment]
> @LMMAMP see #124 & #693

Thanks. If i understood right, not in the “to do” list anymore as technically it is very difficult or even impossible , right?

**Comment by tobification** [comment]
I also updated 1 Shelly Plus and integrated it into HomeKit successfully. 
One thing I identified, that the "Auto off" function I'm not able to save. 
Anyone else the same issue?

**Comment by rojer** [comment]
> > @LMMAMP see #124 & #693
> 
> Thanks. If i understood right, not in the “to do” list anymore as technically it is very difficult or even impossible , right?

correct. not impossible but don't hold your breath.

**Comment by rojer** [comment]
fixed in 2.11.0-alpha2, see #868

**Comment by frankpeters1001** [comment]
Hi,

I tried to update a ShellyPlus1PM, but I got some errors. First, let me explain what I did so that you have a better understanding of whats going on:
I downloaded the file, copied it on the d drive and ran th command prompt as administrator in the directory where I copied the zip file to. I did not get any error at this time. The command prompt showed one device udpated. 
When I tried to connect with Firefox, I got the following messages:
- Failed to apply settings. No handler for shelly.getdeviceinfo
- Failed to apply settings. No handler for shelly.getconfig
- Failed ..... No handler for webhook.listsupported
- Failed...... No handler for schedule.list
- Failed ..... No handler for scipt.list

I do not see anything else in the browser.

Any ideas of what I am doing wrong here?

You help would be appreciated.

**Comment by rojer** [comment]
@frankpeters1001 this looks like old interface cached by firefox trying to talk to the new firmware.
try reloading the page and closing and re-opening the browser.

**Comment by frankpeters1001** [comment]
Thanks for the quick response. It worked. I will flash the other 3 tomorrow or the day after and keep you posted about any issues. Thanks a lot for your help.

**Comment by frankpeters1001** [comment]
Thanks. That was easy. I will flash the other 3 tomorrow or the day after and I will let you know if any issues occur. Thanks a lot for your help.

**Comment by frankpeters1001** [comment]
Hi,

Just wondering if/when the software supports the measurement of the current. 

Looking forward to your response.

**Comment by rojer** [comment]
> Hi,
> 
> Just wondering if/when the software supports the measurement of the current.
> 
> Looking forward to your response.

you want current value reported along with power?

**Comment by frankpeters1001** [comment]
Hi,

Sorry, I meant power measurement.

Von meinem iPhone gesendet

Am 30.12.2021 um 14:49 schrieb Deomid Ryabkov ***@***.***>:

﻿
Hi,

Just wondering if/when the software supports the measurement of the current.

Looking forward to your response.

you want current value reported along with power?

**Comment by rojer** [comment]
in that case, i'm not sure what you mean because we already support it - 1PM and Plus1PM both do.

**Comment by frankpeters1001** [comment]
Hi,

How do I see the power consumption in the HomeKit app? Perhaps, I just do not know how because I am new with this kinda stuff. 

Your help is really appreciated. 

Best wishes

Von meinem iPhone gesendet

Am 31.12.2021 um 17:14 schrieb Deomid Ryabkov ***@***.***>:

﻿
in that case, i'm not sure what you mean because we already support it - 1PM and Plus1PM both do.

**Comment by rojer** [comment]
standard home app does not show power consumption, there's no way.
you can see it on the web interface and we also export charactestics used by the Eve app, so you can see it there too.

**Comment by nikwest** [comment]
You cannot see power consumption in the Home App. You need a 3rd Party app like https://apps.apple.com/de/app/eve-for-homekit/id917695792?l=en <https://apps.apple.com/de/app/eve-for-homekit/id917695792?l=en>

Greetings

Dominik

**Comment by frankpeters1001** [comment]
Hi Dominik,

Thanks for your advice. I downloaded the app. Can I see power consumption in eve or web interface, even though, I updated the software so that I can see the Shelly in the HomeKit app?

**Comment by timoschilling** [comment]
If you updated the software you can see the power consumption in the Home App, Eve App and the Web UI

**Comment by frankpeters1001** [comment]
Hi,

The web UI shows the power consumption. The eve app shows the power, but not the consumption and I do not find it inside the home app at all. 

Am I doing something wrong or do I look at the wrong place?

![image](https://user-images.githubusercontent.com/96680350/147859276-589f8ff6-99f2-41b8-8093-4339de40e39f.png)

![image](https://user-images.githubusercontent.com/96680350/147859282-3118f4f7-0d5b-4a3f-93cd-97d8853c4b36.jpeg)

**Comment by fred80** [comment]
Hello,
I've purchased a Shelly Plus 1 and installed alpha8. It works great with HomeKit! 
However I cannot get the notifications to work with it. I would like iOS to notify me, if the contact has been closed (I have a baby that doesn't sleep that well so I turn of the chime. With Shelly on the door bell I can get notified in my mobile if someone rings the door). Is this an option or does it still need to be developed?

**Comment by rojer** [comment]
can you clarify what you mean by "contact has been closed" - are you referring to an external contact switch connected to shelly's input?

**Comment by fred80** [comment]
> can you clarify what you mean by "contact has been closed" - are you referring to an external contact switch connected to shelly's input?

Hi Rojer,

I meant the input in the Shelly. I have a door bell connected to it. So if someone rings the door bell it closed the contact and actuates the input in the Shelly.

**Comment by rojer** [comment]
then you need to first set switch input mode to "detached", which will create a separate service for the input. then you can attach automations to the input. might want to select mode for the input to be "contact sensor" too.

**Comment by fred80** [comment]
> then you need to first set switch input mode to "detached", which will create a separate service for the input. then you can attach automations to the input. might want to select mode for the input to be "contact sensor" too.

Works great! Thank you very much. :)

**Comment by pedzp14** [comment]
2 curl commands and a great automated interface surely theres no need to remove 2nd curl. software works great as usuall no issues.

**Comment by fred80** [comment]
Hello, I've found a bug: if you select in HAP Type "Doorbell" (simple mistake from my part) then you cannot change to anything else. If you try to change it, it reverts back to "Doorbell" after 1 or 2 seconds. To get the Shelly back working, one has to revert to factory setting and do the curl commands again.

**Comment by timoschilling** [comment]
please read the first post of #868

**Comment by MokkaSchnalle** [comment]
There is now an easier way to flash the Plus model.
Just upgrade to the original 0.10 Beta firmware which enables the /ota endpoint again.

Then you can flash the firmware in the same way as on the older models.

**Comment by 1yoda** [comment]
> Just upgrade to the original 0.10 Beta firmware which enables the /ota endpoint again.


How do I do this? Where can I find and how can I flash the "original 0.10 Beta"?

**Comment by MokkaSchnalle** [comment]
Just click the update beta button on the webinterface (firmware update tab)

**Comment by timoschilling** [comment]
@LoicDelorme they says it in plus/pro presentation video and you will finde some comments from the CEO about it on Facebook

**Comment by jsurpless** [comment]
I'd like to start by saying that this is all very impressive, nice work!

I tried this out yesterday and then restored back to the OEM firmware.  The device seemed to work a bit finicky until I reset back to factory (for instance, Shelly Cloud app would often show as OFFLINE until I closed and re-opened the app).  

Did I do something wrong?

**Comment by rojer** [comment]
> The device seemed to work a bit finicky until I reset back to factory (for instance, Shelly Cloud app would often show as OFFLINE until I closed and re-opened the app).
> Did I do something wrong?

we are not aware of issues after switching back, and "a bit finicky" and "sometimes offline" is not specific enough. we try to wipe all the state introduced by HK firmware but it's always a good idea to perform factory reset after changing.

> Also, any "harm" in configuring the device in HomeKit and then restoring to Shelly firmware without removing it from HomeKit? I see that HomeKit reports device unreachable but will it be pinging the device (perhaps why I was having issues)?

there shouldn't be any harm. as long as the device stops resolving on bonjour, HK should not be contacting it anymore.

**Comment by jsurpless** [comment]
> > The device seemed to work a bit finicky until I reset back to factory (for instance, Shelly Cloud app would often show as OFFLINE until I closed and re-opened the app).
> > Did I do something wrong?
> 
> we are not aware of issues after switching back, and "a bit finicky" and "sometimes offline" is not specific enough. we try to wipe all the state introduced by HK firmware but it's always a good idea to perform factory reset after changing.
> 
> > Also, any "harm" in configuring the device in HomeKit and then restoring to Shelly firmware without removing it from HomeKit? I see that HomeKit reports device unreachable but will it be pinging the device (perhaps why I was having issues)?
> 
> there shouldn't be any harm. as long as the device stops resolving on bonjour, HK should not be contacting it anymore.

Hi Rojer

Thanks for the reply.  

By 'sometimes offline', I was trying to say that the module would say 'OFFLINE' under its name and tapping it would bring up 'EDIT DEVICE', as opposed to being able to configure it.  The only way that I could get it to work properly would be to quit the app on my iPhone and re-open.

**Comment by LMMAMP** [comment]
Hello,

Do you have already ( or scheduled) the door 2  sensor integration to apple homekit firmware?

Thanks
Luis Pereira 

Enviado do meu iPhone

**Comment by rojer** [comment]
no, not yet
