### ISSUE TITLE
Auto Off Timer - Please Match The Requested Format

### ISSUE THREAD

**Issue by LewisSpring** [mongoose-os-apps/shelly-homekit#801]
Hi there,
I just installed shelly-homekit on my Shelly 1, and no matter what format of auto off length I put in, the box will not take it.
I thought it had to be D:HH:MM:SS.SSS, so therefore for 3 seconds it would be 0:00:00:03.0
That does not work, however. Any ideas? Thanks!

**Comment by andyblac** [comment]
for 3 seconds you need to use `0:00:00:03.000`
