### ISSUE TITLE
Shelly 2.5 shows "Opening..." while idle

### ISSUE THREAD

**Issue by MongooseFan** [mongoose-os-apps/shelly-homekit#802]
I have 9 Shelly devices running Mongoose in roller shutter mode and set up in HomeKit. Everything is working as expected. However, one of them is always shown as "Opening..." in the Home app, even though it has reached the desired opening percentage set by my scene and is completely idle. It remains like that no matter what I do, although rebooting the shelly temporarily fixes it. I'm running the latest software version. Any ideas? Thank you and keep up the good work!

**Comment by nestorngh** [comment]
It’s working for me just now:
https://github.com/mongoose-os-apps/shelly-homekit/issues/821#issuecomment-955592318

**Comment by MongooseFan** [comment]
I don't understand the comment by nestorngh.

All my devices are working flawlessly and the last upgrade (2.10.1) improved the temperature of my Shelly 2.5 devices. The only issue I have is that one of them is constantly showing as "Opening..." in the Home app, even though it's idle. This issue is ongoing. I have tried restarting everything (router, Shelly and Home app)

Any ideas?
