### ISSUE TITLE
Initial setup fails from both OTA and python script

### ISSUE THREAD

**Issue by devonhumes** [mongoose-os-apps/shelly-homekit#806]
I'm setting up a Shelly 1 for the first time. I've been able to flash upgrade to the latest firmware, but when flashing the HomeKit image it always fails. It gets stuck in an infinite loop on the UI and the script says that it fails. Any ideas as to what I'm doing wrong? I've attempted flashing from the script and the OTA.

From the python script
![image](https://user-images.githubusercontent.com/693754/137230490-e397fd20-7bdd-41fa-9ecf-1fec3dc9bd84.png)

What the UI looks like.
![shelly-homekit-failing](https://user-images.githubusercontent.com/693754/137230543-570eb0ff-5460-4208-b999-4800d8cbee49.gif)

**Comment by devonhumes** [comment]
Same result in Safari

**Comment by timoschilling** [comment]
@rojer any ideas?

**Comment by rojer** [comment]
looks weird. so de3vice is alive enough to serve the index page but not much more?
does it respond to `/debug/info` and `/debug/log`? (`http://a.b.c.d/debug/info` and `/debug/log` respecitvely)
