### ISSUE TITLE
URL (Turn ON or OFF) for Shelly RGBW2

### ISSUE THREAD

**Issue by StevenBeck93** [mongoose-os-apps/shelly-homekit#808]
Hello,

i tried to turn the Shelly RGBW2 with URL Code on or off, but this Url doesnt work: 

/rpc/Shelly.SetState?id=1&type=0&state=%7b"state"%3atrue%7d

with a Shelly 1, the URL is working.

Please help me, to find the correct URL for a RGBW2.

Thanks

**Comment by StevenBeck93** [comment]
Perfect, thank you very much! It is working :-)

**Comment by manueltuescher** [comment]
how can i take this HAP types and paste it into my RGBW?? i dont get it.. pls help

**Comment by timoschilling** [comment]
You just need to use this url to turn on your rgbw2 http://a.b.c.d/rpc/Shelly.SetState?id=1&type=11&state=%7b"state"%3atrue%7d

**Comment by manueltuescher** [comment]
Hi Timo

Thank you for your answer.. this URL dont work. 




What can i do??

thanks for your help 😊

Mit freundlichen Grüssen

Manuel Tüscher
Projektleiter Elektroplanung / IT
Berufsbildner

 ***@***.***> ***@***.***
079 297 14 53
 <https://www.ast-elektro.ch/> www.ast-elektro.ch
 <https://ast-elektro.ch/> 

 <https://g.page/r/CRTr25MkaZ1ZEB0/review> 

P Bitte denken Sie an die Umwelt, bevor Sie dieses Mail drucken

 

Von: Timo Schilling ***@***.***> 
Gesendet: Samstag, 4. März 2023 17:53
An: mongoose-os-apps/shelly-homekit ***@***.***>
Cc: manueltuescher ***@***.***>; Comment ***@***.***>
Betreff: Re: [mongoose-os-apps/shelly-homekit] URL (Turn ON or OFF) for Shelly RGBW2 (#808)

 

You just need to use this url to turn on your rgbw2 http://a.b.c.d/rpc/Shelly.SetState?id=1 <http://a.b.c.d/rpc/Shelly.SetState?id=1&type=11&state=%7b%22state%22%3atrue%7d> &type=11&state=%7b"state"%3atrue%7d

**Comment by manueltuescher** [comment]
i get this message if i try this url.. 

![4da9028a-499b-4487-9ba3-c47888d45a7c](https://user-images.githubusercontent.com/95418143/222920496-1f8236c6-d177-4dfa-9348-6a9e155f221c.jpg)

i only use the W output. R, G and B arent in use..

**Comment by timoschilling** [comment]
Are you using RGB+W mode or White Mode?

**Comment by manueltuescher** [comment]
i use "White Mode"

**Comment by danricho** [comment]
Once a Shelly device is configured and working, I find it helpful to get the information needed to adjust it via the API (such as type) using the get extended info endpoint:

`rpc/Shelly.GetInfoExt`

**Comment by timoschilling** [comment]
@manueltuescher then it should be id=4 in the url I posted above. 

@danricho I plan to show api urls in the UI
