### ISSUE TITLE
Unable to flash Plug S

### ISSUE THREAD

**Issue by Cibernello** [mongoose-os-apps/shelly-homekit#81]
I was able to successfully flash Shelly 1 with 1.9.1 firmware. It works just fine. When I tried to do the same with Plug S it did not work. I run the update procedure (as I did with Shelly 1) but after the reboot of the device I still see the stock firmware. Any suggestion? Thanks

**Comment by IvanGitter** [comment]
Hi, I have got the same problem with Plug S. I tried to update the firmware to version 2.0.1 with the following URL:

`http://192.168.1.14/ota?url=http://127.0.0.1:8887/build/shelly-homekit-ShellyPlugS.zip`

 The response from the Plug is reported below

`{"status":"updating","has_update":false,"new_version":"20200309-104506/v1.6.0@43056d58","old_version":"20200309-104506/v1.6.0@43056d58"}`

Any clue?
Thanks a lot.

**Comment by andyblac** [comment]
@IvanGitter try using the local ip and not the loopback IP of your PC

**Comment by IvanGitter** [comment]
Thanks @andyblac but it does not work. I tried with the URL reported below and it worked. So there is something in my pc/lan/... that prevents the plug to update the firmware.

`http://192.168.1.14/ota?url=http://rojer.me/files/shelly/shelly-homekit-ShellyPlugS.zip`

**Comment by andyblac** [comment]
glad you got it flashed, it does require your PC to be running a web server so it can host the file.

**Comment by Cibernello** [comment]
Unfortunately I still cannot flash it.

I used the the url 
http://10.0.0.81/ota?url=http://rojer.me/files/shelly/shelly-homekit-ShellyPlugS.zip

And I got this message

{"status":"updating","has_update":false,"new_version":"20200309-104506/v1.6.0@43056d58","old_version":"20200309-104506/v1.6.0@43056d58"}

When plug s reboots I still see the old firmware. I followed the same process for Shelly 1 and it went perfectly. Plug S douse not update. Why? I am sure the IP address of the device is correct... please help me

**Comment by andyblac** [comment]
is this still an issue ?

**Comment by Cibernello** [comment]
No, I was finally able to flash the firmware with one of the latest updates 

Cheers

Marco

Inviato dal mio incredibile iPhone 11 Pro

**Comment by andyblac** [comment]
thanks for letting me know, I'll close ticket.

**Comment by AdriaanBakker74** [comment]
I did run into the same problem. Unable to update
