### ISSUE TITLE
Does the firmware work with Shelly 1 plus

### ISSUE THREAD

**Issue by mkuerten** [mongoose-os-apps/shelly-homekit#810]
Can I use the firmware for the Shelly 1 also for the Shelly 1 Plus?

Thanks!

**Comment by rojer** [comment]
@mkuerten Plus1 and Plus1PM support is being test in 2.11 pre-releases now, please try it out and give us feedback if you can.

**Comment by mkuerten** [comment]
Upgraded my 4 Shelly 1 Plus and so far everything works as it should. Thanks!
