### ISSUE TITLE
Feature request: Shelly 2.5 - Obstacle detection

### ISSUE THREAD

**Issue by erezkoren** [mongoose-os-apps/shelly-homekit#816]
In Shelly 2.5, in the original firmware there is an ability of Obstacle detection, I think it will be great to have it in the `shelly-homekit` and it is a must have feature for safety reasons.
I think it would be great to add it to the Homekit implementation or even just in the WEB UI
https://developer.apple.com/documentation/homekit/hmcharacteristictypeobstructiondetected?language=swift
Homekit (screenshot)
![image](https://user-images.githubusercontent.com/6420426/138583057-619458f8-7151-48ef-a44b-75709c303d00.png)

Also attached the relevant part of the Shelly 2.5 manual
![image](https://user-images.githubusercontent.com/6420426/138582836-3c758caa-6bda-4a05-a8b6-72d6a18662f5.png)
![image](https://user-images.githubusercontent.com/6420426/138582858-e04a666d-da59-41da-b063-5d440dfe1f4f.png)
https://www.youtube.com/watch?v=W0xCL-MGoDQ&ab_channel=DimitarDimitrov

**Comment by timoschilling** [comment]
Already implemented since 2.2.0 in https://github.com/mongoose-os-apps/shelly-homekit/commit/59cad3b47056cbbb207d9d4241806db14840b796

**Comment by seidnerj** [comment]
I am running version 2.11.2 and have multiple Shelly 2.5 devices set up in roller shutter mode. 

I tested this and non of them stopped or behaved any differently when an obstacle was present. Does this need to be enabled somehow? I didn't see anything related in the web interface configuration page.

Thanks in advance!

**Comment by methinks** [comment]
> 

Same here! There is no such option in the newest firmware.

**Comment by methinks** [comment]
> Already implemented since 2.2.0 in [59cad3b](https://github.com/mongoose-os-apps/shelly-homekit/commit/59cad3b47056cbbb207d9d4241806db14840b796)

Was this change reverted? Obstacle detection configuration not available in the newest firmware.
