### ISSUE TITLE
Problem mit Verbindung

### ISSUE THREAD

**Issue by Patavan** [mongoose-os-apps/shelly-homekit#819]
Hallo zusammen,
ich habe 3 x 2,5 Shelly die innerhalb 2 Tagen nicht mehr arbeiten.

Alle haben die gleiche Fehlersymptome.

1. Sie rauschen alle schon erheblich hörbar.
2. Das Reset über den Button auf der Rückseite ist nicht möglich oder das / die Geräte führen es nicht aus. Ob es 10 x grdrückt oder für 10 sec. gehalten wird.
3. Das Reset mit 5 mal drücken auf einem Raster ob Kanal 1 oder 2 wird auch nicht ausgeführt.
4. Im Haus W- LAN werden die Geräte nicht mehr gefunden.
5. Das Geräte eigene W-LAN wird nicht angezeigt.

Wenn das / die Geräte nach solch einem Aufbau vom Strom genommen werden und wieder angeschlossen werden Schaltet innen ein Relais kurz.

Hat jemand von euch noch eine Idee oder eine Abhilfe?

Besten Dank!

**Comment by Michason** [comment]
Hallo zusammen. Identisches Problem hier. 
Nach dem Update auf 2.10.1 auf 3 Shelly‘s 2.5 habe ich bemerkt,dass eine Jalousie  morgens nicht hochgefahren ist. Beim Ausbau des Shelly konnte ich auch ein Rauschen Vernehmen und habe diesen ausgebaut.

**Comment by justperry** [comment]
Yup, same problem here, it won't show up in my Ubiquiti network nor in an IP scanner.
The physical connected switch works  but it's a momentary switch, the setting seems to be reset so it's on Toggle now.
The physical reset button works...I get the fast relay clicking and lights flickering but it does not work.
I see the default Shelly-XXXX wifi ap for a short while, could connect to it shortly but it's gone in a few seconds.
Was on 2.9.5 IIRC, the shelly update.sh script refused to update the shelly 2.5, it showed errors in Terminal, I then tried updating directly OTA through a browser downloading the zip, that didn't work either, eventually I managed to update,  to stock firmware, and since then I lost it.
There might be bugs in downgrading from 2.9.5 to stock firmware.
I am on a mac, don't think that makes a difference though.

**Comment by quoc68** [comment]
gleiches problem hier auch. Das Rauschen hört sich wie eine Heizung an. 3 von 4 Shellys sind nicht mehr seit dem Update erreichbar. gibt es inzwischen eine Lösung dazu ?[https://streamable.com/1iiwwp](url)

**Comment by justperry** [comment]
Why stale, the issue has not been solved.

**Comment by timoschilling** [comment]
@justperry Most users of this issue reported a hardware problem, that means we have no impact on the issue. So we can close it.

**Comment by justperry** [comment]
> @justperry Most users of this issue reported a hardware problem, that means we have no impact on the issue. So we can close it.

That is not true, the firmware update corrupted the shelly 2.5.

**Comment by Gilbert-1705** [comment]
My Shellys also worked perfectly and broke after the update. The other Shellys still work perfect without the update.

**Comment by Michason** [comment]
I replace my Shelly with a new one from Amazon. Custom Firmware own Risk

**Comment by rojer** [comment]
2.10.1 fixed an important hardware issue with 2.5 specifically: a pin was misconfigured and was sinking a lot of current (i would say it is a hardware design mistake: to connect pins that both default to output on reset and rely on software to reconfigure them). it is possible that after prolonged operation in that mode devices could have been damaged, and going back to correct configuration would actually makes it fail. 2.10.1 shares most of the code with other models and we have not heard complaints about other device types, at least not at this level.
if this is indeed the case, and previous firmware has damaged devices - i am sorry, but it is what it is. i fixed it as soon as it was pointed out to me by a user over the email, and the fix will protect users going forward but the unfortunate side effect is possible fallout of some existing devices.

@Gilbert-1705 did you flash them with hk firmware or keep them on stock? i would be interested to know if it runs fine of you still experience issues.

**Comment by Gilbert-1705** [comment]
I had the old ones, which hadn't broken, still running with the hk firmware until mid-January without any issues. 
Currently i run them stock with homebridge. With hombridge and siri they react 2-3s slower then with hk firmeware.

**Comment by petter1** [comment]
https://youtu.be/NrQVhfKCeTo?feature=shared Here is a video help for replacing the caps, which are most likely the reason for hardware defects on shelly 2.5 (maybe others as well)
