### ISSUE TITLE
2.10.1 shelly stability often don't respond after update from 2.10.0

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#821]
I upgraded all my shellys from 2.10.0 to 2.10.1.
Since I've done this, various shelly2.5s have a lot of stability issues and very often don't respond. I had to turn them off and on again many times in the day. I had to go back to the previous version of the firmware and they returned stable and performing! So the problem is the firmware 2.10.1 which he doesn't like because they never gave me problems before, the RSSI is ok ...

**Comment by lucaspinelli85** [comment]
Any news?

**Comment by lucaspinelli85** [comment]
![image](https://user-images.githubusercontent.com/74553551/139535317-2a8568d8-19d9-45ca-b9ec-10f2ddfa72a9.jpeg)
On AirPort is better activate or disactivate IGMP snooping for Shelly HomeKit stability?

**Comment by rojer** [comment]
sorry, no insights... there are no known substantial differences between 2.10.0 and 2.10.1 that impact connectivity, so it's a puzzle

**Comment by andyblac** [comment]
activate it, it will stop ALL mDNS traffic going to ALL clients, when activated it should only send the mDNS data the to client that requests it.

**Comment by lucaspinelli85** [comment]
I understand. But the fact is that 2.10.1 is creating many problems for me and I am forced to go back to 2.10.0 which does not cause me problems. I am worried because I have also tried 2.11.0 which creates the same problems as 2.10.1 and makes me think that I will not be able to update in the future and stay with this version.

**Comment by andyblac** [comment]
@rojer any library updates between the versions?

**Comment by nestorngh** [comment]
Hi everybody. I’ve had the same issues of stability in my Shellys. I’ve tried all the options and ideas mentioned here and in other internet pages. Finally, the problem seems to have been solved creating another wifi (guest wifi in my router asus) only in the 2,4 GHz band and using it only for the shellys.  It was two days ago and 0 disconnects….
I hope it works forever (at least until the next Router/Shelly firmware update), hahaha

**Comment by lucaspinelli85** [comment]
I'm glad I'm not the only one with the problem ...
Question: the guest network does not communicate only with the internet and not in the private network? how do shellys communicate with each other if they are in guest network?🤔
In any case, with my airport I cannot create a second wifi only in 2.4 band...😭
I hope the solution to the puzzle is found in the next firmware! 😊

**Comment by nestorngh** [comment]
In asus firmware, you can let guest network to access to the private network (and keep the wpa2 encryption with different ssid name and password in the guest network).

**Comment by lucaspinelli85** [comment]
Something came to my mind:
In 2 shelly25 that give me problems, I had to configure them with this code:
curl http://A.B.C.D/rpc/Config.Set -d '{"config":{"wc1":{"idle_power_thr":1.0}}, "reboot": true}'
otherwise they did not draw enough current for calibration. Can this be a problem?
The fact is that I have 4 configured like this, but only 2 give the problem...

**Comment by lucaspinelli85** [comment]
Finally I replaced the shellys with new ones ...
I'm sorry because before the update they always worked great, I tried to go back with the firmware, they improved, but I still noticed the problem even if less often. I also tried going back to stock firmware, updating and returning to homekit, but no improvements.
I'll keep them as a spare if a solution is found in the meantime.
