### ISSUE TITLE
Add Device Shelly Bulb RGBW

### ISSUE THREAD

**Issue by derpate1989** [mongoose-os-apps/shelly-homekit#823]
Hi,

Will the Shelly Bulb RGBW be supported in the near future?
https://shelly.cloud/products/shelly-bulb-smart-home-automation-device/

Thanks.

**Comment by LMMAMP** [comment]
Hello, Just to say i am another one that thinks it would be very helpful. Thanks!

**Comment by appliko** [comment]
Me too !

**Comment by timoschilling** [comment]
Will be implement in #885

**Comment by rojer** [comment]
pushed in 2.11.0-alpha9, please help test it (#868).

**Comment by tkaudioservices** [comment]
I'm not sure if I may have missed this elsewhere, so might be commenting in the wrong spot, but I don't seem to be able to control the white element separately. If you try to set white in apple HomeKit it just uses a combination of RGB.

Funnily enough I am testing various setups in different locations and this is the same problem if you run the bulb with its native firmware via homebridge. 

Are you able to "shed some light" on the matter. Ha ha

Cheers

Tom
