### ISSUE TITLE
Adding warmwhite option

### ISSUE THREAD

**Issue by alxshm** [mongoose-os-apps/shelly-homekit#828]
Dear guys,

I use my Shelly RGBW2 with this software and it works nearly perfect. 

My LED Stripe has RGB and a warm white channel. The problem is, that HomeKit/the software thinks, it's a cold white channel and for this a few colors are showed wrong. 

Is it possible to add an option for a warm white channel?
Or maybe change the code in a way that the white channel is warm white for standard?
(I'm not familiar with coding. So thx for helping me!) :)

**Comment by timoschilling** [comment]
I don't know if it's possible to have a RGBW with a warm white. If some one have an algorithm, please post it here.

RGB+W is already requested in #72
