### ISSUE TITLE
Double click and long press detached

### ISSUE THREAD

**Issue by bmpalmeida** [mongoose-os-apps/shelly-homekit#829]
Hello,

I’m using the detached mode to have access in HomeKit to double click and long press events. But the single click gets really slow. Because it needs to be processed by the HomeKit. 

Any change to have the single click “standard”. E.g. turn on and off the lights directly in the switch. Without rely on HomeKit. But expose the double and long press to the HomeKit?

**Comment by lucaspinelli85** [comment]
Very interesting, it would also be useful for me.
It would have many advantages.
- in the absence of wifi, the simple pressure would work the same.
-the single press would be much faster and more direct without going through homekit
-does not need to configure the single press in homekit
-long and double press would be used to make functionality in addition to the standard single press.
All this without putting the single pressure in detached mode

**Comment by andyblac** [comment]
double of https://github.com/mongoose-os-apps/shelly-homekit/issues/9, and that was merged with https://github.com/mongoose-os-apps/shelly-homekit/issues/147

**Comment by timoschilling** [comment]
This is something else then #9

**Comment by andyblac** [comment]
look at #147 @rojer wanted ALL inputs modes in that issue.

**Comment by andyblac** [comment]
also read through the #9 issue it does mention this issue.

**Comment by andyblac** [comment]
see https://github.com/mongoose-os-apps/shelly-homekit/issues/320
