### ISSUE TITLE
Static ip address like the original firmware

### ISSUE THREAD

**Issue by Makaba05** [mongoose-os-apps/shelly-homekit#83]
DHCP makes sometimes a problem when a device doesn’t response quick enough. So, a static ip-address option like at the original Firmware would be good.

**Comment by rojer** [comment]
yeah, can be done. config already supports configuring it (wifi.sta.ip, wifi.sta.netmask, wifi.sta.gw), just need to be exposed via settings.

**Comment by Jaguaza** [comment]
> yeah, can be done. config already supports configuring it (wifi.sta.ip, wifi.sta.netmask, wifi.sta.gw), just need to be exposed via settings.

Good!!!!

**Comment by michaelbublat** [comment]
Is there any documentation on how to expose via settings?

**Comment by smarthome-fan** [comment]
and a 2. way:
flash orignal firmware from shelly. set ip and save. flash shelly-homekit
 firmware. now you have a static ip too in this firmware ;-)

**Comment by lucaspinelli85** [comment]
Can I edit the IP address from HomeKit firmware an set it static without come back to original firmware, set it, and return to HomeKit firmware? Because I loose the switch option when come back to original.

**Comment by andyblac** [comment]
> Can I edit the IP address from HomeKit firmware an set it static without come back to original firmware, set it, and return to HomeKit firmware? Because I loose the switch option when come back to original.

not in this fw atm, mabe just reserve an IP in your router DHCP servers table.

**Comment by healeydave** [comment]
+1 for static IP settings in HK firmware config screen.

**Comment by simonfield76** [comment]
> > Can I edit the IP address from HomeKit firmware an set it static without come back to original firmware, set it, and return to HomeKit firmware? Because I loose the switch option when come back to original.
> 
> 
> 
> not in this fw atm, mabe just reserve an IP in your router DHCP servers table.

Are you planning to put an option in the firmware in the next future? I do not like making ip reservation in my firewall

**Comment by rojer** [comment]
definitely makes sense to have it but as usual - no ETA

**Comment by rojer** [comment]
closing in favor of #501
