### ISSUE TITLE
Homekit firmware problem for RGBW2

### ISSUE THREAD

**Issue by sg-generix** [mongoose-os-apps/shelly-homekit#830]
Hello,
I flashed 2 devices - Shelly RGBW2 with the last firmware, following the standard procedure, described on git hub page. The devices was installed in Shelly app, and after that I updated to homekit using IP adrress and URL http://A.B.C.D/ota?url=http://rojer.me/files/shelly/shelly-homekit-ShellyRGBW2.zip.

The devices lost WIFI connection after update and they switch to AP mode. When I connect with AP and open it from browser, I  try to add WIFI connection they restart again in AP mode. It is interesting that the STATUS button is switching non-stop for every 3-4 seconds and when I check log the device non stop turn on and turn off.  

Any help please? I flashed some other type of devices like Shelly 1 and Shelly Plug S and there is no problem. Everything works perfect.

**Comment by timoschilling** [comment]
Can you post a draw or a picture of your wiring?

**Comment by sg-generix** [comment]
Hello, we connected according the schema rgbw_led_strip_shelly.png. I attached some pictures to see how we made connection. Thank you for helping.
![rgbw_led_strip_shelly](https://user-images.githubusercontent.com/93645599/140290169-fa6347ce-9a33-4617-bd1e-2a0ccf59a0e3.png)
![IMG_0980](https://user-images.githubusercontent.com/93645599/140290228-947e66c0-d803-41ae-b166-dbf8f88f2fac.jpg)

**Comment by timoschilling** [comment]
Remove the 240V to 12V Switch converter, you don't need it in your case and we don't support it at the moment.
<img width="160" alt="Screenshot 2021-11-04 at 12 13 16" src="https://user-images.githubusercontent.com/165599/140304165-a83418db-dc63-4794-89c8-bccccb23ca4e.png">

**Comment by sg-generix** [comment]
Thank you very much. I will test it later and I will report the result.

**Comment by sg-generix** [comment]
Thank you @timoschilling 
Everything works perfect. I removed the switch convector.

**Comment by kellery82** [comment]
> Remove the 240V to 12V Switch converter, you don't need it in your case and we don't support it at the moment. <img alt="Screenshot 2021-11-04 at 12 13 16" width="160" src="https://user-images.githubusercontent.com/165599/140304165-a83418db-dc63-4794-89c8-bccccb23ca4e.png">

Hi timoschilling, apologies for resurrecting a closed post, so if I wanted to wire this up like sg-generix has, I should use my 230v to 12v transformer still and remove the black part provided with the RGBW2 package? I won't be using an LED strip rather some LED bulbs as per the wiring diagram on Shelly's website.

**Comment by timoschilling** [comment]
Using 12 or 24V bulbs is the same as using a strip.
