### ISSUE TITLE
long press input

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#832]
I connected a rain sensor. it happens that when it rains little, or as soon as it starts to rain or there is simply a lot of humidity, the input flickers pulses. Is it possible to activate the relay only if the input lasts more than a few settable seconds? Long press type?
it can be useful to many to filter out false inputs or to differentiate it from the single input

**Comment by timoschilling** [comment]
double of https://github.com/mongoose-os-apps/shelly-homekit/issues/438
