### ISSUE TITLE
changeover circuit causes flashing

### ISSUE THREAD

**Issue by paulhfischer** [mongoose-os-apps/shelly-homekit#834]
i'm using shelly-homekit on my shelly 1 and have set it up as a [changeover circuit](https://forum.creationx.de/index.php?attachment/2472-shelly1-wechselschaltung-png/). It works fine with the stock firmware, but as soon as I install the homekit-patch and actuate a switch, the connected lamp starts to flicker (instantly turning off and on again).

**Comment by timoschilling** [comment]
Can you post a screenshot from the switch settings please.

**Comment by paulhfischer** [comment]
these are my current settings, i also tried with input mode `edge`:

![image](https://user-images.githubusercontent.com/70564747/140487658-e388f060-128c-456b-8d06-e1b9b1390713.png)
![image](https://user-images.githubusercontent.com/70564747/140487695-e9f6fa7a-a50c-4f2e-a05b-3485e2b38936.png)

**Comment by timoschilling** [comment]
Try "Input Mode: Toggle"

**Comment by paulhfischer** [comment]
okay i'm sorry for the issue - seems like a hardware issue. thought it was related to the firmware as it appeared after i flashed the firmware, but it had the same behaviour with the stock firmware i reinstalled later. i installed a new shelly today and have no issue with the homekit firmware so far with this wiring.

thank you anyway for your help :)
