### ISSUE TITLE
Separate - Edge For Roller Shutter

### ISSUE THREAD

**Issue by Yovalane** [mongoose-os-apps/shelly-homekit#841]
Hello, coule we have « Separate - edge » Input mode for Roller Shutter on Shelly 2.5 ?
I need it to be perfect with my switch

**Comment by lucaspinelli85** [comment]
You want to command the roller by more switch?

**Comment by Yovalane** [comment]
No ^^
My switches are not push-buttons (up can be 0 or 1 and down can be 0 or 1), so i want the Roller Shutter to be commanded each time i use the Button. Not just when he Goes 1. I want the « edge » input mode i have with all my other shelly
