### ISSUE TITLE
Press switch twice to return

### ISSUE THREAD

**Issue by jorgerray** [mongoose-os-apps/shelly-homekit#845]
When turning the light off or on with HomeKit, since the switch does not move from position, I have to press it twice to return it to its normal state. I don't know if there's a way this won't happen.

**Comment by jorgerray** [comment]
The Configuration to do this with the original firmware would be: 
Power on: power off or keep 
Button Type : Flank Switch

**Comment by timoschilling** [comment]
Change the Input Mode to Edge

**Comment by jorgerray** [comment]
Ok. Thanks!!!
