### ISSUE TITLE
Use Shelly1 (or any other HK compatible hardware) as a doorbell input

### ISSUE THREAD

**Issue by morettoni** [mongoose-os-apps/shelly-homekit#849]
Hello it is doable to add to the firmware an "option" to configure Shelly1 (or any other device) as a doorbell input? I mean: I'd like to configure one Shelly to detect when someone rings at my external doorbell and trigger some actions, like:

- ring a chime;
- turn on a light;
- and of course receive a notification.

Some times ago I saw something similar in one implementation, but then looks like it is disappeared (correct me if I am wrong).
In any case any comment and/or any other solution is always welcome!

**Comment by timoschilling** [comment]
Please read https://github.com/mongoose-os-apps/shelly-homekit/wiki/Input-Switch-Settings

**Comment by morettoni** [comment]
Hello, sorry if I am going to open again this issue, but I changed the input type to “doorbell” but into HomeKit is reported as “unsupported”. Maybe is a compatibility issue with iOS 15.2?

In attach the Shelly1 settings and Home app screenshot.

Thanks for the help!

![12509C72-D5B5-45D4-8843-E6814A8E633A](https://user-images.githubusercontent.com/752123/146669878-cb92fb5f-1154-464a-abdf-874f2fcb72e3.jpeg)
![86CBD3BE-1596-4BAD-A858-5D3F3031E513](https://user-images.githubusercontent.com/752123/146669879-ec7e32c9-26f1-4c44-8ef0-100d25b2a3d0.jpeg)

**Comment by timoschilling** [comment]
That's not a bug, that's expected. You need to differentiate between HomeKit and the Home App. HomeKit supports that doorbell, but the Home App didn't provide a UI for it. If you want to make a automatization based on the doorbell you need to use the Eve or Home+ app or similar app. The Home App has removed the support for the doorbell years ago.

**Comment by morettoni** [comment]
Thanks for the great clarification!

**Comment by GloWi001** [comment]
Would it be possible to improve the doorbell function?

Currently, the switch must be detached to use the input as a doorbell. The switch can now only be activated via HomeKit.

But if you now want to use a chime on the switch, you always have to configure it via HomeKit. This is error-prone and has a high latency.

It would be better to have a "doorbell mode" directly. In this case, the input gives a trigger to HomeKit and the switch is automatically triggered.

- Daniel

**Comment by timoschilling** [comment]
@GloWi001 you holding it wrong 🤪
Place the Shelly parallel to the chime and not in series. 

That what you want is already requested in a other issue
