### ISSUE TITLE
No cloud access

### ISSUE THREAD

**Issue by bollie1988** [mongoose-os-apps/shelly-homekit#854]
I flashed Shelly 1 successfully with mongoose and added the Shelly to HomeKit. Works like a dream. 

But when I disconnect WiFi and go to cellular connection on my iPhone the connection gets lost with the Shelly.

what did I do wrong ?

**Comment by timoschilling** [comment]
That’s a problem with you HomeKit setup and not with this firmware. So I will close this issue as not related. 

But a hint for you: you need to configure a homehub in you setup. Read the Apple guidelines for that.
