### ISSUE TITLE
Wi-Fi password bulk update?

### ISSUE THREAD

**Issue by hughfr4nc15** [mongoose-os-apps/shelly-homekit#855]
Hello,

First of all thank you for your firmware, it’s priceless.

I have a suggestion/feature request… I’m thinking on changing my Wi-Fi password but have so many devices to update… would it be possible in the future to add an option to update all the Shelly’s Wi-Fi password in every Shelly detected by the script? Similar to what we do with firmwares.

Thanks!

**Comment by timoschilling** [comment]
If I remind it right thats already possible. @andyblac ?

**Comment by andyblac** [comment]
No this is not possible with my script, you can change between DHCP / STATIC, but yes this should be possible, I would have to find the endpoint where the password is saved. I'll look into it see what can be done.

**Comment by hughfr4nc15** [comment]
Thanks a lot for taking the time to look into this.

**Comment by rojer** [comment]
heads up: major changes expected for 2.11 in this aream, my wifi config manager change is almost ready for testing, just needs some finishing touches.
it will be possible to have two wifi sta configs and configure AP, wifi setup flow UX will also be improved.

**Comment by andyblac** [comment]
cheers @rojer I'll wait a little then. thx

**Comment by hughfr4nc15** [comment]
Hello and Happy New Year!

Not pressuring or anything but any idea when the new version will be released?

**Comment by rojer** [comment]
2.11 is being tested here: #868 
i think we'll do a couple more test builds.

**Comment by hughfr4nc15** [comment]
@andyblac with rojer's new alpha9, would you be able to check the possibility of updating all the Shelly’s Wi-Fi password in every Shelly detected by the script?

Thanks.

**Comment by andyblac** [comment]
@hughfr4nc15 I'll take look, just need to find some time.

**Comment by hughfr4nc15** [comment]
Hello @andyblac, no rush at all, thank you for your time.

**Comment by mikila85** [comment]
+1

**Comment by hughfr4nc15** [comment]
Comment to avoid being closed.

**Comment by hughfr4nc15** [comment]
Comment to avoid being closed.

**Comment by hughfr4nc15** [comment]
Comment to avoid being closed.

**Comment by hughfr4nc15** [comment]
Hello @andyblac and @rojer. Not sure if you guys have the bandwidth to make this possible... :) Just wanted to keep it open.
