### ISSUE TITLE
Virtual switch to deactivate the timer

### ISSUE THREAD

**Issue by Cyrille556** [mongoose-os-apps/shelly-homekit#856]
Hello, I am currently using a Shelly 1 for my garden lighting, it has a 5 minute timer. my idea of improvement would be to have in the house application a virtual switch to deactivate the timer during a meal. Thank you
![IMG_3272](https://user-images.githubusercontent.com/78914215/144462288-a99564e0-7b33-496a-954d-6fa0c6a3aa70.JPG)

**Comment by lucaspinelli85** [comment]
You can bypass the timer simply holding 2 Second the button when turn on light

**Comment by andyblac** [comment]
Like @lucaspinelli85 said press hold button when you turn on the light, but 1second is required. Obviously momentary switch mode is required for this.
