### ISSUE TITLE
Status Requests

### ISSUE THREAD

**Issue by Helge37** [mongoose-os-apps/shelly-homekit#865]
After switching my Shelly1PM from stock firmware to shelly-homekit I´m missing the reply on _http://A.B.C.D/status_ requests.
Very useful for monitoring the values (i.e. switch status, temperature, power consumption) in PRTG or similar tools.
Is there a plan to add this feature?

**Comment by timoschilling** [comment]
Please read our [API documentation](https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development#API), a compatible API is not on our roadmap because it didn't make sense.

**Comment by Helge37** [comment]
@timoschilling Happy with the freshly added details in the API documentation.
Exactly what I was looking for.
Thank you!
