### ISSUE TITLE
Curl requests not possible if password is set

### ISSUE THREAD

**Issue by n11f** [mongoose-os-apps/shelly-homekit#869]
I finally managed to control my shelly 1 via curl using the following:

`curl http://my.ip/rpc/Shelly.SetState -d '{"id": 1, "type": 0, "state": {"state": true}}'`

However this will only work as long as there is no password set for security settings. If i protect my Shelly via password, this will not work anymore.

Do you have any idea on how to solve this? 

Thanks in advance

**Comment by n11f** [comment]
anybody?

**Comment by timoschilling** [comment]
have you tried this?
`curl http://user:password@ip/...`

**Comment by n11f** [comment]
> have you tried this? `curl http://user:password@ip/...`

yes that came to my mind as well, but how should this be possible? There is only a password that can be set and no user at all.

**Comment by andyblac** [comment]
> > have you tried this? `curl http://user:password@ip/...`
> 
> yes that came to my mind as well, but how should this be possible? There is only a password that can be set and no user at all.

user is `admin` in this firmware

**Comment by n11f** [comment]
> user is `admin` in this firmware

that does not work either

**Comment by timoschilling** [comment]
try `curl --digest -u admin:1234 http://...`

**Comment by n11f** [comment]
> try `curl --digest -u admin:1234 http://...`

thank you guys, that finally solved it! Maybe you should take this to the docs as well
