### ISSUE TITLE
Even Power consumption

### ISSUE THREAD

**Issue by goeran03** [mongoose-os-apps/shelly-homekit#873]
I see the actual consumed power in Eve but the the accumulated kWh value. The second is always zero even the value shown on Shelly’s website is in range it should displayable. However the current Watt value is correct. I know that there is already an issue discussion around that topic but don’t know if this should be solved or not. 
I observe this on  both Shelly 1PM and Shell plug S with SW 2.10.1 installed.

**Comment by timoschilling** [comment]
closed as double of #362, maybe some day some one will implement it
