### ISSUE TITLE
Dump characteristics and additional infos using http?

### ISSUE THREAD

**Issue by markus-fischbacher** [mongoose-os-apps/shelly-homekit#880]
Hi there,

is it possible to dump supported characteristics and additional infos for HomeKit loaded Shelly devices?
Something like http://192.168.1.10:9000/accessories
Which headers are necessary to be set and with which values?

I want to use NodeRed with the node-red-contrib-homebridge-automation palette.
But the HomeKit flashed Shelly devices are not listed in the device drop down.
I need some more information for the plugin maintainer.
Can be fetched using the above http method.

**Comment by timoschilling** [comment]
The URL you are posted is from your private network, we can't read that.

As far as I know it's not possible with our firmware to access the HomeKit / HAP interface without peering authentication.

Maybe this is helps you https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development#API

**Comment by rojer** [comment]
yes, not possible to directly enumerate HAP characteristics but we have the JSON RPC API.
