### ISSUE TITLE
http request for roller shutter open / close with Shelly 2.5?

### ISSUE THREAD

**Issue by wgrdigitalisierung** [mongoose-os-apps/shelly-homekit#881]
Hi all,
I have tried a lot based on the switch toggle http request examples here, but couldn't get it to work for shelly 2.5/roller shutter.
How would the http request look like for the Shelly 2.5 as a roller shutter ?

mode from the Web-Server / HomeKit setup page is **Roller Shutter** and 
input mode is set to **Separate - momentary**

Roller shutter works well with HomeKit, would like to use it with http requests in addition.
Any help would be highly appreciated.

Best Wolfgang

PS.: I'm on firmware 2.10.1 build 20211016-123111/2.10.1-gc8923b3-master

**Comment by rojer** [comment]
via POST:
```
curl 'http://shelly25-test.local/rpc/Shelly.SetState' -d '{"type": 4, "id": 1, "state": {"tgt_pos": 50}}'
```

you can also do it via GET with some escaping:
```
curl 'http://shelly25-test.local/rpc/Shelly.SetState?type=4&id=1&state=%7b%22tgt_pos%22%3a50%7d'
```

**Comment by andyblac** [comment]
added to API section in WiKi.

**Comment by wgrdigitalisierung** [comment]
WOW, it works like a charm, 
I figured the right parameters, but failed with the additional state parameter to be wrapped around tgt_pos 
My hours of try&error got rewarded :-) :-) :-) 
MANY THANKS for your quick help !!!
