### ISSUE TITLE
Shelly 2.5 restart

### ISSUE THREAD

**Issue by dr-no0815** [mongoose-os-apps/shelly-homekit#882]
Hello,

i had a problem with one shelly 2.5. It works fine for 2 or 3 days an than it won't work. Neither with the switch nor with the app.
For 13 hours it restarts.
![image](https://user-images.githubusercontent.com/97148193/148333188-9d2ed565-11eb-44b2-ae0d-435e82f09288.png)
Any idea what to do, to impede the restart?
I have the log file an from the core.

Greetings Michael

**Comment by rojer** [comment]
> I have the log file an from the core.

please send them to rojer@rojer.me. note that memory dump contains your wifi credentials.
