### ISSUE TITLE
Power Recliner Sofa

### ISSUE THREAD

**Issue by andyblac** [mongoose-os-apps/shelly-homekit#887]
I have a new power recliner sofa due in feb/march, I was just wondering if anyone have tried fitting some Shelly 2.5's to them one for each side for up / down, was thinking of using roller shade mode, and calibrate as the sofa should have auto stop at each end point, then only thing would be normally you press and hold to do movement, and release when you want to stop moving, but I assume for roller you press and release to start movement, and press again to stop.

Would it be possible to add an option for press and hold for movement, and on release stop, and double press would act as normal ie go to end point?

would like people thoughts on this, just though it would be good to say "Hey Siri, Sofa1 to 50%" 😄

**Comment by bmpalmeida** [comment]
I have exactly the same situation.

In my case i have an additional situation, is the the motors are DC, for what i understand there is no possibility to calibrate DC motors, is that correct?

**Comment by lucaspinelli85** [comment]
I have DC motor in sofà with Shelly2.5 and i calibrate it with apposite scheme

**Comment by lucaspinelli85** [comment]
Using 3PDT relay ![image](https://user-images.githubusercontent.com/74553551/148678809-66fba088-2f3a-4fb2-aac6-71746c23ff03.jpeg)
Or DPDT relay and 2 power![image](https://user-images.githubusercontent.com/74553551/148678857-a1f3a814-7125-4285-81cb-ba2aba9dd150.jpeg)
Or SPDT + DPDT![image](https://user-images.githubusercontent.com/74553551/148678901-137e26b0-1353-4097-85ac-3d47aa60ccaa.jpeg)
Is it use fil for you?

**Comment by andyblac** [comment]
can we not power the shelly 2.5 simply via DC ?, also your diagram does not use the manual switch from the sofa itself.

**Comment by lucaspinelli85** [comment]
I don't think the DC powered shelly works in roller shutter mode, because it measures the power for calibration. I don't know, but in my case I had to power it in AC because my motors are in 12V so I had no choice.
for the manual switch simply connect the single button to SW1 (single mode) or the double button to SW1 and SW2.

**Comment by andyblac** [comment]
> I don't think the DC powered shelly works in roller shutter mode, because it measures the power for calibration. I don't know, but in my case I had to power it in AC because my motors are in 12V so I had no choice.
> for the manual switch simply connect the single button to SW1 (single mode) or the double button to SW1 and SW2.

ok, but what about the press and hold manual button?

**Comment by lucaspinelli85** [comment]
> can we not power the shelly 2.5 simply via DC ?, also your diagram does not use the manual switch from the sofa itself.

the concept of the scheme is always the same, but I don't know if the shelly can do the calibration powered in DC. I have never tried and I don't know if it works, otherwise you should use timed manual calibration!![image](https://user-images.githubusercontent.com/74553551/148681162-ef83cede-882f-43e2-83dd-b977d7879fcd.jpeg)

**Comment by lucaspinelli85** [comment]
> > I don't think the DC powered shelly works in roller shutter mode, because it measures the power for calibration. I don't know, but in my case I had to power it in AC because my motors are in 12V so I had no choice.
> 
> > for the manual switch simply connect the single button to SW1 (single mode) or the double button to SW1 and SW2.
> 
> 
> 
> ok, but what about the press and hold manual button?

Currently I press the manual button to start the movement, and then re-start to stop it in the desired position.
I did not understand your need well.
But if you want it to only move when you press then just set to toogle mode and use a physical button!

**Comment by andyblac** [comment]
@lucaspinelli85 thanks I'll give it a try once my new sofa arrives.
