### ISSUE TITLE
Physical switch not responding when flashed, works fine with stock firmware

### ISSUE THREAD

**Issue by lanceuppercut47** [mongoose-os-apps/shelly-homekit#889]
With the stock firmware I’m able to control the lights with the Shelly app but importantly, the physical light switch.

I’ve flashed my 1L and I’m able to control the lights within Apple Home, but my physical switch no longer works.

Tested rolling back to stock, physical switch works, back to this and it stops working again.

**Comment by timoschilling** [comment]
Have you tried the different input modes?

**Comment by lanceuppercut47** [comment]
I’ve tried the default toggle and also edge, both with no luck.

**Comment by timoschilling** [comment]
Have you tried Momentary? What kind of switch do you have?

**Comment by lanceuppercut47** [comment]
I tried all the options in the end and edge shared or whatever it was called, worked even though just “edge” didn’t.
