### ISSUE TITLE
Shelly RGBW switch issue

### ISSUE THREAD

**Issue by brpe001** [mongoose-os-apps/shelly-homekit#890]
First of all thanks for the great work to make Shelly HomeKit enable. Quick question which not sure if an issue or just as it is. I just setup a Shelly RGBW device. I have setup the AC/DC switch for on and off and seems not to be working properly. When the physical switch is on, the Led strip start fading on and off. When physical switch is off then yes, it works ok with HomeKit. I thought that the AC/DC device was wrong but then I reset back to Shelly firmware and there it works well the on/off physical switch. Any guidance or known issue? Thanks.

**Comment by timoschilling** [comment]
Yes that’s an known issue. The problem that the AC/DC adapter didn’t provide a constant signal, so the Shelly receives a flickering on/off signal. The stock firmware has some kind of filter for that which we don’t have. 

So try to change your wiring, an place the switch between your power supply and the Shelly so you don’t need the adapter
