### ISSUE TITLE
Shelly’s don’t work out of home

### ISSUE THREAD

**Issue by jorgerray** [mongoose-os-apps/shelly-homekit#893]
Several Shelly's works fine in local control but they are "not available" in remote

**Comment by jorgerray** [comment]
Several Shelly's works fine in local control but they are "not available" in remote

**Comment by timoschilling** [comment]
Do you have a HomeHub in your setup? HomeHub Is a HomePod, AppleTV or iPad which is configured as HomeHub and acts as a proxy if you leave your home. In the HomeKit architecture that’s the way to control devices remotely. For details about that search for HomeKit hub setup.

**Comment by jorgerray** [comment]
Yes. Two Appletv. Automations don’t  works

**Comment by timoschilling** [comment]
Then you have a problem in your setup. If your automatisations aren't working, your remote access can't work. So it's not a Shelly problem.
