### ISSUE TITLE
Shelly 1 garage door opener: no Sensor in automation

### ISSUE THREAD

**Issue by AlexIsOnlineNow** [mongoose-os-apps/shelly-homekit#897]
Hi,
I use a shelly 1 in the "garage door opener" mode with an magnet sensor. Everything is working fine. 
I have a problem with automation in the Homekit-App. 
Why isn't it possible to select "a sensor detected something"? it's not active
thx

**Comment by timoschilling** [comment]
It’s because the Shelly acts as Gragedoor and not as contact sensor. Take a look in the accessory controlled section.
