### ISSUE TITLE
WiFi 6 (AX)

### ISSUE THREAD

**Issue by RichJonk** [mongoose-os-apps/shelly-homekit#899]
The firmware on my Shelly Plug S has issues with WiFi 6 (AX), the official firmware works very well.

I am using ASUS Zenwifi AX.

**Comment by andyblac** [comment]
make sure you split 2.4ghz and 5Ghz, do not combine them, I have WiFi6 here and have no issues with this firmware.

**Comment by timoschilling** [comment]
I see it different then Andy, but I agree with him that is not an firmware/wifi6 issue. 

@rojer what do you think?

**Comment by RichJonk** [comment]
Yeah, I tried a lot but WiFi 6 works but only when Tri Band Smart Connect is turned of.

When it is turned on the devices are having lots of problems. The device with the Shelly firmware works with that setting on so the Shelly Plug S can work with Tri Band Smart Connect.

I can provide you with logs, not sure what logfiles you need.

![5F729A90-AB9C-47E0-A18D-E0F9239A71B2](https://user-images.githubusercontent.com/97909187/149889236-140fc005-979d-44bc-957f-61826a17a3fd.jpeg)

**Comment by trendchiller** [comment]
AX works here too - without any problems - Handsteuerung is activated…
