### ISSUE TITLE
Shelly 1 shown as "unavailable" in Home App

### ISSUE THREAD

**Issue by Whiterabbit64** [mongoose-os-apps/shelly-homekit#90]
Hello.

I've tried everything on my WiFi network to solve this problem: my 3 SHELLY 1 switches go offline several times a day under Home app.
I have other HomeKit devices (Hue, Netatmo, Xiaomi) on the same WiFi and the SHELLY are the only ones to have this behavior.
When they go offline in Home ap they are still "pingable" with no packet loss. I also see them with the app Discovery on my iPhone. The WiFi coverage is excellent in my house.
I've setup a dedicated SSID for SHELLY after reading posts giving some specific parameters (no WMM, DTIM 2), but no success.
I suspect an issue in the wifi driver of the SHELLY. Any way to check that ?

Thanks.

**Comment by andyblac** [comment]
another thread here https://github.com/mongoose-os-apps/shelly-homekit/issues/46 same issue.

**Comment by andyblac** [comment]
did the update to 2.0.12 fix your issue ?

**Comment by Whiterabbit64** [comment]
As I’m not at home, I can’t update them. Should be able to that by the end of this month.

**Comment by Whiterabbit64** [comment]
Upgrade done yesterday. 

What I observe is a great improvement : Shelly's web page load faster. In Home app, Shelly's status is now instantaneous. Siri on HomePod is now able to interact with Shelly.
So far so good.

I'll post again here in few days to confirm if everything is stable.

**Comment by Whiterabbit64** [comment]
After several days, I can say it's very stable and works like a charm 👍
Issue is now solved.

Well done 👌

**Comment by rojer** [comment]
thanks for getting back, closing this now!
