### ISSUE TITLE
Notifications can’t be enabled for input 1 hap type doorbell

### ISSUE THREAD

**Issue by nachumk** [mongoose-os-apps/shelly-homekit#900]
I am running 2.10.1 on a Shelly1. When I configure input 1 hap type to doorbell, the home app won’t give notifications. Is this something that can be resolved through this firmware or is it a limitation of the home app and doorbell hap type being unsupported? Can the option give a supported style of doorbell instead?

**Comment by timoschilling** [comment]
I retested our implementation and it works as expected. That the Home App say that the doorbell is not supported is just a UI thing. In my test I got a push notification and my HomePods played a bing. Maybe you didn’t get the notification if you have the Home app is open. In the end the behavior isn’t in our hand, that’s dependence only on iOS.
