### ISSUE TITLE
Replacement switch app setting

### ISSUE THREAD

**Issue by LiranETN** [mongoose-os-apps/shelly-homekit#902]
Hi all,
Need assistance with configuring the app. 
I am using shelly 2.5 with 2 Replacement switch that are wired correctly but some configuration makes it endless blinking what is the correct config for this scenario?
Thanks,

**Comment by timoschilling** [comment]
Sorry I don't understand your question. What app are you talking about? What is exactly blinking? You should explain more what your scenario is.

**Comment by LiranETN** [comment]
Sure. 
Shelly 2.5 wire connection:
![image](https://user-images.githubusercontent.com/19948604/149929908-fd103aa4-36cd-405e-ade1-077e4c115de6.png)

This is how Shelly is configured via web connection to the app:
![image](https://user-images.githubusercontent.com/19948604/149930211-76f2abd1-ee08-47d0-bf9d-6a1578db803f.png)

In this scenario, the light is blinking. I think that something needs to be configured correctly so that Shelly know that this is a replacement switch and not a regular switch.

I hope this more clear.

**Comment by timoschilling** [comment]
not sure how your switches are working, have you tried edge or momentary?

**Comment by LiranETN** [comment]
Each switch can turn on/off the current light state. 
I am not sure what the correct config should be so this is why I post here to see if someone knows.

**Comment by LiranETN** [comment]
No. Should I set both switch the same (both edge / both momentary)

**Comment by timoschilling** [comment]
only that one that is wired

**Comment by Adi-Kha** [comment]
This should work in your case !

![42D5F970-42CA-46A7-8F97-65883CF11A7C](https://user-images.githubusercontent.com/78901178/149977657-e22840b6-0577-4a22-a473-1a282cfc6d4e.jpeg)

**Comment by LiranETN** [comment]
OK Thanks. will check and update

**Comment by LiranETN** [comment]
Thanks all works
