### ISSUE TITLE
Set static IP address - Feature request

### ISSUE THREAD

**Issue by MannyFay** [mongoose-os-apps/shelly-homekit#903]
Hello,

is it possible to add the option to set a static IP address in your Shelly-UI?
I use a lot of Shelly 1. If I understand it right, I have to reset them to set a static IP address and then put on your Home Kit software.

That way will be pretty annoying :-P

Regards and many thank's for your smart software,

Manny

**Comment by rojer** [comment]
done, being tested in 2.11 pre-releases - #868
