### ISSUE TITLE
Help with flashing my first Shelly (SHDM-2) - N00b...

### ISSUE THREAD

**Issue by Robmanzzz** [mongoose-os-apps/shelly-homekit#907]
Hi!

I'm probably stupid, but I can't seem to succeed in installing the Homekit firmware on my Shelly 2. I tried OTA and the Python script. OTA updates to (older) stock versions are not a problem.

Here is my return message from Terminal (MacOS)
![Screenshot 2022-01-22 at 00 15 09](https://user-images.githubusercontent.com/8589665/150612002-998241e2-a8fd-4287-9c19-c6af825693eb.png)

In the flashing wiki I found that I need at least firmware version 2.1 to use the Python scripts, but the latest stock firmware is 1.11.7

As I said, probably stupid...

Thanks in advance.

**Comment by timoschilling** [comment]
You don’t have a Shelly 2, you have a Shelly Dimmer 2. That are two different devices. The Shelly 2 is a pre version of the 2.5. We don’t support the Dimmer 2.
