### ISSUE TITLE
Unable to hardware flash

### ISSUE THREAD

**Issue by lorenzocastorina** [mongoose-os-apps/shelly-homekit#908]
hello guys sorry for bothering but maybe someone can help me, I'm trying to flash a new custom firmware on my dimmer 2 because I bricked it by mistake a while ago. This device has an extremely small and difficult connector to deal with, and using esptool I don't receive any response back. This is my config TX of TTL device to RX of shelly, for RX too, and GND and GPIO0 both to GND of the TTL device.

![IMG_1668](https://user-images.githubusercontent.com/46899265/150646274-84677c40-8bdb-4977-a0a0-eb4ccdda9050.jpg)

The shelly receive the 3.3v but it seems to not working, because I get this error every time (my Macbook recognise TTL device in usbserial-0001):

Serial port /dev/tty.usbserial-0001
Connecting......................................

A fatal error occurred: Failed to connect to Espressif device: No serial data received.

I hope to not disturb, maybe is just a simple error, or the TTL controller is wrong... I can't figure it out

**Comment by rojer** [comment]
i think your setup is correct, but that said, your connections don't look super reliable.
either way, it's not specific to shelly-hk, so closing.
