### ISSUE TITLE
Setup in apple homekit not possible

### ISSUE THREAD

**Issue by thefreshap** [mongoose-os-apps/shelly-homekit#910]
Hey guys,

i cannot connect my shelly 1 to apple homekit. he cannot find the device..
the qr code works perfectly but he is not connecting

Firmware 2.10.1

what can i do?

greetings from germany

**Comment by thefreshap** [comment]
But it says no to ![image](https://user-images.githubusercontent.com/98345046/150838904-c07c4e55-9758-4dc8-a774-3401654cdabe.png)

**Comment by timoschilling** [comment]
Do you see the Shelly in the Home app?

**Comment by thefreshap** [comment]
It worked...
no idea why but now i was able to connect the shelly

sorry guys!
but thank you

**Comment by timoschilling** [comment]
Some time's it can happen that the pairing times out, then a retry is the best.
