### ISSUE TITLE
Support for Shelly Plus i4

### ISSUE THREAD

**Issue by GitGabKat** [mongoose-os-apps/shelly-homekit#911]
As it turns out there is no reliable smart switch for HomeKit out there without cloud hazard, Shelly Plus i4 in combination with Shelly smart switch is one opportunity to solve that. Can you adopt your firmware to that device in order to solve that issue?

**Comment by rojer** [comment]
none of us has it on hand at the moment. would you like to donate one?

**Comment by GitGabKat** [comment]
As there would be a high demand for that, more people going to donate. Me as well.

**Comment by markirb** [comment]
I have preordered one and will try to get it running when it arrives and I find time.

@rojer I assume this should not be hard except for finding out the correct parameters and pinning that should be similar to the other new Plus devices, right?

**Comment by rojer** [comment]
yes, should be pretty simple.

**Comment by andyblac** [comment]
@rojer I have one here, anything I do for you ?

**Comment by rojer** [comment]
@andyblac can you confirm the default AP name for it please? is it `ShellyPlusI4-????????????`?

**Comment by rojer** [comment]
then you can try http://rojer.me/files/shelly/misc/i4-test.zip if you feel adventurous.

**Comment by GitGabKat** [comment]
I also have one now. Would also test in next time.

**Comment by GitGabKat** [comment]
> then you can try http://rojer.me/files/shelly/misc/i4-test.zip if you feel adventurous.
> 
> to make it safer, add `-F commit_timeout=300` to your `curl` command, e.g. `curl -F commit_timeout=300 -F file=@shelly-homekit-ShellyPlusI4.zip http://a.b.c.d/update`.
> 
> this way firmware should revert after 5 minutes or if it crashes or reboots for any reason. if everything looks ok after update, go to `curl http://a.b.c.d/update/commit` to make it stick.

I have now a setup of the device. But I am not sure what to do to flash the device. 
Can I use the script-section or is there a link to flash like for the other ones?

**Comment by rojer** [comment]
@markirb sorry, i'd cleaned up the file from the server. restored now.

@GitGabKat 
1. update to beta version from the web UI (device -> firmware version -> update beta; currently 0.10.0-beta4)
2. use the ota?url method - `http://a.b.c.d/ota?url=http://rojer.me/files/shelly/misc/i4-test.zip`

again: this has not been tested but there's a chance it might work. if it bricks your device, you can send it to me for unbricking and adding support properly :)

**Comment by GitGabKat** [comment]
@rojer Have you got a link to a the 0.10.0-beta4? Can't find any.

**Comment by rojer** [comment]
@GitGabKat you don't need a link, it should be in the stock UI as an option. go to device -> firmware version and there should be a button there.

**Comment by timoschilling** [comment]
<img width="796" alt="Screenshot 2022-02-24 at 09 08 28" src="https://user-images.githubusercontent.com/165599/155483863-2ad2c78d-742e-4fbc-9276-4c141b9868ef.png">
<img width="847" alt="Screenshot 2022-02-24 at 09 10 31" src="https://user-images.githubusercontent.com/165599/155484158-4e2a8878-fda4-41c1-b9e6-11662ca0f721.png">

**Comment by GitGabKat** [comment]
Sorry, there is no such option at my i4 
![Screenshot_shellyi4](https://user-images.githubusercontent.com/65626478/155485624-1a7fb0c9-d661-49ec-83f9-4bb21d60295c.jpg)

**Comment by timoschilling** [comment]
Try "check for update" or maybe that beta isn't available for the i4.

Or you can download `http://rojer.me/files/shelly/misc/i4-test.zip` (don't unzip it) and then run `curl -F file=@i4-test.zip http://<hostname or ip of your shelly>/update`

**Comment by rojer** [comment]
yeah, looks like there's no beta for i4 - https://updates.shelly.cloud/update/PlusI4 has no "beta" section.

then use the curl method.

**Comment by markirb** [comment]
Curl method does work :) it's up and running. Will test it further. 

Bugs so far:

Only 3 inputs showing (off by one in Loop?)

Pressing all Inputs once, only one did show up as event (Input 2), so the GPIOs might still be messed up or it is my wiring

**Comment by GitGabKat** [comment]
I also had the opportunity to test and it woks quite well at this stage. 
Like @markirb mentioned, there are currently only three inputs showing up, even it is a 4-swich. Different inputs reacted as programmed in the home app (one, two, long). 
Will keep on testing..

**Comment by markirb** [comment]
Ok indeed I also managed to get events on Inputs 1 and 3 but they're really shaky for me, still do not know the reason

**Comment by markirb** [comment]
@rojer I read that you have other things on your mind right now... all the best for your relatives. 

so eventually could you push your current work on this to a branch, so I can fix the small issues?
