### ISSUE TITLE
Shelly 2.5 reset FW via serial connection

### ISSUE THREAD

**Issue by alexhodos** [mongoose-os-apps/shelly-homekit#912]
Hi, May I ask your help please? I was trying to load the shelly 2.5 firmware to a shelly 2.5 unit. The unit equipped homekitBG firmware, and OTA is disabled. So I ordered a a USB - UART converter, and followed the wiring picture. I can read and create the FW file (shelly.bin) but when I want to write the device, it says "flasher did not respond". what do I wrong? thx in advance.

**Comment by timoschilling** [comment]
Sorry but that issue isn't related to this software project.

One hint maybe you didn't connected GPIO 0 to the flasher or to GND, only then the shelly esp8266 cpu is in flash mode.
I think you should find more help via [google](https://www.google.com/search?client=safari&rls=en&q=flash+esp8266&ie=UTF-8&oe=UTF-8).
