### ISSUE TITLE
Bug with doorbell settings

### ISSUE THREAD

**Issue by timoschilling** [mongoose-os-apps/shelly-homekit#917]
Hello, I've found a bug: in the Input, if you select in HAP Type "Doorbell" (simple mistake from my part) then you cannot change to anything else. If you try to change it, it reverts back to "Doorbell" after 1 or 2 seconds. To get the Shelly back working, one has to revert to factory setting and do the curl commands again.

_Originally posted by @fred80 in https://github.com/mongoose-os-apps/shelly-homekit/issues/800#issuecomment-1023150543_

**Comment by rojer** [comment]
fixed, thanks! will be in the next release.
