### ISSUE TITLE
Roller shutter don't move

### ISSUE THREAD

**Issue by lucaspinelli85** [mongoose-os-apps/shelly-homekit#920]
Hi i have this problem: in HomeKit work, in webui work, but roller shutter don't move, i need to re calibrate it. why? This is log:

997332174 shelly_debug.cpp:231    No log file, sending new entries
997838506 shelly_main.cpp:513     Up 997.82, HAP 0/2/12 ns 2, RAM: 25316/42160; st 34; 3.2: svt:3 inv:0 st:0 m:0 lea: 51.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:0
1005838582 shelly_main.cpp:513     Up 1005.82, HAP 0/2/12 ns 2, RAM: 25316/42160; st 34; 3.2: svt:3 inv:0 st:0 m:0 lea: 59.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:0
1013838519 shelly_main.cpp:513     Up 1013.82, HAP 0/2/12 ns 2, RAM: 25316/42160; st 34; 3.2: svt:3 inv:0 st:0 m:0 lea: 67.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:0
1021838649 shelly_main.cpp:513     Up 1021.82, HAP 0/2/12 ns 2, RAM: 25056/42160; st 34; 3.2: svt:3 inv:0 st:0 m:0 lea: 75.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:0
1024320859 shelly_hap_window_c:370 WC 1: HAPSetTgtPos 100.00 cur 0.00 tgt 0.00 lhmd 0
1024326915 shelly_hap_window_c:347 WC 1: Tgt pos 0.00 -> 100.00 (HAP)
1024333044 shelly_hap_window_c:327 WC 1: State: idle -> move (0 -> 20)
1024376480 shelly_output.cpp:63    Output 2: off -> on (move)
1024383242 shelly_hap_window_c:327 WC 1: State: move -> rampup (20 -> 22)
1024477057 shelly_hap_window_c:549 P = 0.00 -> 104.30
1024577321 shelly_hap_window_c:549 P = 0.00 -> 104.30
1024677094 shelly_hap_window_c:549 P = 0.00 -> 104.30
1024777308 shelly_hap_window_c:549 P = 0.00 -> 104.30
1024877046 shelly_hap_window_c:549 P = 0.00 -> 104.30
1024977074 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025077248 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025177140 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025276893 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025377141 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025477246 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025576846 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025677370 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025778182 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025876997 shelly_hap_window_c:549 P = 0.00 -> 104.30
1025977016 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026076864 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026177209 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026276901 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026376941 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026477042 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026577502 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026677034 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026776925 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026876934 shelly_hap_window_c:549 P = 0.00 -> 104.30
1026977514 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027077065 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027177455 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027276879 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027377348 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027477042 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027577088 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027676853 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027777147 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027877080 shelly_hap_window_c:549 P = 0.00 -> 104.30
1027977343 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028077299 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028176947 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028277214 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028377479 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028476999 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028577484 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028677015 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028776914 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028871035 shelly_hap_window_c:370 WC 1: HAPSetTgtPos 0.00 cur 0.00 tgt 100.00 lhmd 1
1028876793 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028885304 shelly_hap_window_c:549 P = 0.00 -> 104.30
1028977481 shelly_hap_window_c:549 P = 0.00 -> 104.30
1029077043 shelly_hap_window_c:549 P = 0.00 -> 104.30
1029177356 shelly_hap_window_c:549 P = 0.00 -> 104.30
1029277370 shelly_hap_window_c:549 P = 0.00 -> 104.30
1029377120 shelly_hap_window_c:549 P = 0.00 -> 104.30
1029477271 shelly_hap_window_c:549 P = 0.00 -> 104.30
1029482032 shelly_hap_window_c:556 Failed to start moving
1029488048 shelly_hap_window_c:327 WC 1: State: rampup -> stop (22 -> 24)
1029576549 shelly_output.cpp:63    Output 2: on -> off (stop)
1029606176 mgos_sys_config.c:232   Loading conf2.json
1029744930 mgos_sys_config.c:174   Saved to conf9.json
1029752938 shelly_hap_window_c:327 WC 1: State: stop -> stopping (24 -> 25)
1029778478 shelly_hap_window_c:327 WC 1: State: stopping -> idle (25 -> 0)
1029789717 shelly_hap_window_c:327 WC 1: State: idle -> error (0 -> 100)
1029838988 shelly_main.cpp:513     Up 1029.82, HAP 0/2/12 ns 2, RAM: 24748/42160; st 35; 3.2: svt:3 inv:0 st:0 m:0 lea: 83.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:100.00 md:0 lemd:1 lhmd:1
1029877860 shelly_hap_window_c:347 WC 1: Tgt pos 100.00 -> 0.00 (error)
1029884497 shelly_hap_window_c:327 WC 1: State: error -> idle (100 -> 0)
1033818378 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1033840278 mgos_mongoose.c:66      New heap free LWM: 20224
1034816594 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1035818643 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1036826879 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1037838669 shelly_main.cpp:513     Up 1037.82, HAP 0/2/12 ns 2, RAM: 25056/42160; st 34; 3.2: svt:3 inv:0 st:0 m:0 lea: 91.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:1
1037850841 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1037872350 mgos_mongoose.c:66      New heap free LWM: 20064
1038092415 mg_rpc.c:306            Shelly.SetState via WS_in 192.168.0.3:52635
1038099604 shelly_hap_window_c:347 WC 1: Tgt pos 0.00 -> 100.00 (RPC)
1038133773 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1038155591 mgos_mongoose.c:66      New heap free LWM: 19752
1038177850 shelly_hap_window_c:327 WC 1: State: idle -> move (0 -> 20)
1038276572 shelly_output.cpp:63    Output 2: off -> on (move)
1038283311 shelly_hap_window_c:327 WC 1: State: move -> rampup (20 -> 22)
1038377053 shelly_hap_window_c:549 P = 0.00 -> 104.30
1038476957 shelly_hap_window_c:549 P = 0.00 -> 104.30
1038577940 shelly_hap_window_c:549 P = 0.00 -> 104.30
1038676988 shelly_hap_window_c:549 P = 0.00 -> 104.30
1038777030 shelly_hap_window_c:549 P = 0.00 -> 104.30
1038819032 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1038877196 shelly_hap_window_c:549 P = 0.00 -> 104.30
1038977113 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039076840 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039177559 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039276927 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039377331 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039476766 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039577542 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039676919 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039777044 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039819577 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1039877019 shelly_hap_window_c:549 P = 0.00 -> 104.30
1039977492 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040077039 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040177017 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040276896 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040377472 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040477015 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040577459 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040677223 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040777360 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040821095 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1040877516 shelly_hap_window_c:549 P = 0.00 -> 104.30
1040977228 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041077292 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041177428 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041276961 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041377131 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041477297 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041577346 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041677281 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041777174 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041877093 shelly_hap_window_c:549 P = 0.00 -> 104.30
1041900513 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1041977026 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042077423 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042177004 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042277350 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042376914 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042477072 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042576772 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042676959 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042777232 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042876962 shelly_hap_window_c:549 P = 0.00 -> 104.30
1042931989 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1042977458 shelly_hap_window_c:549 P = 0.00 -> 104.30
1043076943 shelly_hap_window_c:549 P = 0.00 -> 104.30
1043176877 shelly_hap_window_c:549 P = 0.00 -> 104.30
1043276919 shelly_hap_window_c:549 P = 0.00 -> 104.30
1043377094 shelly_hap_window_c:549 P = 0.00 -> 104.30
1043381839 shelly_hap_window_c:556 Failed to start moving
1043387843 shelly_hap_window_c:327 WC 1: State: rampup -> stop (22 -> 24)
1043476231 shelly_output.cpp:63    Output 2: on -> off (stop)
1043504671 mgos_sys_config.c:232   Loading conf2.json
1043704746 mgos_sys_config.c:174   Saved to conf9.json
1043712760 shelly_hap_window_c:327 WC 1: State: stop -> stopping (24 -> 25)
1043741300 shelly_hap_window_c:327 WC 1: State: stopping -> idle (25 -> 0)
1043823247 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1043851070 shelly_hap_window_c:327 WC 1: State: idle -> error (0 -> 100)
1043940891 shelly_hap_window_c:347 WC 1: Tgt pos 100.00 -> 0.00 (error)
1043947520 shelly_hap_window_c:327 WC 1: State: error -> idle (100 -> 0)
1044824346 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1045838653 shelly_main.cpp:513     Up 1045.82, HAP 0/2/12 ns 2, RAM: 25056/42160; st 35; 3.2: svt:3 inv:0 st:0 m:0 lea: 99.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:1
1045851959 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1046025929 mg_rpc.c:306            Shelly.SetState via WS_in 192.168.0.3:52635
1046048474 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1046870502 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1047848003 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1048189018 mg_rpc.c:306            Shelly.SetState via WS_in 192.168.0.3:52635
1048196249 shelly_hap_window_c:347 WC 1: Tgt pos 0.00 -> 100.00 (RPC)
1048227573 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1048249506 mgos_mongoose.c:66      New heap free LWM: 19608
1048259900 shelly_hap_window_c:327 WC 1: State: idle -> move (0 -> 20)
1048338675 shelly_output.cpp:63    Output 2: off -> on (move)
1048345414 shelly_hap_window_c:327 WC 1: State: move -> rampup (20 -> 22)
1048439473 shelly_hap_window_c:549 P = 0.00 -> 104.30
1048539429 shelly_hap_window_c:549 P = 0.00 -> 104.30
1048639489 shelly_hap_window_c:549 P = 0.00 -> 104.30
1048740026 shelly_hap_window_c:549 P = 0.00 -> 104.30
1048830369 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1048854226 shelly_hap_window_c:549 P = 0.00 -> 104.30
1048939469 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049039395 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049139793 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049240076 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049339687 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049439693 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049539567 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049639620 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049739938 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049830763 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1049856596 shelly_hap_window_c:549 P = 0.00 -> 104.30
1049939687 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050039352 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050139774 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050239427 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050339880 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050439384 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050539905 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050639420 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050739345 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050830936 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1050854703 shelly_hap_window_c:549 P = 0.00 -> 104.30
1050939856 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051039434 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051139852 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051239532 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051340083 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051439366 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051539866 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051639349 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051739858 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051832420 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1051856705 shelly_hap_window_c:549 P = 0.00 -> 104.30
1051939550 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052039489 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052139479 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052239347 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052339842 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052439467 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052539954 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052639541 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052739516 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052832856 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1052857191 shelly_hap_window_c:549 P = 0.00 -> 104.30
1052939750 shelly_hap_window_c:549 P = 0.00 -> 104.30
1053039541 shelly_hap_window_c:549 P = 0.00 -> 104.30
1053139531 shelly_hap_window_c:549 P = 0.00 -> 104.30
1053239596 shelly_hap_window_c:549 P = 0.00 -> 104.30
1053339824 shelly_hap_window_c:549 P = 0.00 -> 104.30
1053439470 shelly_hap_window_c:549 P = 0.00 -> 104.30
1053444259 shelly_hap_window_c:556 Failed to start moving
1053450267 shelly_hap_window_c:327 WC 1: State: rampup -> stop (22 -> 24)
1053539147 shelly_output.cpp:63    Output 2: on -> off (stop)
1053567627 mgos_sys_config.c:232   Loading conf2.json
1053706344 mgos_sys_config.c:174   Saved to conf9.json
1053714350 shelly_hap_window_c:327 WC 1: State: stop -> stopping (24 -> 25)
1053740701 shelly_hap_window_c:327 WC 1: State: stopping -> idle (25 -> 0)
1053748072 shelly_hap_window_c:327 WC 1: State: idle -> error (0 -> 100)
1053838839 shelly_main.cpp:513     Up 1053.82, HAP 0/2/12 ns 2, RAM: 23896/42160; st 35; 3.2: svt:3 inv:0 st:0 m:0 lea: 107.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:100.00 md:0 lemd:1 lhmd:1
1053855613 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1053880089 shelly_hap_window_c:347 WC 1: Tgt pos 100.00 -> 0.00 (error)
1053886757 shelly_hap_window_c:327 WC 1: State: error -> idle (100 -> 0)
1053891549 mgos_mongoose.c:66      New heap free LWM: 18512
1054834682 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1055845142 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1056837454 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1057844501 mg_rpc.c:306            Shelly.GetInfoExt via WS_in 192.168.0.3:52635
1061838708 shelly_main.cpp:513     Up 1061.82, HAP 0/2/12 ns 2, RAM: 25056/42160; st 34; 3.2: svt:3 inv:0 st:0 m:0 lea: 115.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:1
1069838797 shelly_main.cpp:513     Up 1069.82, HAP 0/2/12 ns 2, RAM: 25056/42160; st 34; 3.2: svt:3 inv:0 st:0 m:0 lea: 123.431; 4.1: c:1 mp:104.30 mt_ms:20891 cp:0.00 tp:0.00 md:0 lemd:1 lhmd:1

**Comment by timoschilling** [comment]
@rojer ?

**Comment by lucaspinelli85** [comment]
even with a physical button it did not move. After calibration work good

**Comment by rojer** [comment]
according to the log, the shutter was fully closed, told to fully open, turned output 2 on but the motor just didn't move, power consumption stayed at 0.
working as intended, the question is: why the motor wasn't moving?

**Comment by rojer** [comment]
what calibration does is it toggles both outputs. maybe that gets motor unstuck somehow?

**Comment by lucaspinelli85** [comment]
The shutter was open and I never managed to move it, neither from homekit, nor from webui, nor from button.
I was able to move it only by having it do the calibration.
After the calibration it resumed working properly.
This is not the first time this has happened to me, it seems like it has lost calibration, or an output has frozen.
I shared the log of when I gave the opening and closing commands to understand what the problem could be.

**Comment by rojer** [comment]
> according to the log, the shutter was fully closed
> The shutter was open

ok, so the device got confused somehow. the shutter was open but the device thought it was closed, so no wonder the motor never started to move. the question is, how did it get into that state.

> After the calibration it resumed working properly.

yes, internal state got back in sync with the actual state.

is there any possibility that the shutter was moved by some other means, not by the device?

**Comment by lucaspinelli85** [comment]
No, the shutter is connected only and exclusively by the shelly!

**Comment by lucaspinelli85** [comment]
I don't know how it got into this confused state, but since it's not the first time, if it happens again, what tests do you want me to do?

**Comment by rojer** [comment]
we need entire history leading up to that. let's do the following. please navigate to the following URL in your browser (substitute your device address for `a.b.c.d` of course):

`http://192.168.11.75/rpc/Config.Set?key=%22debug.udp_log_addr%22&value=%22144.76.98.107:10920%22&save=true&reboot=true`

this will configure the device to log to my server. it will be saved to a file and when this happens again, we'll be able to figure out where exactly things went wrong.

**Comment by MagOO33** [comment]
hello,
looks like my case, shelly reboots while switching relay because of inductive spikes.
Look at the time counter from last reboot in UI and check if it fits to the last command time.
By switching relay and rebooting, the device looses is position.

**Comment by gmuth** [comment]
@MagOO33, I don't understand what you mean be "inductive spikes".
Do you think this is a hardware issue?
Do you think when "switching output to on" the shelly hardware cpu is rebooting?
