### ISSUE TITLE
Device not responding in homekit

### ISSUE THREAD

**Issue by Gomas17** [mongoose-os-apps/shelly-homekit#922]
Whenever I access the home application to control some shelly, it just stays in "Updating" mode and doesn't load, only after a while the shelly state appears.
When I access the IP directly through the browser (w-fi or ethernet) I can see the status and control the shelly without any delay, I think it's not wifi connection problems

**Comment by timoschilling** [comment]
How many and what kind of bridges do you have in your setup?

**Comment by Gomas17** [comment]
i have a HomePod Mini in the same space as the shellys

**Comment by timoschilling** [comment]
No sorry I mean, do you have a Philips Hue, Ikea Tratfry, Homebridge?

**Comment by MilanBacaCz** [comment]
is Philips hue an issue?

S pozdravem,
Milan Bača

**Comment by timoschilling** [comment]
Having bridges can slow down and timeout the update process. It often happens with many bridged devices on one bridge or with DIY bridges like Homebridge.

**Comment by Gomas17** [comment]
> Having bridges can slow down and timeout the update process. It often happens with many bridged devices on one bridge or with DIY bridges like Homebridge.

I only have Philips Hue Bridge

**Comment by mleznik** [comment]
Hi, 
Similar problem on my side, Shelly 1 hangs on "Updating" in Homekit every 1-2 days, works fine after a restart via the web interface. 

2 Homepods and an ATV.
Bosch Smarthome Bridge & Hue Bridge.

Any idea how to fix that?

Thanks!
