### ISSUE TITLE
HTTP Api

### ISSUE THREAD

**Issue by laspinacristian** [mongoose-os-apps/shelly-homekit#925]
Hi,

Wanted to know if HTTP API are still available when using homekit firmware.
I would like to use this firmware without loosing the control the stock firmware gives me. (websocket, MQTT, timed actions, detached mode, webhook)

**Comment by timoschilling** [comment]
Here is the documentation of our API. We are not API compatible with the stock firmware. 
https://github.com/mongoose-os-apps/shelly-homekit/wiki/Development#API
