### ISSUE TITLE
Shelly 2.5 not accessible after crash

### ISSUE THREAD

**Issue by tBerny** [mongoose-os-apps/shelly-homekit#932]
Hey, 

I have tried to revert the software of my shelly 2.5 to factory settings via the web interface. Unfortunately without success. After a few minutes I had to reload the page and everything was unchanged. Also the attempt to upload the software manually did not work. Afterwards, I performed a reset via the web interface. Since then the device is no longer accessible. 
A reset by disconnecting the power supply and pressing the switch five times had no effect aswell. However, I can see the wifi of the AP mode. So I have not given up hope yet. 
Is there a way to save the device? 

Thanks and kind regards
tBerny

**Comment by timoschilling** [comment]
The result of a reset is that the Shelly goes to AP mode. Simply join the AP wifi and reconfigure them.
