### ISSUE TITLE
Keep single switch on/off toggle and expose double an long-click to Home as button

### ISSUE THREAD

**Issue by vifi42** [mongoose-os-apps/shelly-homekit#934]
Hey :) 
This might be a niche request, but in the event of my network going down or my AppleTV/Homepod losing power I'd love to be able to still use my switches and lights.
BUT I'd also love to use the singe/double/long press function in Home for the switches.
So is there a way to create a "combined" switch setting (for momentary switches of course) that combines the on-off-toggle for single press but presents the double and long press to HomeKit (maybe even als separate buttons?)
This would be awesome!
Thanks a lot!

**Comment by lucaspinelli85** [comment]
+1

**Comment by andyblac** [comment]
double of https://github.com/mongoose-os-apps/shelly-homekit/issues/829

**Comment by timoschilling** [comment]
@andyblac i think you referenced the wrong issue/pr #147 hasn’t merged anything. 

I also think this request isn’t covered by #9. it requested a mix of switch and stateless input, which we don’t have yet

**Comment by timoschilling** [comment]
But anyway this is a double of #829.

**Comment by andyblac** [comment]
> @andyblac i think you referenced the wrong issue/pr #147 hasn’t merged anything.
> 
> I also think this request isn’t covered by #9. it requested a mix of switch and stateless input, which we don’t have yet

see https://github.com/mongoose-os-apps/shelly-homekit/issues/320

**Comment by timoschilling** [comment]
In #320 it was requested as a bug fix, here it is requested as a feature.
