### ISSUE TITLE
mac address

### ISSUE THREAD

**Issue by Warner1970** [mongoose-os-apps/shelly-homekit#936]
I've been searching but I can't seem to find this: Is there any way I can read the mac address of the Shelly 1? I would like to make reservations in my DHCP server on mac address.
I could use client ID but I seems my DHCP server is a bit buggy when using client ID

**Comment by timoschilling** [comment]
We don't display them at the moment, but there is a hack: Change the name of the shelly and append `-????????????` (12 x ?) and save it, maybe you need reboot the device. The question marks will be replaced with the Mac address of the shelly. Then you simply need to place a : after each second char.

**Comment by Warner1970** [comment]
Thanks Timo, I'll give it a try. But I also see an enhancement coming up. Great

**Comment by timoschilling** [comment]
There is already a way to read the MAC address without hack! In the Home app, in the accessory informations is the serial number displayed which is equal to the MAC address.

**Comment by Warner1970** [comment]
Yes, found it.. perfect. thanks!
