### ISSUE TITLE
Automations fails after first time

### ISSUE THREAD

**Issue by FranciRoosters** [mongoose-os-apps/shelly-homekit#947]
I have an automation that should turn on my closet light when the door opens and one that should turn the closet light off when the door closes. The automations, as of late, has been very unreliable and it just works the first time I open and close the door. After that, it fails every time. I’m on the latest firmware, have restarted my hub, deleted the automations and recreated them, but nothing. What else can I try? I wouldn’t really want to kill of the power for this. Thank you.

**Comment by timoschilling** [comment]
Is your device responsible when you control it via iPhone?

**Comment by FranciRoosters** [comment]
It is. I also reset the Eve door sensor, but nothing.

**Comment by timoschilling** [comment]
Then it isn’t a problem with the Shelly, it didn’t have any knowledge about automations, it only get commands. Maybe you have a connection issue between your Shelly and your hap

**Comment by FranciRoosters** [comment]
What’s a hap?

**Comment by timoschilling** [comment]
Sorry typo, I mean hub
