### ISSUE TITLE
Activate Homekit Scene

### ISSUE THREAD

**Issue by hubsi208** [mongoose-os-apps/shelly-homekit#948]
Hi, I try to automate scenes with Shelly one.

By switching Shelly on, it should activate the scene and deactivate the scene after x minutes.

Is this not possible? For me it doesn’t work.
Greetings Olaf

**Comment by timoschilling** [comment]
Depending on how do you setup your Shelly:
- if it’s a stateless switch: go to settings of the Shelly in the home app and you can add there a automations for the click
- If it’s something else, go to the automations section in the home app und create a automation there

On one of the automation views you can setup that the scene is deactivated after x min
