### ISSUE TITLE
Shelly 2.5 roller shutter calibration fail

### ISSUE THREAD

**Issue by AzRowD** [mongoose-os-apps/shelly-homekit#953]
Hi,
My Shelly 2.5 work perfectly with the stock firmware but when I put the homekit firmware the calibration doesn't work properly. The roller shutter go down during about 0.5 second then go up during 0.5sec and stop... So when I Close or I Open my roller shutter, it move about 1centimeter haha. I don't know if it's an issue or a bad configuration. Can you help me ? Please see my settings in attachements.
Best Regards
AZD
![192 168 1 26_](https://user-images.githubusercontent.com/52295313/157729968-882c727a-d50f-4ae6-9ef9-d6481c7fa89c.png)
<img width="583" alt="Capture d’écran 2022-03-10 à 18 32 04" src="https://user-images.githubusercontent.com/52295313/157729980-134a8e27-c9d1-4b32-9ca1-9d51237e6e5a.png">

**Comment by timoschilling** [comment]
can you please test it with our 2.11 beta, download this zip file, don't open it, just upload it via UI
https://rojer.me/files/shelly/2.11.0-beta3/shelly-homekit-Shelly25.zip

**Comment by AzRowD** [comment]
Hi @timoschilling,
Thank you for this fast reply, this firmware fix my issue. Calibration work perfectly now, so nice !  Good Job Guys 👍 
So I have also one request/question about my physical switch . Currently I have 3 btn UP/STOP/DOWN. With the Shelly stock firmware the STOP btn work so nice with the config below (in the UI and physicaly), but with the homekit firmware 2.11.O beta it doesn't work and does nothing. Also In the UI I can't see any STOP btn. Is it normal ? or I need some configuration ?

![IMG_0035](https://user-images.githubusercontent.com/52295313/157932946-9d9a24c4-7836-4a14-ac42-e071dfaf21ed.jpg)
![192 168 1 26_](https://user-images.githubusercontent.com/52295313/157933124-55e1a7ef-a4ed-4162-bd5a-9e255ccc413e.png)

Thank you,
Best Regards

AZD

**Comment by timoschilling** [comment]
Nice that 2.11 works for you.

About the STOP button, we didn't support it at the moment, there is already a feature request open for that. Because of that I will close this issue.
