### ISSUE TITLE
Scene NOT triggered in homekit

### ISSUE THREAD

**Issue by snemias** [mongoose-os-apps/shelly-homekit#955]
An i3 should trigger a scene in HomeKit. This does with one particular i3 no longer work. The button in HomeKit reacts when the i3 triggers. And the scene itself works, if I use the test button in HomeKit. Any ideas?

A homepod mini acts as a hub. With v15.3. 
All i3‘s run with 20211016-123134/2.10.1-g¢892363-master

I restarted the homepod and the i3. 

There’s another i3 in the same network in combination with similar shortcuts / scenes. There everything works flawless. 

![DC2BEAE6-C1FE-45B2-B568-855E1CD1BFA3](https://user-images.githubusercontent.com/24624214/157895532-5da406f2-10d4-414f-a451-f9368da9ea3b.jpeg)

**Comment by timoschilling** [comment]
> The button in HomeKit reacts when the i3 triggers

In fact that mean that it is not a software issue on our side.

Maybe you have a configuration issue, how didn't you configured your shelly, please post a screenshot from that input section. What kind of switch do you have wired, toggle or push button?
