### ISSUE TITLE
Shelly i3 will not update from 1.11.8 (stock) to 2.10.1 (Homekit)

### ISSUE THREAD

**Issue by dirkjandevries** [mongoose-os-apps/shelly-homekit#957]
Just received a new Shelly-i3, tried the /ota?url= method **and** the python method, but both methods don't flash the device.

I end up getting the stock Shelly firmware.

Terminal output from the python script ends with:
```
Failed to flash shellyix3-98CDAC24A44A to HomeKit 2.10.1
Current: (1, 11, 8, None, 0)
flash_fw_version: (2, 10, 1, None, 0)
```

What kind of information is useful to trace this problem down to the rootcause?

**Comment by dirkjandevries** [comment]
After 2.10.0 was installed, an Homekit-firmware update to 2.10.1 works also. Hope this gives you guys direction for solving this. Awesome software!!

**Comment by rojer** [comment]
interesting. there isn't much of a difference between 2.10.0 and 2.10.1, nothing that should affect ability to flash it from stock.
i suspect it's some sort of a transient issue.

**Comment by dirkjandevries** [comment]
I tried flashing it for multiple times, over both methods. I have a new one in box lying around, will try the same proces somewhere next week again, with a new device. 

_FYI: The problematic i3 was also new._

**Comment by timoschilling** [comment]
FTR: maybe the reason was found here: https://github.com/mongoose-os-apps/shelly-homekit/issues/958
