### ISSUE TITLE
Unable to convert Shelly 2.5

### ISSUE THREAD

**Issue by MrSimonWood** [mongoose-os-apps/shelly-homekit#958]
Hello, I've successfully updated a few Shelly 2.5s before. Installed a new one, updated stock firmware to 20220209-093016/v1.11.8-g8c7bb8d  and tried to update using the link as I have before
http://A.B.C.D/ota?url=http://rojer.me/files/shelly/shelly-homekit-Shelly25.zip

I get the message:
{"status":"updating","has_update":false,"new_version":"20220209-093016/v1.11.8-g8c7bb8d","old_version":"20220209-093016/v1.11.8-g8c7bb8d"}

And when I go back to the device's IP address, it's still the stock firmware, not the HomeKit version. This is from the log:

1233369661 shelly_update.c:168     Starting ota from http://rojer.me/files/shelly/shelly-homekit-Shelly25.zip
1233877091 mgos_ota_http_clien:270 Update URL: http://rojer.me/files/shelly/shelly-homekit-Shelly25.zip
1233996482 mgos_ota_http_clien:144 Got redirect: [https://rojer.me/files/shelly/shelly-homekit-Shelly25.zip]
1234002788 mgos_ota_http_clien:270 Update URL: https://rojer.me/files/shelly/shelly-homekit-Shelly25.zip
1234020375 mgos_ota_http_clien:102 Failed to connect
1234076431 shelly_update.c:111     SHOTA: error Failed to connect
1234082436 shelly_update.c:130     OTA is fubar

The device appears to be able to connect to the internet as it updated the firmware, so I'm not sure why it's failing to connect for the HomeKit firmware. I'm not sure what else to do to troubleshoot... I'd be grateful for any suggestions, thank you!

**Comment by timoschilling** [comment]
Can you please retry it, there was a other user reporting the same, his problem has solved by retry.

**Comment by ruebyi** [comment]
Happy new year!
I'm running in exact the same problem right now - anything I can do from my side?

**Comment by marcus-aa** [comment]
Same problem now?

174244124333:1782049264920545 mgos_sys_config.c:323   Saved to conf9.json
174244207013 mgos_http_server.c:180  0x3fff2824 HTTP connection from 192.168.20.80:63276
174247335150 mgos_http_server.c:180  0x3fff2d8c HTTP connection from 192.168.20.80:63285
174247365908 json.c:428              RAM: 50720 total, 36192 free
174252259478 mgos_http_server.c:180  0x3fff2d8c HTTP connection from 192.168.20.80:63296
174252287818 json.c:428              RAM: 50720 total, 36192 free
174257501082 mgos_http_server.c:180  0x3fff1c94 HTTP connection from 192.168.20.80:63307
174257514736 shelly_update.c:168     Starting ota from http://rojer.me/files/shelly/shelly-homekit-Shelly25.zip
174257552642 mgos_http_server.c:180  0x3ffefbec HTTP connection from 192.168.20.80:63308
174257580058 json.c:428              RAM: 50720 total, 36272 free
174258020890 mgos_ota_http_clien:276 Update URL: http://rojer.me/files/shelly/shelly-homekit-Shelly25.zip
174258204283 mgos_ota_core.c:268     Starting, timeout 240, commit timeout 0, mem 35692
174258222278 mgos_ota_core.c:652     FW: switch25 esp8266 2.15.0 20260617-172112/2.15.0-gff8da82 sig 0x00
174258227513 shelly_update.c:90      BEGIN: switch25
174258232444 cloud_aes.c:165         Cloud already closed or not connected
174258247078 esp_ota_backend.c:185   Slot 0, FW: switch25.bin -> 0x8000, FS fs.bin -> 0xbb000
174258264093 mgos_ota_core.c:683     0.18% total, esp_init_data_default_v08.bin 128 of 128
174258481415 esp_ota_backend.c:334   Skip writing fs.bin (262144) @ 0xbb000 (digest matches)
174258502036 mgos_ota_core.c:683     0.23% total, fs.bin 512 of 262144
174258523509 mgos_http_server.c:180  0x3fff284c HTTP connection from 192.168.20.80:63306
174262464901 json.c:428              RAM: 50720 total, 32204 free
174263619616 mgos_ota_core.c:683     17.18% total, fs.bin 170496 of 262144
174266084083 mgos_ota_core.c:683     26.38% total, rboot.bin 512 of 2320
174266128762 esp_ota_backend.c:269   735904 @ 0x8000: would overwrite new fs (0 @ 0x8000)
174266134013 mgos_ota_core.c:1050    Update finished, result -1 (Bounds check failed)
174266150218 shelly_update.c:111     SHOTA: error Bounds check failed
**174266155005 shelly_update.c:130     OTA is fubar**
174267626509 mgos_http_server.c:180  0x3fff2824 HTTP connection from 192.168.20.80:63329
174267653842 json.c:428              RAM: 50720 total, 35792 free
174272542408 mgos_http_server.c:180  0x3fff27ac HTTP connection from 192.168.20.80:63340
174272568675 json.c:428              RAM: 50720 total, 35972 free
174274121669 mgos_http_server.c:180  0x3fff2e04 HTTP connection from 192.168.20.80:63341
