### ISSUE TITLE
Support for Shelly 3EM

### ISSUE THREAD

**Issue by higuelzim** [mongoose-os-apps/shelly-homekit#959]
Hi please let me now if there is a flash firmware for shelly em to HomeKit. I didn't find it anywhere.

I appreciate 

Many thanks

**Comment by rojer** [comment]
not currently supported and unlikely to be soon, but fair enough.

**Comment by hughfr4nc15** [comment]
+1

**Comment by kloibs** [comment]
If this were exposed in the Eve app similar to a native Eve product showing a graph with historical consumption... 🤤
