### ISSUE TITLE
RGBW2 as DC fan controller

### ISSUE THREAD

**Issue by mscottco** [mongoose-os-apps/shelly-homekit#960]
Hi All,

I'm looking to use a Shelly RGBW2 to control a DC fan. As I don't have the shelly yet, can anyone tell me whether the shelly-homekit firmware for the RGBW2 allows the device to be configured in HomeKit as a fan accessory type so it's speed can be adjusted via a 0-100% slider?

Hope that makes sense / here is an appropriate place to ask?

Cheers!

**Comment by timoschilling** [comment]
There is already a request for fan support open.
