### ISSUE TITLE
Shelly 2.5 still broadcasting WiFi AP

### ISSUE THREAD

**Issue by Cesco117** [mongoose-os-apps/shelly-homekit#964]
Hi !
First of all, thanks for your plugin, it's working very well !

I just have some minor issues, and one is important for me: 
Even after connecting the Shelly to my WiFi (I see it through my Unifi controller), it still broadcasting the WiFi AP "shellyswitch25-XXXXXX", which is not OK for security and other things.

So i would like to just disable it.

Some informations if it can help:
- i have another Shelly 2.5, working great and not having this issue.
- I push the button behind the Shelly by mistake while I was installing it, maybe it's related ?

Thanks a lot !

**Comment by lieberjott** [comment]
I can confirm that I also had this issue one or two times.

Can't remember what I've done to solve this (either trying to deactivate AP mode via URL command or flashing back to stock firmware, deactivating AP mode there).

**Comment by rojer** [comment]
this is fixed in upcoming 2.11, #868
