### ISSUE TITLE
HomePod doorbell not ringing

### ISSUE THREAD

**Issue by weaselbase1** [mongoose-os-apps/shelly-homekit#965]
Anyone else experiencing the doorbell not ringing HomePods anymore.  Incompatibility with iOS 15.4?  Can see notifications in Home app that the Shelly mongoose doorbell triggered, but HomePods no long chime.

**Comment by timoschilling** [comment]
If you get the notification in the HomeApp, it is a bug in HomeKit or a setup issue.

**Comment by 5xPa** [comment]
Hi, I didn't realise there was a doorbell option. I setup a shelly 1,
experienced the problems you describe. Eventually traced to  HomePod Mini
had updated to IOS 15.4 the iPad and iPhone were on 15.3. Updated HomePod
Minis factory rest and setup again. The doorbell works Ok.

Many thanks
