### ISSUE TITLE
Homekit label layout

### ISSUE THREAD

**Issue by lalolerry** [mongoose-os-apps/shelly-homekit#968]
Hallo everybody from Italy,
I'm a newbie and not a programmer, but I really appreciate your works and this shelly-homekit firmware.
Everything is easy and work flowless, but I've a very little enanchment to suggest.
It is possible to change the QR homekit code layout to look like the orignal Apple one, as used in its HomeKit Accessory Simulator app?
I mean showing out in this way:
![motion_qrcode](https://user-images.githubusercontent.com/101993449/159179067-1ac6f776-3c32-4c1e-bb46-0e29a8e9faae.png)

Because I use to print it on a label and stich it to the devices (like natively supported homekit devices).
thanks!

**Comment by rojer** [comment]
why?

**Comment by rojer** [comment]
> Because I use to print it on a label and stich it to the devices (like natively supported homekit devices).

sorry, missed that part. well, i guess it's possible. if you can contribute the SVG code to draw the outline and the little house, we can try to incorporate it. not sure what to do about the numbers yet.

**Comment by lalolerry** [comment]
Wow, what a quick reply! I'm really honored to speak with you, Rojer!
Unfortunatelly I'm not good in programming at all, I can only donate for this lovely project (as I already did). :/

**Comment by lalolerry** [comment]
> > Because I use to print it on a label and stich it to the devices (like natively supported homekit devices).
> 
> sorry, missed that part. well, i guess it's possible. if you can contribute the SVG code to draw the outline and the little house, we can try to incorporate it. not sure what to do about the numbers yet.

ehm actually I edit later adding this part ;P

**Comment by alexbartsch** [comment]
Hey @rojer and @lalolerry. I'm pretty new to this smart home thing, but I'm a developer for many years. Especially in web development. Let me see what I can do. 😉
