### ISSUE TITLE
RGBW2 support? 🙏

### ISSUE THREAD

**Issue by Tomer51m** [mongoose-os-apps/shelly-homekit#97]
Hi, Is there any chance of seeing Shelly RGBW2 support for HomeKit? 🙏

**Comment by andyblac** [comment]
add your support to this request https://github.com/mongoose-os-apps/shelly-homekit/issues/72

**Comment by rojer** [comment]
i actually have the device now. and now that i'm done with connection stability work, i will go back to adding features.
first on the list is roller shutter support but adding devices is there too.
so, yes, there is a chance. but there's no ETA for it as it's all a spare time hobby project.
