### ISSUE TITLE
Manuel change the open/closing time

### ISSUE THREAD

**Issue by ThomasTom86** [mongoose-os-apps/shelly-homekit#972]
Hy! I'm new here.  I am trying to set the opening and closing times manually.  This is possible in the original firmware.  Is there this possibility in the Shelly Homekit firmware?  thanks

![8D186F0C-74CB-43C4-B4AC-F29E95CE278E](https://user-images.githubusercontent.com/75570143/160254551-9bc14d2c-e7d8-417c-96c4-09d65bb21526.jpeg)

**Comment by timoschilling** [comment]
No, we have a auto calibration mode for that. A manual mode is already request in a different issue.
