### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nk-gx** [mongoose-os-apps/shelly-homekit#975]
I hope I'm wrong, but everything seems that it is.

**Comment by timoschilling** [comment]
Why do you think so?

**Comment by rojer** [comment]
no, it's not dead. 
both me and @timoschilling had some personal circumstances that kept us from being as active on the project but it is far from being dead.
a major new release with new device support and many improvements is almost finished, waiting for just a minor last bit.
stay tuned.
