### ISSUE TITLE
Shelly 1 as sensor type in Homekit

### ISSUE THREAD

**Issue by heili1094** [mongoose-os-apps/shelly-homekit#976]
Hy, is there a way to display in HomeKit the shelly as sensor? I would like to use the shelly in HomeKit with a rain sensor with 12 V? In HomeKit i always can  switch on/off. This is what i would like to prevent!

THX

BR Rene´

**Comment by timoschilling** [comment]
You can set the input mode to detached and then configure the input as sensor (we support different types for example contact). HomeKit didn’t support rain sensor as type, so you need one of our supported types. 

Keep in mind that you need to power the Shelly with the same 12v power source as you use for the rain sensor!

**Comment by heili1094** [comment]
Exactly what i did but couldn't get in HomeKit the automation running with speech text. So target should be that the rain sensor activate shelly 1 and close contact. In HomeKit the automation starts and at least send a iMessage or some sort of audio.

**Comment by heili1094** [comment]
So thanks Timo - i appreciate this quick response!!!!

**Comment by timoschilling** [comment]
Install the beta 2.11, search issues for how to do. That has support for leak sensor which supports audio notifications
