### ISSUE TITLE
Reboot Shelly via Curl

### ISSUE THREAD

**Issue by enji23** [mongoose-os-apps/shelly-homekit#979]
Some of my Shellys keep losing connection to the WIFI. As a solution, I would simply restart the devices every night. Is there a way to do this via curl? For example "http://shelly-1.org/reboot". So far I haven't been able to find the relevant command.

**Comment by timoschilling** [comment]
Yes: http://a.b.c.d/rpc/Sys.Reboot

**Comment by enji23** [comment]
Thanks a lot!! It works😊
