### ISSUE TITLE
Shelly UNI Alarm On/Off

### ISSUE THREAD

**Issue by 5xPa** [mongoose-os-apps/shelly-homekit#984]
I currently use Alarm Panel output relay to trigger a Uni using your superb firmware have them set as "contact" to trigger HomeKit Automations. Which works brilliantly.  Would it be possible to have an option Hap Type "Alarm On / Off" 

I have had the beta version running with no problems

Thank you all for the tremendous effort, I have made a donation few weeks back in recognition of your efforts

**Comment by rojer** [comment]
you mean HAP service "security system"?

**Comment by 5xPa** [comment]
Hi Rojer, if that is what it is called basically just to indicate alarm (security system) is armed / disarmed. Currently can be motion sensor, contact etc which would be associated with the security system

**Comment by timoschilling** [comment]
double of https://github.com/mongoose-os-apps/shelly-homekit/issues/552
