### ISSUE TITLE
Cycle Switch on Shelly 2.5

### ISSUE THREAD

**Issue by antodan91** [mongoose-os-apps/shelly-homekit#986]
Hello, Is there possibile ti have a cycle switch Toggle on shelly 2.5?

cycle switch - At the push of a button, the sequence is:
 Ch1-On Ch-2-Off, Chl-Off Ch-On, Ch1 and Ch2 On, Ch1 and Ch2 Off.

Thanks!

**Comment by timoschilling** [comment]
double of #194
