### ISSUE TITLE
MAC address ERROR in v2.11 beta

### ISSUE THREAD

**Issue by lalolerry** [mongoose-os-apps/shelly-homekit#987]
Hallo everybody,
I'm using some Shelly devices updated to firmware v2.11 beta3 (a lot of new features in it),
but the MAC addresses shown in the web UI are always slightly different (the second digit) from the ones read with the stock firmware.
There is a little bug in MAC reporting in v2.11 beta?
Best Regards

**Comment by timoschilling** [comment]
Can you post some screenshots where we can see that difference? Maybe one from the HomeKit Shelly Ui and one from your router Ui which maybe shows the Mac too

**Comment by lalolerry** [comment]
> Can you post some screenshots where we can see that difference? Maybe one from the HomeKit Shelly Ui and one from your router Ui which maybe shows the Mac too

Sure!
Here they are:
![Shelly2](https://user-images.githubusercontent.com/101993449/166821180-77ed2682-01ca-40a2-a6df-cbabecaadf89.jpg)
![Shelly3](https://user-images.githubusercontent.com/101993449/166821201-381ee174-a3a0-4468-b7dc-3d5bc80bf073.jpg)
![Shelly4](https://user-images.githubusercontent.com/101993449/166821217-5547680a-d409-4de8-9aa7-b18b5d08d709.jpg)
![Shelly5](https://user-images.githubusercontent.com/101993449/166821234-341bec10-70c3-4c89-ba0d-537e1ca9df6a.jpg)

**Comment by lalolerry** [comment]
(sorry I closed issue by mistake. Just reopened)

**Comment by MagOO33** [comment]
Hello,
i confirm that I have the same error on beta 3 UI that shows a wrong MAC.

**Comment by rojer** [comment]
the difference is that we are reporting AP MAC but when the device joins the network it uses its STA MAC.

**Comment by timoschilling** [comment]
Ah ok, we should change that. @rojer how can we display the STA Mac?

**Comment by rojer** [comment]
i need to add a library method for that, will do

**Comment by rojer** [comment]
fixed, will be in the next release
