### ISSUE TITLE
Support for Shelly Uni

### ISSUE THREAD

**Issue by kloibs** [mongoose-os-apps/shelly-homekit#991]
Hi everyone, after trying to sort out using a Shelly 1 for my not smart doorbell, I’ve come to the realization my 12V AC doorbell will not be able to support the Shelly 1. 

The Shelly Uni, however, can be powered with 12-24V AC in order to work.

Will be happy to donate a nice chunk of support for Shelly Uni can be added. 

Thank you!!

**Comment by timoschilling** [comment]
We have already support for the UNI in beta https://github.com/mongoose-os-apps/shelly-homekit/issues/868.

And we also have open issues for a better doorbell support.
