### ISSUE TITLE
Plug S constantly flashing blue with missing Wi-Fi

### ISSUE THREAD

**Issue by chronowerx42** [mongoose-os-apps/shelly-homekit#995]
Hello there,

I have flashed all my Shelly Plug S with the HomeKit firmware and it just works great. But I think a huge problem is my Wi-Fi night shut off. It turns the whole house into a light show because the Plug S flashes permanently blue when there is no Wi-Fi connection at this firmware. Unfortunately, the activated LED Status off function doesn't help either. Since the devices are also in the children's rooms and bedrooms, for now I had to unplug all. I think „LED status off“ should also include missing Wi-Fi connections, as is also the case in the Shelly standard firmware.

**Comment by rojer** [comment]
hm, interesting observation, i would've never guessed it could be a problem :)
currently the "status LED" setting only affects the status LED associated with the switch itself.
but i think you have a point that if it's off, it should also inhibit wifi blinkenlights.

**Comment by rojer** [comment]
fixed, will be in the next release.
